### ISSUE TITLE
Today's Activity

### ISSUE THREAD

**Issue by nzradar** [Ysurac/FlightAirMap#10]
Hello again,

For me in NZ time the Today's Activity reports that the date doesn't exist in the database between NZ midnight and NZ 11:59 am.  This is because the Port 30003 data is converted to UTC on import.

So, either on import the date/time should be local (that's what modesdeco2 is sending) i.e. no UTC conversion, or the PHP page that pulls the date should convert from UTC to NZ time.

Thanks,
Michael

**Comment by Ysurac** [comment]
This is fixed in commit 841305238eb99d039cb910c3e668ca03a3d5d2bf
