### ISSUE TITLE
Upcomin Flights...

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#101]
Hello Someone could explain me exactly what this section means ?. the truth does not quite understand,

I see three flights now I do not understand the significance of such flights in this section.

![captura](https://cloud.githubusercontent.com/assets/4571086/10714781/72085cfa-7afe-11e5-8d58-9a4573a323b3.PNG)

Thank you.

**Comment by Ysurac** [comment]
It's flights that will come, for regular flights. I think there is no regular flights in IVAO ?

**Comment by tonkepen100** [comment]
The truth in Ivao not, unless they can be as regular tours ivao, but it is curious that sometimes you see, out in that section, and that's what I do not understand that reflects, I mean that approach ua to reflect them.

**Comment by Ysurac** [comment]
There is some flights because I see the same flights (ident) more than 10 times at the same hour. So this look likes regular flights.

**Comment by tonkepen100** [comment]
ahhhh fantastic as the idea lame
