### ISSUE TITLE
Posters planes

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#102]
When you click on a flight, and then you click on another, and so on, the signs do not fade as before remain fixed, see attached photo.

![carteles](https://cloud.githubusercontent.com/assets/4571086/11237082/e3085c56-8ddd-11e5-865c-6423722a8b95.PNG)

**Comment by Ysurac** [comment]
For now this popup rendering is disabled in latest commit, the default rendering work well.

**Comment by tonkepen100** [comment]
Ok Ysurac copy , and more more regards my friend
