### ISSUE TITLE
Displays error airplanes

### ISSUE THREAD

**Issue by bilkaPek** [Ysurac/FlightAirMap#105]
Bug have to put $globalMapPopup = TRUE; on settings.php in to see the planes of my virtual airline
without this option the active plane does not right will be displayed on the map
then the flight ivao not generated any problems 

I hope not to be misses a parameter :(

sorry for my English is google translated
Thank.

**Comment by Ysurac** [comment]
Maybe a bug somewhere in the feed.
Could you put **$globalMapPopup = FALSE;** and put the result of *http://[yourdomain]/live/geojson* on pastebin.com ?

**Comment by bilkaPek** [comment]
here is the result
{"type": "FeatureCollection","minimal": "true","features": {"type": "Feature","properties": {"flight_cnt": "0"}}}

**Comment by Ysurac** [comment]
Strange.
If the source feed is public can you give me the url ?

**Comment by bilkaPek** [comment]
my test are localhost
but I also like going to different tested
the same result

$globalSBS1Hosts = array('http://www.phoenixva.org/action.php/acars/data');
$globalSBS1Hosts = array('http://brusselsairlinesva.be/action.php/acars/data');
$globalSBS1Hosts = array('http://www.buffaloairwaysvirtual.com/action.php/acars/data');
$globalSBS1Hosts = array('http://brusselsairlinesva.be/action.php/acars/data');


with ivao with no problems

Thank.

**Comment by Ysurac** [comment]
This should be solved with commit 76568c94b159d5bb6fea709a2a6cefd39bd5882

**Comment by bilkaPek** [comment]
ok problem solved at once
and thank you for Additional Information VATSIM
thou is incredibly efficient  :)
