### ISSUE TITLE
Strange Symbols

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#108]
As is done to remove these strange symbols that do not remember ..
Thank you

![captura](https://cloud.githubusercontent.com/assets/4571086/12003180/fc10d9e0-ab14-11e5-9fd8-bc743b09d374.JPG)

**Comment by Ysurac** [comment]
Done in commit 9439f73414bbc278247d09decc10551fe31bf0ae

**Comment by tonkepen100** [comment]
No, because I think not fix Yurac, I keep getting me those rare for the symbols.

![captura](https://cloud.githubusercontent.com/assets/4571086/12003415/13665288-ab1e-11e5-9213-16c917bf0436.JPG)

**Comment by Ysurac** [comment]
It was HTML encoded. Fixed in latest commit.

**Comment by tonkepen100** [comment]
Oki thanks..
