### ISSUE TITLE
filter Aircrafts option

### ISSUE THREAD

**Issue by bilkaPek** [Ysurac/FlightAirMap#114]
Salut Ysurac 
je sais que tu vas crier à me lire désolé par avance pour le surplus de travail que je te donne... :(
j'espère que ça te dérange pas que je poste en deux langues car le traducteur de Google est loin d'être fiable, car je suis nul en anglais :-1:  comme tu peux le constater et je préfère que tu comprennes mes questions
FR: 
```
Ajouter une option de filtrage dans le panel settings
qui permet d'affiche les avions sur la map 
selon la ou les compagnies aériennes sélectionné par le visiteur 
```

EN:
```
Add a filter option in the settings panel
which can display the aircraft on the map
 according to the airline or airlines Selected by the visitor
```
puis une option dans require/settings.php
an option in require/settings.php
```
//enable or disable panel Airline filter 
$globalFilterAilinesPanel = TRUE; //or FALSE 
```
Panel -1
```
avec option de filtrage et sélection multiples  :
with filtering option and multiple selection:
```
![panel1](https://cloud.githubusercontent.com/assets/16308214/12203765/f5509704-b630-11e5-8e51-3fca310ba4f0.JPG)

Panel -2
```
sans filtre:
without filter:
```
![panel2](https://cloud.githubusercontent.com/assets/16308214/12203766/f55a5e1a-b630-11e5-9b6e-bc81762d7b86.JPG)

option supplémentaire de filtrage qui peut être intégrée dans require/settings.php
après faut voir si on peut faire un filtrage lors de la lecture du fichier IVAO & VATSIM ???.

je m'explique:

on veux juste récupérer les informations correspondant au calsing afin de ne pas enregistrer toutes les données contenues sur le fichier IVAO & VATSIM
par exemple pour: AirFrance:(AFR.XXX) Air Berlin:(BER.XXX) Air Europa:(AEA.XXX)

```
option -1 single filter
$globalAirlineFilter = 'AFR'; // recovered only with a pilot callsign contain [AFR.XXX= Air France]
```

option -2 various filter
```
$globalAirlineFilter = 'AFR', 'ACA', 'EZY', 'AXS'; //recovered the pilot with and various callsign contain [AFR.XXX= Air France] [ACA.XXX= Air Canada] [EZY.XXX= EasyJet] [AXS.XXX= Jet2.com]
 ```

ce qui permettrait de faire un filtrage au moment de la lecture du fichier IVAO & VATSIM 
et qui va réduire les données improrte sur ma base mysql et bien sur ceci reste un filtrage réservée seulement à l'administrateur.

j'espère avoir été claire et précis dans les explications

Et bonne année, santé, prospérité :)

**Comment by Ysurac** [comment]
Airline filter in *settings.php* is now done in commit c89cba0f9987097575465b32553df3ecefcf1a6e
Not yet available in *install/index.php*...

**Comment by bilkaPek** [comment]
I just tested it and it works very well
thank you for your help

**Comment by Ysurac** [comment]
Airline filter for users, done in commit 91b1bc2f7ef9d4109da1d0ff9d194bf3231219fe
