### ISSUE TITLE
Display

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#115]
Now it turns out that I happened to remove one of the options see ivao or vatsim, and removing one and reload the page, and not a single flight is.

![captura](https://cloud.githubusercontent.com/assets/4571086/12214547/71a53c80-b698-11e5-8d09-ee087b9bb145.PNG)

![captura](https://cloud.githubusercontent.com/assets/4571086/12214550/81a012ae-b698-11e5-9eef-0c17a9d8a730.PNG)

Which may be?.

Thank you

**Comment by Ysurac** [comment]
I don't know how to know if a flight is using IVAO or VATSIM with your source.

**Comment by tonkepen100** [comment]
The problem is when uncheck an option, OR WILL COME BACK TO MAKE FLIGHTS, THEN THE cokies suppress the browser and the flights come out again

**Comment by Ysurac** [comment]
yes. I will make a parameter in *settings.php* to disable this option.

**Comment by tonkepen100** [comment]
For iñaki did a column to see if it vatsim or ivao. I know is that if ivao is 0 and if the truth vatsim 1. not more.

![captura](https://cloud.githubusercontent.com/assets/4571086/12215133/e19c41de-b6af-11e5-811d-c5fe10ba2465.PNG)

**Comment by Ysurac** [comment]
This need to be available in *http://piro.biz/lib/skins/skyline/js/recentpireps.php*.

**Comment by tonkepen100** [comment]
Well I do not think I see, now I'm flying with VATSIM and get this ...

{"id":"131606","callsign":"DAL555","name":"Tonique","icon":"plane","pilotid":"1","deplat":"21.316","deplng":"-157.927","arrlat":"35.7647","arrlng":"140.386","title":"DAL555","lat":"35.822","lon":"142.589","alt":"25706","heading":"260","depicao":"PHNL","arricao":"RJAA","deptime":"1452314284","arrtime":"0","gs":"339","aircraft":"CONC","transponder":"2000","route":"LIH 26N68 30N78 33E72 35E62 36E52 AVBET SCORE KAGIS AA631"}

I think that this data does not refer to whether or vatsim ivao, another thing that could be defined in any way in the file, but not as
