### ISSUE TITLE
function call error

### ISSUE THREAD

**Issue by bilkaPek** [Ysurac/FlightAirMap#116]
nonexistent calls function in class.spotter and return error page 500
in page redirect.php when clicking on the calsing the pilot in the popup window
![capturepop](https://cloud.githubusercontent.com/assets/16308214/12215570/dc209080-b6c2-11e5-9079-c3a8f4135f1d.JPG)

````
getBarrieSpotterIDBasedOnFlightAwareID
````

I replaced by another function
````
getSpotterIDBasedOnFlightAwareID
````

**Comment by Ysurac** [comment]
Fixed in commit 29a42b531228c6e6f1ebd2f29559bfb8f6fdf8ff
