### ISSUE TITLE
Everything works, no map

### ISSUE THREAD

**Issue by linuxpronl** [Ysurac/FlightAirMap#118]
Running Fedora / Nginx (with the rewrites), getting data from a working Rasperry PI running dump1090 everything looks fine, data is shown is statistics and so but whatever I choose a mapprovider I don't get a map shown. It stays blank and also the left vertical bar doesn't work. 

Any suggestions since I don't have any errors in the logs.

**Comment by Ysurac** [comment]
What is the result of *http://[ipofinstall]/live/geojson* ?

**Comment by linuxpronl** [comment]
That almost solves the issue, I got a 404 Not found. I guess one the redirects doesn't work or so

**Comment by Ysurac** [comment]
I'm using *install/flightairmap-nginx-conf.include* without problems with nginx on http://www.flightairmap.fr/

**Comment by linuxpronl** [comment]
Solved. Was issue in settings.php coverage area setting

**Comment by Ysurac** [comment]
ok I should check value...
