### ISSUE TITLE
Arrivals Seen

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#119]
Hello Ysurac:

These statistics convinced that in Arrivals Sins, working properly, to me gives me the impression that something is wrong, because if you see the number of daily flights, one marked as arrived very very few.

![captura](https://cloud.githubusercontent.com/assets/4571086/12222971/6c036cc8-b7cb-11e5-92bf-c2a0f600a338.PNG)

what set criteria that are marked as arrivals?

**Comment by Ysurac** [comment]
A flight is marked as arrival if latest latitude/longitude put flight at less than 10km of airport it should arrive OR less than 10km and less than 100m more than altitude of any airport.

**Comment by jmceara** [comment]
I have the same problem. Mine has only 1 in counter.

**Comment by Ysurac** [comment]
You can increase **$globalClosestMinDist**, it's the distance from airport when a flight is marked as arrived to airport. If you are too far from a airport an use SBS this can be always 0.

**Comment by jmceara** [comment]
Already tried with 10, 20, 30, even 80 or 0 for $globalClosestMinDist....still with only 1 arrival seen. My airport is with correct altitude on DB (1804Ft, or about 550m).

**Comment by Ysurac** [comment]
Are you far from airport ? Do you use ADS-B as source ? Do you use it as daemon or cron job ?
If airports are not found you should see, after a long time, with **globalDebug = TRUE** : "Can't fin arrival airport. Airport altitude...."

**Comment by jmceara** [comment]
Running as a daemon and source is my ModeSMixer, I'm exactly 6Km from airport. I'll try to find this string in my logs.
About my project (daemon for sources) I'm without free time :( but it's not dead.

**Comment by jmceara** [comment]
No, there's no string such this in my daemon log. I'm running with MinDist = 0

**Comment by Ysurac** [comment]
With **$globalClosestMinDist = 0** no airports will be found, and nothing in log.

**Comment by jmceara** [comment]
Even with MinDist set to 80Km, there's nothing in log about SBRP.....and I'm 110% sure thats was at least 4~6 arrivals today after I changed to 80.

**Comment by jmceara** [comment]
And what's this distance aboce airport?? Wach time is different.....
![sbrp](https://cloud.githubusercontent.com/assets/3300517/16056103/68424196-324a-11e6-8fbf-9ef98922a7e7.png)

**Comment by Ysurac** [comment]
This is the distance from and to airport based on latest data from flight in DB.

**Comment by jmceara** [comment]
Look:
```
DATA : hex : E48AF6 - ident : AZU4308 - ICAO : AT76 - Departure Airport : SBKP - Arrival Airport : SBRP - Latitude : -21.142422 - Longitude : -47.771451 - waypoints :  - Altitude : 0 - Heading : 165 - Speed : 20 - Departure Airport Time :  - Arrival Airport time :
```

Still not adding to Arrivals...this flight I saw live, my arrival count still 1.
And this is database data for SBRP:
![dbrao](https://cloud.githubusercontent.com/assets/3300517/16253133/326aea08-380a-11e6-9a1b-6b3f38ec0c15.png)

**Comment by Ysurac** [comment]
Altitude of the flight is 0, I was thinking flight always report GPS altitude. This should be fixed in latest commit, but I will do more test tomorrow.

**Comment by Ysurac** [comment]
There is a bug in the formule with negative coordinates. I will fix this asap.

**Comment by jmceara** [comment]
Em 2016-06-22 03:24, Ycarus escreveu:

> Closed #119 [1] via 45d67c5 [2]. 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [3], or mute the thread [4].

It's partially working, I guess. What's the logic for time between
updates of arrival seen? I could see aircraft landing, but as soon as
they landed, pilot turned off ADS-B after a few seconds...and my guess
is that FA didn't get time to update this data. This is the last data
from my data source: 

DATA : hex : E48D37 - ident : AZU4300 - ICAO : AT76 - Departure Airport
: SBKP - Arrival A         irport : SBRP - Latitude : -21.132295 -
Longitude : -47.774658 - waypoints :  - Altitude :          15 - Heading
: 163 - Speed : 101 - Departure Airport Time :  - Arrival Airport time :


At this time, aircraft has just landed (going out of track) 

Links:
------
[1] https://github.com/Ysurac/FlightAirMap/issues/119
[2]
https://github.com/Ysurac/FlightAirMap/commit/45d67c52c8ad39290d9b06f959b5973a58d197eb
[3] https://github.com/Ysurac/FlightAirMap/issues/119#event-700033104
[4]
https://github.com/notifications/unsubscribe/ADJcpZh7MOt1ehJTdm2P9Yvg1KLCHu6Xks5qONUTgaJpZM4HB6_w

**Comment by Ysurac** [comment]
Flights can be seen as arrived not before 3000s after latest ADS-B data.

**Comment by jmceara** [comment]
I don't know if still the same issue or not, but I COULD see more than one destination airport as my local air and altitude 0, but no increment on Arrival Seen.
```
[root@skynet assp]# cat /var/log/messages | grep "SBRP" | grep "Altitude : 0"
Jun 26 13:03:12 skynet cron-sbs.php: DATA : hex : E48274 - ident : TAM3274 - ICAO : A320 - Departure Airport : SBSP - Arrival Airport : SBRP - Latitude : -21.13767 - Longitude : -47.77297 - waypoints :  - Altitude : 0 - Heading : 163 - Speed : 72 - Departure Airport Time :  - Arrival Airport time :
Jun 26 20:22:24 skynet cron-sbs.php: DATA : hex : E48044 - ident : TAM3276 - ICAO : A320 - Departure Airport : SBSP - Arrival Airport : SBRP - Latitude : -21.13699 - Longitude : -47.77317 - waypoints :  - Altitude : 0 - Heading : 163 - Speed : 55 - Departure Airport Time :  - Arrival Airport time :
Jun 26 21:04:07 skynet cron-sbs.php: DATA : hex : E48044 - ident : TAM3275 - ICAO : A320 - Departure Airport : SBRP - Arrival Airport : SBSP - Latitude : -21.12699 - Longitude : -47.77814 - waypoints :  - Altitude : 0 - Heading : 343 - Speed : 14 - Departure Airport Time :  - Arrival Airport time :
Jun 26 21:05:53 skynet cron-sbs.php: DATA : hex : E48044 - ident : TAM3275 - ICAO : A320 - Departure Airport : SBRP - Arrival Airport : SBSP - Latitude : -21.13750 - Longitude : -47.77301 - waypoints :  - Altitude : 0 - Heading : 163 - Speed : 155 - Departure Airport Time :  - Arrival Airport time :
Jun 26 23:41:17 skynet cron-sbs.php: DATA : hex : E48B1D - ident : AZU4308 - ICAO : AT76 - Departure Airport : SBKP - Arrival Airport : SBRP - Latitude : -21.14304 - Longitude : -47.77139 - waypoints :  - Altitude : 0 - Heading : 227 - Speed : 8 - Departure Airport Time :  - Arrival Airport time :
Jun 27 09:18:37 skynet cron-sbs.php: DATA : hex : E48D37 - ident : AZU4300 - ICAO : AT76 - Departure Airport : SBKP - Arrival Airport : SBRP - Latitude : -21.13101 - Longitude : -47.77511 - waypoints :  - Altitude : 0 - Heading : 163 - Speed : 105 - Departure Airport Time :  - Arrival Airport time :
Jun 27 09:18:51 skynet cron-sbs.php: DATA : hex : E48D37 - ident : AZU4300 - ICAO : AT76 - Departure Airport : SBKP - Arrival Airport : SBRP - Latitude : -21.13580 - Longitude : -47.77358 - waypoints :  - Altitude : 0 - Heading : 163 - Speed : 54 - Departure Airport Time :  - Arrival Airport time :
Jun 27 10:01:35 skynet cron-sbs.php: DATA : hex : E48D37 - ident : AZU2423 - ICAO : AT76 - Departure Airport : SBKP - Arrival Airport : SBRP - Latitude : -21.12579 - Longitude : -47.77762 - waypoints :  - Altitude : 0 - Heading : 45 - Speed : 14 - Departure Airport Time :  - Arrival Airport time :
Jun 27 19:24:51 skynet cron-sbs.php: DATA : hex : E48F6B - ident : AZU4306 - ICAO : AT76 - Departure Airport : SBKP - Arrival Airport : SBRP - Latitude : -21.13571 - Longitude : -47.77359 - waypoints :  - Altitude : 0 - Heading : 163 - Speed : 74 - Departure Airport Time :  - Arrival Airport time :
Jun 27 19:25:15 skynet cron-sbs.php: DATA : hex : E48F6B - ident : AZU4306 - ICAO : AT76 - Departure Airport : SBKP - Arrival Airport : SBRP - Latitude : -21.14097 - Longitude : -47.77190 - waypoints :  - Altitude : 0 - Heading : 163 - Speed : 28 - Departure Airport Time :  - Arrival Airport time :
Jun 27 19:59:35 skynet cron-sbs.php: DATA : hex : E48F6B - ident : AZU4307 - ICAO : AT76 - Departure Airport : SBRP - Arrival Airport : SBKP - Latitude : -21.12568 - Longitude : -47.77754 - waypoints :  - Altitude : 0 - Heading : 42 - Speed : 14 - Departure Airport Time :  - Arrival Airport time :
Jun 27 20:22:03 skynet cron-sbs.php: DATA : hex : E47FFE - ident : TAM3276 - ICAO : A320 - Departure Airport : SBSP - Arrival Airport : SBRP - Latitude : -21.13900 - Longitude : -47.77253 - waypoints :  - Altitude : 0 - Heading : 163 - Speed : 56 - Departure Airport Time :  - Arrival Airport time :
Jun 27 20:22:37 skynet cron-sbs.php: DATA : hex : E47FFE - ident : TAM3276 - ICAO : A320 - Departure Airport : SBSP - Arrival Airport : SBRP - Latitude : -21.14268 - Longitude : -47.77136 - waypoints :  - Altitude : 0 - Heading : 163 - Speed : 15 - Departure Airport Time :  - Arrival Airport time :
Jun 27 21:03:00 skynet cron-sbs.php: DATA : hex : E47FFE - ident : TAM3275 - ICAO : A320 - Departure Airport : SBRP - Arrival Airport : SBSP - Latitude : -21.12896 - Longitude : -47.77752 - waypoints :  - Altitude : 0 - Heading : 343 - Speed : 19 - Departure Airport Time :  - Arrival Airport time :
Jun 27 21:06:35 skynet cron-sbs.php: DATA : hex : E47FFE - ident : TAM3275 - ICAO : A320 - Departure Airport : SBRP - Arrival Airport : SBSP - Latitude : -21.13949 - Longitude : -47.77239 - waypoints :  - Altitude : 0 - Heading : 163 - Speed : 165 - Departure Airport Time :  - Arrival Airport time :
Jun 28 00:00:41 skynet cron-sbs.php: DATA : hex : E48F6B - ident : AZU4308 - ICAO : AT76 - Departure Airport : SBKP - Arrival Airport : SBRP - Latitude : -21.13440 - Longitude : -47.77401 - waypoints :  - Altitude : 0 - Heading : 163 - Speed : 84 - Departure Airport Time :  - Arrival Airport time :
Jun 28 00:00:58 skynet cron-sbs.php: DATA : hex : E48F6B - ident : AZU4308 - ICAO : AT76 - Departure Airport : SBKP - Arrival Airport : SBRP - Latitude : -21.13892 - Longitude : -47.77256 - waypoints :  - Altitude : 0 - Heading : 163 - Speed : 45 - Departure Airport Time :  - Arrival Airport time :
Jun 28 09:21:46 skynet cron-sbs.php: DATA : hex : E490B0 - ident : AZU4300 - ICAO : AT76 - Departure Airport : SBKP - Arrival Airport : SBRP - Latitude : -21.13669 - Longitude : -47.77326 - waypoints :  - Altitude : 0 - Heading : 163 - Speed : 56 - Departure Airport Time :  - Arrival Airport time :
Jun 28 10:04:18 skynet cron-sbs.php: DATA : hex : E490B0 - ident : AZU2423 - ICAO : AT76 - Departure Airport : SBKP - Arrival Airport : SBRP - Latitude : -21.12567 - Longitude : -47.77751 - waypoints :  - Altitude : 0 - Heading : 199 - Speed : 6 - Departure Airport Time :  - Arrival Airport time :
Jun 28 12:45:01 skynet cron-sbs.php: DATA : hex : E4851B - ident : TAM3274 - ICAO : A319 - Departure Airport : SBSP - Arrival Airport : SBRP - Latitude : -21.13637 - Longitude : -47.77334 - waypoints :  - Altitude : 0 - Heading : 160 - Speed : 32 - Departure Airport Time :  - Arrival Airport time :
Jun 28 13:34:35 skynet cron-sbs.php: DATA : hex : E4851B - ident : TAM3271 - ICAO : A319 - Departure Airport : SBRP - Arrival Airport : SBSP - Latitude : -21.12636 - Longitude : -47.77814 - waypoints :  - Altitude : 0 - Heading : 25 - Speed : 13 - Departure Airport Time :  - Arrival Airport time :
Jun 28 13:36:00 skynet cron-sbs.php: DATA : hex : E4851B - ident : TAM3271 - ICAO : A319 - Departure Airport : SBRP - Arrival Airport : SBSP - Latitude : -21.13645 - Longitude : -47.77334 - waypoints :  - Altitude : 0 - Heading : 163 - Speed : 150 - Departure Airport Time :  - Arrival Airport time :
Jun 28 16:06:15 skynet cron-sbs.php: DATA : hex : E4917D - ident : AD9262 - ICAO : AT76 - Departure Airport : SBKP - Arrival Airport : SBRP - Latitude : -21.13724 - Longitude : -47.77307 - waypoints :  - Altitude : 0 - Heading : 343 - Speed : 105 - Departure Airport Time :  - Arrival Airport time :
Jun 28 16:06:26 skynet cron-sbs.php: DATA : hex : E4917D - ident : AD9262 - ICAO : AT76 - Departure Airport : SBKP - Arrival Airport : SBRP - Latitude : -21.13374 - Longitude : -47.77419 - waypoints :  - Altitude : 0 - Heading : 343 - Speed : 74 - Departure Airport Time :  - Arrival Airport time :
Jun 28 16:32:44 skynet cron-sbs.php: DATA : hex : E48C4D - ident : TAM3744 - ICAO : A320 - Departure Airport : SBSP - Arrival Airport : SBRP - Latitude : -21.13628 - Longitude : -47.77339 - waypoints :  - Altitude : 0 - Heading : 343 - Speed : 135 - Departure Airport Time :  - Arrival Airport time :
Jun 28 19:34:53 skynet cron-sbs.php: DATA : hex : E4917D - ident : AZU4306 - ICAO : AT76 - Departure Airport : SBKP - Arrival Airport : SBRP - Latitude : -21.13256 - Longitude : -47.77461 - waypoints :  - Altitude : 0 - Heading : 163 - Speed : 94 - Departure Airport Time :  - Arrival Airport time :
Jun 28 23:40:53 skynet cron-sbs.php: DATA : hex : E48B1D - ident : AZU4308 - ICAO : AT76 - Departure Airport : SBKP - Arrival Airport : SBRP - Latitude : -21.14171 - Longitude : -47.77168 - waypoints :  - Altitude : 0 - Heading : 163 - Speed : 29 - Departure Airport Time :  - Arrival Airport time :
Jun 29 07:16:12 skynet cron-sbs.php: DATA : hex : E48AD4 - ident : TAM3270 - ICAO : A320 - Departure Airport : SBSP - Arrival Airport : SBRP - Latitude : -21.13275 - Longitude : -47.77455 - waypoints :  - Altitude : 0 - Heading : 163 - Speed : 115 - Departure Airport Time :  - Arrival Airport time :
Jun 29 07:16:31 skynet cron-sbs.php: DATA : hex : E48AD4 - ident : TAM3270 - ICAO : A320 - Departure Airport : SBSP - Arrival Airport : SBRP - Latitude : -21.13808 - Longitude : -47.77286 - waypoints :  - Altitude : 0 - Heading : 163 - Speed : 47 - Departure Airport Time :  - Arrival Airport time :
Jun 29 07:17:05 skynet cron-sbs.php: DATA : hex : E48AD4 - ident : TAM3270 - ICAO : A320 - Departure Airport : SBSP - Arrival Airport : SBRP - Latitude : -21.14276 - Longitude : -47.77135 - waypoints :  - Altitude : 0 - Heading : 168 - Speed : 11 - Departure Airport Time :  - Arrival Airport time :
Jun 29 08:12:41 skynet cron-sbs.php: DATA : hex : E48AD4 - ident : TAM3277 - ICAO : A320 - Departure Airport : SBRP - Arrival Airport : SBSP - Latitude : -21.12916 - Longitude : -47.77744 - waypoints :  - Altitude : 0 - Heading : 343 - Speed : 22 - Departure Airport Time :  - Arrival Airport time :
Jun 29 08:14:51 skynet cron-sbs.php: DATA : hex : E48AD4 - ident : TAM3277 - ICAO : A320 - Departure Airport : SBRP - Arrival Airport : SBSP - Latitude : -21.13937 - Longitude : -47.77242 - waypoints :  - Altitude : 0 - Heading : 163 - Speed : 170 - Departure Airport Time :  - Arrival Airport time :
Jun 29 09:21:02 skynet cron-sbs.php: DATA : hex : E48D37 - ident : AZU4300 - ICAO : AT76 - Departure Airport : SBKP - Arrival Airport : SBRP - Latitude : -21.13169 - Longitude : -47.77487 - waypoints :  - Altitude : 0 - Heading : 163 - Speed : 98 - Departure Airport Time :  - Arrival Airport time :
Jun 29 09:21:18 skynet cron-sbs.php: DATA : hex : E48D37 - ident : AZU4300 - ICAO : AT76 - Departure Airport : SBKP - Arrival Airport : SBRP - Latitude : -21.13659 - Longitude : -47.77330 - waypoints :  - Altitude : 0 - Heading : 163 - Speed : 53 - Departure Airport Time :  - Arrival Airport time :
Jun 29 09:58:23 skynet cron-sbs.php: DATA : hex : E48D37 - ident : AZU4300 - ICAO : AT76 - Departure Airport : SBKP - Arrival Airport : SBRP - Latitude : -21.12619 - Longitude : -47.77802 - waypoints :  - Altitude : 0 - Heading : 39 - Speed : 15 - Departure Airport Time :  - Arrival Airport time :
```

**Comment by Ysurac** [comment]
If it can't find arrival airport there is, in latest commit, a log like *----- Can't find arrival airport ....* or *----- No Airport near last coord.  ...* else it's *---++ Find arrival airport*

**Comment by Ysurac** [comment]
Do you run **scripts/update_db.php** recently ? If **$globalArchiveMonths** > 0, stats are not real time, only generated by **update_db.php**.
Else you can also check **stats** table.

**Comment by Ysurac** [comment]
I found the problem, I only count distinct airport arrival :)

**Comment by Ysurac** [comment]
Should be fixed in latest commit.

**Comment by jmceara** [comment]
Ok, I'll pull and try.

**Comment by jmceara** [comment]
I guess something is wrong....hehehehe
Flights: 2,484, Arrivals seen: 2,297

**Comment by Ysurac** [comment]
Maybe you have a too high **$globalClosestMinDist** value in *require/settings.php*. Else you are near several airports and see all arrivals :)

**Comment by jmceara** [comment]
I guess not, but I'll try to change. This value is in Km or Miles?

**Comment by jmceara** [comment]
Also, this value of statistics are updated in realtime (while page is opened) or processed in cron-sbs script?
Because I've changed to '10' and nothing happened, still with high value.

**Comment by Ysurac** [comment]
You need to run again cron-sbs script but stats will not be updated, it's only available for new flights.

**Comment by jmceara** [comment]
I'm asking because I'll delete all my flights and start again.

**Comment by Ysurac** [comment]
I can make a script to update this for all old flights.

**Comment by jmceara** [comment]
That would be better.

**Comment by Ysurac** [comment]
I will make this tomorrow.

**Comment by Ysurac** [comment]
I found a bug, too much flights saw as arrival, fix & script will be available tomorrow with some updates for stats.

**Comment by jmceara** [comment]
Looks like is working better now. Just one question: page statistics-airport-arrival.php shows only arrivals that my receiver could detect, right?
Because it's showing this:
```
Airport	Country	# Of Times
1	, Brazil (SBPS)	Brazil	1
2	Miami, United States (KMIA)	United States	1
3	Ribeirao Preto, Brazil (SBRP)	Brazil	1
4	Belo Horizonte, Brazil (SBCF)	Brazil	1
5	Sao Paulo, Brazil (SBGR)	Brazil	1
```

and in statistics, Arrivals Seen = 10. I have truncated my database and I'm using your last commit. My question is because it's near impossible for my receiver to detect arrival on USA.....hehehehehe

**Comment by Ysurac** [comment]
No, it's all arrival of flights seen. So it's also planning arrival airports. But there should be 10 arrivals, I will check if it's only planning airports and if I forget to add detected arrival airports.

**Comment by jmceara** [comment]
Ok, because USA is far away ad it's impossible for my receiver to detect arrival there. I just can see flights from Brazil that will arrive in USA, but not actual arriving/landing.

**Comment by Ysurac** [comment]
I will add a page for detected arrival airports.

**Comment by jmceara** [comment]
Arrival airport statistic page looks fine (about 46 arrivals seen in top-10), but total arrival seen still too high on general statistic page.... Flights: 2825, Arrivals seens: 2653.
You can check here: [http://www.radarvirtual.net.br/log/statistics/airport-arrival](url)

**Comment by Ysurac** [comment]
I didn't change arrival airport statistic page, so it's only planed flights, no detected arrival.
For arrivals seen, did you run script **install/update_arrival_airport.php** ?

**Comment by jmceara** [comment]
Yes, but it didn't changed overall arrival count, so I truncated my database to start all again. 

I probabily have wrong understand of "Arrival Seen". As I understand, Arrival Seen is when my receiver (in my case, ADS-B) got a signal from airplane and position of this plane is at least "GlobalClosestMinDist" from their destination airport.....right? if those criteria are fine (and maybe altitude=0?), Arrival Seen = +1. Is this the right logic?

**Comment by Ysurac** [comment]
It's when **latest position received** is at least *globalClosestMindist* of **any** airport and altitude not too high (or 0). At least it's the case if I don't make mistake. The bug can be if you have flight at altitude 0 even if there at not on ground or crashed.

**Comment by jmceara** [comment]
So, let's say that there is a flight from point A to point B, and between then are my receiver (and my 'local' airport). The last valid signal received from this plane, they are in the border of my City and above my local airport, but too far from destination. This flight, today, it's counting as Arrival, even if they are high. This altitude is configurable? If I may sugest, Arrival should only be counted if last signal is near destination airport, not 'any' airport and lower altitude.

**Comment by Ysurac** [comment]
Flight must be < airport altitude + 5000 m or flight altitude = 0
I don't always know destination airport of a flight.
Put a lower value for *globalClosestMinDist*.

**Comment by Ysurac** [comment]
It's 5000 feet, a little bit too much.

**Comment by jmceara** [comment]
I"m curretly using 10. I'm 110% sure thats impossible to my receiver to get a valid data from airplane in below 5000ft from any airport in USA.

**Comment by Ysurac** [comment]
I don't think it find any USA airport. Airports in statistics airport arrival page are only planed airports.
Could you run and send me some log from *install/update_arrival_airport.php* from latest commit ?
I added more log info, we will see if there is any errors.

**Comment by jmceara** [comment]
Sure. Here's the log. Some of 'mistakes': SJCU and SDWK. I could not find in logs, but in arrival airport status page I can see also KMIA (USA) (LEMD) Spain and others.

[update_arrival.zip](https://github.com/Ysurac/FlightAirMap/files/347786/update_arrival.zip)

**Comment by Ysurac** [comment]
I don't find errors in the log. Even for SJCU and SDWK, flights are really near airport at low altitude, difficult to do more.
I put a fix in latest commit for the script, this should reduce the number of detected flights.

**Comment by jmceara** [comment]
I agree about coordinates.....but probabily these coordinates are wrong processed by sbs-daemon script. I'm getting data direct from my FlightFeeder, the same source for my ModesDeco2 and my MaxRange is about 450Km. From my position (SBRP) to Miami (KMIA) it's exactly 6.293Km, so It's impossible to get even one ADS-B packet from this location. You can check my ModeSDeco2 from: http://live.radar.jonis.com.br . This site use exactly the same source of my ```cron-sbs.php```script.

**Comment by Ysurac** [comment]
As I already said, there is NO detection of airports in the US. What you see on the webpage is planed airports for regular flights. No detection for that, only a database with flight callsign and arrival/departure airport.
