### ISSUE TITLE
planes are not shown on the map

### ISSUE THREAD

**Issue by c0by1** [Ysurac/FlightAirMap#12]
i get my data from dump1090-mutability (port 30003) and the planes are not shown on the map. but the statistics are working.

**Comment by c0by1** [comment]
![flightma1](https://cloud.githubusercontent.com/assets/5725891/7478479/667c4d4a-f35b-11e4-90f2-d8fbc26ae3e8.JPG)
![flightma2](https://cloud.githubusercontent.com/assets/5725891/7478480/667eadce-f35b-11e4-96bf-f643cc9879c4.JPG)

**Comment by c0by1** [comment]
the table is full of planes... what do you mean with the 2nd? put this the behind the url?

![flightma3](https://cloud.githubusercontent.com/assets/5725891/7479152/001f042a-f360-11e4-9bf7-3606f2621521.JPG)


when i put this behind the url, i will be redirectet to another vhost... i use https and i will be redirectet to non https.

**Comment by c0by1** [comment]
fixed the problem. https is disallowed in the .htaccess... http only works.

**Comment by Ysurac** [comment]
I will fix this really dirty *.htaccess* asap
