### ISSUE TITLE
Route CallSign

### ISSUE THREAD

**Issue by jomimota** [Ysurac/FlightAirMap#123]
Hi,

The callsigns TAP23 and TAP023 are the same flight.
In the database we have TAP23 but the flight is detected as TAP023.

It's possible to make the script retrieve the route data in both situations?

Thanks in Advance.

Jorge Mota
http://radar.jorgemota.pt

**Comment by Ysurac** [comment]
The translation table is used for that problem, but only schedule use that table, not route... A mistake. This will be fixed soon.

**Comment by jomimota** [comment]
Thank you.

**Comment by Ysurac** [comment]
Should be done in commit 022292cb7f8701f1b1219972a8d1265d5094da36
