### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#124]
Hello Yurac and installed in another reseller, a new copy to my real flight, not IVAO and VATSIM.

and I get this error ...

Connecting... Connection in progress to 87.216.162.112:9742(sbs).... Connected! SCAN MODE 
Warning: socket_read(): unable to read from socket [111]: Connection refused in /home/dospirob/public_html/radar/scripts/daemon-spotter.php on line 548
ERROR : Reconnect...Connection in progress to 87.216.162.112:9742(sbs).... 
Warning: socket_read(): unable to read from socket [111]: Connection refused in /home/dospirob/public_html/radar/scripts/daemon-spotter.php on line 548
ERROR : Reconnect...Connection in progress to 87.216.162.112:9742(sbs).... 

Thanks Ysurac

**Comment by Ysurac** [comment]
It can't connect to 87.216.162.112:9742, connection is refused. Port 9742 is open ? reseller allow to connect to it ?

**Comment by tonkepen100** [comment]
If that port is open on the server,

**Comment by tonkepen100** [comment]
uffff is open but see..

Connecting... Connection in progress to 87.216.162.112:30054(sbs).... Connected! SCAN MODE Wrong line format. Ignoring... Ç½ÆK]G‡aNˆGŽ °L¡´v£ñRL¨H`¹ƒ8¤T2ÅÊ]G‡aˆÀ¶Array ( [0] => Ç½ÆK]G‡aNˆGŽ °L¡´v£ñRL¨H`¹ƒ8¤T2ÅÊ]G‡aˆÀ¶ ) Reconnect after an error... Connection in progress to 87.216.162.112:30054(sbs).... Wrong line format. Ignoring... íÃL§·™Eº”@	‚øÅIQÎh¹DUAù‰ßI¤ÆL¨H`¹†<HB¢ï]Ç4#ˆæçµl0ëksÉ '€’!,àÔYd	Z ¶‹Ê ¸ @u9Ø8 KŽÎÕ4~ËG‡aXÍ‡¨QSþŽ…NŸËG‡a™Å&€ûíArray ( [0] => íÃL§·™Eº”@	‚øÅIQÎh¹DUAù‰ßI¤ÆL¨H`¹†<HB¢ï]Ç4#ˆæçµl0ëksÉ '€’! [1] => àÔYd	Z ¶‹Ê ¸ @u9Ø8 KŽÎÕ4~ËG‡aXÍ‡¨QSþŽ…NŸËG‡a™Å&€ûí ) Reconnect after an error... Connection in progress to 87.216.162.112:30054(sbs).... Wrong line format. Ignoring... Ø¼:]L¦ª?_RË:]IR‡üöwÌ>]L¦ªa7¼@¨¶„9ÿ2ßÿArray ( [0] => Ø¼:]L¦ª?_RË:]IR‡üöwÌ>]L¦ªa7¼@¨¶„9ÿ2ßÿ ) Reconnect after an error... Connection in progress to 87.216.162.112:30054(sbs).... Wrong line format. Ignoring... ¦¿ ¶°0¤4cˆ5§ì™À 0Àx/ðüß ¦¿ ¶°0¤4cˆ5§ì™À 0Àx/ðüßá—°9dêïa¿·@ ÆP0¨L¨HõÓþAKX¥—ØTÜArray ( [0] => †H>á—°9dêïa¿·@ ÆP0¨L¨HõÓþAKX¥—ØTÜ ) Reconnect after an error... Connection in progress to 87.216.162.112:30054(sbs).... Wrong line format. Ignoring... |1ÀIÓh™É‰ Ž®Äæ¸KŽj5]]Ä |1ÀIÓh™É‰ Ž®Äæ¸KŽj5]]Ä ´’Aá—°L¢$;ä\B9dêX¿èqN#’Š/Cá-##€É×Cá”06´à0¤F]4ƒ3 ) Reconnect after an error... Connection in progress to 87.216.162.112:30054(sbs).... Wrong line format. Ignoring... ¸9Á]4#ˆÖ½Ž	Â >.¬S;mËÂ]L¦ª%±Array ( [0] => ¸9Á]4#ˆÖ½Ž	Â >.¬S;mËÂ]L¦ª%± ) Reconnect after an error... Connection in progress to 87.216.162.112:30054(sbs).... Wrong line format. Ignoring... q^Aá¼hA2Zè±–D41Array ( [0] => q^Aá¼hA2Zè±–D41 ) Reconnect after an error... Connection in progress to 87.216.162.112:30054(sbs)....

**Comment by Ysurac** [comment]
It's not a supported format.This is a binary output. AVR binary output is supported on 30002 port, else only SBS format on port 30003 is supported.

**Comment by tonkepen100** [comment]
Well, it got solved in output modesmixer, different output formats ...

PROG_ARGS="--inConnect 192.168.1.135:30054 --outServer beast:30005 --outServer avr:30002 --outServer sbs10001:30001 --outServer sbs30006:30003 --web 8080 --location 41.649376:-0.882105 --db /home/pi/modemixer2/basestation.sqb --frdb /home/pi/modemixer2/flightroute.sqb --silhouettes /home/pi/modemixer2/Siluetas"

Now to the issue of Acars only it works with acardec, or could also run acarsdeco2?

http://forum.flightradar24.com/threads/7921-AcarsDeco2-multi-channels-console-RTLSDR-ACARS-decoder

Thank you

**Comment by Ysurac** [comment]
ACARS from acarsdeco2 is not supported for now, I need to find the format used for UDP output...

**Comment by tonkepen100** [comment]
ohhh thanks Ycarus

**Comment by Ysurac** [comment]
In fact acarsdeco2 & acarsdec use the same output so it's working.
You need to add *--udp 0.0.0.0:9999* (or any settings you configure in **require/settings.php**) to **acarsdeco2** command lines and run **scripts/daemon-acars.php**.

**Comment by linuxpronl** [comment]
It is going to possible to use an extern stream instead of local ?

**Comment by Ysurac** [comment]
You can use what you want, set *--udp ip-where-daemon-acars-is-running:port*.
**daemon-acars.php** act as an UDP server, IP you set in **require/settings.php** is the local IP **daemon-acars.php** must bind to.
