### ISSUE TITLE
Check multiple sources

### ISSUE THREAD

**Issue by linuxpronl** [Ysurac/FlightAirMap#125]
When using data from more than one dump1090 source, how can I see / check both (or more) sources are used? 

from require/settings.php : 
$globalSBS1Hosts = array('xxx.xxx1.xxx.xxx:30003','xx.xxx.xxx.xxx:31003');

When using telnet at the given ports on the Flightairmap server I can connect and I'm receiving data.

**Comment by Ysurac** [comment]
When you see all flights :)
If there is no error in log with *$globalDebug* enabled all should be ok. Else you can mix sources with **dump1090** or **ModeSMixer2**.

**Comment by linuxpronl** [comment]
mixing source with dump1090 I'll look into and after restarting the cron daemon I see more flight now that on the each source itself so it seems to be working.
