### ISSUE TITLE
lots of 404 errors

### ISSUE THREAD

**Issue by jchisholm59** [Ysurac/FlightAirMap#128]
My sql databases are working and being populated by my adsb feeder, the front page map is there
but every link (Statistics etc)  results in a 404 Not Found error
eg clicking on Statistics gives me

Not Found

The requested URL /statistics/ was not found on this server.

Apache/2.4.7 (Ubuntu) Server at 192.168.2.140 Port 80

And so on, same with /aircraft not found etc.

**Comment by Ysurac** [comment]
The **.htaccess** is not read. What's your Apache configuration for the site ?
**mod_rewrite** is enabled ?

**Comment by Ysurac** [comment]
I added configuration for Apache on the wiki : https://github.com/Ysurac/FlightAirMap/wiki/Installation

**Comment by jchisholm59** [comment]
Apache/2.4.7 (Ubuntu)
mod_rewrite is enabled, still getting the same 404 errors.
Not sure what you mean by " .htaccess is not read". Do I need a .htaccess for
this install?

**Comment by Ysurac** [comment]
The file *.htaccess* in the root path of your FlightAirMap installation seems to be not read by Apache.

You have a mistake in your Apache configuration, check your options between *\<Directory\>\</Directory\>* tag.

**Comment by jchisholm59** [comment]
What should be the ownership/permissions of the .htaccess file?

**Comment by Ysurac** [comment]
Should be readable by *apache* user.

**Comment by Ysurac** [comment]
Do you have **AllowOverride All** between Directory tag ?

**Comment by Ysurac** [comment]
You can pull latest commit : I've added checks to see if *mod_rewrite* is enabled and if *.htaccess* is interpreted.

**Comment by jchisholm59** [comment]
Same problems, not sure where the results of the checks should be seen but manually running the install script I get
ERROR 29 (HY000) at line 1: File '/tmp/awy.dat' not found (Errcode: 13)
ERROR 29 (HY000) at line 1: File '/tmp/routes.csv' not found (Errcode: 13)
ERROR 29 (HY000) at line 1: File '/tmp/basestation.csv' not found (Errcode: 13)

Those files certainly are there

# ls -al /tmp/*
-rw-r--r-- 1 root root 32816315 Feb 18 17:41 /tmp/airspace.sql
-rw-r--r-- 1 root root  5155609 Feb 18 17:41 /tmp/awy.dat
-rw-r--r-- 1 root root 13839789 Feb 18 17:41 /tmp/basestationall.zip
-rwxrwxrwx 1 root root 14100506 Feb 18 17:41 /tmp/basestation.csv
-rw-r--r-- 1 root root 61955072 Feb 17 09:16 /tmp/BaseStation.sqb
-rw-r--r-- 1 root root  6755669 Feb 18 17:41 /tmp/countries.sql
-rwxrwxrwx 1 root root        0 Feb 18 17:41 /tmp/routes.csv
-rw-r--r-- 1 root root        0 Feb 18 17:41 /tmp/StandingData.sqb
-rwxrwxrwx 1 root root  3722112 Feb 18 17:39 /tmp/StandingData.sqb.gz
-rwxrwxrwx 1 root root  5307456 Feb 17 20:34 /tmp/StandingData.sqb.gz.1
-rwxrwxrwx 1 root root  5307456 Feb 17 20:34 /tmp/StandingData.sqb.gz.2
-rw-r--r-- 1 root root  5307456 Feb 17 20:34 /tmp/StandingData.sqb.gz.3
-rw-r--r-- 1 root root    58611 Feb 18 17:41 /tmp/translation.csv
-rw-r--r-- 1 root root    20159 Feb 18 17:41 /tmp/translation.zip

**Comment by Ysurac** [comment]
It's not the same problem.

What script do you run ? You should only use PHP scripts.

**Comment by jchisholm59** [comment]
install_db.sh

**Comment by jchisholm59** [comment]
This is after the web-based script fails/hangs indefinitely

**Comment by Ysurac** [comment]
You can use the *populate_all.php* if you want to populate table and install script take too much time.

**Comment by Ysurac** [comment]
You can also try to run web-based script again if it fails, this will retry install.

**Comment by jchisholm59** [comment]
Thanks, here's the latest:

# php5 populate_all.php 
Populate all tables...
Routes : Download...Gunzip...PHP Fatal error:  Call to undefined function gzopen() in /var/www/flightairmap/install/class.update_db.php on line 30

**Comment by jchisholm59** [comment]
Let me ask. what platform/distribution do YOU use ?

**Comment by jchisholm59** [comment]
Changed gzopen at line 30 in populate_all.php to gzopen64 and at least that script now apparently completes..

**Comment by jchisholm59** [comment]
Ubuntu 14.04's php does not seem to have been compiled with Zlib

**Comment by Ysurac** [comment]
I use Gentoo.

I will add a check for Ubuntu gzopen64...
Web-based script should work in latest commit (at least if max_execution_time is long enough).

**Comment by jchisholm59** [comment]
I've got "AllowOverride All" written on everything except the cat, kids and wife and still no go with reading that .htaccess file. Also the main page is not opening with the map anymore but just the text-only version.
Just about ready to call it quits :(

**Comment by Ysurac** [comment]
Paste your Apache configuration and your *require/settings.php* without password on pastebin.com

**Comment by jchisholm59** [comment]
Well my friend I have no idea what magic combination I hit on but it's now working.
Now I'm gonna feed it some data from my adsb setup and see what happens .
Thanks for your patience!

**Comment by Ysurac** [comment]
No problem. I know I need to make the install script better...
Don't forget to add *scripts/update_db.php* as cron job if you want DB to be keep up to date.
