### ISSUE TITLE
How to connect to remote ACARS

### ISSUE THREAD

**Issue by linuxpronl** [Ysurac/FlightAirMap#129]
I've flighairmap running on a different server as where my acars dump1090 runs. How to connect to the acars source ?  I've seen that I can run it local but not how to connect to a remote source

**Comment by Ysurac** [comment]
For ACARS you need to run *scripts/daemon-acars.php* then **acarsdec** or **AcarsDeco** and configure UDP output to the IP/port defined in FlightAirMap *require/settings.php*.

Example with **acarsdec** :

    ./acarsdec -v -N ipofFlightAirMap:5555 -r 0 131.525 131.550 131.725 131.825

**Comment by linuxpronl** [comment]
So when my flightairmapserver has ip  1.2.3.4 I start on my acars pc which has ip 192.168.1.11
../acarsdec -v -N 1.2.3.4:5555 -r 0 .......

and in /require/settings.php I use:
$globalACARS=true;
$globalACARShost=???; // Local IP to listen
$globalACARSPost='5555'; 

I'm a bit confused I guess..

**Comment by Ysurac** [comment]
True. In *-$globalACARShost** you can put *0.0.0.0* to listen to all IP, or *1.2.3.4* to listen only to *1.2.3.4*

**Comment by linuxpronl** [comment]
Tnx, I'm gonna try that this evening.. the acars table in the database is soo empty ;)

**Comment by linuxpronl** [comment]
running acars at my home pc and see incoming messages, daemon-acars.php is running but I see nothing in the database, all the acars tables are still empty. Any suggestions?  (Checked firewall and that's open for udp/port)

**Comment by Ysurac** [comment]
Set *$globalACARShost* to *0.0.0.0* if it's not the case. If UDP port is open everywhere all should work.

You could also check with for example **netstat -lapute** that *daemon-acars.php* is listening on server and *acarsdec* connect to server on home pc.

**Comment by linuxpronl** [comment]
I see on the flighairmap host with netstat (running server and acars home pc at port 9742): 
udp    0  0 0.0.0.0:9742    0.0.0.0:*        root       291133970  24957/php   

so that seems to be listening and on the home pc with acarsdec running: 

udp   0   0 pinguin.linuxpro.:22833 <flightairmapservername>:9742  ESTABLISHED root  99742576   30161/./acarsdec  

That looks fine to me too..

**Comment by Ysurac** [comment]
This seems correct... Try to set your IP to *$globalACARShost*, make sure you have *$globalDebug* set to *TRUE* in *require/settings.php*. If the daemon receive something, a line should be displayed.

**Comment by linuxpronl** [comment]
I see ACARS messages on my pc at home on screen, but nothing on the flightairmap server... still (de)bugging me. Firewall is open on both sides for UDP/port ...

**Comment by Ysurac** [comment]
You can install **tcpdump** and check if data is received on flightairmap server:

    tcpdump -i eth0 udp port 9742 -vv -X

At least with that we will see if data come to the server. If it's the case it's a bug in configuration or in my script.

**Comment by linuxpronl** [comment]
I did and tcpdump returns stuff like this: 

14:10:11.354622 IP (tos 0x0, ttl 61, id 17863, offset 0, flags [DF], proto UDP (17), length 304)
    xx-xxx-xxx-xxx.xxx.xxxl.10640 > mx1.linuxpro.nl.9742: [udp sum ok] UDP, length 276
        0x0000:  4500 0130 45c7 4000 3d11 9172 52a8 df70  E..0E.@.=..rR..p
        0x0010:  5117 e253 2990 260e 011c cfc6 2020 286e  Q..S).&.......(n
        0x0020:  756c 6c29 2031 2032 352f 3032 2f32 3031  ull).1.25/02/201
        0x0030:  3620 3133 3a31 303a 3130 2030 202d 3138  6.13:10:10.0.-18
        0x0040:  2047 202e 462d 4842 584b 2021 2048 3120  .G..F-HBXK.!.H1.

So it seems data is coming in on the flightairmap server and yes! some info is now in the database (acars_live table) ... Now see if I can find the acars info on flightairmap website ;-)

I'm not sure why I didn't receive messages into the database yesterday

**Comment by Ysurac** [comment]
Cool.
If you set **$globalACARS** to **TRUE** in *require/settings.php*, you should see ACARS message in **Explore->Latest ACARS message**. They are also on each flight that send them.
ACARS message are also used to populate DB with flight airport depart/arrival, real name of flights,...

**Comment by linuxpronl** [comment]
GREAT, I was looking for that and it works. Tnx! (http://flightinfo.linuxpro.nl)
