### ISSUE TITLE
Error daemon-spotter.php

### ISSUE THREAD

**Issue by linuxpronl** [Ysurac/FlightAirMap#130]
After a git pull and reinstall/fill the database I get this : 

./daemon-spotter.php 
PHP Fatal error:  Call to a member function prepare() on a non-object in /data/nginx/sites/FlightAirMap/require/class.ATC.php on line 70

**Comment by Ysurac** [comment]
This is a problem of connection with the DB. I will put better errors reporting...

**Comment by linuxpronl** [comment]
A reinstall of the database seems to be a solution although after running install/index.php I have a working database but I'm missing route info and airplaine pic's

**Comment by Ysurac** [comment]
You are using IVAO or VATSIM ? If it's the case there is no route. If not check your *require/settings.php* that IVAO and VATSIM are disabled.

**Comment by linuxpronl** [comment]
IVAO was turned on, switched it off... problem solved.
