### ISSUE TITLE
Problem with new instalation

### ISSUE THREAD

**Issue by sp2ong** [Ysurac/FlightAirMap#131]
I have setup FAM on debian v7 with acarsdeco and apache2/mysql
When I have run acarsdeco and script daemon-acars.php it look like this daemon collect information from acarsdeco but on map I have still 0 detected aircraft. How to find where is problem?

============== screen dump message from daemon-acars.php =======
Test if not already in Live ACARS table...Add Live ACARS data...Done
Human readable data : Message to/from terminal - Digital Flight Data Acquisition Unit
Reg. : .VQ-BWD - Ident : SU2024 - Label : H1 - Message : #DFB01
8.3 47 49  76  77 -691554
Test if we add ModeS data...- Ident : AFL2024 - Check if needed to add translation AFL2024... Done
 Can't find ModeS in spotter_output - Done
Test if not already in Live ACARS table...Add Live ACARS data...Done
Human readable data : Message to/from terminal - Digital Flight Data Acquisition Unit
Reg. : .HB-JVL - Ident : 2L1385 - Label : _d - Message : 
Test if we add ModeS data...- Ident : OAW1385 - Check if needed to add translation OAW1385... Done
 Can't find ModeS in spotter_output - Done
Reg. : .G-TTOB - Ident : BA0851 - Label : Q0 - Message : 
Test if we add ModeS data...- Ident : BAW851 - Check if needed to add translation BAW851... Done
 Can't find ModeS in spotter_output - Done
Human readable data : ACARS link test
Reg. : .OH-LZK - Ident : AY07XL - Label : 5V - Message : 
Test if we add ModeS data...- Ident : FIN7XL - Check if needed to add translation FIN7XL... Done
 Can't find ModeS in spotter_output - Done
Reg. : .D-AIBA - Ident : LH02RM - Label : 5V - Message : 
Test if we add ModeS data...- Ident : DLH2RM - Check if needed to add translation DLH2RM... Done
 Can't find ModeS in spotter_output - Done
Reg. : .G-TTOB - Ident : BA0851 - Label : Q0 - Message : 
Test if we add ModeS data...- Ident : BAW851 - Check if needed to add translation BAW851... Done
 Can't find ModeS in spotter_output - Done
Human readable data : ACARS link test
Reg. : .G-TTOB - Ident : BA0851 - Label : Q0 - Message : 
Test if we add ModeS data...- Ident : BAW851 - Check if needed to add translation BAW851... Done
 Can't find ModeS in spotter_output - Done
Human readable data : ACARS link test
Reg. : .SP-LNE - Ident : LO0267 - Label : _d - Message : 
Test if we add ModeS data...- Ident : LOT267 - Check if needed to add translation LOT267... Done
 Can't find ModeS in spotter_output - Done

**Comment by sp2ong** [comment]
I have see information about aircraft when I have select from menu Explore -> Latest ACARS messages
but not information on map.

**Comment by Ysurac** [comment]
ACARS don't give enough information to put aircraft on map : a lot of messages don't have latitude and longitude. Only ADS-B give latitude, longitude and altitude.

**Comment by sp2ong** [comment]
Ah yes I have found that ACARS only used to send shor message but no any information about coordinates. Ok thanks

**Comment by sp2ong** [comment]
But I have read on:
https://github.com/brmlab/acarsdec

"Lots of ACARS messages are messages without position report, so be patient before seeing aircraft plotted on the map."

it is look like in ACAS message are exist position aircraft.

**Comment by Ysurac** [comment]
Some have this info, but it's not really usable to track aircraft : there is not enough messages with infos and not enough aircraft sending positions over ACARS. ADS-B is much better for that.

ACARS is used for now to populate database with aircraft name, departure/arrival airports,...

Maybe I will add ACARS on map later, but very difficult to test with so few usable messages...

**Comment by sp2ong** [comment]
Ok,

I have start my dump1090 and I can telnet to 30003 port and see message. I have configure FAM to listen dump1090 

dump1090 --modeac --net-sbs-port 30003 --net-beast --quiet --device-index 1 --net --metric --ppm -106 --enable-agc

and after run

./daemon-spotter.php 
Connecting...
Connection in progress to 192.168.1.1:30003(sbs)....
Connected!
SCAN MODE 

ERROR : socket_select give this error Operation now in progress
Restarting...
Shutdown all sockets...Restart all connections...Connection in progress to 192.168.1.1:30003(sbs)....
ERROR : socket_select give this error Operation now in progress
Restarting...
Shutdown all sockets...Restart all connections...Connection in progress to 192.168.1.1:30003(sbs)....
ERROR : socket_select give this error Operation now in progress
Restarting...
Shutdown all sockets...Restart all connections...Connection in progress to 192.168.1.1:30003(sbs)....

Is it normal ???

Best regards

**Comment by Ysurac** [comment]
no, it can't connect to 192.168.1.1 port 30003.

**Comment by sp2ong** [comment]
Why ??? when I have use in console 

telnet 192.168.1.1 30003  

I have connected and I have message displayed on console from dump1090

**Comment by Ysurac** [comment]
what is your value of **$globalSBS1TimeOut** in *require/settings.php* ?

**Comment by Ysurac** [comment]
And what is your version of PHP ? ( there is some bug with some old version and **socket_select** )

**Comment by sp2ong** [comment]
Hi,

I have use PHP 5.4.45 and  $globalSBS1TimeOut=15

**Comment by Ysurac** [comment]
The script connect to 192.168.1.1:30003 but it read no data for 60 seconds (**$globalSBS1TimeOut** value) and try to reconnect. Do you spot many aircraft ?

**Comment by sp2ong** [comment]
A OK, it is reconnect if no data after 60 second. I have spot aircraft but traffic is very low. In my area I have see on dump1090 with other web map solution one or three aircraft per hour

**Comment by Ysurac** [comment]
ok, you could increase **$globalSBS1TimeOut** if you want, reconnection are not really a problem.

**Comment by sp2ong** [comment]
Thank you very much for help and many thanks for your development of FlightAirMap solution, which is very useful.
Maybe it feature add to display aircraft position from ACARS will be nice 

Best regards

**Comment by Ysurac** [comment]
No problem
True, I will add it soon...

Thanks
