### ISSUE TITLE
Error after fresh install

### ISSUE THREAD

**Issue by linuxpronl** [Ysurac/FlightAirMap#134]
After having some problems, I pulled flighairmap from git, run install and that ended with an error null and daemon-spotter telling me:    

 ./daemon-spotter.php  &
[2] 8443
[root@mx1 scripts]# PHP Warning:  Packets out of order. Expected 1 received 0. Packet size=131072 in /data/nginx/sites/FlightAirMap/require/class.Spotter.php on line 1915
PHP Warning:  PDOStatement::execute(): MySQL server has gone away in /data/nginx/sites/FlightAirMap/require/class.Spotter.php on line 1915
PHP Warning:  PDOStatement::execute(): Error reading result set's header in /data/nginx/sites/FlightAirMap/require/class.Spotter.php on line 1915
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in /data/nginx/sites/FlightAirMap/require/class.Spotter.php:1915

No problems with MySQL by the way, actually MariaDB, other sites are working without a problem

**Comment by Ysurac** [comment]
You should check *max_allowed_packet* on MariaDB config and try to increase value.
