### ISSUE TITLE
daemon-spotter.php issue

### ISSUE THREAD

**Issue by linuxpronl** [Ysurac/FlightAirMap#135]
After doing a complete fresh install now I get 

You MUST update to latest schema. Run install/index.php

And that is just after running the install script...

**Comment by Ysurac** [comment]
True, I forget to update *config.sql*, you have to run this on Mysql/MariaDB:

    UPDATE airradar.config SET value = '14' WHERE config.name = 'schema_version';

**Comment by linuxpronl** [comment]
Thanks, that did the trick, although now daemon-spotter.php crashes : 

./daemon-spotter.php 
Connecting...
Connection in progress to 82.168.223.112:30003(sbs)....
Connected!
SCAN MODE 

*********** New aircraft hex : 49528A ***********
*********** New aircraft hex : 485122 ***********
*********** New aircraft hex : 485061 ***********
*********** New aircraft hex : 896199 ***********
*********** New aircraft hex : 44A8AD ***********
*********** New aircraft hex : 4D20CD ***********
*********** New aircraft hex : 471F5F ***********
PHP Warning:  Error while sending QUERY packet. PID=3198 in /data/nginx/sites/FlightAirMap/require/class.Spotter.php on line 1915
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in /data/nginx/sites/FlightAirMap/require/class.Spotter.php:1915
Stack trace:
#0 /data/nginx/sites/FlightAirMap/require/class.Spotter.php(1915): PDOStatement->execute(Array)
#1 /data/nginx/sites/FlightAirMap/require/class.SpotterImport.php(192): Spotter->getAllAircraftType('4841A5')
#2 /data/nginx/sites/FlightAirMap/scripts/daemon-spotter.php(670): SpotterImport->add(Array)
#3 {main}
  thrown in /data/nginx/sites/FlightAirMap/require/class.Spotter.php on line 1915

I adjusted the mariadb config :  max_allowed_packet=64M
