### ISSUE TITLE
No squawk found for medical urgency helicopter

### ISSUE THREAD

**Issue by linuxpronl** [Ysurac/FlightAirMap#137]
Hi,

I've noticed that no squawks (6221-6224) can't be found in acars_live or acars_archive. These are used by the Dutch medical urgency helicopters (called lifeliner). Should these heli's be in the database and shown on the map or are some kind of aircrafts filtered. These heli's are flying frequently and I think I should have received them regulary.

**Comment by Ysurac** [comment]
Squawks are send over ADS-B, they are not in ACARS messages.
Nothing is filtered, but all flights don't use ADS-B: some use FLARM (supported via glidernet APRS server) and some nothing other than voice radio.

**Comment by linuxpronl** [comment]
Okay, thanks, I'm pretty sure they use ADS-B but next time I speak a lifeliner pilot I'll ask. They fly VFR most of the time so perhaps they don't use their transponder...

**Comment by linuxpronl** [comment]
Haven't found the squawk the last week in the database, don't think they are using it.
