### ISSUE TITLE
No ACARS in archive

### ISSUE THREAD

**Issue by linuxpronl** [Ysurac/FlightAirMap#138]
The last days I receive ACARS messages and I can see them on the site. I expected to see older ACARS messages to be appear in archive, but they don't.  What am I missing ?

**Comment by Ysurac** [comment]
For now, only messages with label 10,80,81,82 or 3F (some free text messages) are put in archive.
I will put an option in config to choose which messages are archived.

**Comment by linuxpronl** [comment]
Okay, tnx.

**Comment by carlosmiranmm** [comment]
[http://www.carmachicago.com/profiles/acars.pdf](url)

**Comment by carlosmiranmm** [comment]
[the meaning of the label](https://github.com/gat3way/rtl_acars_ng/blob/master/datasets/acars_mls.txt)
