### ISSUE TITLE
empty screen

### ISSUE THREAD

**Issue by rstroom** [Ysurac/FlightAirMap#139]
I am fighting for a few day this script. Before I install I have a nice screen
![voor install](https://cloud.githubusercontent.com/assets/17556601/13441941/2d1c8f1a-dffa-11e5-8b41-f152d6b017ab.png)

After installing it's empty even settings what worked before installation. won't work anymore.
![after install](https://cloud.githubusercontent.com/assets/17556601/13441959/45864c80-dffa-11e5-920b-b068c1100868.png) 

What did I wrong?

I run a Ubuntu 14.04 VPS. 

This is what my error log reports: 

[Tue Mar 01 21:25:46.575577 2016] [ssl:warn] [pid 3522] AH01909: RSA certificate configured for xxxxxxxxxx.com:443 does NOT include an ID which matches the server name

Thanks.

**Comment by Ysurac** [comment]
Multiple possibilities:
* **$globalMapProvider** is not defined or defined to Mapbox without Id and token defined
* You choose a not working provider on settings on the left tab of map
* You defined not working values as latitude/longitude coverage area

If you don't find the error, you can paste your *require/settings.php* on pastebin.com without passwords.

**Comment by rstroom** [comment]
Step by step bud now I have the following error 



/var/www/vhosts/xxxxx.nl/httpdocs/scripts# php -f daemon-sp                                                                                             otter.php
Connecting...
Connection in progress to 127.0.0.1:30003(sbs)....
Connect to aircraftlist.json source (http://xx.xxx.xx.xxx:8080/VirtualRadar/Air                                                                                                 craftlist.json)...
Connect to aircraftlist.json source (http://global.adsbexchange.com/VirtualRadar                                                                                                 /AircraftList.json)...
Connected!
SCAN MODE

Wrong line format. Ignoring...
*5D4CA623AABC8F;Array
(
    [0] => *5D4CA623AABC8F;
)
Reconnect after an error...
Connection in progress to 127.0.0.1:30003(sbs)....
Connect to aircraftlist.json source (http://81.169.130.231:8080/VirtualRadar/Air                                                                                                 craftlist.json)...
Connect to aircraftlist.json source (http://global.adsbexchange.com/VirtualRadar                                                                                                 /AircraftList.json)...
*********** New aircraft hex : 4CA520 ***********
*********** New aircraft hex : 4CA770 ***********
*********** New aircraft hex : 4CAA5F ***********
*********** New aircraft hex : 4844C2 ***********
*********** New aircraft hex : 73920E ***********
*********** New aircraft hex : 4D20CF ***********
*********** New aircraft hex : 394C04 ***********
*********** New aircraft hex : 4A08E8 ***********
Check if aircraft is already in DB... Not in DB.
\o/ Add ROT56DD in archive DB : PHP Fatal error:  Cannot access protected proper                                                                                                 ty PDOException::$message in /var/www/vhosts/xxxxxxx.nl/httpdocs/require/cl                                                                                                 ass.Image.php on line 78

**Comment by Ysurac** [comment]
Fixed error display available in latest commit
