### ISSUE TITLE
daemon-spotter.php fails....  (sorry)

### ISSUE THREAD

**Issue by linuxpronl** [Ysurac/FlightAirMap#143]
PHP Warning:  PDOStatement::execute(): MySQL server has gone away in /data/nginx/sites/FlightAirMap/require/class.Spotter.php on line 1913
PHP Warning:  PDOStatement::execute(): Error reading result set's header in /data/nginx/sites/FlightAirMap/require/class.Spotter.php on line 1913
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in /data/nginx/sites/FlightAirMap/require/class.Spotter.php:1913
Stack trace:
#0 /data/nginx/sites/FlightAirMap/require/class.Spotter.php(1913): PDOStatement->execute(Array)
#1 /data/nginx/sites/FlightAirMap/require/class.SpotterImport.php(190): Spotter->getAllAircraftType('406D79')
#2 /data/nginx/sites/FlightAirMap/scripts/daemon-spotter.php(670): SpotterImport->add(Array)
#3 {main}
  thrown in /data/nginx/sites/FlightAirMap/require/class.Spotter.php on line 1913

**Comment by linuxpronl** [comment]
after a few restarts it seems to be working again...

**Comment by Ysurac** [comment]
Strange, this should never happen now...

**Comment by linuxpronl** [comment]
It just did, runnning it the 1st time after the last commit and running install/install.php and went away after a few restarts...

**Comment by Ysurac** [comment]
It happen often when too many connections are opened. Now I should open less connections...

**Comment by linuxpronl** [comment]
Otherwise I can also look in MariaDB is running out of connections, unlikely but I'll check it

**Comment by Ysurac** [comment]
yes, or with *netstat -lapute* if there is too many **TIME_WAIT**
You can also try to put **$globalDBPersistent = FALSE;** in *require/settings.php*.

**Comment by Ysurac** [comment]
as said on bug #144 : 
Bug was when **$globalFork** is set to **TRUE**.
I disabled forking in latest commit. This seems to work well for me. Fork was closing parent connection each time...

**Comment by linuxpronl** [comment]
Works again, tgnx
