### ISSUE TITLE
Statistic empty

### ISSUE THREAD

**Issue by sp2ong** [Ysurac/FlightAirMap#144]
When I have select z menu STATISTIC I have empty screen and in log:

PHP Fatal error:  Can't use method return value in write context in /var/www/radar/require/class.Stats.php on line 659,

**Comment by Ysurac** [comment]
Should work in latest commit, seems to be a limitation of PHP < 5.5

**Comment by rstroom** [comment]
I found this myself and it gives more errors, and the same doesn't move 

/var/www/vhosts/xxxxx.nl.nl/httpdocs/scripts# php -f daemon-sp                                                                                                 otter.php
Connecting...
Connection in progress to 127.0.0.1:30003(sbs)....
Connect to aircraftlist.json source (http://xx.xxx.xxx.xxx:8080/xxxxx.nl/Aircraftlist.json)...
Connect to aircraftlist.json source (http://global.adsbexchange.com/xxxxx.nl/AircraftList.json)...
Connected!
SCAN MODE

Wrong line format. Ignoring...
*A0000232DD296B122114236C4A3E;Array
(
    [0] => *A0000232DD296B122114236C4A3E;
)
Reconnect after an error...
Connection in progress to 127.0.0.1:30003(sbs)....
Connect to aircraftlist.json source (http://xx.xxx.xxx.xxx:8080/xxxxx.nl/Aircraftlist.json)...
Connect to aircraftlist.json source (http://global.adsbexchange.com/xxxxx.nl/AircraftList.json)...
*********** New aircraft hex : 47806E ***********
*********** New aircraft hex : 48A449 ***********
*********** New aircraft hex : 4492E9 ***********
*********** New aircraft hex : 4CA9C3 ***********
*********** New aircraft hex : 48418A ***********
Check if aircraft is already in DB... Not in DB.
\o/ Add KLM39S in archive DB : PHP Notice:  Undefined property: PDOException::$getMessage in /var/www/vhosts/xxxxx.nl.nl/httpdocs/require/class.Image.php on line 78
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in /var/www/vhosts/xxxxx.nl.nl/httpdocs/require/class.Spotter.php:2010
Stack trace:
#0 /var/www/vhosts/xxxxx.nl.nl/httpdocs/require/class.Spotter.php(2010): PDO Statement->execute(Array)
#1 /var/www/vhosts/xxxxx.nl.nl/httpdocs/require/class.Spotter.php(2794): Spotter->getAircraftOwnerByRegistration('PH-BXO')
#2 /var/www/vhosts/xxxxx.nl.nl/httpdocs/require/class.SpotterImport.php(525): Spotter->addSpotterData('48418A-20160304...', 'KLM39S', 'B739', 'EHAM', 'LIPZ', 52.259262, 4.787064, '', 25, 164, 191, '2016-03-04 19:4...', '', '', '3170', NULL, '', '48418A', 'PH-BXO', '', '', '', false, 'aircraftlistjso...')
#3 /var/www/vhosts/xxxxx.nl.nl/httpdocs/scripts/daemon-spotter.php(357): SpotterImport->add(Array)
#4 {main}
  thrown in /var/www/vhosts/xxxxx.nl.nl/httpdocs/require/class.Spotter.php on line 2010

**Comment by Ysurac** [comment]
Same bug as #143 
You can also try to put **$globalDBPersistent = FALSE;** in *require/settings.php*.
Else you can try to increase **max_connections** in *mysql/my.cnf*.

**Comment by sp2ong** [comment]
Ok I have php 5.4 and with latest FAM working statistics

Thanks

Waldek

**Comment by rstroom** [comment]
siil the same no difference

**Comment by rstroom** [comment]
i change now from distri from ubuntu to centos

**Comment by Ysurac** [comment]
This seems to be a bug when **$globalFork** is set to **TRUE** in *require/settings.php*.

**Comment by Ysurac** [comment]
I disabled forking in latest commit. This seems to work well for me. Fork was closing parent connection each time...
