### ISSUE TITLE
Phpvms install

### ISSUE THREAD

**Issue by Fredd-30** [Ysurac/FlightAirMap#145]
Please someone can help to me to setup scripts for phpvms please?
http://www.skydream-airlines.com/flightairmap

for now just empty screen

Regards Fred

**Comment by Ysurac** [comment]
There was a bug when **$globalAirportPopup** was set to **TRUE** in *require/settings.php*. This is fixed in latest commit and you should not see an empty screen after update.

**Comment by Fredd-30** [comment]
Thanks Fix the map is Ok but missing acarsdata
`<?php
//INSTALLED OR NOT ?
$globalInstalled = FALSE;

//GLOBAL SITE NAME
$globalName = 'SkyDream-Airlines';

// GLOBAL URL
$globalURL = 'http://www.skydream-airlines.com/flightairmap';

// Logo URL
$logoURL = '/images/logo2.png';

// Activate debug
$globalDebug = TRUE;

// LANGUAGE
$globalLanguage = 'FR'; // Used only for wikipedia links for now

// MAP PROVIDER
$globalMapProvider = 'OpenStreetMap'; // Can be Mapbox, OpenStreetMap, MapQuest-OSM or MapQuest-Aerial
$globalMapboxId = 'examples.map-i86nkdio'; // Mapbox id
$globalMapboxToken = ''; // Mapbox token

//COVERAGE AREA (its based on a box model. i.e. top-left | top-right | bottom-right | bottom-left)
$globalLatitudeMax = '46.92'; //the maximum latitude (north)
$globalLatitudeMin = '42.14'; //the minimum latitude (south)
$globalLongitudeMax = '6.2'; //the maximum longitude (west)
$globalLongitudeMin = '1.0'; //the minimum longitude (east)

$globalCenterLatitude = '46.38'; //the latitude center of your coverage area
$globalCenterLongitude = '5.29';//the longitude center of your coverage area

$globalLiveZoom = '9'; //default zoom on Live Map

// FLIGHTS MUST BE INSIDE THIS CIRCLE
$globalDistanceIgnore = array();
// ^^ example for 100km : array('latitude' => '46.38','longitide' => '5.29','distance' => '100');

// DATABASE CONNECTION LOGIN
$globalDBdriver = 'mysql'; // PDO driver used. Tested with mysql, maybe pgsql or others work...
$globalDBhost = 'localhost'; //database connection url
$globalDBuser = ''; //database username
$globalDBpass = ''; //database password
$globalDBname = ''; //database name
$globalTransaction = TRUE; //Activate database transaction support


//FLIGHTAWARE API INFO
$globalFlightAware = FALSE; //set to TRUE to use FlightAware as data import
$globalFlightAwareUsername = ''; //FlightAware Username
$globalFlightAwarePassword = ''; //FlightAware Password/API key

// TIMEZONE
$globalTimezone = 'Europe/Paris';

// DAEMON
$globalDaemon = TRUE; // Run cron-sbs.php as daemon (don't work well if source is a real SBS1 device)
$globalCronEnd = '60'; //the script run for xx seconds if $globalDaemon is disable in SBS mode

// FORK
$globalFork = TRUE; // Allow cron-sbs.php to fork to fetch schedule, no more schedules fetch if set to FALSE

// MINIMUM TIME BETWEEN UPDATES FOR HTTP SOURCES (in seconds)
$globalMinFetch = '50';

// DISPLAY FLIGHT INTERVAL ON MAP (in seconds)
$globalLiveInterval = '200';

// LIVE MAP REFRESH (in seconds)
$globalMapRefresh = '30';

// IDLE TIMEOUT (in minutes)
$globalMapIdleTimeout = '30';

// DISPLAY INFO OF FLIGHTS IN A POPUP
$globalMapPopup = TRUE;

// DISPLAY ROUTE OF FLIGHT
$globalMapRoute = TRUE;

// DISPLAY FLIGHTS PATH HISTORY
$globalMapHistory = TRUE;

// WRAP MAP OR REPEAT
$globalMapWrap = TRUE;

//IVAO
$globalIVAO = TRUE;

//VATSIM
$globalVATSIM = FALSE;

//User can choose between IVAO or VATSIM
$globalMapVAchoose = TRUE;

//ADS-B, SBS1 FORMAT
$globalSBS1 = FALSE; //set to FALSE to not use SBS1 as data import
$globalSBS1Hosts = array('http:','http://www.skydream-airlines.com/action.php/acars/data','http://api.ivao.aero/getdata/whazzup/whazzup.txt');
// ^^ in the form array('host1:port1','host2:port2','http://xxxxx/whazzup.txt'); Use only sources you have the rights for.
$globalSBS1TimeOut = '15';
$globalSBS1update = '10'; //Put data in DB after xx seconds/flight

//ACARS Listen in UDP
$globalACARS = FALSE;
$globalACARSHost = '0.0.0.0'; // Local IP to listen
$globalACARSPort = '9999';

//Minimal distance to tell if a flight is arrived to airport (in km)
$globalClosestMinDist = '10';

// To display Squawk usage we need Squawk country for now
$globalSquawkCountry = 'FR';

//BIT.LY API INFO (used in the search page for a shorter URL)
$globalBitlyAccessToken = ''; //the access token from the bit.ly API

//British Airways API info
$globalBritishAirwaysKey = '';

// Lufhansa API info
$globalLufthansaKey = array('key' => '','secret' => '');

// Transavia API info
$globalTransaviaKey = '';

//ignore the flights during imports that have the following airports ICAO (departure/arrival) associated with them
$globalAirportIgnore = array();
//accept the flights during imports that have the following airports ICAO (departure/arrival) associated with them
$globalAirportAccept = array();

//ignore the flights that have the following airline ICAO
$globalAirlineIgnore = array();
//accept the flights that have the following airline ICAO
$globalAirlineAccept = array();

//accept the flights that have the following pilot id (only for VA)
$globalPilotIdAccept = array();

//Archive all data
$globalArchive = TRUE;

//NOTAM
$globalNOTAM = TRUE;
$globalNOTAMSource = ''; //URL of your feed from notaminfo.com

//METAR
$globalMETAR = TRUE;
$globalMETARcycle = TRUE; // If update_db.php in cron job, all METAR are downloaded from NOAA
// else put an url as METAR source, can be vatsim.
$globalMETARurl = ''; // Use {icao} to indicate where airport icao must be put in url

//Retrieve private Owner
$globalOwner = FALSE;

//Retrieve Image from externals sources
$globalAircraftImageFetch = TRUE;
//Sources for Aircraft image
$globalAircraftImageSources = array('ivaomtl','wikimedia','airportdata','deviantart','flickr','bing','jetphotos','planepictures','planespotters');

//Retrieve schedules from externals sources (set to FALSE for IVAO or if $globalFork = FALSE)
$globalSchedulesFetch = TRUE;
//Sources for airline schedule if not official airline site
$globalSchedulesSources = array('flightmapper','costtotravel','flightradar24','flightaware');

//Retrieve translation from external sources (set to FALSE for IVAO)
$globalTranslationFetch = TRUE;
//Sources for translation, to find name of flight from callsign
$globalTranslationSources = array();

$globalAircraftSize = '';

$globalMapAltitudeColor = TRUE;

$globalAircraftIconColor = '1a3151';

$globalAirportZoom = '7';

$globalAirportPopup = FALSE;
?>
`
Something wrong ?

**Comment by Ysurac** [comment]
**$globalURL** should be **$globalURL = '/flightairmap'** only
**$globalSBS1Hosts** should be : $globalSBS1Hosts = array('http://www.skydream-airlines.com/action.php/acars/data','http://api.ivao.aero/getdata/whazzup/whazzup.txt');

Else I will test your config this evening.

**Comment by Fredd-30** [comment]
Merci beaucoup :) mais même en changeant les URL il ne se passe rien

**Comment by Ysurac** [comment]
**scripts/daemon-spotter.php** est lancé ?

**Comment by Fredd-30** [comment]
non, il y a t'il un autre moyen de communications entre toi et moi stp ?

**Comment by Fredd-30** [comment]
Page blanche avec mon IP

**Comment by Ysurac** [comment]
**scripts/daemon-spotter.php** doit être lancé pour remplir la base de donnée.
Soit en tant que service (en utilisant *install/init/flightairmap.init.openrc* si openrc est utilisé), soit en *cron job* mais pour cela **$globalDaemon** doit être **FALSE**

**Comment by Ysurac** [comment]
Sinon en moyen de communication je suis sur IRC: Freenode, channel #flightairmap par exemple.

**Comment by Fredd-30** [comment]
en faisant http://www.skydream-airlines.com/flightairmap/scripts/daemon-spotter.php

page blanche avec mon ip

Tu n'as pas skype ?

**Comment by Ysurac** [comment]
Il ne peut pas être lancé depuis un navigateur. Uniquement en tant que service en le lançant dans une console, ou en le lançant dans un cron job.

Je n'ai pas skype.

**Comment by Fredd-30** [comment]
je suis sur le channel

**Comment by Ysurac** [comment]
non

**Comment by Fredd-30** [comment]
irc je viens de m'y mettre je n'ai jamais utilisé
