### ISSUE TITLE
Popup links

### ISSUE THREAD

**Issue by sp2ong** [Ysurac/FlightAirMap#146]
When I have open popup flight info and try to click from this window following 

The requested URL /redirect/3C66A8-201603050809 was not found on this server.

The requested URL /registration/D-AIUH was not found on this server.

The requested URL /airport/UUDD was not found on this server.

My www patht is 

/radar/....

When I have put manually to url:  /radar/airport/UUDD 
all display correct
  
it is look like links from popup window have missed my path url

**Comment by Ysurac** [comment]
what is set to **$globalURL** in *require/settings.php* ?

**Comment by Ysurac** [comment]
A bug. Fixed.
