### ISSUE TITLE
Add more in statistic

### ISSUE THREAD

**Issue by sp2ong** [Ysurac/FlightAirMap#147]
It will be nice to have in statistic display polar plot . It is coverage of detected aircraft 
like similar on image:

[http://rtlsdrblog.rtlsdrblog.netdna-cdn.com/wp-content/uploads/2015/04/modesdeco2.png](http://rtlsdrblog.rtlsdrblog.netdna-cdn.com/wp-content/uploads/2015/04/modesdeco2.png)

[http://livedoor.blogimg.jp/jg3pup/imgs/b/d/bddbc6c9.jpg](http://livedoor.blogimg.jp/jg3pup/imgs/b/d/bddbc6c9.jpg)

it is useful information about our pattern  antenna 

Regards

Waldek

**Comment by Ysurac** [comment]
True, it's why I added "offline" statistics calculation. It use too much time/CPU/memory to do that each time it's requested. A "cron job" will do that (and a lot more statistics like countries,...)

**Comment by Ysurac** [comment]
Polar is added in statistics and on map.
