### ISSUE TITLE
Timezone problem

### ISSUE THREAD

**Issue by kletellier** [Ysurac/FlightAirMap#149]
I've a timezone problem... I've updated to last version (and as a noobs, i've not saved the previous commit id...) .

And in the site my flight lists appears with one hour added ex : for a flight at 9:00 am it's writted 10:00 am

Here is my configuration : 

Rpi 2 with debian Jessie , default MySQL provided with distribution

Php timezone : Europe/Paris
Website (settings.php) : Europe/Paris
MySQL Timezone : @System
System Timezone : Europe/paris

after few search in db, it seems that in spotter_live date was saved in utc time, and spotter_output in timezone time 

ex for 1 flight seen at 09:00am (Europe/Paris)

in spotter_live : 08:00am
in spotter_output : 09:00am
displaying in website : 10:00am

Pb also occurs on my other Rpi1

**Comment by Ysurac** [comment]
There was a bug in spotter live. I will check display in site now...
