### ISSUE TITLE
Populate database with externals data... forever

### ISSUE THREAD

**Issue by jmr123** [Ysurac/FlightAirMap#15]
It said "can be very slow" Waited 30min. 
install/index.php just spinning. No error messages. 
Ubuntu 14.04, apache2, mysql5.6, fresh install.

apache error log shows, dunno if it helps.
[Fri May 08 22:24:42.911869 2015] [:error] [pid 4402] [client myip:62591] PHP Notice:  ob_end_flush(): failed to delete and flush buffer. No buffer to delete or flush in /var/www/FlightAirMap/install/index.php on line 536, referer: http://myhost/FlightAirMap/install/

**Comment by jmr123** [comment]
Ok.. I'm polling the database and it seems it's doing something, so standy, it just might take that long ;)

**Comment by Ysurac** [comment]
The error in log is not really important.
I've added a console install script in commit 0ee43965784aa634f35a72249fa5b8e679d35566 : install/install_db.php
This will populate DB (or at least, this will tell you where it fails).

**Comment by jmr123** [comment]
It's been populating database for a hour, but i can see it's putting more data to 'routes' table from mysql client. Should I wait or abort and try the new commit?
Is it really taking over a hour to populate the database?
How many routes there?

**Comment by Ysurac** [comment]
If it's putting data, it's not died at least.
If you put $globalTransaction to TRUE in *require/settings* this will be really faster (if it works). I will put this by default I think...
You can stop and then run install_db.php script without problem if you want.

**Comment by jmr123** [comment]
It's not working with $globalTransactions = true. Still spinning... ( now it doesn't load anything to 'routes' table though ). Can you tell how long it normally takes to finish?

**Comment by jmr123** [comment]
Running update_db.php..

PHP Parse error:  syntax error, unexpected ';' in /var/www/cc/FlightAirMap/install/class.update_db.php on line 478

**Comment by jmr123** [comment]
And update_db.php in browser:
#!/usr/bin/php
That's all I get.

**Comment by Ysurac** [comment]
With *globalTransaction* all is put in the table at the same time for each table. At least it work for me, but it seems not with some old MySQL/MariaDB versions.
Fix for *update_db.php* in commit f533911fa353cc62612837bd96705390fe7954fb
install_db.php or update_db.php should be run in console, not inside browser even if they should work without the first line *#!/usr/bin/php*

Time to sleep here, no bugfix for about 8-9 hours ;)

**Comment by jmr123** [comment]
Didn't work.. Still same problm. Can you try with fresh ubuntu if it works?

**Comment by Ysurac** [comment]
If you run *install/install_db.php* in console, what do you get ? (in browser you can't have debug log)
If it don't show any log, check if *$globalDebug = TRUE* in *require/settings.php*

**Comment by jmr123** [comment]
Routes : Download...Gunzip...Add to DB... - Delete previous routes from DB - - Add routes to DB -

It's stuck in there

**Comment by Ysurac** [comment]
What DB do you use and what is the version ?

**Comment by jmr123** [comment]
mySQL version  5.6.19-0ubuntu0.14.04.1

**Comment by Ysurac** [comment]
ok, not so old...
php version ?

**Comment by jmr123** [comment]
PHP 5.5.9-1ubuntu4.9 (cli) (built: Apr 17 2015 11:44:57)

**Comment by Ysurac** [comment]
I think all is ok with PHP modules because some lines was added to route table...
All should work... Can be very very slow if it's on a very very slow computer... Not yet tested by me on a raspberry for example...
