### ISSUE TITLE
Best dump1090 options

### ISSUE THREAD

**Issue by linuxpronl** [Ysurac/FlightAirMap#151]
What options are best when receiving ads-b signals, my current parameters are: 

dump1090  --net --phase-enhance --forward-mlat --mlat --raw --mlat

**Comment by Ysurac** [comment]
--gain and --ppm can help

**Comment by linuxpronl** [comment]
I ran kal to get the ppm (-1.4 in my case)   Is there a way to determine the optimal gain ?

**Comment by Ysurac** [comment]
Not really, only testing.
*--gain -10* set it to tuner AGC, else you can try *--enable-agc* (without using *--gain*) to use RTL AGC.

**Comment by linuxpronl** [comment]
works
