### ISSUE TITLE
Difference between positions in dump1090

### ISSUE THREAD

**Issue by linuxpronl** [Ysurac/FlightAirMap#152]
I notice a difference between the flights with positions in the webinterface of dump1090 and flightairmap. Eg. in dump 1090 I have 97 total aircrafts and 59 with positions, in flightairmap I see 38 aircrafts detected.  How can that be such a big difference ?

**Comment by Ysurac** [comment]
Maybe you set **$globalLiveInterval** in *require/settings.php* too low.
If *daemon-spotter.php* is running as daemon not as cron job, there should not be a big difference (or more flight in FlightAirMap if **$globalLiveInterval** is big).

**Comment by linuxpronl** [comment]
These are my settings.. can you advise?

$globalDaemon = TRUE; 
$globalCronEnd = '30'; 
$globalMinFetch = '30';
$globalMapRefresh = '30';
$globalLiveInterval = '30';

My idea was to update the map every 30seconds but it doesn't work if I'm missing planes :)

**Comment by Ysurac** [comment]
You have to increase **$globalLiveInterval**. Default is 200 for example. With your config if last message from a flight is more than 30s old, the flight will not be displayed.

**Comment by linuxpronl** [comment]
Aha.. it works that way, I'm gonna change the setting.. now dump1090 is showning 87 planes with positions and flightairmap only shows 51... let you know

**Comment by linuxpronl** [comment]
restarted the daemon-spotter.php and refreshed the fam site.. still a big difference 74 - 66 ... any more suggestions I might try ?

**Comment by Ysurac** [comment]
Increase it... I don't know the timeout of Dump1090.

**Comment by linuxpronl** [comment]
changed it to 250, now the difference is minimal, tnx
