### ISSUE TITLE
Heli shown via dump1090 but not on fam

### ISSUE THREAD

**Issue by linuxpronl** [Ysurac/FlightAirMap#154]
I've found out that sometimes I see heli's flying by on the web output of dump1090 via MLAT. These flights doesn't show in FAM. Is this correct or am I doing something wrong ?

**Comment by Ysurac** [comment]
If you set **--forward-mlat** option to Dump1090 you should see them on FlightAirMap.

**Comment by linuxpronl** [comment]
Done.
