### ISSUE TITLE
Error trafic Ivao Vatsim

### ISSUE THREAD

**Issue by bilkaPek** [Ysurac/FlightAirMap#157]
since the last commit
IVAO and VATSIM traffic and no longer works correctly
the traffic is limited not exceed the 20 aircraft on map

**Comment by Ysurac** [comment]
In fact all seems to work properly now. Time inside whazzup and vatsim-data files are now used and not generated.
If you want to see flight older increase **$globalLiveInterval** in *require/settings.php*.

**Comment by Ysurac** [comment]
Fixed now. Data used as time was *time logon*, it's not good.

**Comment by bilkaPek** [comment]
Merci

**Comment by bilkaPek** [comment]
pardon 
je me suis fait mal comprendre
ce que je voulais dire c'est que le nombres d'avion affiche sur la carte et incorrect 
il m'en affiche pas plus 20 alors qu'il devrait affiche tout le trafic (Ivao ou vatsim )

pas de filtrage pour les pilotes 

$globalLiveInterval = '300';
$globalMapRefresh = '120';
$globalPilotIdAccept = array();

**Comment by Ysurac** [comment]
Oui j'avais compris. Ce coup ci le dernier commit doit fonctionner.
