### ISSUE TITLE
Install/Update/Check Databases

### ISSUE THREAD

**Issue by nzradar** [Ysurac/FlightAirMap#16]
During the install of the current latest revision, at least the routes table and aircraft_modes table are not created which causes all other updates and checks of the database to fail!  I'm not sure which other tables are not created.

**Comment by nzradar** [comment]
After the third install attempt I get the following error, so it tries to create the routes table:

ERRORERROR (ADD NEW COLUMNS TO ROUTES TABLE) : SQLSTATE[42000]: SYNTAX ERROR OR ACCESS VIOLATION: 1067 INVALID DEFAULT VALUE FOR 'DATE_ADDED'

I'm not sure where this code is so I can't check out why it fails.

**Comment by Ysurac** [comment]
This fail because MySQL < 5.6.5. CURRENT_TIMESTAMP as default value for DATETIME type is not available before.

**Comment by nzradar** [comment]
So this will never work for me if I have MySQL 5.5.41?  Is that what you are saying?

**Comment by Ysurac** [comment]
True, or I will have to support MySQL < 5.6...
You can try to remove "DEFAULT CURRENT_TIMESTAMP" in *class.update_schema.php*.
For example :
sed -i 's: DEFAULT CURRENT_TIMESTAMP::g' install/*.php

This should work.

**Comment by Ysurac** [comment]
Latest version should work with MySQL 5.5 (only airspaces can't work).
