### ISSUE TITLE
error  beta 0.5 ubuntu

### ISSUE THREAD

**Issue by rstroom** [Ysurac/FlightAirMap#160]
output install/index.php

Write configuration....SUCCESS
Update schema if needed....SUCCESS
Error : error (import ../db/stats_country.sql) : SQLSTATE[42000]: Syntax error or access violation: 1068 Multiple primary key defined

**Comment by Ysurac** [comment]
Yes there is a bug in beta 0.5

**Comment by Ysurac** [comment]
To solve the bug run this in MySQL/MariaDB :  **UPDATE `config` SET `value` = '18' WHERE `name` = 'schema_version';**
