### ISSUE TITLE
Search page doesn't load at all or very slowy

### ISSUE THREAD

**Issue by szarka77** [Ysurac/FlightAirMap#162]
Hi Ysurac:

Merci bien for all your work on flightairmap.  

I am having a problem with the search page. It loads very slowly or sometimes not at all. Sometimes I get a "script unresponsive" error also. Doesn't matter what browser I use, same result.

www.kpw3.com/flight

Any thoughts on this? Maybe newer version of jquery?

Thanks.

**Comment by Ysurac** [comment]
I know this page is too slow and too big. I need to find a way to optimize it. Maybe with some AJAX... This will be for next week.

**Comment by szarka77** [comment]
Thanks for the new fixes.  

It does seem a bit faster to recover but unfortunately still quite slow. I am still getting an "unresponsive script" error in both Chrome and Firefox.  If I wait long enough the search function does work and will display results. After the results are displayed the script hangs again and the page cannot be scrolled up and down for a long time and displays the same script error. Sorry!

Could this be related to the huge list of airports that the page is downloading?

**Comment by szarka77** [comment]
After installing the latest commits the search page is **much** faster and responsive than before. 

Bon travail!
