### ISSUE TITLE
after latest pull SQL error

### ISSUE THREAD

**Issue by linuxpronl** [Ysurac/FlightAirMap#165]
After the last update I get 

Write configuration....SUCCESS
Update schema if needed....SUCCESS
Error : error (import ../db/stats_country.sql) : SQLSTATE[42000]: Syntax error or access violation: 1068 Multiple primary key defined

When running /install ...

**Comment by Ysurac** [comment]
What is the value of *schema_version* in **config** table ?

    SELECT value FROM `config` WHERE `name` = 'schema_version';

If it's 17, for unknow reason schema version wasn't updated so type this in MySQL/MariaDB :   

    UPDATE `config` SET `value` = '18' WHERE `name` = 'schema_version';

**Comment by linuxpronl** [comment]
If I ran the update query to set the schema_version to 18 I get:

Write configuration....SUCCESS
Update schema if needed....SUCCESS
Error : error (update stats) : SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'type'

**Comment by Ysurac** [comment]
Really strange... You insert some files from **db/** manually ?
