### ISSUE TITLE
Stats table not incrementing

### ISSUE THREAD

**Issue by szarka77** [Ysurac/FlightAirMap#166]
In my installation flights_bymonth in stats table is not incrementing.  It has stopped at 821 flights.  Not sure why this is.  It has happened 3 times.  Not always at 822 but at other seemingly random numbers. The other times I have just deleted everything and created a new database. I'd really like to stop doing that.  8-)

The spotter_live table continues to record new flights but the stats do not change.

Server information:

    Server: Localhost via UNIX socket
    Server type: MariaDB
    Server version: 10.0.23-MariaDB-log - MariaDB Server
    Protocol version: 10
    Server charset: UTF-8 Unicode (utf8)
    Apache/2.4.18 (Fedora) PHP/5.6.19
    Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503
    PHP extension: mysqli curl mbstring
    PHP version: 5.6.19

Thoughts?

**Comment by Ysurac** [comment]
You have to put the script **scripts/update_db.php** in a cron job. This script update stats.
Don't put it too often, there is a bug for now: It can run even if previous one was not finished, this will be fixed next week.

**Comment by szarka77** [comment]
Sorry wasn't aware of that.  That's done it.  I've set a cron to run every 5 minutes. I now get the updates. 

Thanks.

**Comment by Ysurac** [comment]
ok and bug is fixed; it will not run if already running (only need to make this work under windows maybe...)
