### ISSUE TITLE
Question about Latest ACARS Messages page

### ISSUE THREAD

**Issue by szarka77** [Ysurac/FlightAirMap#167]
I notice that this page, "Latest ACARS Messages," never actually has any data in it. At the same time, the "Archived ACARS Messages" page does have data. I am wondering why this is?

I am running daemon-acars.php and it seems to run very well. .

Thanks.

**Comment by Ysurac** [comment]
You should see some, but live ACARS messages keep only messages for 30 minutes.

**Comment by szarka77** [comment]
Hmmmmm....I just got an ACARS message:  Sun, 10 Apr 2016 13:43:43 -0400 local time on the archive page but not on the Latest ACARS messages page.  Only 7 minute difference.  Not a big problem I suppose since I do get the messages.
