### ISSUE TITLE
Unit of measure KM is hardcoded into table-output.php

### ISSUE THREAD

**Issue by szarka77** [Ysurac/FlightAirMap#168]
First, sorry to be spamming you so much with all my questions and comments...!

I see that table-output.php line 507 has the following code:
`	if ($distance != '') echo '<br/><i>'.$distance.'km</i>'; 
`
Line 554 also has this code:
`if ($distance != '') echo '<br/><i>'.$distance.'km</i>';`

I mention this because when I changed the unit of measure from km to miles on line 137 of require/class.Common.php:
`public function distance($lat, $lon, $latc, $lonc, $unit = 'km') {`
The distances displayed on the "Current Activity" page (currently.php) are correct in miles or meters or whatever unit of measure one chooses, but the page always displays the unit as km.

I changed this by editing lines 507 and 554 above to:
`if ($distance != '') echo '<br/><i>'.$distance.' miles</i>';`
Of course, this is not a big problem, but perhaps the unit of measure could be changed to a variable rather than hardcoded in table-output.php?

The more I look at your code the more I realize that you must have spent hundred of hours creating it.
Thanks so much for sharing it!

**Comment by Ysurac** [comment]
True. In fact this could be better everywhere on the site. Or display both each time ?

**Comment by szarka77** [comment]
One or the other would be fine for me but some people may like to display both.
