### ISSUE TITLE
Arrivals seen and incorrect KBGR elevation

### ISSUE THREAD

**Issue by szarka77** [Ysurac/FlightAirMap#169]
In the database's airport table KBGR is listed at an elevation of 192 meters (629 feet). This should actually be about 58 meters (192 Feet) so I edited the altitude field and made it 58. I am wondering if this is why I only show one arrival on the stats page when I know there have been dozens? The elevation at my receive location is 145 feet or about 44 meters.

I also note that a number of small airports in my area (Maine, USA) 0B2 for example, have substituted feet for meters. 0B2 is listed at 124 meters, but should actually be 124 feet.  ME68 and KBHB are also off by hundreds of feet.

Is there a global fix for this in one of the scripts or does the entire database need to be edited?

**Comment by Ysurac** [comment]
I will check if I can fix database. I think all airports in US don't have the correct elevation.
To see more arrivals seen, you could try to increase **$globalClosestMinDist** in *require/settings.php*.

**Comment by Ysurac** [comment]
All elevations are in feet in database, the error is where it's in meter. I will check if there is no errors in DB.
Check for closest airport should be better in latest commit.

**Comment by szarka77** [comment]
Ok, I had it set for 8 Km and I've changed it to 30.  We'll see what happens.

**Comment by Ysurac** [comment]
I set it to 50km, airports are not so close and ADS-B data is not send so often in fact.

**Comment by szarka77** [comment]
D'accord then 50 it is.

**Comment by jmceara** [comment]
I"m not sure if is the same problem, but I only see 1 arrival in my local airport. In database, my airport is set to 1804 (550 meters) and it's correct. My settings are for '50' (default) and I have a lot of arrivals in my airport, but only one in database. I'm about 6,5Km from airport.
