### ISSUE TITLE
No Flights on Map 

### ISSUE THREAD

**Issue by nzradar** [Ysurac/FlightAirMap#17]
I now have a database and cron-sbs is running with data going in to the tables, yahoo!

But........I have no planes on the map and when I click on EXPLORE >> LATEST ACTIVITY I get an 404 error.  No other PHP pages load from clicking on the menu items.  If I click on STATISTICS I get a 404 error but if I append .php I get some nice statistics.

I have changed from nginx to apache2 but don't thing the configuration is set up correctly.  Any ideas?

Cheers,
Michael

**Comment by Ysurac** [comment]
This is a problem with the *.htaccess*.
You need to have *AllowOverride All* in Apache site conf and rewrite module installed.

**Comment by nzradar** [comment]
I have the AllowOveride All set in sites-enabled/000-default and no .htaccess files but still the same, so the only thing I don't understand is your reference to rewrite module being installed.

**Comment by Ysurac** [comment]
There is a *.htaccess* file with FlightAirMap.
*mod_rewrite* is an Apache module.

**Comment by nzradar** [comment]
OK, I copied the .htaccess into the /var/www/ folder and I now have aircraft but I can't load the pages when I click on the menu items.  This can be tested at http://118.92.188.70

**Comment by Ysurac** [comment]
Strange... It's working for */live/geojson* but no others pages... So Apache seems to read *.htaccess*. Check your log, I have no idea, this should work.

**Comment by nzradar** [comment]
OK thanks.
