### ISSUE TITLE
ACARS Archived messages page

### ISSUE THREAD

**Issue by szarka77** [Ysurac/FlightAirMap#170]
When clicking on the Aircraft History drop-down at the extreme right under the date column it seems that all registration results are prefixed with a '.' 

Examples: /flight/registration/**.**G-CIVS  and  /flight/registration/**.**F-GSPR

Of course, this generates the message, "Sorry, this registration does not exist in this database. :("

If I remove the leading '**.**' from the generated search URL then the search succeeds. 

Thanks.

**Comment by Ysurac** [comment]
Should be fixed.
