### ISSUE TITLE
Access password Protected VRS Website

### ISSUE THREAD

**Issue by Reloc** [Ysurac/FlightAirMap#171]
Hi,

I'm trying to retrieve aircraftlist.json from a VRS website that is protected with a username / password.
I've looked in the settings.php file but can't see where I would as the login details.

Running the cron-sbs.php shows connected but nothing else

:/var/www/html/scripts$ php -f cron-sbs.php
Connecting...
Connect to aircraftlist.json source (http://xxxx.xxxx.com/VirtualRadar/Aircraftlist.json)...
Connected!
SCAN MODE

Thanks
Nigel

**Comment by Ysurac** [comment]
I don't know if it's possible. Maybe try *http://user:pass@xxxx.xxxx.com/VirtualRadar/Aircraftlist.json*.
I never tried, I don't have any example case to test.

**Comment by Reloc** [comment]
Hi,

Thanks for the tip it worked perfectly :)

Nigel

**Comment by Ysurac** [comment]
Good.
