### ISSUE TITLE
Aircraft Detected Zero

### ISSUE THREAD

**Issue by Reloc** [Ysurac/FlightAirMap#173]
Hi,

When I run # php daemon-spotter.php or cron-sdb.php from the command line I can see that database is being added to & "Aircraft Detected" on the website starts to rise to maybe 500 or so. After a few mins the number will drop to zero & no aircraft are displayed on the web page , however I do not see any error messages in the console even with $globalDebug = TRUE set in the settings.php

I'm collecting live flight data from a VRS Server Aircraftlist.json file hosted on a remote server & don't see anything on that side that would indicate a problem there.

Thanks
Nigel

**Comment by Ysurac** [comment]
**daemon-spotter.php** is running as daemon with **$globalDaemon = TRUE;** in *require/settings;php* ? If yes, on console you should see data when an aircraft is added and moving.

**Comment by Reloc** [comment]
Yes I have that option set , I see data being added even when the A/C detected on the webpage is zero

**Comment by Ysurac** [comment]
What is the content of **http://yourinstall/live/geojson** ?
If there is no error in this file (*"flight_cnt": "0"}*), you can increase **$globalLiveInterval**, at something like 600 or more.

**Comment by Reloc** [comment]
At the moment live-geojson show's this

{"type": "FeatureCollection","minimal": "true","features": {"type": "Feature","properties": {"flight_cnt": "0"}}}

If I kill damon-spotter.php & restart it then live-geojson show's

![live-geojson](https://cloud.githubusercontent.com/assets/13242284/14492598/acde2450-0180-11e6-9d16-b07f36adfaa5.jpg)

Then after a few minutes "{"type": "FeatureCollection","minimal": "true","features": {"type": "Feature","properties": {"flight_cnt": "0"}}}"

**Comment by Ysurac** [comment]
Try to increase **$globalLiveInterval**.
All flights are shown when the daemon is run because they are in the source VRS file, but then I only show flights with new data since **$globalLiveInterval** value.

**Comment by Ysurac** [comment]
what's your value of **$globalMinFetch** ?

**Comment by Reloc** [comment]
I increased the $globalLiveInterval to 600 but still have the same problem but after a longer period

$globalMinFetch = '50';

As a little more info my VRS server gets around 3700 a/c displayed during day time so the feed is roughly the same size as your website

**Comment by Ysurac** [comment]
Try lastest commit, this don't use time reported by VRS as last time position. Maybe this will work ?

**Comment by Reloc** [comment]
Seems to be a lot better now , I changed the $globalMinFetch = '50'; to $globalMinFetch = '20'; before you posted the commit , should I change that back to the default ?

**Comment by Ysurac** [comment]
As you want, it fetch data from your VRS server more often.

**Comment by Reloc** [comment]
Ok

Thanks for all the help
