### ISSUE TITLE
A few English grammar suggestions

### ISSUE THREAD

**Issue by szarka77** [Ysurac/FlightAirMap#174]
Hi Ysurac:

First, thanks for the new commits they are working well. 

If I may, I'd like to suggest a few changes to the language on some pages.

On the flight detail page, e.g.: /flight/flightid/5629

There is a sentence that reads, 

"Disclaimer: The image come from wikimedia and is copyright Robert Underwood (under cc-by-sa-2.0). This system may not always 100% accuratly show the actual aircraft."

The word "come" should be "comes." The word "accuratly" should be "accurately"  if you want to keep that sentence. If not, probably better to say, 

"Disclaimer: The source of the above image is wikimedia and is copyright Robert Underwood (under cc-by-sa-2.0). This system may not always show the actual aircraft with 100% accuracy.

Also, on some of the Date & Time statistics pages there is the phrase:

"MOST BUSIEST TIME OF THE DAY"

In English, "most busiest" is redundant.  Better to just say, "BUSIEST TIME OF THE DAY"

and not "MOST BUSIEST DAY" but simply "BUSIEST DAY"

Thanks.

**Comment by Ysurac** [comment]
Fixed. Thanks. I don't know when I put the most busiest...

**Comment by szarka77** [comment]
Wow...you're fast! Merci bien.
