### ISSUE TITLE
Changing the Aircraft Image Source

### ISSUE THREAD

**Issue by Reloc** [Ysurac/FlightAirMap#175]
We have local spotters who contribute their own pictures to us & it would be nice if there was a way we  can change / edit the image source rather than using sources you currently have available to either a local image stored on the web server or a url

Thanks
Nigel

**Comment by me2tkt** [comment]
I'm trying to access photos on my localhost.
Unfortunately the configuration as below does not populate the spotter_image.db.
What is wrong ?
 
$globalAircraftImageCustomSources = array('thumbnail' => 'http://192.168.178.37/Website/Photo/{registration}.jpg','original' => 'http://192.168.178.37/Website/Photo/{registration}.jpg','source_website' => 'http://192.168.178.37/Website/Photo/{registration}.jpg', 'source' => 'localhost', 'exif' => FALSE);

**Comment by Ysurac** [comment]
Do you have **$globalAircraftImageFetch** set to **TRUE** and $globalAircraftImageSources** set to **array('customsources')** ?

**Comment by me2tkt** [comment]
$globalAircraftImageFetch is set to TRUE

Left unchanged :
$globalAircraftImageSources = array('customsources','ivaomtl','wikimedia','airportdata','flickr','jetphotos','planepictures','planespotters');

**Comment by Ysurac** [comment]
This should work if aircraft have registration and pic with this name can be read from FlightAirMap.

**Comment by me2tkt** [comment]
If I manually add into the field image_url the location of the photo e.g. http://192.168.178.37/Website/Photo/G-BMRB.jpg. Then it is shown on the webpage.
But the spotter_image db is not updated with links to the local photos by the script.
I deleted all all links in spotter_image, after some hours all planes had external links

**Comment by Ysurac** [comment]
All should work, I don't see a bug in this. Without an access to the URL, I don't think I will be able to debug...

**Comment by me2tkt** [comment]
I have set 
                  $globalAircraftImageSources = array('customsources');
but still it is still accessing external databases.
(I restarted daemon-spotter just to be sure)

Only when I set 
                  $globalAircraftImageFetch = FALSE;
does it stop - as expected

**Comment by Ysurac** [comment]
if **$globalAircraftImageSources** is not empty it only use source specified.
Check that **$globalAircraftImageSources** is not repeated in *require/settings.php*.

**Comment by me2tkt** [comment]
Looks like I found my error ;-(((
I did not restart daemon_spotter after a change to the settings.php.
Now it is using local thumbnails. ;-)))
Sorry !
I see that it looks for external photos when there is no local photo - Great!
Is it possible to use local thumbnails and external large photos ?

**Comment by Ysurac** [comment]
Good.
Not possible.

**Comment by me2tkt** [comment]
Ah pity - I thought so.
Would be nice to have ;-)

Thank you for your patience.
