### ISSUE TITLE
Read wazzup file from locally source

### ISSUE THREAD

**Issue by bilkaPek** [Ysurac/FlightAirMap#176]
generating my own whazzup file on my linux server FS
could you add whazzup.txt reading the file from a local source

I tested playback from a web source...
`http://domaine.tdl/whazzup.txt`
it does not read the file

> I created a page .php for the worm redirects the whazzup nothing changes my file

>`header('Content-Disposition: attachment; filename="whazzup.txt"');`

## thank you for your help

**Comment by Ysurac** [comment]
You can use *file:///path/of/file/whazzup.txt*, I tested: it works.

**Comment by bilkaPek** [comment]
I thank you tested soon

**Comment by bilkaPek** [comment]
RE
sorry to bother you,
I still have the same problems
Unable to read whazzup both local `file: ///whazzup/whazzup.txt by the` `http://domaine.com/whazzup/whazzup.txt` link
while corespondances with ivao file are correct and vatisim

you can see a sample file on 
(http://fsd.apollo3.com/whazzup/whazzup.txt)

### thank you for your help

**Comment by Ysurac** [comment]
If there is usable data in the file, this should work. 
* What is the error ? 
* File is readable by user running **spotter-daemon.php** ?
* File can be read by **curl** on command line using same url as in *settings.php* ?

**Comment by bilkaPek** [comment]
- then these are the testes made
I start the daemon-spotter.php script from the **command line** to see the mistake !

> root@debian8:/var/www/clients/client1/web1/web/scripts# php -q daemon-spotter.php
Connecting...
Connect to whazzup source (file:///var/www/clients/client1/web1/web/whazzup/whazzup.txt)...
Connect to whazzup source (http://flightairmapserver.com/whazzup/whazzup.txt)...
Connected!
SCAN MODE

No error displays

- The file is readable by the user running daemon.php-spotter?
> Yes
> same group and the same user

- File can be read by curl on command line using same url as in settings.php ?

> yes 

I did another test
> I put in the same file from different source lines
in whazzup.txt, ivao and VATSIM, to see the reaction of the script

-  whazzup **Vatsim Source**
`DAL1687:222222:JOHN DOE LEZG:PILOT::48.728890:2.375507:35825:391:B739/L:450:KMSP:36000:KSAN:USA-C:100:1:6371:::2:I:1405:0:3:51:6:0:KLAX:OPR//DELTAVA CS//DELTA REG//N801DZ RMK//P3DV3/PMDG/ASN NOAA WX/AIRAC1604/vPilot /v/:SCHEP8 ONL BFF EKR HVE J60 BCE EED LYNDI4:0:0:0:0:::20160425165658:260:29.747:1007:`

-  whazzup"**Vatsim Client**" on my Server
`AFR5032:222222:JOHN DOE LEZG:PILOT::48.728885:2.375507:294:0:BE58/H:172:LFMP:10555:LEMD:FSServer:1:1:1200:0:40:1:I:1900:0:1:35:2:50:LFBD:VATSIM CLIENT /v/:AMB B19 POI UT182 CNA UN858 DGO B11 GASMO:::::::20160425165658
`

-  whazzup "**FSINN CLIENT**" on my Server
`AFR8514:222222:JOHN DOE LEZG:PILOT::48.728890:2.375510:294:0:T/BE58/F:180:LFPO:FL260:LEMD:FSServer:1:1:1200:0:40:2:I:1713:0:0:0:0:0::FSINN CLIENT:AMB B19 POI UT182 CNA UN858 DGO B11 GASMO:::::::20160425165658
`

if you meet the three source in wazzup Source VATSIM he read and no other source ! strange :(
I do not know where to look

I think the play structure ??
such as the file it was empty my this is not the case

**Comment by bilkaPek** [comment]
problem is it comes from reading structure does not corespont to that of the deamon-spotter.php
- performs tests

> additions of false information on whazzup `:FAL:SE:IN:FO:ON:FI:LE`
and magic :)

So my initial impression was not good on the structure
the I think this is a good track for you

**Comment by bilkaPek** [comment]
I thank you test as soon as I have time
