### ISSUE TITLE
Connect

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#18]
Hi Mario:

Sorry for my English is very bad but ...

They put up the web following the steps, loaded the tables perfectly ...

![captura](https://cloud.githubusercontent.com/assets/4571086/7584700/8347a3ae-f89f-11e4-99a7-e6d0b7b4bacf.JPG)

But nothing comes out, my radar is a kinetic puck, and works with basestation through the port 30003, so that when I run 127.0.0.1:30003, see the data, but on the web does not leave anything.

![212123](https://cloud.githubusercontent.com/assets/4571086/7584711/a4361046-f89f-11e4-8d34-ee56fb12478d.JPG)

The truth and tried everything but I stay here, the truth is not followed.

http;//tres,piro.biz

Could I please take a hand, it would be very important for me to work.

My web ivao... http://piro.biz
My probe FlightAirmap: http://tres.piro.biz
My Teamspeak3: ts.piro.biz - No pass

Thanks

**Comment by Ysurac** [comment]
What do you get when you run *php cron-sbs.php* under console ?

**Comment by tonkepen100** [comment]
In my cpanel and put these, the truth if they are not well placed or not ....

![captura](https://cloud.githubusercontent.com/assets/4571086/7585017/2575c1e0-f8a2-11e4-9759-d8baa097921a.JPG)

By the way thank you very much for your prompt response

**Comment by tonkepen100** [comment]
when I run out this ....

![captura](https://cloud.githubusercontent.com/assets/4571086/7585245/624172b2-f8a3-11e4-8f48-fa74b78f0177.JPG)

**Comment by Ysurac** [comment]
*update_db.php* is a cron job, but weekly is more than enough (files are not updated often and it's really slow).
*sbs.init.openrc* is not a cron job, it's an init job for openrc init, not a cron job.
Run *cron-sbs.php* under console or as daemon (I didn't make an init script for it other than openrc). This can't be run under web browser.
Check if config table have value 6 for *schema_version*. Else run *install/index.php* again.

**Comment by tonkepen100** [comment]
As it has the 5, 6 and the change to give back to install it?

![captura](https://cloud.githubusercontent.com/assets/4571086/7585511/78938720-f8a4-11e4-8f8e-c54ee4c32246.JPG)

**Comment by tonkepen100** [comment]
Well now pulls this error ...

![captura](https://cloud.githubusercontent.com/assets/4571086/7585614/d5b32f50-f8a4-11e4-979c-f75897496465.JPG)

**Comment by Ysurac** [comment]
It try to connect on localhost:30003 and it have no success. Is the port 30003 really on the same server than *cron-sbs.php* (that you should'nt run under a web browser).

**Comment by tonkepen100** [comment]
Good to see:

this is the current situation ...

- My puck radar is in my house with this IP 87.222.29.220 ....
![captura1](https://cloud.githubusercontent.com/assets/4571086/7586526/0b4d0f42-f8ae-11e4-9fa6-ed98961ae815.JPG)

- The core of the program is uploaded to a server that I have at this address 200.61.181.209

![captura100](https://cloud.githubusercontent.com/assets/4571086/7586538/264d8e84-f8ae-11e4-8ea3-1aa4cbde4ad1.JPG)

- Locally 127.0.0.1:30003 see through the data browser that delivers my puck.
![captura345](https://cloud.githubusercontent.com/assets/4571086/7586552/41fb9144-f8ae-11e4-9e05-f63c703a8314.JPG)

- Positions in the cpanel crones are so ....

![capturacron](https://cloud.githubusercontent.com/assets/4571086/7586586/a5c9af44-f8ae-11e4-86db-e53822b02dec.JPG)

- Settings in the core settings are so ....
![capturaconfig](https://cloud.githubusercontent.com/assets/4571086/7586616/e504b546-f8ae-11e4-8ce2-f339851cb488.JPG)

- The table schemas this so ... 6

and from here as I really am very clumsy, which I'm sorry, because I was not well configure the truth.

**Comment by Ysurac** [comment]
*cron-sbs.php* is a daemon in fact, not a cron job. Don't run it as cronjob (I should really rename it...).
Else I see no problems.

**Comment by tonkepen100** [comment]
While it away from cron cpanel, if executed from the browser tells me this ...

![captura](https://cloud.githubusercontent.com/assets/4571086/7587226/1403bd6e-f8b5-11e4-8d6f-915ae82850dc.JPG)

**Comment by Ysurac** [comment]
Don't run it from browser, I have really no idea if this could work... Also check if port is open in firewalls on server.

**Comment by tonkepen100** [comment]
it will try to open that port on the server and test

**Comment by tonkepen100** [comment]
good and tried to put it in place and not work for me, well I'll leave that in the end I will blow his head.

Thanks for your attention.
