### ISSUE TITLE
Busieset month total aircraft count displayed is one month behind

### ISSUE THREAD

**Issue by szarka77** [Ysurac/FlightAirMap#181]
Ysurac:
For some reason my "BUSIEST MONTHS OF THE LAST 12 MONTHS" graph on the statistics page is one month behind. The flight count displayed as March is actually the April count while the April count is actually the number of flights so far in this month, May.

I assume this is something in one of the DB tables. (?)

Thanks.

**Comment by Ysurac** [comment]
Do you have **$globalArchiveMonths** > 0 in *require/settings.php* ? If this is the case you have to run *scripts/update_db.php* more often.

**Comment by szarka77** [comment]
$globalArchiveMonths = '8' in my settings.php file.
Update_db.php runs every 5 minutes so...??

**Comment by Ysurac** [comment]
What is the **Last update** date at the beginning of Statistics page ?

**Comment by szarka77** [comment]
Three minutes ago: Last update: 2016-05-12 14:55:34

http://www.kpw3.com/flight/statistics

**Comment by Ysurac** [comment]
strange... What is the version of FlightAirMap used ?

**Comment by szarka77** [comment]
I did a git pull just last night so I believe it is up to date.

**Comment by Ysurac** [comment]
What is the result of:

    SELECT YEAR(spotter_output.date) AS year_name, MONTH(spotter_output.date) as month_name, count(*) as date_count FROM spotter_output GROUP BY year_name, month_name ORDER BY date_count DESC

**Comment by szarka77** [comment]
`SELECT YEAR(spotter_output.date) AS year_name, MONTH(spotter_output.date) as month_name, count(*) as date_count FROM spotter_output GROUP BY year_name, month_name ORDER BY date_count DESC`


year_name	month_name	date_count   	
2016	             4	                  19261	
2016	             5	                  9883

**Comment by Ysurac** [comment]
Strange...
What is your timezone ?

**Comment by szarka77** [comment]
US Eastern Standard Time, but at this time of year Eastern Daylight Time.  EDT is UTC -4:00.

**Comment by szarka77** [comment]
After applying commit, seems to be the same.  Still showing April flight total as March.

**Comment by Ysurac** [comment]
even after running scripts/update_db.php ?

**Comment by szarka77** [comment]
Trying that now...

**Comment by szarka77** [comment]
Sorry, after running scripts/update_db.php no change.  I note that table spotter_archive_output has no data.  Is that to be expected?

**Comment by Ysurac** [comment]
Could you give me the result of:

    show index from stats;

**Comment by szarka77** [comment]
show index from stats

```
show index from stats
stats	0	PRIMARY	1	stats_id	A	22				BTREE			
stats	0	type	1	type		A	22				BTREE			
stats	0	type	2	stats_date	A	22				BTREE	
```

**Comment by Ysurac** [comment]
ok, no problems here.
What is the result of:

    SELECT * FROM `stats` WHERE `type`='flights_bymonth';

**Comment by szarka77** [comment]
I think I see the problem:
```
SELECT * FROM `stats` WHERE `type`='flights_bymonth'


stats_id	type	cnt	stats_date	
17905	    flights_bymonth	19407	2016-03-31 20:00:00	
1	        flights_bymonth	19407	2016-04-01 00:00:00	
17906	    flights_bymonth	10357	2016-04-30 20:00:00	
122	        flights_bymonth	10264	2016-05-01 00:00:00
```

**Comment by Ysurac** [comment]
Yes, and stats was good, last change seems to put this strange date...

**Comment by szarka77** [comment]
That may have been caused by me exporting an old DB table into the new DB in early April. 

I'll delete the March entry.

**Comment by Ysurac** [comment]
you could delete data when hour is not 00:00:00.
I found the bug. I will commit in a few minutes.

**Comment by szarka77** [comment]
I deleted:
`17905       flights_bymonth 19407   2016-03-31 20:00:00`

But I still show month as March!

**Comment by Ysurac** [comment]
This will be solved in next commit. I commit in a few minutes, I have some others changes in this commit.

**Comment by szarka77** [comment]
Merci bien.

**Comment by szarka77** [comment]
Installed last commit.  Updated database.  Now I have NO stats.  Uh-oh!

**Comment by Ysurac** [comment]
How do you update database ? Do you run **install/index.php** ?

**Comment by szarka77** [comment]
No, I ran scripts/update_db.php.  Shall I run the installer again?

**Comment by Ysurac** [comment]
Yes : there is an update of the database.

**Comment by szarka77** [comment]
I ran the installer again and updated db  Still no stats.

Getting error:
`Data column(s) for axis #0 cannot be of type string`

See here: [(http://www.kpw3.com/flight/statistics)]

**Comment by Ysurac** [comment]
Try latest commit and run **scripts/update_db.php** again.

**Comment by szarka77** [comment]
No change.

When I run update_db.php I am seeing error:
`PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/flight/require/class.Common.php on line 261`

**Comment by Ysurac** [comment]
I think you deleted all data from stats table with type "flights_by_month", and maybe some others...

You need to remove data from config with name **last_update_stats**. Run **scripts/update_db.php** to try to get all stats from the beginning. 

If this don't work, you will have to **TRUNCATE** all contents of all stats* tables, remove **last_update_stats** again and run the script again.

**Comment by szarka77** [comment]
Ok, all the stats are back but it is still showing March as the first month...lol.
Not sure I know what MYSQL command to use to Truncate all tables.

**Comment by Ysurac** [comment]
If all is here, it's ok. Delete in *stats* table all **flights_by_month** where time is not *00:00:00* and date not *2016-xx-01*, and all should be ok.

**Comment by szarka77** [comment]
Deleted all those entries so all references to the month of March are gone.  However, the graph points  are now all wrong.  8-(  

Getting very late for you now so maybe continue this later.

**Comment by Ysurac** [comment]
I think is faster to do a **TRUNCATE stats;** and the same for all stats_xxx tables. Then remove again *last_update_stats*, run **scripts/update_db.php** and all stats should be ok.

**Comment by szarka77** [comment]
Sorry to keep adding to closed tickets, but.....

The TRUNCATE on all the stats_* tables seemed to work well with one exception. The May 13th flight count of 7554 is WAY too high.  It became that way last Friday when we were trying to solve all these troubles.

I am guessing there is some duplication of data in the spotter_archive table.

Thoughts?

**Comment by Ysurac** [comment]
You don't truncate all tables if you have previous stats. Check if all "stats*" are empty.

**Comment by szarka77** [comment]
I thought that's what you suggested on Friday: (?)

> I think is faster to do a TRUNCATE stats; and the same for all stats_xxx tables. Then remove again last_update_stats, run scripts/update_db.php and all stats should be ok.

Anyway, I did that and then did an update_db and all of the stats tables seem to have been rebuilt OK.

The only issue is the flight count on 13 May.

**Comment by Ysurac** [comment]
If all **stats*** table are empty before running *update_db.php*, all is calculated again, so only real number should be in table. You can do a **SELECT * FROM stats;** to check

**Comment by szarka77** [comment]
That is what I did.  I truncated ALL stats tables then ran update_db. 

The query does show the totals but they are impossibly high. My VRS database shows that on May 13th there were 1421 flights.

**Comment by Ysurac** [comment]
What is the result of:


    SELECT DATE(CONVERT_TZ(spotter_output.date,'+00:00','-04:00')) AS date_name, count(*) as date_count FROM spotter_output GROUP BY date_name ORDER BY date_count DESC LIMIT 10 OFFSET 0

**Comment by szarka77** [comment]
SELECT DATE(CONVERT_TZ(spotter_output.date,'+00:00','-04:00')) AS date_name, count(*) as date_count FROM spotter_output GROUP BY date_name ORDER BY date_count DESC LIMIT 10 OFFSET 0

```
date_name	date_count   	
2016-05-13	7554	
2016-04-08	1152	
2016-05-14	912	
2016-04-17	909	
2016-04-16	895	
2016-04-14	878	
2016-04-22	875	
2016-04-23	871	
2016-05-15	866	
2016-04-09	864	
```

**Comment by Ysurac** [comment]
So it's strange but there is 7554 flights in database for **2016-05-13**.
I have really no idea how this can be possible... I will try to reproduce this bug.

**Comment by szarka77** [comment]
Do you know a simple duplicate search query we can run?  If not, I'll try to find one.

**Comment by Ysurac** [comment]
No, as they can't be really duplicate. It's why it's strange.
