### ISSUE TITLE
error report 

### ISSUE THREAD

**Issue by bilkaPek** [Ysurac/FlightAirMap#185]
return error on the chart of time
`Data column(s) for axis #0 cannot be of type string`
current value
`('hour');`

the value should be empty or change by VALUE
on statistics.php
line 557 
`$hour_array = $Stats->countAllHours('value');`

on statistics-time.php
line 16 
`$hour_array = $Stats->countAllHours('value');`

**Comment by Ysurac** [comment]
Try latest commit, this should display the real error now.

**Comment by bilkaPek** [comment]
Merci Yannick 

Another error found
the planes do not see the map from the flightid-overview page source since the last commit
