### ISSUE TITLE
Error from source phpvms

### ISSUE THREAD

**Issue by bilkaPek** [Ysurac/FlightAirMap#186]
since the last version, I noticed an error in source and phpvms
the flight when complete the airplane remains displayed on the map several hours

I tested with latest version and this problem does not present ..?

**Comment by Ysurac** [comment]
I now keep data in table SpotterLive for 2 hours (instead of 1 hour), but this shouldn't change anything if **$globalLiveInterval** is not too high.

**Comment by bilkaPek** [comment]
I tested different configuration and always the same result

my config
```
$globalLiveInterval = '120';
$globalMapRefresh = '30';
```
we'd say it freeze 
strange...

**Comment by Ysurac** [comment]
Latest commit maybe fix the problem.

**Comment by bilkaPek** [comment]
Hello 
I just do a test with the last commit
and the problem persists
I executed the command line it returns an error
`PHP Warning:  Invalid argument supplied for foreach() in /scripts/daemon-spotter.php on line 543`
while traffic and NUUL 'no active flight' on VA

**Comment by bilkaPek** [comment]
problems solved ....

in the last commit, I think you have to change the configuration related schedules
the problem came from the line 558

`$data['datetime'] = $line['lastupdate'];`

I change
`$data['datetime'] = date('Y-m-d H:i:s');`

thank you for your support

**Comment by Ysurac** [comment]
The lastupdate field for phpvms should be really the last update date of the flight. Maybe it's not always in UTC ?

**Comment by bilkaPek** [comment]
okay no problem
but why it is no longer supported
of the flight that ends the script returns an error after  'X minutes'
`PHP Warning: Invalid argument supplied for foreach() in /scripts/daemon-spotter.php on line 543`


you has it changed since the last commit for that part of the code is no longer supported

**Comment by bilkaPek** [comment]
I just tested the last commit and all is well
a thousand thanks


> I see a filter for the source phpvms, while it is not worth knowing that the pilots of the VA needs no filtering

in place to have a general filtering as is currently the case
it is well know and dissociation of filtering accordance with the sources

> here is an example

```
// $globalFilteredSources = TRUE;

$globalFilteredFromSources = array('ivao','vatsim','aircraftlistjson'); 

// filter Pilots * VATSIM *
$globalPilotIdAcceptVatsim = array('999999','888888','777777');
// filter Airlines * VATSIM *
$globalAirlineAcceptVatsim = array('AFR','KLM','IBE');

// filter Pilots * IVAO *
$globalPilotIdAcceptIvao = array('111111','222222','333333');
// filter Airlines * IVAO * 
$globalAirlineAcceptIvao = array('AFR','KLM','IBE');

// filter according to their ICAO airline code Example:('AFR','KLM','IBE')

// filter Airlines From Aircraftlistjson
$globalAirlineAcceptAircraftlistjson = array('AFR','KLM','IBE');

// filter Airlines From Deltadbtxt
$globalAirlineAcceptDeltadbtxt = array();

// filter Airlines From Planeupdatefaat 
$globalAirlineAcceptPlaneupdatefaat = array();

```
