### ISSUE TITLE
Nothing is shown

### ISSUE THREAD

**Issue by linuxpronl** [Ysurac/FlightAirMap#187]
After git pull the latest version there ar no plans shown. The page does show, history / stats /acars is working, but no planes, the aircraft detected round is going on and on. The ads-b source is available (check https://radar.linuxpro.nl  it's the dump1090 web proxied with Nginx)  
I ran /install, no errors. Any clues?

**Comment by Ysurac** [comment]
There is nothing in *current activity*. What is the output of **daemon-spotter.php** ?

**Comment by linuxpronl** [comment]
I think daemon-spotter.php was still trying to connect to the old ads-b source, killing it and restared it with globaldebug enabled shows output.
