### ISSUE TITLE
Difference between mlat / ads-b planes

### ISSUE THREAD

**Issue by linuxpronl** [Ysurac/FlightAirMap#188]
When I take a look at the dump1090 html pages and what is shown in fam is see a difference:
- missing planes in fam
- missing most of the MLAT planes in FAM

You can see the difference https://radar.linuxpro.nl  <-> https://fligthinfo.linuxpro.nl  

Any suggestions what settings to look at: ?   

Running latest dump1090 with this as parameters: 

`dump1090 --net --forward-mlat --mlat --enable-agc --ppm -1.4 --net-verbatim --raw --mlat`

**Comment by Ysurac** [comment]
For planes "missing" not MLAT: **$globalMapRefresh** is not the same value for dump1090 and FAM, FAM filter false data,...

For MLAT, you can try:

    piaware-config -mlatResultsFormat "ext_basestation,listen,30106"
    piaware-config restart

Then add **ipofpiaware:30106** as source. You should then remove *--forward-mlat* from dump1090.

**Comment by linuxpronl** [comment]
Did that and MLAT planes are showing up. Like to see MLAT or so in the pop-up info
