### ISSUE TITLE
Missing folders

### ISSUE THREAD

**Issue by Spog99** [Ysurac/FlightAirMap#189]
Hi,
Just installed FlightAirMap and have working with two RTLSDR dongles using dump1090 ADSB data and decoding ACARS. Works really well but I see an issue when selecting some of the web pages which throw up an error in the nginx error.log complaining that the /statistics and /tools folder do not exist. I've re-downloaded using git clone and re installed but unable to find the directories. What am i doing wrong?

**Comment by Ysurac** [comment]
You have to include *flightairmap-nginx-conf.include*. See https://github.com/Ysurac/FlightAirMap/wiki/Installation for an example.

**Comment by Spog99** [comment]
Thanks for the quick response. The server block was copied from that page but rewrite does not seem to work. Is it enabled somewhere else.? This is the server block from /sites-enabled/default.
server {
      listen 80;
      server_name localhost;
      root /var/www/FlightAirMap;
      index index.php index.html index.htm index.nginx-debian.html;

      location ~ \.php$ {
         #fastcgi_split_path_info ^(.+\.php)(/.+)$;
           fastcgi_pass unix:/var/run/php5-fpm.sock;
           fastcgi_index index.php;
           include /etc/nginx/fastcgi.conf;
           fastcgi_read_timeout 300;
      }
           include /var/www/FlightAirMap/install/flightairmap-nginx-conf.include;
}

**Comment by Ysurac** [comment]
this seems to be ok. **rewrite** must be compiled with nginx. It's a USE flag under gentoo. I don't know what is your system.

**Comment by Spog99** [comment]
Sorry should have mentioned that.
I've installed on a RPI 3 running Jessie.
I used 'apt-get install nginx' originally, so probably should have included some flags.

**Comment by Ysurac** [comment]
ok I will try tomorrow on a rpi to check.

**Comment by Spog99** [comment]
Hi, I checked the nginx website https://www.nginx.com/resources/admin-guide/installing-nginx-open-source/ which suggest rewrite is included as default with an option to exclude at compile stage. 
Here is the output from nginx -V

nginx version: nginx/1.6.2
TLS SNI support enabled
configure arguments: 
--with-cc-opt='-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2' 
--with-ld-opt=-Wl,-z,relro 
--prefix=/usr/share/nginx 
--conf-path=/etc/nginx/nginx.conf 
--http-log-path=/var/log/nginx/access.log 
--error-log-path=/var/log/nginx/error.log 
--lock-path=/var/lock/nginx.lock 
--pid-path=/run/nginx.pid 
--http-client-body-temp-path=/var/lib/nginx/body 
--http-fastcgi-temp-path=/var/lib/nginx/fastcgi 
--http-proxy-temp-path=/var/lib/nginx/proxy 
--http-scgi-temp-path=/var/lib/nginx/scgi 
--http-uwsgi-temp-path=/var/lib/nginx/uwsgi 
--with-debug 
--with-pcre-jit 
--with-ipv6 
--with-http_ssl_module 
--with-http_stub_status_module 
--with-http_realip_module 
--with-http_auth_request_module 
--with-http_addition_module 
--with-http_dav_module 
--with-http_geoip_module 
--with-http_gzip_static_module 
--with-http_image_filter_module 
--with-http_spdy_module 
--with-http_sub_module 
--with-http_xslt_module 
--with-mail 
--with-mail_ssl_module 
--add-module=/build/nginx-sYtngi/nginx-1.6.2/debian/modules/nginx-auth-pam 
--add-module=/build/nginx-sYtngi/nginx-1.6.2/debian/modules/nginx-dav-ext-module 
--add-module=/build/nginx-sYtngi/nginx-1.6.2/debian/modules/nginx-echo 
--add-module=/build/nginx-sYtngi/nginx-1.6.2/debian/modules/nginx-upstream-fair 
--add-module=/build/nginx-sYtngi/nginx-1.6.2/debian/modules/ngx_http_substitutions_filter_module

No sign of the rewrite module!!

**Comment by Ysurac** [comment]
Yes it's included: https://wiki.debian.org/Nginx
I never tried with a so old version. But this should work. Do you have something in log ?

**Comment by Ysurac** [comment]
You could try to remove *index index.php index.html index.htm index.nginx-debian.html;* in your config.

**Comment by Spog99** [comment]
Hi, I've uninstall and reinstalled nginx this evening with no improvement in the situation. I downloaded mainline version 1.11.1 from nginx website and compiled as per the guide.

See attached error log

Also tried commenting out index with no change in the situation.

**Comment by Spog99** [comment]
Here's the error.log and a screenshot of the problem.
![image](https://cloud.githubusercontent.com/assets/19764119/16322211/7219de30-3999-11e6-8554-ef35c7007270.png)

**Comment by Spog99** [comment]
Sorry! had a problem uploading the file.
Here's the error log
[nginx error.txt](https://github.com/Ysurac/FlightAirMap/files/330939/nginx.error.txt)

**Comment by Ysurac** [comment]
ok, it's not a problem with rewrite. What is your value of **$globalURL** in *scripts/settings.php* ?

**Comment by Spog99** [comment]
// GLOBAL URL
$globalURL = '.';

**Comment by Ysurac** [comment]
It's the error. Why did you put a **.** ? remove it, all should work.

**Comment by Ysurac** [comment]
ok I put a . by default... Why did I put that here ? Sorry.

**Comment by Spog99** [comment]
You are amazing. Thank you so much for all your help. It all works perfectly now.
How did you deduce that was the problem from the error log?

Many thanks from a very grateful Flightairmap user.

**Comment by Ysurac** [comment]
I deduce that from the screenshot in fact. It's also visible in the log with 404: It was checking for css files at the wrong place.

**Comment by Spog99** [comment]
I wish I understood things like you, but this is a great learning experience. Thanks again I'll close the issue.

Take care & good luck.
