### ISSUE TITLE
Error during fresh install

### ISSUE THREAD

**Issue by linuxpronl** [Ysurac/FlightAirMap#190]
When doing a fresh install the installation stops with:

Error : error (import /data/nginx/sites/FlightAirMap/install/tmp/countries.sql) : SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'

**Comment by Ysurac** [comment]
What is the DB engine ? MySQL/Mariadb or PostgreSQL ?

**Comment by linuxpronl** [comment]
Using MariaDB

**Comment by Ysurac** [comment]
Strange. In latest commit I drop table if already exist, so it should work.

**Comment by linuxpronl** [comment]
That's right, the table is dropped if it exists but when importing the data the error occurs. Tried manually to fill the country table (first dropped the table) and then it goes fine

**Comment by Ysurac** [comment]
Really strange... Maybe some system don't like this binary import. I will make some tests.

**Comment by linuxpronl** [comment]
Is there a 'dummy' guide for setting it up using postgres?  I'm a dummy for postgres but like to try

**Comment by Ysurac** [comment]
I will make a guide. I need to try a new fresh install with postgres.
