### ISSUE TITLE
Forbidden You don't have permission to access getImages.php on this server

### ISSUE THREAD

**Issue by ariedeleen** [Ysurac/FlightAirMap#191]
There are a lot of 403 forbidden when plotting the airplane png images. But not always.
It looks like the header sometimes is Content-Type:text/html and not Content-Type:image/png
Running on PHP 7, Apache 2.2.15
![getimages403](https://cloud.githubusercontent.com/assets/5099451/16379085/d21c7b2a-3c6f-11e6-9ef2-37ce8f26fcca.PNG)

**Comment by Ysurac** [comment]
It's a problem in your apache configuration. You should allow more connection by user.  This should be **MaxRequestWorkers** for Apache 2 if I remember well.
I will try to find a way to don't load each airplane pics at the same time.

**Comment by ariedeleen** [comment]
Thanx for the quick responce,

For apache 2.2 this could be
MaxClients is has now the value 256. I have doubled this value to 512 but still got 403's
Or maybe it is another value that has to be set.

Throttle the amount of airplanes would be better.

**Comment by Ysurac** [comment]
It's strange that you have this problem there is only 89 flights, it's more often the case when we have more than 2000 flights.
Now I'm banned from your site.

**Comment by ariedeleen** [comment]
Yes, that's temporary ;-) because fail2ban hostdeny ;-) security kick's in.
We also run https://tower.ykoon.nl/gmap.html on this server.
Also other websites that are doing fine.

**Comment by ariedeleen** [comment]
And In the settings menu left.  When set (ticked) Aircraft icon color based on altitude to yes. It seems to produce more 403's

**Comment by Ysurac** [comment]
It open more connections, more pics to downloads. Seems to be really a limit of connection number.

**Comment by ariedeleen** [comment]
Solved, the mod_evasive apache module was installed on this webserver.
In the module config file only  _DOSWhitelist 127.0.0.1_ (localhost) was white listed.
But FlightAirmap was running on a different IP address. This was causing the 403's.

**Comment by Ysurac** [comment]
ok. Thanks for the comment.
