### ISSUE TITLE
Tried to add a second flight data source. But only one is picked up.

### ISSUE THREAD

**Issue by ariedeleen** [Ysurac/FlightAirMap#194]
Tried to add a second flight data source. But only one is picked up.

And these lines are logged:
PHP Warning: Invalid argument supplied for foreach() in webroot/scripts/daemon-spotter.php on line 92
PHP Notice:  Undefined variable: hosts in webroot/scripts/daemon-spotter.php on line 789

So, pulled all the (new) files from github. But howto update the database schema.

Using PHP7

**Comment by Ysurac** [comment]
To update the database schema, run again *install/index.php*
For the error in data source, paste the value of *$globalSources* in **require/settings.php**.

**Comment by ariedeleen** [comment]
The value is already in require/settings.php but only the first one in the array is used. Not the second one.
Both the sources work. And when swapped, SDR2, SDR1 then SDR2 is used. But not both.

$globalSources = array(array('host' => '192.168.1.11','port' => '30003','name' => 'SDR1','format' => 'auto'), array('host' => '192.168.1.12','port' => '30003','name' => 'SDR2','format' => 'auto'));

**Comment by Ysurac** [comment]
Strange.
You use it as daemon or cronjob ?
When you run **scripts/daemon-spotter.php** at the beginning it try to connect to sources, what is the log ?

**Comment by ariedeleen** [comment]
Tried both daemon and cronjob.

[root@serverfam scripts]# php daemon-spotter.php
Connecting...
Connection in progress to 192.168.1.11(sbs)....
Connected!
SCAN MODE

The purpose is to enrich the own collected data with an external source.
The external source is: http://public-api.adsbexchange.com/VirtualRadar/AircraftList.json?lat=52.17&lng=4.50&fDstL=0&fDstU=500

When only the external source is used it works. But when you add a second working source then the external source is skipped.

Works:
$globalSources = array(array('host' => 'http://public-api.adsbexchange.com/VirtualRadar/AircraftList.json?lat=52.17&lng=4.50&fDstL=0&fDstU=1500','port' => '80','name' => 'Aircraft list','format' => 'aircraftlistjson'));

External get skipped:
$globalSources = array(array('host' => 'http://public-api.adsbexchange.com/VirtualRadar/AircraftList.json?lat=52.17&lng=4.50&fDstL=0&fDstU=1500','port' => '80','name' => 'VirtualRadar','format' => 'auto'), array('host' => '192.168.1.11','port' => '30003','name' => 'Own data','format' => 'auto'));

**Comment by Ysurac** [comment]
You have to set the format, auto will not work in this case.
But mixing URL and TCP source will not work very well : script have to download the file and put it in DB then the TCP source. Some data from TCP sources will be missing. 
I don't think there is really a way to solve this.

**Comment by ariedeleen** [comment]
Ok, thanx for explanation
