### ISSUE TITLE
How to debug daemon-spotter.php issue?

### ISSUE THREAD

**Issue by Spog99** [Ysurac/FlightAirMap#195]
Hi,
I'm running FlightAirMap on a RPI3 feeding acars data from RTLSDR and ADSB data from SBS3 all works fantastically well but occasionally daemon-spotter.php hangs and I need to kill th eprocess and restart to getting processing messages. Is there a way to debug why it hangs? I live within 10 miles of LGW and problem seems to occur around 1400 when traffic peaks, but it never does it when I'm monitoring.
Here's a screenshot of daemon-spotter.php when its hung. See the speed calculation has gone bad.
Any other logs/debug I can check?

Thanks in advance
Chris...

Time : 57s - Distance : 25138m -Speed : 1587.6631578947 km/h - Lat : 51.92798 - long : -0.56602 - prev lat : 51.88889 - prev long : -0.92697 
!!! Too much distance in short time... for RYR808
Time : 57s - Distance : 25229m -Speed : 1593.4105263158 km/h - Lat : 51.92809 - long : -0.56470 - prev lat : 51.88889 - prev long : -0.92697 
!!! Too much distance in short time... for RYR77QF
Time : 118s - Distance : 61554m -Speed : 1877.9186440678 km/h - Lat : 52.17761 - long : -1.22513 - prev lat : 52.66706 - prev long : -1.64928 
!!! Too much distance in short time... for RYR86QQ
Time : 113s - Distance : 73884m -Speed : 2353.8265486726 km/h - Lat : 50.73907 - long : 1.51552 - prev lat : 50.23466 - prev long : 2.19539 
!!! Too much distance in short time... for LZB852
Time : 62s - Distance : 39048m -Speed : 2267.3032258065 km/h - Lat : 51.16640 - long : 0.55046 - prev lat : 51.18386 - prev long : -0.00900 
!!! Too much distance in short time... for MPH6122
Time : 58s - Distance : 30366m -Speed : 1884.7862068966 km/h - Lat : 51.57746 - long : -0.22911 - prev lat : 51.32719 - prev long : -0.40451 
!!! Too much distance in short time... for KLM
Time : 121s - Distance : 69868m -Speed : 2078.7173553719 km/h - Lat : 51.68381 - long : 0.62258 - prev lat : 51.75279 - prev long : 1.63073 
!!! Too much distance in short time... for IBK2907
Time : 124s - Distance : 60368m -Speed : 1752.6193548387 km/h - Lat : 50.97093 - long : 0.83397 - prev lat : 51.40915 - prev long : 1.34538 
!!! Date previous latest data !!!
!!! Date previous latest data !!!
!!! Date previous latest data !!!
!!! Date previous latest data !!!
!!! Date previous latest data !!!
!!! Date previous latest data !!!
!!! Date previous latest data !!!
!!! Date previous latest data !!!
!!! Date previous latest data !!!
!!! Date previous latest data !!!
!!! Date previous latest data !!!
!!! Date previous latest data !!!
!!! Date previous latest data !!!
!!! Date previous latest data !!!
!!! Date previous latest data !!!
!!! Date previous latest data !!!
!!! Too much distance in short time... for EZY45WK
Time : 60s - Distance : 26590m -Speed : 1595.4 km/h - Lat : 51.97293 - long : -0.61363 - prev lat : 52.04416 - prev long : -0.98450 
!!! Date previous latest data !!!
!!! Too much distance in short time... for EIN386
Time : 107s - Distance : 45707m -Speed : 1537.8056074766 km/h - Lat : 51.30522 - long : -0.45578 - prev lat : 51.31279 - prev long : -1.11326 
!!! Too much distance in short time... for LHB1
Time : 46s - Distance : 25921m -Speed : 2028.6 km/h - Lat : 51.18315 - long : -0.21060 - prev lat : 51.01674 - prev long : -0.47058 
!!! Too much distance in short time... for LHB1
Time : 46s - Distance : 26001m -Speed : 2034.8608695652 km/h - Lat : 51.18356 - long : -0.20963 - prev lat : 51.01674 - prev long : -0.47058 
!!! Too much distance in short time... for DLH3NH
Time : 124s - Distance : 79790m -Speed : 2316.4838709677 km/h - Lat : 51.47798 - long : -0.64758 - prev lat : 52.09126 - prev long : -1.24992 
!!! Too much distance in short time... for DAL3
Time : 59s - Distance : 36059m -Speed : 2200.2101694915 km/h - Lat : 51.60562 - long : -1.67381 - prev lat : 51.52203 - prev long : -1.16975 
!!! Too much distance in short time... for DAL3
Time : 59s - Distance : 36184m -Speed : 2207.8372881356 km/h - Lat : 51.60590 - long : -1.67557 - prev lat : 51.52203 - prev long : -1.16975 
!!! Too much distance in short time... for BAW8WE
Time : 118s - Distance : 67859m -Speed : 2070.2745762712 km/h - Lat : 51.10812 - long : 1.46568 - prev lat : 51.15697 - prev long : 0.49624 
!!! Too much distance in short time... for BAW375
Time : 110s - Distance : 50139m -Speed : 1640.9127272727 km/h - Lat : 51.05086 - long : -0.90302 - prev lat : 50.63525 - prev long : -1.18009 
!!! Too much distance in short time... for BAW375
Time : 110s - Distance : 50190m -Speed : 1642.5818181818 km/h - Lat : 51.05119 - long : -0.90240 - prev lat : 50.63525 - prev long : -1.18009 
!!! Too much distance in short time... for SHT9G
Time : 49s - Distance : 23571m -Speed : 1731.7469387755 km/h - Lat : 51.87634 - long : -1.13345 - prev lat : 52.06023 - prev long : -1.30463 
!!! Too much distance in short time... for AAL107
Time : 52s - Distance : 22899m -Speed : 1585.3153846154 km/h - Lat : 51.50533 - long : -1.01802 - prev lat : 51.45717 - prev long : -0.69649 
!!! Too much distance in short time... for TWB302D
Time : 122s - Distance : 84193m -Speed : 2484.3836065574 km/h - Lat : 51.32961 - long : 0.27443 - prev lat : 51.78359 - prev long : -0.70030 
Not a message. Ignoring... 
pi@raspberrypi:/var/www/FlightAirMap/scripts $ sudo php -f daemon-spotter.php

**Comment by Ysurac** [comment]
Data seems to be strange...
How many flights do you have at 1400 ?
What is the format used ? (sbs, raw,...)
What is the DB used ? (MySQL, MariaDB, PostgreSQL)

**Comment by Spog99** [comment]
Yes, data very strange! 
Number of flights will be high, maybe peaking at 150. Difficult to tell exactly because it fails when I'm away and I'm unable to find any historical stats or error logs that show the actual time it fails.
Format is set to 'auto' in settings.php using port 30003 which I believe is SBS format.
Using MariaDB with MYSQL.

**Comment by Ysurac** [comment]
150 is not very high. If the source is only SBS, date can't be *previous latest data*, the only case is if system date is changed. You use **ntp** ?

**Comment by Spog99** [comment]
Sure, but is there any way to check the database to see how many flights
logged during certain time period.  The stats page seems to show peak
numbers.
Using RPI3 which has ntp by default and ntpd is running.
Source of data is SBS3 but RPI3 is taking data feed from Basestation PC.
Basestation PC is also running ntp as it also feeds Planeplotter, but I
don't think that should affect it.
I think I was getting "*previous latest data*" message when running ADSB
from RTL dongle. I try this evening with a local feed and see what happens.

Best Regards

**Comment by Spog99** [comment]
OK - so i reconnected the RTL dongle and using that as ADSB data source. I get same output see below. I'll let you know when I get home form work if it hung or not

Regards

Screenshot below
  - Altitude : 143 - Heading : 76 - Speed : 370 - Departure Airport Time :  - Arrival Airport time : 
\o/ Add DLH2LX from sbs in Live DB : (Add to SBS archive : success)success
!!! Date previous latest data !!!
!!! Date previous latest data !!!
!!! Date previous latest data !!!
!!! Date previous latest data !!!
!!! Date previous latest data !!!
!!! Date previous latest data !!!
DATA : hex : 3C6655 - ident : DLH9H - ICAO : A321 - Departure Airport : EGLL - Arrival Airport : EDDF - Latitude : 51.22696 - Longitude : -0.18016 - waypoints :  - Altitude : 113 - Heading : 96 - Speed : 322 - Departure Airport Time :  - Arrival Airport time : 
\o/ Add DLH9H from sbs in Live DB : (Add to SBS archive : success)success
!!! Date previous latest data !!!
^CERROR : socket_select give this error Interrupted system call
Restarting...
Shutdown all sockets...Restart all connections...Connection in progress to 127.0.0.1(sbs)....


ctrl-c or kill signal received. Tidying up ... Bye!
pi@raspberrypi:/var/www/FlightAirMap/scripts $

**Comment by Ysurac** [comment]
When source is SBS, I use local system time not source time (lot of problems with sources times).
In latest commit I added more log info for this problem.
Checking the DB for a certain period of time is not so easy. But even if there is 600 for a SBS source, it's not a problem for the script. I never tried on a RPI3 for now.

**Comment by Spog99** [comment]
Hi,
Have been running all day without problem but very low message rate as only internal antenna on RTL dongle. Still get Date previous latest data message. Will switch back to SBS3 source and run latest commit.
See screenshot.
DATA : hex : 4CA52B - ident : BCY128 - ICAO : RJ85 - Departure Airport : EIDW - Arrival Airport : EGLC - Latitude : 51.30806 - Longitude : -0.64262 - waypoints :  - Altitude : 166 - Heading : 90 - Speed : 368 - Departure Airport Time :  - Arrival Airport time : 
\o/ Add BCY128 from sbs in Live DB : (Add to SBS archive : success)success
!!! Date previous latest data !!!
DATA : hex : 400DB4 - ident : EZY43DK - ICAO : A319 - Departure Airport : LFMN - Arrival Airport : EGKK - Latitude : 51.08894 - Longitude : 0.23834 - waypoints :  - Altitude : 39 - Heading : 30 - Speed : 227 - Departure Airport Time :  - Arrival Airport time : 
\o/ Add EZY43DK from sbs in Live DB : (Add to SBS archive : success)success
!!! Date previous latest data !!!
!!! Date previous latest data !!!
!!! Date previous latest data !!!
!!! Date previous latest data !!!
!!! Date previous latest data !!!
DATA : hex : 400E13 - ident : EZY92FM - ICAO : A319 - Departure Airport : EGGW - Arrival Airport : LFMN - Latitude : 50.55559 - Longitude : 0.06681 - waypoints :  - Altitude : 288 - Heading : 144 - Speed : 533 - Departure Airport Time :  - Arrival Airport time : 
\o/ Add EZY92FM from sbs in Live DB : (Add to SBS archive : success)success
DATA : hex : 3991E4 - ident : AFR380B - ICAO : A320 - Departure Airport : LFPG - Arrival Airport : EGLL - Latitude : 51.10775 - Longitude : 0.27428 - waypoints :  - Altitude : 128 - Heading : 303 - Speed : 287 - Departure Airport Time : 20:30 - Arrival Airport time : 20:45
\o/ Add AFR380B from sbs in Live DB : (Add to SBS archive : success)success
!!! Date previous latest data !!!
DATA : hex : 3C5428 - ident : BCS6773 - ICAO : A306 - Departure Airport : EDDP - Arrival Airport : EDDS - Latitude : 50.99112 - Longitude : -0.85508 - waypoints :  - Altitude : 126 - Heading : 26 - Speed : 297 - Departure Airport Time :  - Arrival Airport time : 
\o/ Add BCS6773 from sbs in Live DB : (Add to SBS archive : success)success
DATA : hex : 344281 - ident : VLG7825 - ICAO : A320 - Departure Airport : EGKK - Arrival Airport : LEBL - Latitude : 51.12460 - Longitude : -0.35904 - waypoints :  - Altitude : 43 - Heading : 258 - Speed : 226 - Departure Airport Time :  - Arrival Airport time : 
\o/ Add VLG7825 from sbs in Live DB : (Add to SBS archive : success)success
!!! Date previous latest data !!!
!!! Date previous latest data !!!
DATA : hex : 4063DE - ident : BAW48BC - ICAO : A320 - Departure Airport : EGLL - Arrival Airport : LEBL - Latitude : 50.89407 - Longitude : -0.33844 - waypoints :  - Altitude : 166 - Heading : 164 - Speed : 441 - Departure Airport Time :  - Arrival Airport time : 
\o/ Add BAW48BC from sbs in Live DB : (Add to SBS archive : success)success
!!! Date previous latest data !!!
!!! Date previous latest data !!!
!!! Date previous latest data !!!
!!! Date previous latest data !!!
!!! Date previous latest data !!!
DATA : hex : 4CA81D - ident : AZA247 - ICAO : A320 - Departure Airport : EGLL - Arrival Airport : LIML - Latitude : 50.42436 - Longitude : 0.10890 - waypoints :  - Altitude : 251 - Heading : 150 - Speed : 488 - Departure Airport Time : 20:00 - Arrival Airport time : 22:55
\o/ Add AZA247 from sbs in Live DB : (Add to SBS archive : success)success
!!! Date previous latest data !!!
!!! Date previous latest data !!!
!!! Date previous latest data !!!
!!! Date previous latest data !!!
!!! Date previous latest data !!!
Check if aircraft is already in DB... Not in DB.
\o/ Add VIR601 in archive DB : --- Delete old values with id 4CA9D1-201607141826
---++ Find arrival airport. airport_icao : EGKK
--- Delete old values with id 406D8C-201607141841
success
DATA : hex : 406D4C - ident : VIR601 - ICAO : B789 - Departure Airport : EGLL - Arrival Airport : FAJS - Latitude : 51.33440 - Longitude : -0.56706 - waypoints :  - Altitude : 71 - Heading : 152 - Speed : 288 - Departure Airport Time :  - Arrival Airport time : 
\o/ Add VIR601 from sbs in Live DB : (Add to SBS archive : success)success
!!! Date previous latest data !!!
!!! Date previous latest data !!!
DATA : hex : 3C6628 - ident : GWI7CP - ICAO : A320 - Departure Airport : EGLL - Arrival Airport : EDDK - Latitude : 51.29192 - Longitude : -0.01151 - waypoints :  - Altitude : 138 - Heading : 77 - Speed : 381 - Departure Airport Time : 19:15 - Arrival Airport time : 21:40
\o/ Add GWI7CP from sbs in Live DB : (Add to SBS archive : success)success
!!! Date previous latest data !!!
*********** New aircraft hex : 4CA216 ***********
!!! Date previous latest data !!!
DATA : hex : 342582 - ident : VLG8772 - ICAO : A320 - Departure Airport : EGKK - Arrival Airport : LFPG - Latitude : 50.92647 - Longitude : 0.05402 - waypoints :  - Altitude : 69 - Heading : 323 - Speed : 246 - Departure Airport Time :  - Arrival Airport time : 
\o/ Add VLG8772 from sbs in Live DB : (Add to SBS archive : success)success
DATA : hex : 400D5A - ident : BAW46PX - ICAO : A319 - Departure Airport : LIPX - Arrival Airport : EGKK - Latitude : 51.18339 - Longitude : 0.18730 - waypoints :  - Altitude : 36 - Heading : 345 - Speed : 181 - Departure Airport Time :  - Arrival Airport time : 

Rgds
Chris

**Comment by Spog99** [comment]
OK - have updated latest commit and relaod with SBS as source.

Getting !!Too much distance error almost immediately
!!! Too much distance in short time... for BEL183
Time : 46s - Distance : 36018m -Speed : 2818.8 km/h - Lat : 52.29044 - long : -0.89165 - prev lat : 52.10620 - prev long : -0.45695 
!!! Too much distance in short time... for BEL183
Time : 46s - Distance : 36167m -Speed : 2830.4608695652 km/h - Lat : 52.29158 - long : -0.89302 - prev lat : 52.10620 - prev long : -0.45695 
^CERROR : socket_select give this error Interrupted system call
Restarting...
Shutdown all sockets...Restart all connections...Connection in progress to 192.168.2.10(sbs)....

Using Planeplotter I can see Mode S message rate is 600 msgs per second.

How do I ensure system time is using local?

Rgds
Chris

**Comment by Ysurac** [comment]
*Too much distance error* is the result of a check, a flight can't go at 2830 km/h. I can make an option to disable message filtering, but this would result in strange flights.
What do you mean by system time using local ?

The problem can be:
* Raspberry Pi 3 is too slow for the script or for MySQL/MariaDB (this can be optimized).
* SBS3 send data in a different way than Dump1090, ModeSMixer,...

How to test:
* Open a TCP connection to your SBS3 for me (port 30003)
* Try to use Dump1090 on the Rasp and redirect SBS3 to Dump1090 (nc -d ipsbs 30002 | nc 127.0.0.1 30001 not sure about the ports)
* Check with top, htop or anything like that if CPU/Memory is not full. MariaDB sometimes use LOT of memory/CPU. (You should test that first)

**Comment by Spog99** [comment]
I think RPI3 is struggling with high message rates and db often seen running at 100% CPU. Leave it with me to do some more tests and I'll get back in a few days. At least the !!!Date previous latest data !!! messages seem to have stopped.

RE: comment about local time... You said earlier "When source is SBS, I use local system time not source time (lot of problems with sources times)". I think I'm already using RPI local time.

Thanks for your help.
B. Regards

**Comment by Ysurac** [comment]
If it is set to **TRUE** set **$globalArchive** in *require/settings.php* to **FALSE**. This can stress the DB a little bit less. **$globalSchedulesFetch** can be set to **FALSE** too, at least for test.
When I'm speaking of source time, I speak about time send by the SBS device/software. This time is ignored, FlightAirMap use system time, so RPI time in your case. It's why time on the RPI must be stable.

I will try to make some test on a RPI tomorrow or next week.

**Comment by Spog99** [comment]
Hi, Just to update you on progress with this issue. I think we can close this case as it looks like a RPI3 capability issue.
I made the changes suggested above and have been running the system non-stop for 5 days with ADBS via SBS3 and ACARS via RTL dongle and have experienced zero errors :-)
Current number of aircraft approx 150 with message rates of greater than 1000 msgs per second.
Using TOP the only processes running high is mysqld which hits 150% occasionally but doesnt have further impact. PHP & ACARSD processes running at less than 50% (peak).

I'm happy that this is a RPI limitation and will install on a linux PC when I get the time and inclination.
Thanks for your help debugging.

Best Regards

**Comment by Ysurac** [comment]
Maybe this work a little bit better since recent commit.
The problem is with MySQL, there is a problem with ARCHIVE table format (that I will remove soon).
PostgreSQL seems to be faster for now. I will make more test.

**Comment by Spog99** [comment]
OK - That would be good to see some performance improvements. I'll leave this case open and perhaps you would kindly let me know when ready for testing. Although I am happy to close the case if that is better.
