### ISSUE TITLE
Connection failed 36 Operation now in progress

### ISSUE THREAD

**Issue by frameshift18** [Ysurac/FlightAirMap#196]
When I run php daemon-spotter.php I get the error Connection failed to 10.1.1.191 : 36 Operation now in progress. No data is shown. /live/geojson has no data.

Connecting...
PHP Notice:  Undefined index: _ in /usr/local/www/FlightAirMap/scripts/daemon-spotter.php on line 210
Connection failed to 10.1.1.191 : 36 Operation now in progress
Connected!
SCAN MODE

**Comment by Ysurac** [comment]
What are the setting of *$globalSources* in **require/settings.php** ?
Are you sure you can connect to this address (without firewall, listening to the port you set,...) ?

**Comment by frameshift18** [comment]
$globalSources = array(array('host' => '10.1.1.191','port' => '30003','name' => 'sdr1','format' => 'auto','sourcestats' => FALSE));

dump1090 is running on a pi with 10.1.1.191. I can run 'nc 10.1.1.191 30003' and see the output from dump1090

**Comment by Ysurac** [comment]
Strange. What is the version of PHP ?
What is the value of **$globalSBS1TimeOut** ?

**Comment by frameshift18** [comment]
It fails instantly upon running the script. Using PHP 5.6.24 with nginx and mysql. Running on FreeBSD.

$globalSourcesTimeOut = '60';

**Comment by Ysurac** [comment]
You could try latest commit, maybe this solve the issue. Else I will have to try on FreeBSD.

**Comment by frameshift18** [comment]
Latest commit did not change any errors on my FreeBSD box. I just installed on a RPi3 and it seems to be fully working. Far as I can tell same configuration as on my FreeBSD box.

**Comment by Ysurac** [comment]
This is solved in commit 3f174d3131c5ca5f9826aef656deacec65698024

**Comment by frameshift18** [comment]
Working correctly now with commit 3f174d3. Thank you!
