### ISSUE TITLE
cron-sbs.php hangs after a little while

### ISSUE THREAD

**Issue by uppaljs** [Ysurac/FlightAirMap#20]
Hi,

I have noticed that cron-sbs.php hangs after a little while. The only way to recover it is to kill the process and run it again , Is there any way I can enable debugging for troubleshooting this issue?

Thanks,

**Comment by Ysurac** [comment]
If you set *$globalDebug = TRUE* in *require/settings.php* and run *cron-sbs.php* in console you will see why it hangs.

**Comment by uppaljs** [comment]
Hi,

I have  $globalDebug = TRUE in my settings.php all i see are the entries like below , and after a random interval , it just stops adding new planes ( i removed the detail from the entry below )


DATA : hex : 42XXX - ident : KXXXXX - ICAO : A320 - Departure Airport : NA - Arrival Airport : NA - Latitude :XXXXXX - Longitude : XXXXXX - waypoints :  - Altitude : 260.5 - Heading : 240 - Speed : 448 - Departure Airport Time :  - Arrival Airport time :
\o/ Add KXXXXX in Live DB : success

I actually see it on my ADSB receiver as well

Port 30003
12.05.2015 19:39:49(G) Port 30003: established #1 from 192.168.20.19:57214
12.05.2015 19:40:26(G) Port 30003: Operation canceled
12.05.2015 19:42:53(G) Port 30003: established #1 from 192.168.20.19:57234
12.05.2015 19:43:30(G) Port 30003: Operation canceled
12.05.2015 19:46:56(G) Port 30003: established #1 from 192.168.20.19:57280
12.05.2015 19:47:19(G) Port 30003: Operation canceled
12.05.2015 19:49:09(G) Port 30003: established #1 from 192.168.20.19:57291
12.05.2015 19:49:15(G) Port 30003: Operation canceled
12.05.2015 19:51:04(G) Port 30003: established #1 from 192.168.20.19:57298
12.05.2015 19:51:09(G) Port 30003: Operation canceled
12.05.2015 20:51:52(G) Port 30003: established #1 from 192.168.20.19:57309

**Comment by Ysurac** [comment]
Strange... The problems is after some minutes ? hours ? days ?
I will try to check why it ca can't reconnect correctly... This shouldn't happen with current commit...

**Comment by uppaljs** [comment]
@Ysurac , its random , like in the past 30 minutes , it has happened 2 times. I can open up the port if you'd like to test my feed data directly from my receiver?

**Comment by Ysurac** [comment]
If you want, but I will not have the time before tomorrow morning, so in about 9-10 hours.

**Comment by uppaljs** [comment]
Hi,

Thanks , sent it to your email listed on the github profile , The receiver is always on-line.

Regards,

**Comment by Ysurac** [comment]
Strange feed, sometimes work, sometimes not... I tried with *cron-sbs.php*, *wget*, a web browser,... same. Sometimes no problem, but sometimes no data or timeout. Don't seems to be a problem with my script but with the feed, seems like a CPU usage too high on your Radarscape.
Maybe I can use http://radarcape/deltadb.txt or http://radarcape/aircraftlist.json if you give me some example files.  I will also support try to support AVR format, should be less CPU intensive.

**Comment by uppaljs** [comment]
Strange , doesn't happen here. I just mapped 9192 to port 80 on the same host , you can try the http urls mentioned above.

Below are the ports that are available , i can map any for your development.

Port 10002 (unchecked true raw data)
Port 10003 (all data formats, including Mode-AC, CRC checked)
Port 10004 (DF11/DF17 CRC checked)
Port 10005 (non ADS-B frames, CRC checked)
Port 10006 (all data formats, no Mode-AC, CRC checked)
Port 30003

**Comment by uppaljs** [comment]
Oh wait , sorry , please try now , Since you were outside my network , it was routing all of your traffic over my vpn , not a smart idea , the feed should be okay for you now

**Comment by Ysurac** [comment]
It's better now, I receive the feed without problems. I investigate...

**Comment by Ysurac** [comment]
No crash since more than 4 hours, still testing...

**Comment by Ysurac** [comment]
OK, I succeeded to crash it. After I killed *cron-sbs.php*, I had only timeout from port 30003. This seems to be a problem with Radarcape or the way I connect to it.

I added support of *http://radarcape/deltadb.txt* and *http://radarcape/aircraftlist.json* in commit 18094508b4b9b8f37e1074d22966371f144d5c86. You only have to add the URL to *$globalSBS1Hosts*. 
**For example :** *$globalSBS1Hosts=array('http://radarcape/deltadb.txt');*

**Comment by uppaljs** [comment]
Thanks , Getting the latest build and will report back.

**Comment by uppaljs** [comment]
Reporting back that using the deltadb.txt with RadarCape actually fixes the issue with the crashes.

Thanks a lot.

**Comment by uppaljs** [comment]
Apologies to report back again , crashed after a day. cron-sbs.php just hanged and I couldn't even stop it with ctrl+c , had to kill the process.

**Comment by Ysurac** [comment]
This doesn't seems to be on my side. After a crash with *cron-sbs.php*, for me a wget/web browser/curl/... at the same source timeout also.

**Comment by Ysurac** [comment]
Seems to have the same problems from an other source. I'm trying to resolve and reproduce the bug...

**Comment by uppaljs** [comment]
If you need access to the feed again , please do let me know.

Thanks,

**Comment by c0by1** [comment]
same here. crashed after a while.

**Comment by Ysurac** [comment]
Not yet after 52 hours... Strange...

**Comment by c0by1** [comment]
my crashed after a few hour. did you update the cron-sbs.php ?

**Comment by Ysurac** [comment]
lol yes.
What is your source ? Dump1090, Radarcape, ... ?

**Comment by c0by1** [comment]
dump1090-mutability

**Comment by Ysurac** [comment]
I use the same source, so the problem is not here...
What DB do you use ? version ?
Same for PHP.

**Comment by c0by1** [comment]
? php version and mysql version?

**Comment by c0by1** [comment]
PHP 5.4.41-1~dotdeb+7.1 (cli) (built: May 15 2015 10:59:59)

mysql  Ver 14.14 Distrib 5.6.23, for debian-linux-gnu (x86_64) using  EditLine wrapper

**Comment by Ysurac** [comment]
I'm using PHP 5.5 and MariaDB, but this shouldn't make so much change...
I have really no idea where the bug can be for now...
You can try to set **$globalFork = FALSE** in *require/settings.php*, maybe a problem with that...

**Comment by c0by1** [comment]
I've changed it and restart the script... I will see it tomorrow and notice you.

**Comment by Ysurac** [comment]
Thanks.

**Comment by c0by1** [comment]
No problem...

**Comment by c0by1** [comment]
crashed again

**Comment by c0by1** [comment]
how do you let the cron-sbs.php run? with screen ?

**Comment by c0by1** [comment]
some workaround...

#go in dir
cd /var/www/flight
#kill all runing screen sessions
killall -15 screen
#run script with screen in background
screen -d -m ./cron-sbs.php


######

nano /etc/crontab

* */2 * * * user /scripte/flight.sh

^^

**Comment by Ysurac** [comment]
really dirty ;) I run it with init script, without screen.
Dump1090 is used locally ?
How many flights do you have at the same time ?

**Comment by c0by1** [comment]
^^ Nope i use it remote. Vserver -> Home connection. simultaneously flights 5 - 40...

**Comment by Ysurac** [comment]
Could you try commit fd7db4dee24b3bf9943ec580c0f884fb0e4f918b ?

**Comment by c0by1** [comment]
i am trying

**Comment by c0by1** [comment]
tricky... sometimes craches after hours... sometimes after minutes...

**Comment by Ysurac** [comment]
What is the last message do you have after a crash ?

**Comment by c0by1** [comment]
Added ***** in Live DB : success


Debug mode is on.

**Comment by Ysurac** [comment]
Strange. This should display something else after that if there is an error...
Difficult to debug because it's working since several days on 2 computers for me...

**Comment by c0by1** [comment]
i am trying it now without screen in the foreground...

**Comment by Ysurac** [comment]
I pushed a new commit, maybe we will see an error now...

**Comment by c0by1** [comment]
can you give me a hint, to update the git clone? how can i do this? i download the new (raw) files via wget... by hand.

**Comment by Ysurac** [comment]
*git pull* inside the cloned directory

**Comment by c0by1** [comment]
git pull
Updating 96418f3..cc46fcb
error: Your local changes to the following files would be overwritten by merge:
        .htaccess
        cron-sbs.php
        require/class.Spotter.php
Please, commit your changes or stash them before you can merge.
Aborting

**Comment by Ysurac** [comment]
you have local changes, remove them.
**rm .htaccess cron-sbs.php require/class.Spotter.php**
**git pull**

**Comment by c0by1** [comment]
wrong port? i use 30003!

![fl](https://cloud.githubusercontent.com/assets/5725891/7884364/8567ccb4-061d-11e5-87f4-d7bbad93e59f.png)

**Comment by Ysurac** [comment]
Ok, this should be better in latest commit 9e255889014bdc179376b554de53d7b2ea80f6f8

**Comment by c0by1** [comment]
i will test...

**Comment by Ysurac** [comment]
Not working well. But this time fail on one of my computer. Not same fork of Dump1090. I investigate...

**Comment by c0by1** [comment]
stopped again... without error message

![fl1](https://cloud.githubusercontent.com/assets/5725891/7887469/9b2eace8-0631-11e5-91aa-ea70bbec6a44.png)

**Comment by Ysurac** [comment]
I made some changes, I test them and if I have no crash I will commit them in about 2 hours.

**Comment by c0by1** [comment]
ok. give me a notice here.

**Comment by c0by1** [comment]
reproducible...

![image](https://cloud.githubusercontent.com/assets/5725891/7888309/dfe055fc-0637-11e5-99d2-6cf9525b2295.png)

**Comment by Ysurac** [comment]
You can try commit 6af793e49baaf2c31f944c16141398949abd111b

**Comment by c0by1** [comment]
on my way...

**Comment by c0by1** [comment]
looks stable. still running.

**Comment by c0by1** [comment]
but i see no planes... /live/geojson stays white...

**Comment by c0by1** [comment]
spotter tv is also empty / white...

**Comment by Ysurac** [comment]
Should be fixed in commit 2b35587fa657d815d22bd0a3b34e68d773af8d1c
(A new feature not yet finished... need to add a new table... disabled for now)

**Comment by c0by1** [comment]
seems to be fixed but the 24h disconnect from my isp, killed the script. do got an solution for this? do you know the problem?

i get after 24h a new ip address...

**Comment by Ysurac** [comment]
It's a bug. The script should restart automatically. I investigate...

**Comment by c0by1** [comment]
screen was open and i saw an empty shell... without an running script.

**Comment by c0by1** [comment]
Email test. i will delete this message..

**Comment by Ysurac** [comment]
Script try to restart, but it's not working.
Should be fixed in commit 217bbf9695bcb5f139628eaa67c2c8995d8e0a73

**Comment by c0by1** [comment]
ehem... runs stable... i pull the new one now...

**Comment by c0by1** [comment]
i would say: can be closed. runs fine and stable.

**Comment by Ysurac** [comment]
I love to close bugs.
