### ISSUE TITLE
Proces stops

### ISSUE THREAD

**Issue by rstroom** [Ysurac/FlightAirMap#201]
I run daemon-potter.php bij putty. After about one hour it stops and send the next message: 

PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':00:00.000 - latitude)*pi()/180/2),2)+COS( 01:00:00.000 *pi()/180)*COS(latitude*' at line 1' in xxx/require/class.Spotter.php:8996
Stack trace:
#0 xxx/require/class.Spotter.php(8996): PDOStatement->execute()
#1 xxx/require/class.SpotterImport.php(129): Spotter->closestAirports('01:00:00.000', '0001/01/01', '50')
#2 xxx/require/class.SpotterImport.php(176): SpotterImport->arrival('A802C5')
#3 xxx/require/class.SpotterImport.php(685): SpotterImport->del()
#4 xxx/require/class.Spotter.php on line 8996

What can I do so the proces keeps running?

**Comment by Ysurac** [comment]
Strange data... What source are you using ?

**Comment by rstroom** [comment]
I use SBS taken from Virtual Radar Server in Basestation mode

**Comment by Ysurac** [comment]
ok, never tried that... It seems to send wrong data sometimes, I will add more check tomorrow.

**Comment by Ysurac** [comment]
This should be solved since commit ffb22c06ae773b3cef02af69700d20889aa71a5b
