### ISSUE TITLE
aircraftlist.json

### ISSUE THREAD

**Issue by rstroom** [Ysurac/FlightAirMap#205]
How do I run aircraftlist.json format from vrs to Flightairmap

**Comment by Ysurac** [comment]
Put the url of your VRS installation using install script or directly in **settings.php** like this
*$globalSources = array(array('host' => 'http://urlofyourvrsinstall/AircraftList.json', 'port' => '80', 'name' => 'VRS', 'format' => 'aircraftlistjson', 'sourcestats' => FALSE));*

**Comment by rstroom** [comment]
and run daemon-spotter.php?

**Comment by Ysurac** [comment]
yes
