### ISSUE TITLE
How to connect data source?

### ISSUE THREAD

**Issue by DeanXLiu** [Ysurac/FlightAirMap#206]
I already install apache,php and mysql,but I can not connect any data source,please help me,thanks!

**Comment by Ysurac** [comment]
I need more info...
* What source do you want to connect to ?
* Did you already run and configure FlightAirMap with **install/index.php** ? 
* What is the problem ?

**Comment by DeanXLiu** [comment]
I already run install/index.php,and I can see the map on Home page,I don't know how to config the real data source or virtual.

**Comment by Ysurac** [comment]
This can be configured in **install/index.php**.
What source do you have ?

**Comment by DeanXLiu** [comment]
If I want to connect the real flights data source,should I buy Physical hardware?
And if I want to connect IVAO(virtual flights),how should I configure that?

**Comment by Ysurac** [comment]
For real flights you could buy antenna and usb rtlsdr key, find someone that share it's data, use glidernet APRS server (but it's only for small flights often used in Europe),...
For IVAO as source you can use *http://api.ivao.aero/getdata/whazzup/whazzup.txt*
For VATSIM this can be *http://info.vroute.net/vatsim-data.txt*

**Comment by DeanXLiu** [comment]
Thank you,but I still don't know how to write on index.php,or should I set something in settings.php?

**Comment by Ysurac** [comment]
Use **install/index.php**, all configuration can be made here.
