### ISSUE TITLE
Install today

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#21]
Hello today is not to install and yesterday if I skip this now .....

![captura](https://cloud.githubusercontent.com/assets/4571086/7618615/8e4c749a-f9b3-11e4-87df-5edc9ff04a98.JPG)

Thanks

**Comment by Ysurac** [comment]
Fixed in commit 1e93b58b5bdbf86a6645d48ceeef1464ca77901f
sorry

**Comment by tonkepen100** [comment]
Atention the tables waipoints and routes are clear and thanks

**Comment by Ysurac** [comment]
Sorry, I don't understand.

**Comment by tonkepen100** [comment]
waipoints yesterday tables and routes filled with data, are now empty.

**Comment by Ysurac** [comment]
You can delete all tables and run install script again. All should work.

**Comment by tonkepen100** [comment]
![image](https://cloud.githubusercontent.com/assets/4571086/7620879/eeeaea0c-f9c2-11e4-9165-44ab18cdb208.png
![captura](https://cloud.githubusercontent.com/assets/4571086/7620891/fc71df00-f9c2-11e4-960f-11bb39b8b9f3.JPG)

**Comment by Ysurac** [comment]
Fixed in commit 6d506633f1c51c7566f5f214bc13c9834237cdc2
Sorry, I should really sleep...
This script should be run under console. Only *install/index.php* can be run under web browser.

**Comment by tonkepen100** [comment]
nothing happens, but the web is in my hosting and'd tell me as I do from a console if you do not have access

**Comment by Ysurac** [comment]
*update_db.php* don't display anything under web browser, even if it could work silently.

*cron-sbs.php* or *cron-acars.php* will not work without console access. I don't know if I can make an usable version without this need...

**Comment by tonkepen100** [comment]
If work looks ....

the problem now is that when you put intall / install.php stops and says queya is finished without carrying any tables you send photo and you see, all via web yesterday charged.
![captura](https://cloud.githubusercontent.com/assets/4571086/7621326/47fee06e-f9c6-11e4-93ff-007ac9abc32d.JPG)

**Comment by tonkepen100** [comment]
See and sorry my english is verry bad...
![captura](https://cloud.githubusercontent.com/assets/4571086/7621369/9f43a922-f9c6-11e4-91e5-4729a73b92e2.JPG)

**Comment by Ysurac** [comment]
*install/index.php* is only used for create/populate database for fresh install, update *require/settings.php* and update table schema after a pull of a new version.
*install/update_db.php* is to update data that are fetch from internet and is means to be run weekly or monthly.
But now you should have all data needed in database (else remove all tables and run *install/index.php* again to create them again), all you need is to run *cron-sbs.php*, but under web browser it will stop each time you close the browser.

Time to go to bed for me here. No more answer before 9 hours.

**Comment by tonkepen100** [comment]
Thanks verry thanks
