### ISSUE TITLE
Display satellite in 3D world

### ISSUE THREAD

**Issue by Ysurac** [Ysurac/FlightAirMap#213]
For now ISS can be displayed. Why not other space stations and satellites ?
Data can be get from NORAD.
3D models will be needed.

**Comment by Ysurac** [comment]
TLE files from celestrak are downloaded and parsed so coordinates can be calculated.
All satellites will be available by type and name.
Need to find 3D models for space stations and satellites.

**Comment by tonkepen100** [comment]
https://nasa3d.arc.nasa.gov/models

**Comment by Ysurac** [comment]
It's one of my source but I have problems to convert some files to the format used for 3D map.

**Comment by tonkepen100** [comment]
what is the format?

**Comment by Ysurac** [comment]
From the NASA it's lwo or fbx and I need to import them into blender, convert them to dae and then to  gltf and finally to glb.
I have a bug in Blender import for now. But I will solve that.

**Comment by Ysurac** [comment]
Models I have for now:
* GPS
* Globalstar
* o3b
* ibex
* ISS
* Tiangong 1

More to come...

It's fun to see GPS constellation.

**Comment by tonkepen100** [comment]
Gooooddd, Gooddd Ysurac

**Comment by Ysurac** [comment]
It's available and working. Selection of particular satellites will maybe be added later...
