### ISSUE TITLE
report error 

### ISSUE THREAD

**Issue by bilkaPek** [Ysurac/FlightAirMap#214]
1- have not see planes on" flightid-overview" page for the individual track

2- do not recognize the name of the Airlines' statistics page and flightid-overview "everything goes into the" Owner "`$ globalOwner = FALSE` on `"settings.php"`

![screen1](https://cloud.githubusercontent.com/assets/16308214/18809872/d807ce96-8287-11e6-9184-49edef66c40b.JPG)

3- No stats on the map

- TOP 10 MOST COMMON DEPARTURE AIRPORTS
and airport-departure page

- 4  TOP 10 MOST COMMON ARRIVAL AIRPORTS
and airport-arrival page

**Comment by Ysurac** [comment]
1- Fixed in latest commit
2- Check your airlines table and check that VATIM & IVAO is not checked in install script if you use a real flights source
3- Table of airport-departure and airport-arrival is empty or not ?

**Comment by bilkaPek** [comment]
VATIM & IVAO is not checked in install script

> IVAO and VATSIM is `FALSE`

Table of airport and airport-departure-arrival is empty or not?

> Not because I recovered from direct source real flights

airlines table

> db is ok (total de 1061 airlines )

**Comment by Ysurac** [comment]
**globalphpVMS** is also set to FALSE ? Your airline table have VATSIM airlines. If IVAO,VATSIM or phpVMS was checked at install, vatsim airlines are used. You can insert db/airlines.sql manually to fix this.

For table, it's the table in airport-departure-arrival page. It's only the map or all the page that is empty ?

**Comment by bilkaPek** [comment]
the problem is solved for airlines after reset table

only the map page statistics that does not return information it remains static map
page /statistics
> airport-departure & airport-arrival

the continent not react because no data in the table

> page /statistics/airport-departure-country
page /statistics/airport-arrival-country

![screen2](https://cloud.githubusercontent.com/assets/16308214/18810313/6954cef2-8293-11e6-906e-38db81967684.JPG)
![screen3](https://cloud.githubusercontent.com/assets/16308214/18810314/6958a900-8293-11e6-8f1a-898333d62b34.JPG)

**Comment by Ysurac** [comment]
Should be fixed in latest commit.
