### ISSUE TITLE
Black screen when switching to 3D

### ISSUE THREAD

**Issue by linuxpronl** [Ysurac/FlightAirMap#215]
When I go to 3D (selecting a flight or not) I get a black screen, no world, no plane(s)   Latest git pull done and ran /install and update_db.php   any suggestions?

Linux/CentOS 7/Chome-stable

**Comment by Ysurac** [comment]
Your browser support webgl ? Test on http://get.webgl.org/

**Comment by linuxpronl** [comment]
Yep, I see a spinning cube on that test site

**Comment by Ysurac** [comment]
Check browser console log in developer tools if there is an error.

**Comment by linuxpronl** [comment]
Console says: This application is using Cesium's default Bing Maps key.  Please create a new key for the application as soon as possible and prior to deployment by visiting https://www.bingmapsportal.com/, and provide your key to Cesium by setting the Cesium.BingMapsApi.defaultKey property before constructing the CesiumWidget or any other object that uses the Bing Maps API.

**Comment by Ysurac** [comment]
You can try to create a Bing Maps key but this is not the problem, a default key should be used.
You have no others errors ?

**Comment by linuxpronl** [comment]
I created a bing map api, created a key and added to settings.conf and now I've 3D

**Comment by Ysurac** [comment]
OK. I will put in install script that Bing key is needed.
Thanks
