### ISSUE TITLE
AIRCRAFT TYPES & LOGOS

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#216]
Well this is the idea ...

We see in the section TYPES AIRCRAFTS, the planes detected by our radar out in letters ...

![captura1](https://cloud.githubusercontent.com/assets/4571086/18913728/b2145dda-8589-11e6-94ff-3ed717becc09.JPG)

And we see in the AIRCRAFT table, the ICAO column.

![captura](https://cloud.githubusercontent.com/assets/4571086/18913730/b670a1ea-8589-11e6-94c2-90b1e5e850b5.JPG)

Well the issue is that we have downloadable files silhouettes of all aircraft and other owners here ....

http://radarspotting.com/forum/index.php?action=tpmod;dl=cat288

The issue is that the names of those silhouettes icao match the column of the table, you could say to him to take these silhouettes program, so they left the silhouettes in the section TYPES AIRCRAFTS.

While the issue is that they are in bmp, but change is very simple.

And also seen the logos of the companies are in PNG, for example by rasperris or beagles or small teams, sensational serious they could be put into lighter formats, not if he could but I think it's easy.

Also I leave here the download web logos of companies, if anyone wants to modify existing images. or put those missing, which are numerous.

http://radarspotting.com/forum/index.php?action=tpmod;dl=cat288

Thank you.

**Comment by me2tkt** [comment]
I tried to convert the BMP files from the link above into PNG files - but it did not look very good.
Used the Faststone picture editor and set it to give the same file size as the PNG file in the installtion package.
But on the webpage the converted logos were lumpy and off centre.
Any recommendations for the conversion settings ?

**Comment by Ysurac** [comment]
You want to use them for the map ? Why ?

**Comment by Ysurac** [comment]
Pics are too small to be used, this can only be lumpy.
For center they need to be exactly the same size, orientation and position as mine.

**Comment by me2tkt** [comment]
I only want the airline logos for the staistics page, etc.
Particularly for airlines which do not have a logo in the install package.

Here are some example BMP logo
[Pictures.zip](https://github.com/Ysurac/FlightAirMap/files/622090/Pictures.zip)

**Comment by Ysurac** [comment]
It's better to tell me what airlines (and airlines ICAO) you need. Or submit them. 
In fact I often use wikipedia as source for airlines logo. I will maybe make a script to download all...

**Comment by me2tkt** [comment]
Thank you for updating the airline logos.

Coming back to tonkenpen originla qustion.
I would like to use silhuettes for the statistic pages instead of image thumbnails.
These are available as BMP named after the registrations of the aircraft.
My idea would be to add a field to the image-spotter.db with the local URL of the silhuette.
Obviously some logic to switcht from thaumbnail to silhuette would be required.

Would that be possible ?


[Pictures.zip](https://github.com/Ysurac/FlightAirMap/files/629461/Pictures.zip)
