### ISSUE TITLE
Error during Installation "Invalid default value for 'real_departure_airport_time'"

### ISSUE THREAD

**Issue by jjx-** [Ysurac/FlightAirMap#219]
Hi,
I am getting the following error during Installation again and again.
DB is: mysql  Ver 14.14 Distrib 5.7.15, for Linux (x86_64)

Write configuration....SUCCESS
    Create database....SUCCESS
    Create and import tables....SUCCESS

Error : error (import ../db/spotter_output.sql) : SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'real_departure_airport_time'

**Comment by Ysurac** [comment]
Really strange...
What version of FlightAirMap are you using ? git or a release ?
