### ISSUE TITLE
Button Home

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#22]
When you click on the home button, it stays on the same page you were previously viewing. The web address is the same does not change and remains at the last visit.

![captura](https://cloud.githubusercontent.com/assets/4571086/7626621/9addb896-fa0c-11e4-8f03-316aef34facc.JPG)

**Comment by Ysurac** [comment]
True. I know this since a long time, maybe this will be fixed sometimes...

**Comment by Ysurac** [comment]
Fixed in commit 2dc36502166fa11023c75a6a9c835555277ec345
