### ISSUE TITLE
Error when updating

### ISSUE THREAD

**Issue by linuxpronl** [Ysurac/FlightAirMap#220]
after the last git pull and running install I get:

Error : error (add unique key in stats) : SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'type'; check that column/key exists

**Comment by Ysurac** [comment]
You have to update to latest commit, run this in MySQL/MariaDB:

    drop index stats_type on stats;ALTER TABLE stats ADD UNIQUE stats_type (stats_type,stats_date,stats_airline,filter_name);

then you can run install/index.php
