### ISSUE TITLE
New source for NOTAM

### ISSUE THREAD

**Issue by Ysurac** [Ysurac/FlightAirMap#221]
A new source for NOTAM, that should cover all the world is in dev.

**Comment by Ysurac** [comment]
Done

**Comment by xyziolite** [comment]
Hi and Thank you very much... 
error => updating NOTAM...NOTAM from FlightAirMap website : Download...Gunzip...Add to DB
...ERROR : Q)WIARADIUSOF1NMANDAMAXHGTOF375FTAMSL.325FTAGL
Done

**Comment by xyziolite** [comment]
i used latest commit 28/10/2016 these error came out

**Comment by Ysurac** [comment]
It's a bad formatted NOTAM. Not a problem.

**Comment by xyziolite** [comment]
ok , i try to update again , Thanks
