### ISSUE TITLE
Report various errors from last commit

### ISSUE THREAD

**Issue by bilkaPek** [Ysurac/FlightAirMap#222]
1. page Type aircrafts "flightairmap/aircraft/A332" return SQL error 
`Invalid query : SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'WHERE ORDER BY spotter_output.date DESC LIMIT 25 OFFSET 0' at line 1 Whole query: SELECT spotter_output.* FROM spotter_output WHERE spotter_output.ident <> '' AND (spotter_output.aircraft_icao = :aircraft_type) WHERE ORDER BY spotter_output.date DESC LIMIT 25 OFFSET 0`

2. Notams
 circles Notam on the map is displayed but does not return any information when mouseover

3. Waypoints Beug on map
![capturewaypoints](https://cloud.githubusercontent.com/assets/16308214/19342717/42e13040-9133-11e6-9ee9-a652c59c5414.JPG)

4 . Airspace layers
Airspace layers are not shown on the map can be under developement
or I lack a condition that right will be displayed ?

5 . Track it Link !
return home index.php page
![capturetrackerlink](https://cloud.githubusercontent.com/assets/16308214/19343595/199e1a3c-9137-11e6-96e3-042cae90c4a6.JPG)

**Comment by Ysurac** [comment]
1. Fixed
2. True. This seems to be a bug in Leaflet. I will try to revert to a previous version.
3. beautiful. But I'm not able to reproduce this. Web browser and version ? DB and version ?
4. The checkbox *Add waypoints, airspace and countries data* must be checked.
5. True. But it's a feature. If the flight is on map, it should be selected with info, else this return to flight page.

**Comment by Ysurac** [comment]
2. fixed in latest in commit

**Comment by bilkaPek** [comment]
- [ ] Mysql server 
Version du serveur : 5.5.52-0+deb8u1 - (Debian)

- [ ] return Error with two web browser Chrome & Firefox
return link to the address bar
`flightairmap?2d&trackid=1206249-IBK108`

- [ ] Airspace and Waypoints the tables are full

**Comment by bilkaPek** [comment]
- [ ] Another error in / statistics/airline-country

`error : SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'GROUP BY airline_country ORDER BY airline_country_count DESC LIMIT 10 OFFSET 0' at line 1`

**Comment by Ysurac** [comment]
page statistics/airline-country fixed in latest commit

**Comment by bilkaPek** [comment]
Une erreur étrange se produit
si je ne met pas `TRUE` a `$globalIVAO = TRUE;` ou `$globalVATSIM = TRUE;`
je n'ais que Ryanair comme airline sur la map 
d'ou le problemes antérieur de translation des airlines 
alors que la source est `adsbexchange` ave le format aircraftlistjson
avec tout par default dans le code source 
j'ai même refais une install du dernier commit pour être sur du code...
et le problème persiste, très étrange :(

**Comment by Ysurac** [comment]
Certainement un soucis avec la table airlines. Si VATSIM a été mis à un moment, la liste des lignes a été remplacé par celles de VATSIM. Pour résoudre le soucis il suffit d'importer la table *db/airlines.sql*.
Si ça ne change rien, il faut vérifier les options de filtrages (barre à gauche de la carte).

**Comment by bilkaPek** [comment]
lors de l'intall ni ivao ni vatsim sont sélectionne  
j'ai même refait un clean install supprimé toutes les tables mes le problème persiste 
j'ai réinstaller la table airlines.sql manuellement  même résultat  
pas de filtrage dans la barre de gauche  "Display airlines" dans le setting non plus 
je vient de faire un autres test en mettant `$globalMapVAchoose = TRUE`
```
// *** Virtual flights ***
//IVAO
$globalIVAO = FALSE;

//VATSIM
$globalVATSIM = FALSE;

//phpVMS
$globalphpVMS = FALSE;

//User can choose between IVAO, VATSIM or phpVMS
$globalMapVAchoose = TRUE;
```
 et tout fonctionne bien 
très étrange

**Comment by Ysurac** [comment]
Bizarre... Il faudrait essayer de virer tous les cookies pour le site.
Sinon il me faudrait une ligne de la table spotter_live pour voir si le soucis est la.

**Comment by bilkaPek** [comment]
je pense avoir touvé 
la condition dans class.spotter.php
a la` ligne 2524` je les commenter et jais réactive l’antérieur a la `ligne 2420` et tout fonctionne a nouveaux 
`/*if (isset($globalAirlinesSource) && $globalAirlinesSource != '') $forsource = $globalAirlinesSource;
			elseif (isset($globalVATSIM) && $globalVATSIM) $forsource = 'vatsim';
			elseif (isset($globalIVAO) && $globalIVAO) $forsource = 'ivao';
			if ($forsource == NULL) {
				$query = "SELECT DISTINCT icao AS airline_icao, name AS airline_name, type AS airline_type FROM airlines WHERE forsource IS NULL ORDER BY name ASC";
				$query_data = array();
			} else {
				$query = "SELECT DISTINCT icao AS airline_icao, name AS airline_name, type AS airline_type FROM airlines WHERE forsource = :forsource ORDER BY name ASC";
				$query_data = array(':forsource' => $forsource);
			}*/`

**Comment by Ysurac** [comment]
Donc le soucis vient de la table *airlines*.
La commande suivante doit retourner plusieurs valeurs, dont **NULL**:

     SELECT DISTINCT forsource FROM airlines;

Si ce n'est pas le cas, il faut mettre à jour au dernier commit et remettre la table airlines manuellement.

**Comment by bilkaPek** [comment]
la commande retourne seulement  `forsource  NULL `

**Comment by Ysurac** [comment]
ok, donc parfait. Je vois pas pourquoi ça fonctionne pas du coup... (et que ça fonctionne autrement)

**Comment by bilkaPek** [comment]
je dispose deja du dernier commit
tout est par défaut aucune modifications du code source
Une nouvel erreur vient d’apparaître si je zoom plus sur la carte le compteur disparaît

![capturecount](https://cloud.githubusercontent.com/assets/16308214/19356202/4e3d1f96-916d-11e6-893b-2dd72add64a3.JPG)


dessolé de te donne du travail :(

**Comment by bilkaPek** [comment]
cela me tracasse  :(
je vais crée un domaine pour faire des test depuis zero et je te dit de quoi il retourne.
dessole pour ce tracas...

**Comment by Ysurac** [comment]
J'ai réglé le *aircrafts deteted* dans le dernier commit. Je l'avais oublié lors de la mise à jour de leaflet...
Je teste avec la même source pour voir si j'arrive à reproduire le soucis.
Pas de soucis pour les tracas, j'ai fait pas mal de mise à jour et j'ai pas finis les tests donc y'a des bugs. Pour ça que je fais des releases, le git est instable par nature.

**Comment by bilkaPek** [comment]
voila nouvelle installation faite avec la DB qui va avec. 
- [ ] source de donné comme tu peut le voir aucun filtre sur l'URL 
dans le settings non plus tout est par défaut 
Lien du settings  [pastbien](http://pastebin.com/Vw6tNyiN)

- [ ] après 10mn que du Ryanair sur la map 

- [ ] après 20mn d'autre compagnies apparaisse tout est très lent pas plus de 20 avions

**Comment by Ysurac** [comment]
A part le *sourcestats* qui devrait être à FALSE car inutile et faux sur ce type de source.
J'ai des avions immédiatement sur la carte moi.
Si d'autres compagnies apparaissent avec le temps c'est que le soucis est ailleurs.

* Tu fais tourner ça sur quoi ? Raspberry 1,2,3 ? CHIP ? Z80 ? Pentium 90 avec disquette 5"1/4 ?
* **daemon-spotter.php** affiche quoi ? Il est bien lancé en daemon et pas en cron ?

**Comment by bilkaPek** [comment]
le script est en daemon  pas de "cron" trop lourd :)
j'ai un serveur dédié en datacenter OVH  

![capturesrv](https://cloud.githubusercontent.com/assets/16308214/19361039/4c6eba1c-9181-11e6-8d66-387028a2a8ea.JPG)

la charge serveur est plus que correcte 

![capturedaemon](https://cloud.githubusercontent.com/assets/16308214/19360880/a2894e68-9180-11e6-9866-875551b6b5b7.JPG)

je vient de  faire un test j'ai changer le script du daemon que tu fourni et que j'utilisé depuis peux par un des mien et le résultat est immédiat en -10 seconde plus de 150 appareil sur la map "incompréhensible" 
bizarre la relation de cause a effet du script que je n'arrive pas du-tout a comprendre,  je ne saurait te la donne mes cela fonctionne parfaitement a présent, mes je ferais plus de test demain car cela m'intrigue.
 
si tu cherche un cobaye tu peut compter sur moi :)  car tout ce qui peux arrive de bizarre m'arrive
Et je suis ce projet avec passion depuis que je l'ai découvert 

encore mille merci pour tes efforts et ta patience

**Comment by Ysurac** [comment]
Tu parles de quel script ? l'init ou daemon-spotter ? et remplacé par quoi ?

**Comment by bilkaPek** [comment]
Je parle de l'init, mes tout cela me paraît bien étrange je regarderai demain de quoi il en retourne

**Comment by Ysurac** [comment]
Oui étrange. Mais à part l'init openrc je n'ai pas testé les autres. Celui pour systemd est fait d'après la doc, mais aucune idée si c'est bon...

**Comment by bilkaPek** [comment]
Re bonjour 
après maintes recherche dans tout les log's, rien de spéciale tout ça reste bien étrange pour moi!
plusieurs test effectue depuis et pas de confit en vue dans les log's rien qui cloche ou je ne le vois pas..

mes jais qu'en même apporte quelle que modification au fichier  `flightairmap.service.systemd` afin d'améliorer les performances et qu'il ne ce gave pas des ressources système sans contrôle qu'en t'il traites beaucoup d'informations.

dans la documentation systemd il précise bien que celui-si doit être optimiser selon la distribution 
le `service.systemd` que tu a produit et très bien mes un peut trop générique a toutes les distribution après lecture de la doc, ils recommande de l'adapter a ça distribution ce qui a pour effet de l'amélioré 

en ce qui concerne le `daemon-spotter.php ` le fait de le parse par l'option `php -f` le rend plus souple 
"selon la doc de php" sela ne ser a rien...? je te laisse me confirme c'est ton domaine 
>alors que  L'option -f est facultative et peut être omise Le seul nom du fichier est suffisant. 

exemple pour que tu me comprenne 

> Pour une debian 7 & 8

> `ExecStart=/usr/bin/php -f /var/www/flightairmap/scripts/daemon-spotter.php`

Gestion Block IO: qui attribue un poids IO à un service spécifique et gestion de la mémoire 

> ```
> [Service] 
> # spécifié l'utilisateur 
> User=root
> # Type process 
> Type=daemon
> IOAccounting=true
> BlockIOWeight=500
> MemoryAccounting=true
> MemorySoftLimit=100M
> MemoryMax=160M
> ```
je ne développe pas toutes options mes faut s'appliquer a lire la doc que je recommande a tous
car elle facilite bien les chose 

voila pour ses quelle-que paramètres qui reste utile elle donne l'avantage de bien géré mes services

Si tu a des recommandations ou suggestions je suis preneur, si tu lit des bêtises merci de me reprendre

**Comment by Ysurac** [comment]
Pour le -f il sert à rien dans mon car il y a un seul script.
Pour systemd, j'en ai aucune idée, et je vois pas trop pourquoi il faudrait lui donner des options qui le limite pour qu'il fonctionne correctement, à moins qu'il y ait des options par défaut encore plus stricte. Je n'utilise pas systemd et je fais tout pour pas l'utiliser :)

**Comment by bilkaPek** [comment]
Oui je comprend pour le -f 
(Systemd) pas mal dencré coule à ce  sujet
Mes j'en suis dépendent pour d'autres services il est vrai que j'ai pris l'abitude de l'utilise car il me rend bien service 😆

**Comment by Ysurac** [comment]
Un peu trop usine à gaz pour moi. Je reste à OpenRC (Gentoo) quand je peux.

**Comment by bilkaPek** [comment]
oui je confirme :) 
prochaine migration red Hat ou Fedora, maintenant faut ce décider Test sur VM puis migration de tout les services sur dédier
