### ISSUE TITLE
Add suport for VAM

### ISSUE THREAD

**Issue by bilkaPek** [Ysurac/FlightAirMap#226]
In preparation for my v.a with virtual airline manager that is not supported by FlightAirmap

basic there is no file that returns enough information file to be operated by flightairmap
I created a simple file to return information in the format json ['`vam_json.php`'](http://pastebin.com/h1vV3m8e) and '`flight_json.json`' to be operated locally

could you integrated ?
thank you.

**Comment by Ysurac** [comment]
It would be better if I can find a file that return the info...
In your code you don't need to generate a .json, only return the result.

**Comment by Ysurac** [comment]
**vam/get_map_coordinates.php** is maybe usable.

**Comment by Ysurac** [comment]
Maybe with **vam/get_live_flights.php** for callsign. Need to find how to associate callsign with pilotid...

**Comment by Ysurac** [comment]
**vam_live_flights_map.php** can also be parsed. It would be far better if VAM provide a good json...

**Comment by Ysurac** [comment]
Seems that you are right... need to create a file...

**Comment by bilkaPek** [comment]
I wanted to reproduce the Aircraftlistjson format.
I experience my difficulty has generated the same format for lack of experiences

> for callsign. Need to find how to associate callsign with pilotid...

you will notice that my file is `gvauser_id  `that is unique to the pilot and the `callsign` that the also

- JSON returns its information

`[{"gvauser_id":"40","callsign":"VAM500","flight_id":"AFR524 ","name":"Jhon Doe","plane_type":"B739","departure":"SVMI","arrival":"LFPO","latitude":"42.7328860921521","longitude":"2.87433614409404","altitude":"147","heading":"307","ias":"1","gs":"0","flight_status":"BOARDING","last_update":"2016-10-23 16:51:31"}]`

**Comment by Ysurac** [comment]
is there something unique to the flight ?
Why do you do a substr for flight_id ?
What is this callsign ? this don't seems to be flight callsign (flight_id seems to be)

**Comment by Ysurac** [comment]
I've made a new version of the file : http://pastebin.com/ABrqsevS
Only need to be inside the VAM directory, this use VAM user, pass,...

I need to now the unit used for altitude and ground speed now...

**Comment by bilkaPek** [comment]
you can choose for speed in the file between IAS and GS and the altitude it is FT

**Comment by Ysurac** [comment]
ok for the altitude, but for the speed I need the unit : knots, mph, km/h,...

**Comment by bilkaPek** [comment]
if I'm not mistaken error is `knots`  value

**Comment by Ysurac** [comment]
ok. Support is in latest commit.

**Comment by bilkaPek** [comment]
thank you I test it soon

**Comment by bilkaPek** [comment]
ajouter l'argument  `new`  dans VAM-json.php a la ligne 8 sinon retourne une erreur SQL `$db = new mysqli`

**Comment by Ysurac** [comment]
fixed

**Comment by bilkaPek** [comment]
test performs
it inconclusive
daemon-spotter.php in a loop, it no returns data


```
Connected!
SCAN MODE

Get Data...
Sleeping...
Get Data...
Sleeping...
```

**Comment by Ysurac** [comment]
Seems that VAM-json.php return empty data.
If it's not the case this will be difficult to debug without an access I think...

**Comment by bilkaPek** [comment]
I have Data a return but are not read by daemon-spotter
I work locally but I'll make an install and I will provide a link

**Comment by Ysurac** [comment]
I've updated VAM-json.php
This can be better...

**Comment by bilkaPek** [comment]
no improvement after the changes has VAM-json.php
here is a [link](https://f-airmap.tk/vam/VAM-json.php) to the data

**Comment by Ysurac** [comment]
Fixed in latest commit

**Comment by bilkaPek** [comment]
yes it works perfectly :+1: 
thank you very much
