### ISSUE TITLE
Showing Planes that have been blocked on Flightradar24 etc

### ISSUE THREAD

**Issue by Bigben83** [Ysurac/FlightAirMap#227]
if I pickup a plane with ADS-B signal will it show on FlightAirMap even if its been blocked on Flightradar24 or Flightaware.

**Comment by Ysurac** [comment]
Yes it will show. No planes using ADS-B are blocked. No options are even available to block some plane for ADS-B: there is no public list of plane that should/want to be blocked, or flag in ADS-B signal,...

Only planes from glidernet APRS source with stealth flag are not displayed.

**Comment by Bigben83** [comment]
Interesting, Thanks for that there was a plane i saw that I hadn't picked up and it had flown overhead, looked like a military plane.

**Comment by Ysurac** [comment]
Some military plane don't send any ADS-B signals or ADS-B without coordinates.
