### ISSUE TITLE
Map Box

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#23]
Back to load ...

1. Create an account on MapBox, create the map and put the ID in setting, so it looks something seems to be something wrong, or not shoots.

![captura](https://cloud.githubusercontent.com/assets/4571086/7627989/fcb726a4-fa1d-11e4-8199-1553f5dc37c3.JPG)

![captura1](https://cloud.githubusercontent.com/assets/4571086/7627991/02714688-fa1e-11e4-9337-9a4f9cbcc74d.JPG)

![captura3](https://cloud.githubusercontent.com/assets/4571086/7627992/071953ec-fa1e-11e4-9589-1d49f1fd068e.JPG)

On the other hand impressive your work, I congratulate you.

2.- could somehow create a cron so that it can run via cron job and would act as the cron-db.php?

thanks

**Comment by Ysurac** [comment]
It was set to v3 in *header.php*,  you are in v4, maybe it work now...
No idea if I can make it work as real cron job... I will try to see what I can do...

**Comment by tonkepen100** [comment]
@Ysurac Thanks and thanks, No. mapbox no run good in this moment but again thank you very much for the patience you have with me

**Comment by Ysurac** [comment]
Fixed in commit e08a1f3c684999e8270d8c69c1ea5bc998045dcc
Need a token now, new setting : *$globalMapboxToken*

**Comment by tonkepen100** [comment]
Ohhhhhhhhhhhhhhhhhhhhhhhhh , oHHHHhhhhhhhhhhhhhhhhhh the bestttttttttttttttttttt , the bestttttttttttttttttttttttttt thanksssssssssssssssssss Ysurac thankssssssssssssss

**Comment by tonkepen100** [comment]
![captura](https://cloud.githubusercontent.com/assets/4571086/7639672/f92533c2-fa7d-11e4-893e-d49cd8167e7b.JPG)

**Comment by tonkepen100** [comment]
Oleeeeeeeeeeeeeeeeeeeeeeee
