### ISSUE TITLE
Explore > Upcoming Flights

### ISSUE THREAD

**Issue by gugaua** [Ysurac/FlightAirMap#230]
Explore > Upcoming Flights will show

Not Found
The requested URL /upcoming was not found on this server.

**Comment by Ysurac** [comment]
And an other pages are working ?
What is the web server used ? Apache ? Nginx ?

**Comment by gugaua** [comment]
Yes
Apache

**Comment by Ysurac** [comment]
You try the latest commit. I modified the **.htaccess**

**Comment by gugaua** [comment]
Now it works!
