### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ChrisAHD** [Ysurac/FlightAirMap#231]
I am trying to install this module on my website and i am getting trouble, can you assist?

**Comment by Ysurac** [comment]
It's not a module of anything.
What problem/error do you have ?

**Comment by ChrisAHD** [comment]
The problem is when I install it, the pages not coming up correctly. Cant seem to figure out why.


Regards Chris


________________________________

**Comment by Ysurac** [comment]
I really need more info... What pages ? when ? Do you successfully run **install/index.php** ?
Are you using Apache ? Nginx ? version ? PHP version ?

**Comment by me2tkt** [comment]
I think had a similar issue. 
It turned out that my GlobalURL in settings.php was not correct.
Check issue '
