### ISSUE TITLE
Not connecting to RadarCape deltadb.txt

### ISSUE THREAD

**Issue by me2tkt** [Ysurac/FlightAirMap#232]
First let me congratulate to a great job. I already had Barrie Spotter downloaded but was not able to convert it to my requirements, particularly for connecting to my own ADSB receiver.

I am having a problem with connecting via daemon-spotter.php.
(I downloaded the package last week)

I think there is a typeing error in line 337 : it should be "deltadb.txt" not "deltadbtxt"
Without the dot daemon.spotter just ends after printing SCANMODE

With the dot I get a connection but them for each line 356 - 352 an undefined offset error for each aircraft. No data is being transfered to the database or showing on the map.

I think the dot might also be missing in the settings.php file as well.

Below is an excerpt of the deltadb.txt output from my receiver :+1: 1478360234,3D119B,,,,,,,,0000
1478360226,3C5EF7,GWI9M,39025,480,70,,,0,2026
1478360231,405B66,EZY57NB,39000,475,60,,,0,2056
1478360218,3C55A5,DLH3FE,25925,355,274,50.5503,7.46766,-2048,1000
1478360220,3423C4,,37000,414,216,51.4482,5.18703,-64,3522
1478360233,06A1A5,QTR8285,40000,421,288,51.0714,8.43216,0,3220
1478360221,3D349D,,1400,,,,,,0000
1478360235,4CA84C,RYR98EA,37000,489,103,50.6206,5.81399,-64,4711
1478360235,3C650D,DLH424,36000,421,291,50.4451,7.4269,0,4136
1478360201,478387,SAS67G,33975,413,219,51.4547,5.43794,0,0763
1478360235,780A98,CPA239,38000,448,239,54.7133,9.97858,64,3511
1478360178,3D1B84,,1400,,,,,,0000
1478360235,406B49,,39975,461,233,54.7534,8.66455,64,0743
1478360235,406F26,IBK2557,35975,408,291,50.4931,6.86512,0,4725
1478360215,3FEEEA,DMFFK,1200,,,,,,7000
1478360235,484B31,KLM1357,27475,,,,,,1000
1478360234,06A1A2,QTR8245,22000,308,285,50.6307,6.79415,64,3212
1478360235,461FA1,FIN2HW,34975,481,41,52.4719,5.50835,0,2373
1478360235,4841D7,TRA22Q,37475,404,293,51.792,8.14568,-832,1000
1478360235,471EA7,WZZ2XS,30350,511,94,51.4782,7.76258,1152,2561
1478360235,471F6B,WZZ131,34950,495,100,50.4747,7.01658,0,2231
1478360221,48488D,PHJMP,7800,,,,,,6405
1478360235,4BA9D3,THY81D,36000,429,292,51.7238,7.90689,-64,3271
1478360235,406542,EZY85BA,35000,494,105,52.2572,6.54738,0,3401
1478360235,471F57,WZZ1120,37025,489,81,52.797,6.86966,-64,3467
1478360235,760917,PIA791,38000,443,258,52.7132,8.16063,64,2205
1478360229,406A9C,BAW35,36975,542,101,50.4006,7.55115,64,4742
1478360235,4CA65A,RYR4533,37000,388,245,51.0065,7.62703,64,3104
1478360235,504DD9,MLD834,38975,510,95,52.0529,7.02507,-64,2024
1478360235,478533,NAX2BL,35975,421,230,53.6744,8.44927,0,0740
1478360235,3D1BB9,DEITD,2300,,,,,,7000
1478360235,398564,AFR553U,38000,,,,,,0737
1478360235,4CA2FE,RYR89VN,37000,482,91,53.1649,7.42143,64,2054
1478360235,3D1B9B,DEIRZ,3200,,,,,,7000
1478360235,3C6DD4,GWI89T,39000,487,85,52.6156,7.75423,-64,0714
1478360221,394A65,BGA231F,26975,332,189,51.7329,9.16141,0,1340
1478360235,47873E,NAX3CX,35975,422,218,53.2842,7.38752,0,0757
1478360235,345206,VLG1GY,39000,422,222,53.0091,7.69969,-64,0755
1478360235,3FF4FF,DMTBZ,1825,,,,,,7000
1478360235,4840DF,KLM898,22300,378,246,53.0535,6.66954,-1472,3526
1478360227,3C0A46,AUA373,10900,276,282,52.4222,5.88687,-2240,1000
1478360189,471F4E,WZZ1B,37000,499,97,51.9478,9.39017,128,3406
1478360196,406531,BAW704W,35025,502,103,51.6109,9.4334,0,3425
1478360235,8A03A5,GIA089,31000,537,103,51.7351,8.59116,0,3157
1478360235,4BA9EA,THY7,36000,439,287,52.5539,5.01338,0,3275
1478360235,44049F,OEGES,41000,,,,,,2032
1478360234,3D0948,DEBTO,2400,,,,,,4423
1478360234,71BF84,KAL907,36000,437,235,52.614,5.16312,0,3525
1478360235,3D12E3,DEFKD,1800,,,,,,0000
1478360235,3D2BAA,DEOUC,2300,,,,,,7000

**Comment by Ysurac** [comment]
There is no missing dot. The format is deltadbtxt.
What error do you have when you don't change anything ?

**Comment by me2tkt** [comment]
The daemon-spotter output stops after the message SCAN NOW

**Comment by me2tkt** [comment]
Ok. I reset the formats in the settings.php line 136 and daemon-spotter line line 337 to "deltadbtxt".
Restarted web page and daemon-spotter.
Daemon spotter connectss but still gives the undefined offset error

**Comment by Ysurac** [comment]
what is exactly the error ?

**Comment by Ysurac** [comment]
I made some change for deltadb in latest commit... maybe this will work...

**Comment by me2tkt** [comment]
I have started the changed daemon-spotter.php.
The offset error is gone.

Console output is : 
Connecting ...
Connect to all...
Connection in progres to 192.168.xxx.yyy:30003 (deltadbtxt)....
Connected!
SCAN MODE

Sleeping...
Sleeping...

But I am not seeing any aircraft or updates in the database ;-(

**Comment by Ysurac** [comment]
Are you sure that you are in deltadb.txt format ?
Port 30003 is used by sbs format and you don't use a URL.

**Comment by me2tkt** [comment]
I see your point - that is were I am probably wrong 
Radarcape has a port 30003 output - that is not in deltaadb format but I think AVR
The deltadb.txt is supplied by the webserver of the radarcape.

So how do I tell the programme to connect.
As SBS with port 30003, or directly to the Radarcape without any port ?

My section of the settings file
$globalSBS1 = FALSE; //set to FALSE to not use SBS1 as data import
$globalSourcesTimeOut = '';
$globalSourcesupdate = '10'; //Put data in DB after xx seconds/flight

//DATA SOURCES
$globalSources = array(array('host' => '192.168.178.49','port' => '30003','name' => 'Radarcape','format' => 'deltadbtxt','sourcestats' => TRUE));

This is what comes from port 30003 of the Radarcape : 
MSG,5,111,11111,400CD7,111111,2016/11/05,19:00:02.175,2016/11/05,19:00:02.175,,39000,,,,,,,0,,0,0
MSG,8,111,11111,424940,111111,2016/11/05,19:00:02.180,2016/11/05,19:00:02.180,,,,,,,,,,,,0
MSG,4,111,11111,780A3B,111111,2016/11/05,19:00:02.187,2016/11/05,19:00:02.187,,,526,78,,,0,,,,,
MSG,5,111,11111,3C56EE,111111,2016/11/05,19:00:02.196,2016/11/05,19:00:02.196,,13200,,,,,,,0,,0,0
MSG,8,111,11111,780463,111111,2016/11/05,19:00:02.205,2016/11/05,19:00:02.205,,,,,,,,,,,,0
MSG,5,111,11111,4CA8E7,111111,2016/11/05,19:00:02.207,2016/11/05,19:00:02.207,,34600,,,,,,,0,,

**Comment by Ysurac** [comment]
If you use port 30003, format is **sbs** (or **auto**).
If you want to use deltadb.txt, you need to provide the url of deltadb.txt file and **deltadbtxt** format (or **auto**).
For both **$globalSBS1** should be set to **TRUE**.
**$globalSourcesTimeOut** should be at the default setting of **15** (this was one was a bug, fixed in lastest commit).

**Comment by me2tkt** [comment]
Thank you Ysurac.
SBS with auto is working :-)))
I will check the other settings and report any issues.

So there was no issue with the daemon-spotter routine.
My wrong interpretation of the descrption

Thanks again for a great website and database development.
Have a good weekend

**Comment by Ysurac** [comment]
No problem.
Good week end.
