### ISSUE TITLE
Linked pages losing Global URL

### ISSUE THREAD

**Issue by me2tkt** [Ysurac/FlightAirMap#233]
I am sure this is a problem with my setup.
The first web pages are all shown correctly.
But if I go to following pages e.g. from a statistic table then the  URL seems to get doubled and the browser cant find the required files anymore
From the FireFox debugger:
GET 
http://192.168.178.25/WebSite/FlightAirMap/**FlightAirMap**/css/style.css [HTTP/1.1 404 Not Found 155ms]

or

GET 
http://192.168.178.25/WebSite/FlightAirMap/FlightAirMap/airline/BAW/FlightAirMap/images/logo2.png [HTTP/1.1 404 Not Found 27ms]
GET 
http://192.168.178.25/WebSite/FlightAirMap/FlightAirMap/airline/BAW/FlightAirMap/images/airlines/BAW.png

It seems that the URL is being doubled

In settings.php I have entered the Global URL
// GLOBAL URL
$globalURL = '../FlightAirMap';
Without the "../" no page will show correctly.
 
My Folder structure is
C:\xampp\htdocs\WebSite\FlightAirMap

I am using an Apache WebServer.
I tried to add the mod_rewrite option to Apache http_conf but then everything died

**Comment by Ysurac** [comment]
Try with **$globalURL = 'WebSite/FlightAirMap';**
It's the directory from the root of the website. So if is the index is at http://192.168.178.25/WebSite/FlightAirMap/index.php, $globalURL is WebSite/FlightAirMap

**Comment by me2tkt** [comment]
Ok, I will try that when I am back at home.
I am always struggling with the HTML/Apache file  references.It always ends in tral and error.
Everything else seems to be working fine.
Thank you


 
      Von: Ycarus <notifications@github.com>
 An: Ysurac/FlightAirMap <FlightAirMap@noreply.github.com> 
CC: me2tkt <me2tkt@yahoo.com>; Author <author@noreply.github.com>
 Gesendet: 15:32 Sonntag, 6.November 2016
 Betreff: Re: [Ysurac/FlightAirMap] Linked pages losing Global URL (#233)
   
Try with $globalURL = 'WebSite/FlightAirMap';
It's the directory from the root of the website. So if is the index is at http://192.168.178.25/WebSite/FlightAirMap/index.php, $globalURL is WebSite/FlightAirMap—

**Comment by me2tkt** [comment]
Got hone today and changed the URL as per your recommendation.
Everything is working.
I knew it was my mistake  just couldnt figure out the right address.
Unfortunately the last Windows update crashed my PC, so didnt get much data to analyse yet.

Thank you again.
