### ISSUE TITLE
Multiple image id's for aircraft in spotter-image.db

### ISSUE THREAD

**Issue by me2tkt** [Ysurac/FlightAirMap#236]
I notice that for the same aircraft multiple image_id  (up to 29 !) are being created in the spotter_image database.

The App only seems to use the first image_id found.
Can I delete/prevent the duplicates  ?

**Comment by Ysurac** [comment]
Should be fixed in latest commit.

**Comment by me2tkt** [comment]
![spotter_image-multiples](https://cloud.githubusercontent.com/assets/23280102/20246351/53098022-a9b5-11e6-9e02-26314b9e2717.jpg)

This is a screenshot from my spotter_image database.
The aircraft has in total 23 entries.

This is what I meant. 
Maybe the field "REGISTATION" should be declared as *unique* ?

**Comment by Ysurac** [comment]
True.
This is fixed in latest commit, and I will make it unique in next schema update.
