### ISSUE TITLE
Problem with country database

### ISSUE THREAD

**Issue by me2tkt** [Ysurac/FlightAirMap#237]
When I look into the country database it contains only 23 countries?
I have tried to re-populate it but that did not change anything.

Should I delete it and reinstall ?

Probably as a consequence - In my statistics I see that all flight over a country are only shown as in Algeria e.g. for Air Lingus.
As I cant receive any flights from Algeria something is confusing the Statistics

I have the XAMP package which uses Maria DB Version 10.1.9.
Maria DB is suposed to be compatible to MySQL and can show the GIS data (via phpMyAdmin) of the 23 countries loaded.

**Comment by Ysurac** [comment]
You should have 246 countries. Did you try to add manually the file **db/countries.sql.gz** (after gunzip it) ?
For algeria, I have no idea...

**Comment by me2tkt** [comment]
I get a error from the server :.

    Unkown Keyword. (near "ON" at position 25)

**Comment by Ysurac** [comment]
Strange.
I'm also using MariaDB without errors. It's even a dump from a MariaDB database.
I tested right now to import **countries.sql** on a MariaDB 10.1.14 without problems.

**Comment by me2tkt** [comment]
Tried to import on a different computer with MySQL Workbench and a newer phpMyAdmin (7) but all fail at the same point.

**Comment by me2tkt** [comment]
Seems to be related to the length of the individual lines in the SQL file.

**Comment by Ysurac** [comment]
When I was speaking manually, it was on command line with mysql executable.
I've made a new countries.sql with each country on is line, at least we should see where is the error...

**Comment by me2tkt** [comment]
Tried to import the new sql file via phpMyAdmin. 
But it failed again at Canada.
I then removed the line for Canada and it imported upto Russia.
Without Canada and Russia everything imports.
Being the two largest countries I wonder if this has something to do with the size of the ogc_geom field for these two countries.
So it s something on my side - not sure how to set this up correctly.

**Comment by Ysurac** [comment]
I don't use phpMyAdmin, so no idea. If the problem is from MySQL/MariaDB side it should tell an error better than the *Unknown keyword*.

**Comment by me2tkt** [comment]
I will try to import it via the console. Always a problem with Windows :-(

But I had the same problem when using MySQL Workbench instead of phpMyAdmin.

**Comment by Ysurac** [comment]
I never tried workbench. I don't like GUI :-)

**Comment by Ysurac** [comment]
You could try to set **max_allowed_packet** to an higher value for MySQL/MariaDB in my.cnf. It's set to 100M in my config.

**Comment by me2tkt** [comment]
Ok - increased max_allowed_packet from 1M to 8M - and it worked.
All countries are imported. ;-) ;-)

Thank you !!

Without Canada and Russia the size of the sql file deacreses a lot. About 1.8 -2M per country
MySQL Workbench dosnt like Maria DB. Always complaining about non compatible database but still does most things write. Only used when phpMyAdmin is totally lost.

**Comment by Ysurac** [comment]
Thanks, I will add a check for that value in the install script.
I will check why canada and russia are so big.
