### ISSUE TITLE
Deleting unplausible data

### ISSUE THREAD

**Issue by me2tkt** [Ysurac/FlightAirMap#238]
Would it be possible to provide filter or setting for unplausible data ?

1) Positions further than 400km from the receiver

2) Airspeeds over 2000km/h

3) Altitude over 30000m

**Comment by Ysurac** [comment]
It's already the case. Only altitude is not checked, but never add a problem with that.
For distance from receiver you can use **$globalDistanceIgnore**.

**Comment by me2tkt** [comment]
Thank you - didnt see that. Now set it now to 400km 
Always get strange distance peaks from all programs.

Just saw one aircraft speed calculated as 4300km/h in the console window.

Altitude was just an idea.
Might be interesting to set as range or flightlevel for people only interested in specific aircraft.
For me no problem.

**Comment by Ysurac** [comment]
If it's a calculated speed it's strange. It's a flight that send also bad coordinates. Check with coordinates shouldn't add it to DB.
