### ISSUE TITLE
7700.7600.7500

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#24]
Again heavy ..

It is not exactamnte to this section but I think it could be done in a section for reporting of codes 7700, 7600 and even 7500.

I leave photos of the idea ...

![captura2](https://cloud.githubusercontent.com/assets/4571086/7640067/3ec51e3a-fa81-11e4-9c87-c4aa0c8b6a6a.JPG)

![captura](https://cloud.githubusercontent.com/assets/4571086/7640072/4d343ed8-fa81-11e4-8af6-7b67420f11a0.JPG)

So anyone SQ to occur during data collection is reflected.

**Comment by Ysurac** [comment]
It's already done. But only first time flight is saw by hour. This will be fixed soon.

**Comment by tonkepen100** [comment]
Gooddddddddd

**Comment by Ysurac** [comment]
Fixed in commit 96418f3
