### ISSUE TITLE
daemon-spotter and PHP 7.0.13

### ISSUE THREAD

**Issue by me2tkt** [Ysurac/FlightAirMap#240]
I installed the recent update of FlightAirMap on a different PC.
Before that I updated the XAMPP package (with Apache, MySQL and PHP)
This update includes the current version of PHP aka 7.0.13 .
However when I try to run daemon-spotter I get the following error

Connecting...
Connect to all...

Fatal error Uncaught Error 
Call to undefined function socket_create() in C:\xampp_NEW\htdocs\Website\FlightAirMap\scripts\daemon-spotter.php:87
Stack trace:
C:\xampp_NEW\htdocs\Website\FlightAirMap\scripts\daemon-spotter.php(206): create_socket('192.168.178.49', '30003', NULL, NULL)
C:\xampp_NEW\htdocs\Website\FlightAirMap\scripts\daemon-spotter.php(271): connect_all(Array)
{main} thrown in C:\xampp_NEW\htdocs\Website\FlightAirMap\scripts\daemon-spotter.php on line 87

When using the older version of PHP 7.0.1 on the same PC this problem does not occur.
The other scripts runs as expected with PHP 7.0.13

**Comment by Ysurac** [comment]
sockets need to be enabled when you compile PHP.

**Comment by me2tkt** [comment]
I am using a pre-compiled  PHP package for Windows downloaded today from 
the XAMPP site.
Then it seems that the XAMPP package has an error.

As 7.0.13 is a security update I thought that maybe some PHP internals 
have changed so that it is no longer compatible

**Comment by Ysurac** [comment]
It's compatible, I use PHP 7.0.13 under Linux Gentoo.
Must be an error in XAMPP package.

**Comment by Ysurac** [comment]
(sockets is not enabled, they failed to compile it)

**Comment by me2tkt** [comment]
I just found out that in some XAMPP installations the DLL required for PHP sockets is disabled in the php.ini file
To use sockets you have to uncomment the line, e.g.
extension=php_sockets.dll
