### ISSUE TITLE
Database table creation error

### ISSUE THREAD

**Issue by szarka77** [Ysurac/FlightAirMap#246]
Decided to give FlightAirMap another try.

On new database creation I get the error:

 Write configuration....SUCCESS
    Create database....SUCCESS
    Create and import tables....SUCCESS
    Populate aircraft_modes table with externals data for ADS-B....SUCCESS

    Error : error : SQLSTATE[HY000]: General error: 1 no such table: Aircraft

Proceeding after that error results in no aircraft photos being displayed and **N/A N/A ()** in the aircraft detail window.

Thoughts?

**Comment by szarka77** [comment]
Thanks, but there seems to still be a upper case/lower case error in one of the files.

Now I get:
`Error : error : SQLSTATE[HY000]: General error: 1 no such table: aircraft`

Still no aircraft photos, etc.

**Comment by Ysurac** [comment]
Check that aircraft table exist. Strange...
