### ISSUE TITLE
Another db creation error

### ISSUE THREAD

**Issue by szarka77** [Ysurac/FlightAirMap#247]
Re: issue #246 

`SQLSTATE[HY000]: General error: 1 no such table: aircraftModes`

I see the actual table name is "aircraft_modes"

**Comment by szarka77** [comment]
![image](https://cloud.githubusercontent.com/assets/18219000/21075347/7a0761ca-bedd-11e6-8b55-2723eda109e5.png)

**Comment by Ysurac** [comment]
I never call an aircraftModes table in any file. So no idea for this...

**Comment by Ysurac** [comment]
You use Mysql ? MariaDB ? PostgreSQL ? version ?

**Comment by szarka77** [comment]
Mariadb 10.1.19 on Fedora 24

**Comment by szarka77** [comment]
I will try renaming the table.

**Comment by Ysurac** [comment]
this will not work.
You use latest commit ?
I really don't have anywhere a call to an aircraftModes table

**Comment by szarka77** [comment]
Yes, I completely reinstalled 1 hour ago and dropped old database.

**Comment by szarka77** [comment]
still this:
![image](https://cloud.githubusercontent.com/assets/18219000/21075390/0a32de54-bedf-11e6-87ee-26213dee5da3.png)

**Comment by Ysurac** [comment]
aircraft_modes table is empty ?

**Comment by szarka77** [comment]
No:
![image](https://cloud.githubusercontent.com/assets/18219000/21075407/7251cf36-bedf-11e6-8217-72023463c6c2.png)

**Comment by Ysurac** [comment]
What is the result of:
    SELECT DISTINCT Source FROM aircraft_modes;

**Comment by szarka77** [comment]
![image](https://cloud.githubusercontent.com/assets/18219000/21075459/cea47210-bee0-11e6-9d0f-eddabbc20793.png)

**Comment by Ysurac** [comment]
OK. Only data for glidernet/APRS.
You can run **install/populate_all.php**. This should try to populate all tables again.

**Comment by szarka77** [comment]
I will try that and get back to you.

Thanks.

**Comment by szarka77** [comment]
Ran install/populate_all.php  no change in output from SELECT DISTINCT Source FROM aircraft_modes;

Only glidernet/APRS   8-(

**Comment by szarka77** [comment]
`[root@cheesewhiz install]# ./populate_all.php

Populate all tables...
Routes : Download...Gunzip...Add to DB... - Delete previous routes from DB - - Add routes to DB -Done
Translation : Download...Unzip...Add to DB...Done
Translation from FlightAirMap website : Download...Gunzip...Add to DB...Done
NOTAM from FlightAirMap website : Download...Gunzip...Add to DB...ERROR : Q)WIARADIUSOF1NMANDAMAXHGTOF375FTAMSL.325FTAGL
ERROR : Q)W(BTNJAND
ERROR : Q)A(BTNJAND
ERROR : Q)RADIATINGONTEST.DONOTUSE.CREATED:12Nov201608:25:00SOURCE:EUECYIYN
Done
Modes : Download...Unzip...Add to DB...error : SQLSTATE[HY000]: General error: 1 no such table: aircraftModes Flarmnet: Download...Add to DB...Done
Modes OGN: Download...Add to DB...Done
`

**Comment by Ysurac** [comment]
And no errors ?
You have **$globalDebug** set to **TRUE** in *require/settings.php* ?

**Comment by Ysurac** [comment]
ok, so the same error...

**Comment by Ysurac** [comment]
I found the error: the file is no more available at this source. I try to find another source...

**Comment by Ysurac** [comment]
Fixed in latest commit, I use the latest version available. I will try to find an updated source next week.

**Comment by szarka77** [comment]
It also appears that my install/tmp/airlines.sql has a bunch of garbage binary data in it(??)
I am assuming it should be all text?

**Comment by Ysurac** [comment]
ModeS is now really fixed in latest commit with latest available data.
If you speak about airspace.sql, it's geospatial binary data encoded in hexadecimal.

**Comment by szarka77** [comment]
OK.  Planebase.biz is now subscription only.  if you want to use it you must have a sponsor and I have neither.  8-(

**Comment by szarka77** [comment]
With new commit site is working properly....whew!
