### ISSUE TITLE
Turkish Airlines

### ISSUE THREAD

**Issue by szarka77** [Ysurac/FlightAirMap#248]
International Turkish airlines flights are identified as Anadolujet.

![image](https://cloud.githubusercontent.com/assets/18219000/21076580/2cd1b476-befd-11e6-97eb-5675217f1677.png)

**Comment by Ysurac** [comment]
True. It's because airline ICAO is the same: https://en.wikipedia.org/wiki/AnadoluJet
It's fixed in latest commit.
