### ISSUE TITLE
Polar Plot 9.6 thousand mile range

### ISSUE THREAD

**Issue by szarka77** [Ysurac/FlightAirMap#249]
How can I fix this:

![image](https://cloud.githubusercontent.com/assets/18219000/21078480/24dc1418-bf3f-11e6-8ae4-95a9e98d4f2a.png)

![image](https://cloud.githubusercontent.com/assets/18219000/21078483/44ab024a-bf3f-11e6-83d4-f76466e423d9.png)

**Comment by Ysurac** [comment]
Sometimes this can happen when I receive wrong data from a flight.
You can filter from your source (Dump1090 can ignore flights too far away) or use the setting **$globalDistanceIgnore** in **require/settings.php**.

**Comment by szarka77** [comment]
I'm not certain that will fix it.  This is what I have now:
`$globalDistanceIgnore = array('latitude' => '44.809','longitude' => '-68.9143','distance' => '475');`

**Comment by Ysurac** [comment]
This is reseted every day.

**Comment by szarka77** [comment]
Hmmmmm...my plot still showing 9.6K miles.

[http://www.kpw3.com/FlightAirMap/statistics](url)

**Comment by szarka77** [comment]
Perhaps mine is not being reset at the end of the day?
![image](https://cloud.githubusercontent.com/assets/18219000/21082710/2e6e1e16-bfaf-11e6-9950-d58b89465f32.png)

**Comment by Ysurac** [comment]
When I check **Flights Distance for Hermon**, there is a problem.
Location name must be the same as source_name, so "Hermon" and not "Hermon Receiver". I need to change that...

**Comment by Ysurac** [comment]
It's not the problem, I already use **source** field in location table in fact. So this should work.

**Comment by Ysurac** [comment]
Did you set location without restarting the daemon ?

**Comment by szarka77** [comment]
Maybe.  Do you mean daemon-spotter.php ?

**Comment by Ysurac** [comment]
yes

**Comment by szarka77** [comment]
I will restart it now.

**Comment by szarka77** [comment]
Done.

**Comment by Ysurac** [comment]
Changes will only be really visible tomorrow, or you can delete data in *stats_source* table.

**Comment by szarka77** [comment]
OK deleted all stats_source table data but not tables themselves..  I also changed "Hermon Receiver" to "Hermon."

Thanks,

**Comment by Ysurac** [comment]
In fact you should stop **daemon-spotter.php**, delete content of **stats_source** table, and run again -**daemon-spotter.php**, else previous data are keep in memory. Sorry.

**Comment by szarka77** [comment]
Ok, I've done that.  So far, tables are not re-populating.

**Comment by Ysurac** [comment]
There is data now, and it's better

**Comment by szarka77** [comment]
Yes I see.  Now working properly.  Merci.
