### ISSUE TITLE
Most common airport by route - link not correect

### ISSUE THREAD

**Issue by me2tkt** [Ysurac/FlightAirMap#251]
If I click on the "Route Profile" in this table then the  info shown on the next page / map is not correct.
Either the airports are wrong or everything goes to N/A.

See screenshot for 
![routes](https://cloud.githubusercontent.com/assets/23280102/21499641/f7e9a99c-cc37-11e6-8f90-0f8a07f4ce6a.jpg)

Link shows EDDT to EDDK but map shows EDDM to LYBE.

I wish you all the best for 2017 !!

**Comment by Ysurac** [comment]
I'm not able to reproduce this bug on any of my install for now.

**Comment by me2tkt** [comment]
I updated to the latest commit and issue is gone.
So for me closed
