### ISSUE TITLE
Search Registration error

### ISSUE THREAD

**Issue by me2tkt** [Ysurac/FlightAirMap#254]
A glider D-0643 appears as belonging to GermanWings in the results table, together with a GWI Flightnumber.
Could this data be 'left-over' from a previous search ?
![wrong airline](https://cloud.githubusercontent.com/assets/23280102/21589010/4cfb1506-d0ed-11e6-88e7-64b38dd89f3d.png)

**Comment by Ysurac** [comment]
No, maybe a wrong/old ModeS info or a flight that use the wrong ModeS hex code.

**Comment by me2tkt** [comment]
Ok, from which databases does the search get its data ?
I could not find a connection between Airline, Flightnumber and Regstration.

**Comment by Ysurac** [comment]
modeS is checked in aircraft_modes that give me registration and icao type code and Airline come from callsign. This checks are done when data are imported in DB.
Search check data in spotter_output table.

**Comment by me2tkt** [comment]
Checked spotter_output.
Showing ground speed of over 450 km at a height of 150m !
Strange for a glider. But one location is close to a military air base .......
