### ISSUE TITLE
Stat heading    strange

### ISSUE THREAD

**Issue by me2tkt** [Ysurac/FlightAirMap#255]
How can there be > 200 owners and > 300 airlines when only 73 aircraft were seen ?
![stats- heading](https://cloud.githubusercontent.com/assets/23280102/21589034/9b07445e-d0ed-11e6-8d44-fe5268e9be39.png)

Do the stats reset on 1.1. ?

**Comment by Ysurac** [comment]
Stats are reset on 01/01 if setting is set.
Aircrafts is aircraft type. Like Airbus A380, Boeing B777,...

**Comment by me2tkt** [comment]
Ah, then I understand.
I saw aircraft as individual registrations.
Maybe to make it clearer you could change " Aircrafts" to "Aircraft Types" ?

**Comment by me2tkt** [comment]
My settings.php has $globalDeleteLastYearStats = FALSE;
Will this keep or delete the stats ?

**Comment by Ysurac** [comment]
This will keep stats. 
When set to true I don't delete all stats, I only reset count of aircraft types, airlines, registration, callsign, owner, pilots and departure/arrival airport. Previous count are archived in DB.

**Comment by me2tkt** [comment]
Thank you.
