### ISSUE TITLE
Database recovery

### ISSUE THREAD

**Issue by me2tkt** [Ysurac/FlightAirMap#258]
Due to a power loss my SQL database has become corrupted.
So the data from December is gone.
The flightmap idb and frm and the ibdata files are still available

- any ideas on how to recover/repair the innodb files ?
   The solutions described in the internet are beyond my understanding

- any suggestions for a backup procedure ?

**Comment by Ysurac** [comment]
To repair you can try:

    mysqlcheck -u root -p -A --auto-repair

To make backup you can use **mysqldump**. A backup of DB binary files can also be done (*/var/lib/mysql*).

**Comment by me2tkt** [comment]
Thanks for the info - unfortunately it didnt work.
