### ISSUE TITLE
PHP Warnigs and Notices

### ISSUE THREAD

**Issue by me2tkt** [Ysurac/FlightAirMap#260]
Sometimes the following PHP warnings occur 

----------
PHP Warning:  Illegal string offset 'original' in C:\xampp\htdocs\Website\FlightAirMap\require\class.Image.php on line 466
PHP Warning:  Illegal string offset 'original' in C:\xampp\htdocs\Website\FlightAirMap\require\class.Image.php on line 467
PHP Warning:  get_headers(): This function may only be used against URLs in C:\xampp\htdocs\Website\FlightAirMap\require\class.Common.php on line 222

PHP Warning:  get_headers(): Filename cannot be empty in C:\xampp\htdocs\Website\FlightAirMap\require\class.Common.php on line 222

PHP Notice:  Undefined index: copyright in C:\xampp\htdocs\Website\FlightAirMap\require\class.Image.php on line 475

PHP Notice:  Trying to get property of non-object in C:\xampp\htdocs\Website\FlightAirMap\require\class.Scheduler.php on line 209

------
The first two refer to images could be do to my use of local links.

Anything important ?

**Comment by Ysurac** [comment]
There is a wrong configuration with your custom source of pics (**$globalAircraftImageCustomSources**). There is no "original" field.

**Comment by me2tkt** [comment]
Ok - found them.
Thank you.
