### ISSUE TITLE
Airline Alliances

### ISSUE THREAD

**Issue by me2tkt** [Ysurac/FlightAirMap#264]
I always wanted to see aircraft based on the airline alliances.
Would it be possible/interesting to add a page and/or filter in which only the flights, aircraft, routes, stats of a selected airline alliance are shown ?

e.g. SkyTeam, Star Aliance, OnWorld, etc..

**Comment by Ysurac** [comment]
Possible. I will have to modifies airlines table and add that based on wikipedia data.

**Comment by Ysurac** [comment]
Filter on alliance is available to display flights on 2D/3D map.
Need to add stats by alliance.

**Comment by Ysurac** [comment]
Statistics by alliance done in latest commit
Need to add a filter for airlines page and maybe current, latest,... activity pages.

**Comment by Ysurac** [comment]
Done in airlines pages
