### ISSUE TITLE
Get Data out of Simconnect

### ISSUE THREAD

**Issue by gugaua** [Ysurac/FlightAirMap#265]
Hello Ysurac,

our community is using JoinFS
it a multiplayer system with allmost no lag.

my question is, if I provide a file with a script programmed by us with live data, what data fields would you need to make ot work? For example speed heading position...

Best Regards
gugaua

**Comment by Ysurac** [comment]
Hi,
I must have an unique ID, altitude, latitude and longitude. It's better if I have also heading, speed, aircraft ICAO type. I can also use a pilot id, pilot name, squawk, departure airport icao (or iata), arrival airport icao (or iata), aircraft registration, vertical rate.
This file can be in json, csv, tsv,... available locally, by TCP or UDP.

If it's possible, and it's far better, I can connect directly to the source over TCP or UDP. The source is directly JoinFS or Simconnect ?

**Comment by gugaua** [comment]
The source is simconnect, I´m not sure if there is a direct way to connect, maybe its necessary to create an API

**Comment by Ysurac** [comment]
For SimConnect, something like that can be used: https://github.com/EulPi/fsx
But I don't have Flight Simulator, and I don't even have windows.
Else you can wait a little, JoinFS should have an export file soon: http://pmem.uk/joinfs/forum/viewtopic.php?f=3&t=125

**Comment by gugaua** [comment]
Hello @Ysurac 

I wrote in their forum, I wasn´t aware that they are planing to do that.
Let´s see if they are going to implement this feature.

**Comment by Ysurac** [comment]
Seems to be implemented, a live link use FlightAirMap on joinFS site.
