### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by me2tkt** [Ysurac/FlightAirMap#266]
I have downloaded the latest commit.
When running install I get a lot of database errors 

Error : error (import ../db/acars_archive.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/acars_label.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/acars_live.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/accidents.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/aircraft.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/aircraft_modes.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/aircraft_owner.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/aircraft_registration.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/airlines.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/airport.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/atc.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/config.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/faamfr.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/metar.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/notam.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/routes.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/source_location.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/spotter_archive.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/spotter_archive_output.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/spotter_image.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/spotter_live.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/spotter_output.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/squawk.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/stats.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/stats_aircraft.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/stats_airline.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/stats_airport.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/stats_callsign.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/stats_country.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/stats_flight.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/stats_owner.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/stats_pilot.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/stats_registration.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/stats_source.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/taf.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/tle.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/translation.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected error (import ../db/waypoints.sql) : SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected

**Comment by Ysurac** [comment]
It can't use the database. Check the name of the DB in **require/settings.php**

**Comment by me2tkt** [comment]
Ok - my error.
Seems I copied the wrong settings file to the new install.

Sorry :-(

**Comment by Ysurac** [comment]
No problems. I added a better log when there is an error like this.
