### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by me2tkt** [Ysurac/FlightAirMap#268]
Clicking on the "See full statistics" button  for the "Fatalities by Years" and "Fatalities last 12 Months" results in a 404 page. I assume you are still working on that.

When looking at the statistics for an airline the button with the number of military flight is still shown - this button could be deleted.

On the airline statistics page only the overall fatalities are shown.
It might be interesting to limit these to the fatalities of the particular airline or just to delete the graphs

Could you add the name of the airline to the statistics page heading to make it more prominent
e.g. Instead of "Statistics" something like "Statistics for Air France"

**Comment by Ysurac** [comment]
Fatalities fixed, an error in the *.htaccess*.

Military removed.

I removed fatalities for now, I don't always have an ident/callsign with all commercial accident/incident.

Name of the airline added.

**Comment by me2tkt** [comment]
Sorry fatalities is still going to a 404.

Just noticed 
When an airline is selected the "flights over country"  on the main statistic page does not change but remains as for all airlines. Going to full statistics gives an empty map and no table.
When clicking on "Busiest time of day" or "Busiest day" the graphs change but the tables remains as for all airlines.

**Comment by me2tkt** [comment]
Statistic pages remember the airline selected.
However the airline selection is not reset for all sub pages when selecting a new airline on the main page.
On each subpage the airline has to be selected as well.

**Comment by me2tkt** [comment]
Great - everything is working, except 
Clicking on a month in the "Fatalities last 12 months" table gives the following error

Accidents from Tuesday November 1, 2016
The table below shows the Accidents on Tuesday Nov 1, 2016.
error : SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION flightmap.to_char does not exist

Same error occurs when clicking on a year in the "Fatalities by year" table

**Comment by Ysurac** [comment]
All should be fixed in latest commit.

**Comment by me2tkt** [comment]
Ok - everything works.
However now the airline has to be selected on each statistics subpage
i.e. the full statistics button shows a subpage with the data for all airlines
Now you have to select the airline on each subpage. Not good when your looking for WizzAir ;-)

I prefered the previous way. The subpages initially inherited the airline from the main page
But yesterday the subpage statistics did not change when selecting a new airline on the main page

**Comment by me2tkt** [comment]
The number of owners and the number of aircraft types shown in the blue fields does not always match the data shown in the graphic and the details table. e.g. Malaysian Airlines, Air Lingus, ANA
Could be a data error.

**Comment by Ysurac** [comment]
All should be fixed now.

**Comment by me2tkt** [comment]
Confirmed.
The total number of flights for February is calculated (today) as over 94000 !
For January it was only about 6000 !
This is repeated for the airlines 
Therefore the graphs ahow only on peak for today, due to scaling to the extreme and wrong value.

Not sure if it is a problem with my db as during the install mysql froze and had to be restarted.

**Comment by me2tkt** [comment]
Todays stats are in the normal range.
So it looks that something broke during the install/update.
Is it possible to recalculate the stats, e.g. by emptying the stats db's ?

**Comment by Ysurac** [comment]
What is the name of the stats that are false exactly ?
The stats are also false when you select the month ?
There is an option to calculate all the stats again, but before I need to be sure there is no problems with data in the table.

If this give too many result:

   SELECT COUNT(*) FROM spotter_output WHERE date = '2017-02-09';


You can check data:

   SELECT * FROM spotter_output WHERE date = '2017-02-09' LIMIT 10;

And give me the result.

**Comment by me2tkt** [comment]
It s a problem with the data in spotter.output.

It seems that during the time the update script was runing something went wrong.
(The PHP script timed out after about 30min and I later stopped mysql manually - not good I know)

The data in spotter.output on the 9.2.2017 between 22:50 and 23:29 is definetely wrong-
- this is the time the script was running !
e.g. just for 23:29:56 there are 74235 flights ! 
(Up to ten entries per second for one ModeS, strangely enough with different positon data)
This started at about 22:50:34 (with 3262 flights)
I have allready deleted all flights between 22:50 and 23:30 - 973077 in total.

The graphs look better but still not correct as the values before the 9.2.17 are too low.

The  data in spotter_archive looks correct but has no data for this time interval.
Which is correct as the daemon was not running during this time.

Is it possible to copy / replace the spotter_output data with the data from spotter_archive and the run the stats ?

**Comment by Ysurac** [comment]
It's why I need a example of the data. If the *last_seen* column seems to be right, you only have to do:

    UPDATE spotter_output SET date = last_seen WHERE last_seen < date;

I have no idea why the date data was changed... Maybe you should try before a:

    SHOW indexes FROM spotter_output;

If there is a **on update** in extra column there is something wrong.
You shouldn't delete anything manually from the DB. There is always an other way.

**Comment by me2tkt** [comment]
This is an extract from spotter_output. All last_seen have the same time stamp.

![spotter_output](https://cloud.githubusercontent.com/assets/23280102/22856552/eae48034-f093-11e6-9810-80d79e75203e.png)

This is the result from Show index

![show_index](https://cloud.githubusercontent.com/assets/23280102/22856570/3b2ec5e0-f094-11e6-8392-3f1b2074a91b.png)

**Comment by Ysurac** [comment]
Sorry, it was a *desc spotter_output;* that I wanted.

**Comment by me2tkt** [comment]
Please clarify.

As the flight counts for all previous dates are now very low it seems to me that older flights were shifted to the then current date of the update i.e. to the 9.2.17

**Comment by Ysurac** [comment]
I wanted to see a description of the table, on command line it's:

    desc spotter_output;


**date** column seems to be set to the date of the update, but it's strange because I don't make any change on this column. But it's possible if there is an "on update" on the date column.

**Comment by me2tkt** [comment]
That commans doesnt work, but I think I know what you mean.

![spotter_desc](https://cloud.githubusercontent.com/assets/23280102/22856839/2069bc64-f09a-11e6-89a1-606a5229ba4a.png)

**Comment by Ysurac** [comment]
ok. That is the problem: **ON UPDATE CURRENT_TIMESTAMP**. This shouldn't be here.
After some search, it's a default behavior of some version of MySQL... What is the version you use ?

**Comment by Ysurac** [comment]
It's on all version. Sorry. It's my fault. You have to remove this "ON UPDATE" property. Should be easy with PHPMyAdmin, else I can give you the SQL command.

**Comment by me2tkt** [comment]
Done

![spotter_desc](https://cloud.githubusercontent.com/assets/23280102/22858027/e4fab674-f0b2-11e6-8d57-a9580241240a.png)

Any other db which have to be changed ?

**Comment by Ysurac** [comment]
No it's all. Sorry again.

**Comment by Ysurac** [comment]
What do you have for **last_seen** column ?

**Comment by me2tkt** [comment]
spotter_archive and spotter_ouput_archive also had date column properts set to "on update".
I removed that.

last_seen is timestamp only - no other property

![spotter_desc](https://cloud.githubusercontent.com/assets/23280102/22858299/6075d878-f0b9-11e6-97b1-5358f4555021.png)

**Comment by me2tkt** [comment]
My statistics seem to stop around the 20.3 or 21.3.16
Data is there until today.
Config shows latest update to be today.
