### ISSUE TITLE
Spotted Duration

### ISSUE THREAD

**Issue by me2tkt** [Ysurac/FlightAirMap#269]
On Page "Search results for registration ... " the table header does not have the new column "Spotted Duration"
Maybe also missing on other pages.

I dont quite understand the time calculation.
One flight starts at 11.2.17- 07:56:01 and ends at 11.2.17-08:44:14 for me this does would be about 48 min, but table value is 23:11.47

**Comment by Ysurac** [comment]
I will fix that.

It's a bug. It's why I changed the column *last_seen* format to timestamp in latest schema update (and made lot of problems for you), but this doesn't seems to be enough... This seems to be a timezone problem, I will make some test on a new install using MySQL.

**Comment by me2tkt** [comment]
Dont worry - no data was really lost and it still is a hobby ;-))
I have to improve my backup concept anyway - currently their isn't really one :-((
(spotter_archive is already over 1Gb  with over 5Mio records !)

I still run VRS and Planeplotter with full data logging on another PC.
(One of my future questions will be - how to add historical data to the database ?
For the data from Nov - Dec 1026 I lost in the power failure in early January but also to have yearly and monthly stats going back to 2013. But that is a later issue.)

**Comment by Ysurac** [comment]
If I know the format to import old data, it's not a big problem.
I don't understand why there is a bug with duration. There is the problem for all flights ? Can you make a screenshot ?
I will look at that tomorrow.

**Comment by me2tkt** [comment]
![duration](https://cloud.githubusercontent.com/assets/23280102/22858494/a93d4a68-f0bf-11e6-883f-53565211673b.png)

The last one is totally wrong - but that is probably due the data being corrupted.

**Comment by Ysurac** [comment]
OK it's a timezone problem. The first date is the first time the flight is seen, and the date below is the last time the flight is seen. Did you restart **daemon-spotter.php** after the update ?

**Comment by me2tkt** [comment]
Yes. Update was on the 9.2.17.
The daemon scripts sometimes stops unexpectedly but normally is always running.

**Comment by Ysurac** [comment]
Daemon shouldn't stop, can you give me the latest output ?

I tried on a fresh install, and duration is ok on MariaDB. For now I have no idea... I will try to reproduce the problem by changing the timezone...

**Comment by me2tkt** [comment]
This only happens after some days (cant really say how many, but over 4-5) and could also be a Windows or other fault.
I can route the output to file but that produces about  1-2 Megabites a day ;-))

**Comment by Ysurac** [comment]
I think it's a schedule fault, when it try to get schedule from external sites, sometimes there is a problem. But I need to have the latest debug info from spotter_daemon to know where it's exactly. Only the latest 20 lines should be enough :)

**Comment by me2tkt** [comment]
Correction - log file is about 50Mb a day ;-)
