### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by nzradar** [Ysurac/FlightAirMap#27]
I have an issue or two and some questions.

The spotter_live table retains old data, I have some records going back to the day I installed my current version, 6 days ago!  Is the spotter_live only supposed to keep the flights that are live?

I assume that the spotter_output should be recording one row per flight once they stop from becoming 'live' flights, is that correct?

Why do I have no records in the spotter_archive table?  Is there a purpose to this table?

When updating a route record in the routes table or an aircraft in the aircraft_modes table there's no retrospective update for the flight info in the spotter_output table meaning I have to update all the records in there as well.

Is there a possibility that non ADS-B data could be databased, i.e. Mode-S?  I get quite a few interesting aircraft fly around my QTH that don't have ADS-B but can be identified with their Mode-S code.

Thanks,
Michael
hfaero.com

**Comment by Ysurac** [comment]
I keep, for now, in *spotter_live* last flight data by ident. This will go in *spotter_archive* soon.

In *spotter_output* there is a record added when the flight is seen, at the beginning.

Data are added in *spotter_archive* if **$globalArchive** is set to *TRUE*. Data are not yet used, soon...

When you update manually data in DB, you have to run *install/check_data.php*. This should update all.

For now, it's not possible to add data without ident and longitude/latitude.

**Comment by nzradar** [comment]
Okay, thank you Ysurac
