### ISSUE TITLE
SQLSTATE[HY000]: General error: 1031

### ISSUE THREAD

**Issue by linuxpronl** [Ysurac/FlightAirMap#270]
After the latest git pull I get:
1031 Table storage engine for 'spotter_archive_output' doesn't have this option

Suggestions how to solve? 

env:
fedora 21
mariadb 10.1.19
kernel 3.19.8

**Comment by Ysurac** [comment]
When you update or a fresh install ?
If this is an update, what is the output of:

    SELECT * FROM config;

**Comment by linuxpronl** [comment]
update from previous git pull and output of query is : 
select * from config;
+------+-------------------------+----------------------------------+
| id   | name                    | value                            |
+------+-------------------------+----------------------------------+
|    1 | schema_version          | 34                               |
| 1554 | airspace_version        | aff32fc25d1ed33b5ddcc3c5b553732f |
| 5834 | last_update_owner_db    | 2017-01-29 02:02:44              |
| 6266 | last_update_airspace_db | 2017-02-06 19:06:02              |
| 6377 | last_update_db          | 2017-02-10 08:21:06              |
| 6440 | last_update_accident_db | 2017-02-11 14:07:42              |
| 6447 | last_update_notam_db    | 2017-02-11 17:06:03              |
| 6480 | last_update_metar       | 2017-02-12 09:06:16              |
| 6481 | last_update_stats       | 2017-02-12 9:13:04               |
+------+-------------------------+----------------------------------+
9 rows in set (0.00 sec)

**Comment by Ysurac** [comment]
Should be fixed in lastest commit: I don't update this table anymore, not really needed.

**Comment by linuxpronl** [comment]
latest pull resolved the issue
