### ISSUE TITLE
Flights not showing

### ISSUE THREAD

**Issue by me2tkt** [Ysurac/FlightAirMap#271]
Flights are no longer appearing on the map.
Daemon-spotter is running but "Aircraft detected" keeps turning (> 30Min)
Calling the Current or latst page shows flights.

Another question : the Upcoming or Highlighted flights pages never show any data - is this correct

**Comment by Ysurac** [comment]
Check you don't have filters on the map. If flights are on current/latest pages, flights should show on map.

Upcoming show flights if I have enough data to display flights that always flights at the same hour.
Highlighted flights is when a flight use an emergency/hijack squawk or if a flight have an accident/incident.

**Comment by me2tkt** [comment]
No filters set - everything on "all".
But now after restart the browser flights are back (normally using Firefox - but IE also did not show any flights)

I have been noticing this for the last two weeks or so.
Sometimes flights are there immediately, sometimes after a few minutes, sometimes only after a few restarts of the browser.

For Upcoming do you refer to the local database ?

**Comment by Ysurac** [comment]
Strange... Never had this problem yet (under firefox and chromium). And this should always be immediately (or some seconds). Under chromium you could try to check with dev tools if there is something strange in console or network tab when you have the problem.

I refer to local database, it's not using schedule.

**Comment by me2tkt** [comment]
Ok, I will check next time (Firefox has a small set of develepor tools)

When do upcoming flights appear ?
Do you need some weeks/months of data ?

I have never seen anything on this page.

**Comment by Ysurac** [comment]
I check if there is more than 5 flights with same ident at the same day of week and between current hour and next 3 hours. So it need at least 6 weeks of data.

**Comment by me2tkt** [comment]
Ok - then upcoming flights data should appear soon ;-)

I pressed "Remove all filters" even though none were marked.
That has brought the response time back to normal.

I did have the impression that the sidebar is not always showing the selected options properly.

**Comment by me2tkt** [comment]
Would it be possible to auto-update the flight data in the pop-up to reflect the movement of the aircraft selected ? T
hen the pop-up could also close when the aircraft is out of range.
Currently the pop-up only shows the position when the aircraft was selected.

**Comment by Ysurac** [comment]
All is possible, this will be done.

**Comment by me2tkt** [comment]
After repeatedly clearing the filters the problem seems to have dissapered.
