### ISSUE TITLE
Replace all statistics maps/graphs from Google

### ISSUE THREAD

**Issue by Ysurac** [Ysurac/FlightAirMap#272]
For map, kartograph ( http://kartograph.org/ ) seems very good. It's used by Piwik for the user map plugin.
For graphs, d3 can be used, it's already used for polar and gage on stat page.

**Comment by me2tkt** [comment]
Looks very good !!!
If it saves download/connection time from Google that would be even better.

**Comment by Ysurac** [comment]
No more connection to Google, all will be local. Sometimes it's really slow to connect to Google...

**Comment by me2tkt** [comment]
Not sure if Google is the problem, but on my system it takes about 1.5 min before the stats page appears.

**Comment by Ysurac** [comment]
Shouldn't take so much time. Can you paste me the source of the page on pastebin.com ? There is debug data on this page (lot of *Time elapsed* info).

**Comment by me2tkt** [comment]
Source is too big for pastebin (> 1.2Mb)
Takes about 60sec for the script, the rest is drawing the airports which I increased to 40 ;-)

**Comment by me2tkt** [comment]
Put up an extract with the longest time, called FMap Stats.
Seems that accidents and incidents take a long time - which is also true when calling these directly via "Explore"

**Comment by Ysurac** [comment]
Strange, the stats page is small.

Accidents/Incidents can take some time using explore page because I make lot of checks, but this is taking no more than 10s on a big DB for now.

**Comment by me2tkt** [comment]
Small  extract of statistics.html (as written by Firefox)  

 

     <h2>**Busiest Day in the last 7 Days**</h2>     
    
     

     <a href="http://192.168.178.37/Website/FlightAirMap/statistics/**fatalities/year**" class="btn btn-default btn" role="button">See full statistic»</a>
     

     <h2>**Fatalities last 12 Months**</h2>

**Comment by Ysurac** [comment]
Really slow. I forget to add index...

**Comment by Ysurac** [comment]
Should be better with latest commit. This update the DB, you have to run *install/index.php*.

**Comment by me2tkt** [comment]
Sorry to say but this did not improve things. It now takes about 4  - 6 Min to complete the Stats page !
It seems that subsequent calls to th Stats page are processed faster.
Are you reindexing/checking the whole database after every update ?

From the statistics.html -
Statistics
Last update: 2017-02-22 21:17:26

"badge">146</span> Military
  -- Time elapsed : 0.65303707122803s -->
  -- Time elapsed : 0.65303707122803s -->
Top 10 Most Common Aircraft Type
   -- Time elapsed : 0.69404006004333s -->
Top 10 Most Common Airline
   -- Time elapsed : 0.72504115104675s -->
Top 10 Most Common Owners
   -- Time elapsed : 0.90505194664001s -->
Top 20 Most Common Country a Flight was Over
   -- Time elapsed : 0.90505194664001s -->
Top 10 Most Common Departure Airports
   -- Time elapsed : 1.2350709438324s -->
Top 10 Most Common Arrival Airports
   -- Time elapsed : 1.2720730304718s -->
Busiest Months of the last 12 Months
   -- Time elapsed : 1.2730729579926s -->
Busiest Day in the last Month
    -- Time elapsed : 1.5050859451294s -->
Busiest Day in the last 7 Days
   -- Time elapsed : 1.5090861320496s -->
Busiest Time of the Day
  -- Time elapsed : 1.5130870342255s -->

**Fatalities by Years**
   -- Time elapsed : 240.23289608955s -->
**Fatalities last 12 Months**
    -- Time elapsed : 273.16837310791s -->

**Comment by Ysurac** [comment]
Strange. Can you give me the result of:

    SHOW INDEX FROM accidents;

*(You should have a "registration_idx" key on "registration" column, a "rdts" key on "registration","date","type" and "source" columns, and a "type" key on "type" and "date" columns)*

And the result of:

    EXPLAIN SELECT EXTRACT(year FROM date) AS year, SUM(fatalities) as count FROM accidents WHERE accidents_id IN (SELECT MAX(accidents_id) FROM accidents WHERE fatalities > 0 AND EXTRACT(year FROM date) > 2006 GROUP BY registration) GROUP BY EXTRACT(year FROM date) ORDER BY year;

Also the result of:

    SELECT COUNT(*) FROM accidents;

**Comment by me2tkt** [comment]
SHOW INDEX FROM accidents;
![showidx](https://cloud.githubusercontent.com/assets/23280102/23279403/6ed1334e-fa15-11e6-8a82-6528c1d7574f.png)

**Comment by me2tkt** [comment]
EXPLAIN.

![expl](https://cloud.githubusercontent.com/assets/23280102/23279460/a9943d32-fa15-11e6-92c7-bd759c234036.png)

**Comment by me2tkt** [comment]
COUNT(*) 	
103471

**Comment by Ysurac** [comment]
* index are ok
* explain is ok
* count is ok

So no problems here.
You may need to change some settings of mariadb, in **my.cnf**: you can increase *query_cache_size*, I have 64M, *tmp_table_size* I have 1G, *max_heap_table_size* . 1G also. 

Then you can try to increase *key_buffer_size* to 16M, *max_allowed_packet* to 4M, *table_open_cache* to 600, *sort_buffer_size* to 2M, *read_buffer_size* tp 1M; *myisam_sort_buffer_size* to 8M

I think I will also precalculate accidents/incidents stats...

**Comment by me2tkt** [comment]
I changed some parameter as you suggested. Some where not even in the my.ini file.

That has reduced the time by 50% at least.

The standard XAMPP my.ini seems to be for a minor test application only. Settings in kB range !
But they also supply alternatives for more work intensive server applications. 
I will change to one of those configurations.

**Comment by me2tkt** [comment]
Comming back to the original theme - Have you decided on using kartograph ?
Any tests ?

**Comment by Ysurac** [comment]
I will use kartograph, but I didn't have time yet to add it. This will be done ASAP.

**Comment by me2tkt** [comment]
Looking forward to seeing it.
Take your time - you are doing so much aready !!!

**Comment by me2tkt** [comment]
On all the new graphs the data points are called "flights"
Personally I dont like the smoothed, curvy lines. 
I prefered straight lines or even bars - but then I am an engineer ;-)
The curves imply intermediate data points which do not exist.

**Comment by me2tkt** [comment]
I also have a problem with the scaling of the number of airports.
The colors fade very quickly and the dots also get very small,  both make less frequent airports hard to see.
Are you using a linear scale, maybe a logarthmic scale would be better ?

**Comment by Ysurac** [comment]
I changed line style, I like curvy lines but these lines are sometimes really strange...

For airport, I really don't know. With log scale we will not see that some airports really have more flights than others. I will make so try...

**Comment by me2tkt** [comment]
Some line graphs are still curvy e.g. fatalities.
Maybe bar charts would actually be better datawise than the line charts (which are prettier)
Bar charts would give you more space for showing longer time periods e.g. fatalities per year could go back further than 10 years.

But if its only me then leave it.
