### ISSUE TITLE
Whazzup data not showing unless CID is numeric

### ISSUE THREAD

**Issue by roo2002** [Ysurac/FlightAirMap#273]
Firstly congratulations on the program, it's one of the best maps I've seen.
The extra information that it shows is great, thank you.

The issue I have is as titled.

I'm using a whazzup.txt file to display information from a private FSD server on the map.

If the CID of the client is not numeric (12345678) they will not be shown on the map.

Is there somewhere I could change this to Alphanumeric?

Roo

**Comment by Ysurac** [comment]
This should work with latest commit now.

**Comment by roo2002** [comment]
All working perfectly.
Thank you.
