### ISSUE TITLE
PHP error

### ISSUE THREAD

**Issue by roo2002** [Ysurac/FlightAirMap#274]
I get the below error using PHP Version 5.6.30

[Code]BUSIEST TIME OF THE DAY
Below is a list of the most common time of day.

error : SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'integer) ASC' at line 1[/code]

I also used to see a picture of the aircraft and now I dont.
I can't see what I've missed?

**Comment by Ysurac** [comment]
What is the DB used (Mysql, MariaDB or PostgreSQL) ? version ?

For pictures, do you have **$globalAircraftImageSourcesFetch** set to **TRUE** in *require.settings.php* and what do you have in **$globalAircraftImageSources** ?

**Comment by roo2002** [comment]
I'll check the settings.php in a min and I'm using MySQL

**Comment by Ysurac** [comment]
What is the version of MySQL used ?

**Comment by roo2002** [comment]
I'm using MySQL

And

//Retrieve Image from externals sources
$globalAircraftImageFetch = TRUE;
//Sources for Aircraft image
$globalAircraftImageSources = array('ivaomtl','wikimedia','airportdata','deviantart','flickr','bing','jetphotos','planepictures','planespotters','customsources');
// Custom source configuration {registration} will be replaced by aircraft
registration (exif get copyright from exif data for each pic)
// example of config : $globalAircraftImageCustomSources = array('thumbnail' => 'http://pics.myurl.com/thumbnail/{registration}.jpg','original' => 'http://myurl/original/{registration}.jpg','source_website' => 'https://www.myurl.com', 'source' => 'customsite', 'exif' => true);
// ************************

I'm using a whazzup.txt so registration isn't sent unless it's the callsign.

**Comment by roo2002** [comment]
MySQL version 5.5.54

**Comment by Ysurac** [comment]
MySQL 5.5 is not supported anymore. You need at least version 5.6.1

If you have also **$globalIVAO** set to **TRUE** and curl PHP module is activated, you should see some pics. Only aircraft ICAO and airline ICAO is used to search pics on http://mtlcatalog.ivao.aero/

**Comment by roo2002** [comment]
Thank you.
I'll upgrade in a moment.

**Comment by roo2002** [comment]
Upgraded to MySQL version 5.6.35

Images are working as they should, but the above PHP error still shows.

**Comment by Ysurac** [comment]
Should be working with latest commit. This was working with MariaDB but not with MySQL.

**Comment by roo2002** [comment]
Working perfectly.
Thank you again.
