### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by me2tkt** [Ysurac/FlightAirMap#277]
When trying to run update, it fails with the following error 👍 
Count fatalities stats...

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error' in C:\xampp\htdocs\WebSite\FlightAirMap\require\class.Stats.php:974
Stack trace:
#0 C:\xampp\htdocs\WebSite\FlightAirMap\require\class.Stats.php(974): PDOStatement->fetchAll(2)
#1 C:\xampp\htdocs\WebSite\FlightAirMap\require\class.Stats.php(1628): Stats->deleteStatsByType('fatalities_byye...')
#2 C:\xampp\htdocs\WebSite\FlightAirMap\scripts\update_db.php(90): Stats->addOldStats()
#3 {main}
  thrown in C:\xampp\htdocs\WebSite\FlightAirMap\require\class.Stats.php on line 974

Any idea ?

**Comment by Ysurac** [comment]
Should be fixed, a little error.

**Comment by me2tkt** [comment]
I updated my database after a server crash.
Now I get the following messages from the update script 
The message repeas for all vehicles
--
Vehicules models from FlightAirMap website : Download...Check files...
Downloading vehicules model ball.glb ...

Warning: fopen(C:\xampp\htdocs\WebSite\FlightAirMap\install/../models/vehicules/ball.glb): failed to open stream: No such file or directory in C:\xampp\htdocs\WebSite\FlightAirMap\install\class.update_db.php on line 14

Warning: curl_setopt(): supplied argument is not a valid File-Handle resource in C:\xampp\htdocs\WebSite\FlightAirMap\install\class.update_db.php on line 21

Warning: fclose() expects parameter 1 to be resource, boolean given in C:\xampp\htdocs\WebSite\FlightAirMap\install\class.update_db.php on line 24

**Comment by Ysurac** [comment]
fixed in latest commit.
