### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by me2tkt** [Ysurac/FlightAirMap#279]
Just updated the scripts.
Regardless of the value for $globalInstalled in settings.php, the index script gives the following error -

"You need to change $globalInstalled in settings.php to FALSE if you want to access setup again."

**Comment by Ysurac** [comment]
Strange.
You can try to run **install/install-action.php?reset**. This will reset all sessions variables if it's the problem.

**Comment by me2tkt** [comment]
Running reset gives the following :
Notice: Undefined index: install in C:\xampp\htdocs\WebSite\FlightAirMap\install\install-action.php on line 64
Last session :
Notice: Undefined index: done in C:\xampp\htdocs\WebSite\FlightAirMap\install\install-action.php on line 65
Reset session !!

But install still complains about $globalinstalled .-(

I have restarted PC and all programs
I have checked all settings.php on my disk
All have $globalInstalled = FALSE;
Just to be sure I renamend all unused settipgs.php

**Comment by Ysurac** [comment]
So it was not a Session problem.
You could try to add:

    var_dump($globalInstalled);

in *install/index.php* after the **if ($globalInstalled &&.....) {** line at the beginning. 
If this display TRUE you have this settings that is set somewhere. 

Under linux you can check with a grep -R globalInstalled \* from the root path of FlightAirMap.

**Comment by me2tkt** [comment]
bool(true)
You need to change $globalInstalled in settings.php to FALSE if you want to access setup again.

So its not accessing the correct settings.php ?
I will searc again.

**Comment by Ysurac** [comment]
It only use the **require/settings.php** file. Check that you don't have the file opened multiple times, that you have write right on it and really change the settings, and check if $globalInstalled is only defined one time in the file.

**Comment by me2tkt** [comment]
My settings.php seems to be damaged.
With a new file from github install  works

**Comment by me2tkt** [comment]
You got it.
For whatever reason there was a second $globalInstalled right at the end !

There is a typo in the marine.identify.sql .
It should be INCREMENT not INCEREMENT.

Install complains that databases (marine or tracker9 are already installed.
Probably from previous runs.
I deleted them and restarted install.
Install completed successfully

**Comment by Ysurac** [comment]
OK.
I fixed the sql. Thanks.

**Comment by Bigben83** [comment]
after doing a git pull and running install.php
then doing a scripts/update_db.php

I get the following error

updating NOTAM...NOTAM from FlightAirMap website : Download...Gunzip...Add to DB...ERROR : Q)WIARADIUSOF1NMANDAMAXHGTOF375FTAMSL.325FTAGL
ERROR : Q)W(BTNJAND
ERROR : Q)A(BTNJAND
.........

**Comment by Ysurac** [comment]
It's not a problem, only bad formatted NOTAM.
