### ISSUE TITLE
.htaccess problem again

### ISSUE THREAD

**Issue by c0by1** [Ysurac/FlightAirMap#28]
i can click what i want... i only see the main page from the stats.

left upper corner... is the current url.

![fam_2](https://cloud.githubusercontent.com/assets/5725891/7768462/7689519c-007b-11e5-9063-d27dc8ed3b53.JPG)
![fam_3](https://cloud.githubusercontent.com/assets/5725891/7768464/7694accc-007b-11e5-8ecd-a6ba29168278.JPG)
![fam_1](https://cloud.githubusercontent.com/assets/5725891/7768463/768f7d9c-007b-11e5-894e-1f8583d67eef.JPG)

**Comment by Ysurac** [comment]
There is nothing special for statistics in the .htaccess.
What do you have in your logs ?

**Comment by c0by1** [comment]
Nothing. When i open the direct link, maybe "statistics-aircraft.php", then i see the correct site... but not when i use the menu.

**Comment by c0by1** [comment]
and the browser didnt mark the right menu point.

**Comment by c0by1** [comment]
PHP Notice:  Undefined index: FromAirport_ICAO in /var/www/c.net/flight/require/class.Spotter.php on line 7446
PHP Notice:  Undefined index: ToAirport_ICAO in /var/www/c.net/flight/require/class.Spotter.php on line 7447
PHP Notice:  Undefined index: FromAirport_ICAO in /var/www/c.net/flight/require/class.Spotter.php on line 7451
PHP Notice:  Undefined index: ToAirport_ICAO in /var/www/c.net/flight/require/class.Spotter.php on line 7451

**Comment by c0by1** [comment]
only something like this.

**Comment by Ysurac** [comment]
It's fixed now, but it's not related.
Are you sure Apache read the .htaccess ?

**Comment by c0by1** [comment]
yes. /tv results in the tv.php...

**Comment by c0by1** [comment]
order deny, allow
deny from all


works too.

**Comment by c0by1** [comment]
[Fri May 22 13:01:44 2015] [error] [client x.x.x.x] PHP Notice:  Undefined variable: additional_query in /var/www/c.net/flight/require/class.Spotter.php on line 2672, refer$
[Fri May 22 13:01:44 2015] [error] [client x.x.x.x] PHP Notice:  Undefined variable: limit_query in /var/www/c.net/flight/require/class.Spotter.php on line 2675, referer: h$
[Fri May 22 13:02:01 2015] [error] [client x.x.x.x] PHP Notice:  Undefined variable: additional_query in /var/www/c.net/flight/require/class.Spotter.php on line 2672, refer$
[Fri May 22 13:02:01 2015] [error] [client x.x.x.x] PHP Notice:  Undefined variable: limit_query in /var/www/c.net/flight/require/class.Spotter.php on line 2675, referer: h$
[Fri May 22 13:02:17 2015] [error] [client x.x.x.x] PHP Notice:  Undefined variable: additional_query in /var/www/c.net/flight/require/class.Spotter.php on line 2672, refer$
[Fri May 22 13:02:17 2015] [error] [client x.x.x.x] PHP Notice:  Undefined variable: limit_query in /var/www/c.net/flight/require/class.Spotter.php on line 2675, referer: h$
[Fri May 22 13:02:34 2015] [error] [client x.x.x.x] PHP Notice:  Undefined variable: additional_query in /var/www/c.net/flight/require/class.Spotter.php on line 2672, refer$
[Fri May 22 13:02:34 2015] [error] [client x.x.x.x] PHP Notice:  Undefined variable: limit_query in /var/www/c.net/flight/require/class.Spotter.php on line 2675, referer: h$
[Fri May 22 13:02:50 2015] [error] [client x.x.x.x] PHP Notice:  Undefined variable: additional_query in /var/www/c.net/flight/require/class.Spotter.php on line 2672, refer$
[Fri May 22 13:02:50 2015] [error] [client x.x.x.x] PHP Notice:  Undefined variable: limit_query in /var/www/c.net/flight/require/class.Spotter.php on line 2675, referer: h$
[Fri May 22 13:03:06 2015] [error] [client x.x.x.x] PHP Notice:  Undefined variable: additional_query in /var/www/c.net/flight/require/class.Spotter.php on line 2672, refer$
[Fri May 22 13:03:06 2015] [error] [client x.x.x.x] PHP Notice:  Undefined variable: limit_query in /var/www/c.net/flight/require/class.Spotter.php on line 2675, referer: h$
[Fri May 22 13:03:22 2015] [error] [client x.x.x.x] PHP Notice:  Undefined variable: additional_query in /var/www/c.net/flight/require/class.Spotter.php on line 2672, refer$
[Fri May 22 13:03:22 2015] [error] [client x.x.x.x] PHP Notice:  Undefined variable: limit_query in /var/www/c.net/flight/require/class.Spotter.php on line 2675, referer: h$
[Fri May 22 13:03:39 2015] [error] [client x.x.x.x] PHP Notice:  Undefined variable: additional_query in /var/www/c.net/flight/require/class.Spotter.php on line 2672, refer$
[Fri May 22 13:03:39 2015] [error] [client x.x.x.x] PHP Notice:  Undefined variable: limit_query in /var/www/c.net/flight/require/class.Spotter.php on line 2675, referer: h$

**Comment by Ysurac** [comment]
Old bug fixed, not related.

**Comment by c0by1** [comment]
or is something server side / php missing? the menu doesnst correctly redirect to the right file... i think.

**Comment by Ysurac** [comment]
What is your Apache version ?

**Comment by c0by1** [comment]
Server version: Apache/2.2.22 (Debian)
Server built:   Dec 23 2014 22:48:29

**Comment by Ysurac** [comment]
Never tested on Apache 2.2... Maybe the change in commit ed186d7159cc998311b94125a09e0e0191d136e6 will work.

**Comment by c0by1** [comment]
nope same problem... i get only the main page... what version or what webserver, do you use?

**Comment by Ysurac** [comment]
Just checked, Apache 2.2.29 in fact... So it's not the problem.
If you have **AllowOverride All** in your Apache configuration, I have no idea where is your config problem.

**Comment by c0by1** [comment]
"AllowOverride All"

stands in the vhost..

**Comment by Ysurac** [comment]
You can add : 
> RewriteEngine On
> RewriteLog "/var/log/rewrite.log"
> RewriteLogLevel 9

to see if there is an error inside *.htaccess* with rewrites.

**Comment by c0by1** [comment]
put this in the .htaccess?

**Comment by Ysurac** [comment]
In your vhost conf.

**Comment by c0by1** [comment]
yeah my fault... ^^

**Comment by c0by1** [comment]
http://c0by.net/rewrite.log

have a look

**Comment by c0by1** [comment]
a hint. the site runs on a vhost from the apache...

**Comment by Ysurac** [comment]
A see a link *statistics.php*. What URL do you use to access statistics page ?

**Comment by c0by1** [comment]
this from the page. 

http://c0by.net/flight/ ?

**Comment by c0by1** [comment]
hmm? redirects to the wrong file or?

add path info postfix: /var/www/empoweb/blub/statistics.php -> /var/www/empoweb/blub/statistics.php/date

musst be this or?

-> statistics-date.php

**Comment by c0by1** [comment]
normal rewrite works for me... i've tested again.

**Comment by Ysurac** [comment]
Seems to work for all *xxx*but none *xxx/yyy* url.
It add a *.php* to all uri, so it can't apply pattern.
What's your vhost config ? Do you use PHP as module ? What's your configuration of PHP inside Apache ?

**Comment by c0by1** [comment]
<VirtualHost *:80>
ServerName c0by.net
ServerAlias c0by.net
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/c0by
        <Directory />
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
        </Directory>
                ErrorLog /var/log/apache2/c0by./error.log
                CustomLog /var/log/apache2/c0by/access.log combined
                LogLevel warn
</VirtualHost>

**Comment by c0by1** [comment]
i've installed php via apt-get

**Comment by c0by1** [comment]
http://c0by.net/flight/p.php

**Comment by Ysurac** [comment]
Try http://c0by.net/flight/p
It works. There is a rewriterule that add *.php* to everything, and this make a conflict with the *.htaccess*.

**Comment by c0by1** [comment]
hmm! damn! works with http://c0by.net/flight/ppp to...

**Comment by c0by1** [comment]
fuuu. every vhost do this... and i dont know the option for this.

**Comment by c0by1** [comment]
got it... but the rewrite doesnt work at all now... hmpf

**Comment by c0by1** [comment]
had to change

Options Indexes FollowSymLinks MultiViews

in

Options Indexes FollowSymLinks

..


works fine now..


big thx.
