### ISSUE TITLE
Date search 

### ISSUE THREAD

**Issue by me2tkt** [Ysurac/FlightAirMap#280]
There seems to be a small problem with the correct path in the date search.

If I look at "Flights from Friday March 17, 2017" everything is fine
Using the "select date" feature leads to a 404 error.

Link for current date : http://192.xxx.yyy.zz/Website/FlightAirMap/date/2017-03-17
Link for selected date : http://192.xxx.yyy.zz/date/2017-03-08

If I add the missing part to the selected date link URL then the correct page is shown.

**Comment by Ysurac** [comment]
What is the value of **$globalURL** in **require/settings.php** ?

**Comment by me2tkt** [comment]
$globalURL = '/Website/FlightAirMap'

**Comment by me2tkt** [comment]
Same problem for date search on the Accident and Incidents pages
