### ISSUE TITLE
Can not run /install/index.php

### ISSUE THREAD

**Issue by thebaldgeek** [Ysurac/FlightAirMap#281]
Tried installing about a year ago, had install issues then as well, but want to persist more and get it running this time.

Apache2 2.2.22
Linux 3.8.0
Ubuntu 12.04 LTS (Command line only).
MySQL 5.5.37
Hosting a stock Wordpress site on the URL.

http://url.net/adsb/install/index.php
I get the error "The url.net page isn’t working
url.net is currently unable to handle this request.
HTTP ERROR 500"

I am confident that I have the mod_rewrite enabled and the other dependencies met.
I unzipped master.zip into /var/www/adsb
Can see all the files and directories under that directory.
All files owned by root.

**Comment by Ysurac** [comment]
Check  the logs of apache ( can be in /var/log/apache2/error_log ) to check if there is an error here.

**Comment by thebaldgeek** [comment]
tail error.log
[Mon Mar 20 10:08:23 2017] [notice] Apache/2.2.22 (Ubuntu) PHP/5.3.10-1ubuntu3.21 with Suhosin-Patch mod_ssl/2.2.22 OpenSSL/1.0.1 configured -- resuming normal operations
[Mon Mar 20 10:08:26 2017] [error] [client 98.112.44.167] PHP Parse error:  syntax error, unexpected T_STRING in /var/www/adsb/require/class.APRS.php on line 368
[Mon Mar 20 10:08:32 2017] [error] [client 98.112.44.167] PHP Parse error:  syntax error, unexpected T_STRING in /var/www/adsb/require/class.APRS.php on line 368
[Mon Mar 20 10:08:33 2017] [error] [client 98.112.44.167] PHP Parse error:  syntax error, unexpected T_STRING in /var/www/adsb/require/class.APRS.php on line 368

**Comment by thebaldgeek** [comment]
PHP version as follows.

php -v
PHP 5.3.10-1ubuntu3.21 with Suhosin-Patch (cli) (built: Oct 28 2015 01:43:56)
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2012 Zend Technologies

**Comment by Ysurac** [comment]
This error is not related with the index.php problem.
At least PHP 5.4 is required.

**Comment by thebaldgeek** [comment]
Thanks for your quick responce.
PHP 5.4 is not available for my version of Ubuntu.

Issue closed.

**Comment by Ysurac** [comment]
I don't test anymore on PHP 5.3, too many functions are not supported or give strange results.

**Comment by thebaldgeek** [comment]
Yup. Understood. No problem.
(Will look at spinning up a newer version of Ubuntu and try your install/index.php on that system).
