### ISSUE TITLE
Install REV 408

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#29]
Hello again dear friend Ysurac.

Now I have new reseller with more trnsferencia and all, download the fix 408 and put all the necessary libraries as well as config PHP 5.4, and MySQL correct.

to put the cms is the perfect site, but installing the error log jumps this ....

[29-May-2015 12:52:17 UTC] PHP Parse error: syntax error, unexpected '$ globalDBdriver' (T_VARIABLE) in /home/airpiro/public_html/require/settings.php on line 38

and is all in white can not do anything else.

**Comment by Ysurac** [comment]
Did you edit *settings.php* manually ? You have a syntax error in it.

**Comment by tonkepen100** [comment]
if I'll look and I say, thanks

**Comment by tonkepen100** [comment]
either edit it, but I do not see any syntax error, I think okay

// DATABASE CONNECTION LOGIN
$globalDBdriver = 'mysql'; // PDO driver used. Tested with mysql, maybe pgsql or others work...
$globalDBhost = 'localhost'; //database connection url
$globalDBuser = 'airpiro_radar'; //database username
$globalDBpass = 'xxxxxxxxxxxx'; //database password
$globalDBname = 'airpiro_radar'; //database name
$globalTransaction = TRUE; //Activate database transaction support


//FLIGHTAWARE API INFO
$globalFlightAware = FALSE; //set to TRUE to use FlightAware as data import
$globalFlightAwareUsername = ''; //FlightAware Username
$globalFlightAwarePassword = ''; //FlightAware Password/API key


and the result is this ....

http://airpiro.ovh

Gracias

**Comment by c0by1** [comment]
sometimes there is missing one ";"... at the sbs settings...

**Comment by tonkepen100** [comment]
as it is true in the array that, as you can and change that leaves so base

thanks

**Comment by tonkepen100** [comment]
This,,,,

// FLIGHTS MUST BE INSIDE THIS CIRCLE
$globalDistanceIgnore = array();
