### ISSUE TITLE
 Illegal mix of collations

### ISSUE THREAD

**Issue by me2tkt** [Ysurac/FlightAirMap#290]
On Lastest accidents I get the following message:

Latest Accidents
The table below shows the latest Accidents.

Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '=' in C:\xampp\htdocs\WebSite\FlightAirMap\require\class.Image.php:32 Stack trace: #0 C:\xampp\htdocs\WebSite\FlightAirMap\require\class.Image.php(32): PDOStatement->execute(Array) #1 C:\xampp\htdocs\WebSite\FlightAirMap\require\class.Accident.php(114): Image->getSpotterImage('9\xD0\xA2-HM-1') #2 C:\xampp\htdocs\WebSite\FlightAirMap\accident-latest.php(36): Accident->getAccidentData('0,25', 'accident') #3 {main} thrown in C:\xampp\htdocs\WebSite\FlightAirMap\require\class.Image.php on line 32

Does not occur on Todays Accident or Latest Incedent or any other page

**Comment by Ysurac** [comment]
It's an error in crash list, I fixed it. Latest commit should mitigate this error.

**Comment by me2tkt** [comment]
I changed my database from swedish to utf. But that did not change anything.
Now I'll try the new commit.

**Comment by Ysurac** [comment]
Changing collation will not work because it was put in DB with wrong one. In latest commit I ignore wrong registration data.
