### ISSUE TITLE
spotter damon stopped

### ISSUE THREAD

**Issue by me2tkt** [Ysurac/FlightAirMap#291]
Today the spotter daemon stopped.
The last messages were : 

Error: socket.select gives this error (translated from German) The process was stopped successfully.
Restarting ...
Shutdown all sockets...
Restart all connections...

I'm using Windows and a Radarcape receiver.

**Comment by Ysurac** [comment]
This was a network error. It should try to reconnect after sleeping a little.

**Comment by me2tkt** [comment]
Slept for over 8h ;-)

**Comment by Ysurac** [comment]
strange. Maybe better in latest commit.
