### ISSUE TITLE
N callsign image

### ISSUE THREAD

**Issue by roo2002** [Ysurac/FlightAirMap#292]
Our map and images etc work great.
The only issue I've found is if an Aircraft has a US N callsign/registration, the image of the aircraft is only displayed in the information page and not in the popup. 
Is there anything I can edit to correct this?
I have emptied The IATA database so random Callsigns are not shown for a N reg aircraft.

**Comment by Ysurac** [comment]
Strange, same data are used for aircraft info and pages.
Which IATA db ?

**Comment by roo2002** [comment]
Airlines IATA.
Do you think that may be the issue?

Http://roo.servebeer.com/jfs is the map.
N1234 over Australia is the test aircraft.

**Comment by Ysurac** [comment]
You can try latest commit, else I will try to find the bug tomorrow.

**Comment by roo2002** [comment]
I'll try the latest tomorrow.
Thanks for the help.

**Comment by roo2002** [comment]
Downloaded latest commit and installed on a fresh database.
I've found that the N reg images show only if they are using iata in their callsign.
So if I delete the iata info from the database the images won't show, but if I leave the iata info in the data base a random callsign is shown.

**Comment by Ysurac** [comment]
A registration seems to be used as callsign from your source, it's why airlines checking is not valid. You should set the **$globalNoAirlines** value to **TRUE** in *require/settings.php* (or the checkbox no airlines in the install/index.php).
You should also set **$globalVA** to **TRUE** (or checkbox Virtual Airlines in install/index.php).

**Comment by roo2002** [comment]
Still no joy with the above.
But I solved the problem by replacing the iata callsign names for each N callsign.

Thanks for the help
