### ISSUE TITLE
Error running cronjob update_db.php

### ISSUE THREAD

**Issue by MrDalle** [Ysurac/FlightAirMap#293]
Hey!

the map is running great with no issues but every hour when my plesk runs the update_db.php script im getting lots of errors..

`PHP Warning:  fopen(/var/www/vhosts/dd-photography.de/map.fswire.net/install/../models/vehicules/ball.glb): failed to open stream: No such file or directory in /var/www/vhosts/dd-photography.de/map.fswire.net/install/class.update_db.php on line 14
PHP Warning:  curl_setopt(): supplied argument is not a valid File-Handle resource in /var/www/vhosts/dd-photography.de/map.fswire.net/install/class.update_db.php on line 21
PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /var/www/vhosts/dd-photography.de/map.fswire.net/install/class.update_db.php on line 24
PHP Warning:  fopen(/var/www/vhosts/dd-photography.de/map.fswire.net/install/../models/vehicules/boat.glb): failed to open stream: No such file or directory in /var/www/vhosts/dd-photography.de/map.fswire.net/install/class.update_db.php on line 14
PHP Warning:  curl_setopt(): supplied argument is not a valid File-Handle resource in /var/www/vhosts/dd-photography.de/map.fswire.net/install/class.update_db.php on line 21
PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /var/www/vhosts/dd-photography.de/map.fswire.net/install/class.update_db.php on line 24
PHP Warning:  fopen(/var/www/vhosts/dd-photography.de/map.fswire.net/install/../models/vehicules/car.glb): failed to open stream: No such file or directory in /var/www/vhosts/dd-photography.de/map.fswire.net/install/class.update_db.php on line 14
PHP Warning:  curl_setopt(): supplied argument is not a valid File-Handle resource in /var/www/vhosts/dd-photography.de/map.fswire.net/install/class.update_db.php on line 21
PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /var/www/vhosts/dd-photography.de/map.fswire.net/install/class.update_db.php on line 24
PHP Warning:  fopen(/var/www/vhosts/dd-photography.de/map.fswire.net/install/../models/vehicules/car.gltf): failed to open stream: No such file or directory in /var/www/vhosts/dd-photography.de/map.fswire.net/install/class.update_db.php on line 14
PHP Warning:  curl_setopt(): supplied argument is not a valid File-Handle resource in /var/www/vhosts/dd-photography.de/map.fswire.net/install/class.update_db.php on line 21
PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /var/www/vhosts/dd-photography.de/map.fswire.net/install/class.update_db.php on line 24
PHP Warning:  fopen(/var/www/vhosts/dd-photography.de/map.fswire.net/install/../models/vehicules/Cesium_Ground.glb): failed to open stream: No such file or directory in /var/www/vhosts/dd-photography.de/map.fswire.net/install/class.update_db.php on line 14
PHP Warning:  curl_setopt(): supplied argument is not a valid File-Handle resource in /var/www/vhosts/dd-photography.de/map.fswire.net/install/class.update_db.php on line 21
PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /var/www/vhosts/dd-photography.de/map.fswire.net/install/class.update_db.php on line 24
PHP Warning:  fopen(/var/www/vhosts/dd-photography.de/map.fswire.net/install/../models/vehicules/cycle.glb): failed to open stream: No such file or directory in /var/www/vhosts/dd-photography.de/map.fswire.net/install/class.update_db.php on line 14
PHP Warning:  curl_setopt(): supplied argument is not a valid File-Handle resource in /var/www/vhosts/dd-photography.de/map.fswire.net/install/class.update_db.php on line 21
PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /var/www/vhosts/dd-photography.de/map.fswire.net/install/class.update_db.php on line 24
PHP Warning:  fopen(/var/www/vhosts/dd-photography.de/map.fswire.net/install/../models/vehicules/firetruck.glb): failed to open stream: No such file or directory in /var/www/vhosts/dd-photography.de/map.fswire.net/install/class.update_db.php on line 14
PHP Warning:  curl_setopt(): supplied argument is not a valid File-Handle resource in /var/www/vhosts/dd-photography.de/map.fswire.net/install/class.update_db.php on line 21
PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /var/www/vhosts/dd-photography.de/map.fswire.net/install/class.update_db.php on line 24
PHP Warning:  fopen(/var/www/vhosts/dd-photography.de/map.fswire.net/install/../models/vehicules/police.glb): failed to open stream: No such file or directory in /var/www/vhosts/dd-photography.de/map.fswire.net/install/class.update_db.php on line 14
PHP Warning:  curl_setopt(): supplied argument is not a valid File-Handle resource in /var/www/vhosts/dd-photography.de/map.fswire.net/install/class.update_db.php on line 21
PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /var/www/vhosts/dd-photography.de/map.fswire.net/install/class.update_db.php on line 24
PHP Warning:  fopen(/var/www/vhosts/dd-photography.de/map.fswire.net/install/../models/vehicules/truck.gltf): failed to open stream: No such file or directory in /var/www/vhosts/dd-photography.de/map.fswire.net/install/class.update_db.php on line 14
PHP Warning:  curl_setopt(): supplied argument is not a valid File-Handle resource in /var/www/vhosts/dd-photography.de/map.fswire.net/install/class.update_db.php on line 21
PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /var/www/vhosts/dd-photography.de/map.fswire.net/install/class.update_db.php on line 24
PHP Warning:  fopen(/var/www/vhosts/dd-photography.de/map.fswire.net/install/../models/vehicules/vehicules_models.md5sum): failed to open stream: No such file or directory in /var/www/vhosts/dd-photography.de/map.fswire.net/install/class.update_db.php on line 14
PHP Warning:  curl_setopt(): supplied argument is not a valid File-Handle resource in /var/www/vhosts/dd-photography.de/map.fswire.net/install/class.update_db.php on line 21
PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /var/www/vhosts/dd-photography.de/map.fswire.net/install/class.update_db.php on line 24
`

**Comment by Ysurac** [comment]
Same as #277 
Fixed (directory models/vehicule didn't exist, do this fail when marine or tracker is enabled).
