### ISSUE TITLE
Error after latest pull

### ISSUE THREAD

**Issue by linuxpronl** [Ysurac/FlightAirMap#294]
When I tried to run install after latest pull I got:

Error : error (add index flightaware_id, date on spotter_archive) : SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 8 bytes

**Comment by Ysurac** [comment]
Strange. 
* What is the version of MySQL or MariaDB ?
* What is the format of spotter_archive table ? (Should be InnoDB)
* What is the schema of the table ? (*DESC spotter_archive*)
