### ISSUE TITLE
Enhancement: Leading line to ARR Airport

### ISSUE THREAD

**Issue by MrDalle** [Ysurac/FlightAirMap#295]
Would it be possible to make a "leading line" so pilots see also where they are going?
Maybe with an option somewhere to show or hide it.
![b3ad393f1389776ae148b1744820bed8](https://cloud.githubusercontent.com/assets/7756672/25580510/d6226d24-2e81-11e7-8b30-839ff32c1a10.png)

**Comment by Ysurac** [comment]
You can already see route by using settings tab on map and click "display flight route and click", but it's true that this "leading line" is better. I will add that.
