### ISSUE TITLE
METAR not updating correctly

### ISSUE THREAD

**Issue by MrDalle** [Ysurac/FlightAirMap#299]
It looks like the METAR is updating "randomly" on some airports. Most of the Aiports are very accurate but some of them recieved the last update like a month ago...

I tried also to change it to the vatsim metar but nothing changes.. 

`//METAR
$globalMETAR = TRUE;
$globalMETARcycle = TRUE; // If update_db.php in cron job, all METAR are downloaded from NOAA
// else put an url as METAR source, can be vatsim.
$globalMETARurl = 'http://metar.vatsim.net/metar.php?id={icao}'; // Use {icao} to indicate where airport icao must be put in url`

Thanks!

**Comment by Ysurac** [comment]
For real flights, METAR are downloaded from NOAA server based on the hour, so if **scripts/update_db.php** is running every hours all data in every METAR is added. If data are old for an airport, then it's that no new data are available for that airport.

For IVAO, METAR come from http://wx.ivao.aero/metar.php and I don't think that all METAR are available for IVAO and VATSIM, and no idea if it's real METAR.

**Comment by kferrano** [comment]
Übersetzen

Wie oft wird http://wx.ivao.aero/metar.php geupdatet

Am Beispielt von EDDC sehe ich in der metar.php keine veränderung obwohl sich die metar geändert hat um 20:50Z

164/5000
How often is http://wx.ivao.aero/metar.php updated

The example of EDDC I see in the metar.php no change although the metar has changed at 20: 50Z
