### ISSUE TITLE
Problems with map update

### ISSUE THREAD

**Issue by kferrano** [Ysurac/FlightAirMap#305]
After server move, updates do not go anymore although everything is set as before
[View ](https://youtu.be/g9VeJ36Onxs)

**Comment by Ysurac** [comment]
I need more info...
Source used ? Version used ?...

**Comment by kferrano** [comment]
Version latest
Source phpvms

**Comment by Ysurac** [comment]
Working with my test phpvms source.
Check again your configuration, check that the flight is really moving (if I have data in the source, I display it), check output of spotter-daemon.php,...
Without your source URL, I can't make more test.

**Comment by kferrano** [comment]
[output spotter-daemon.php](https://pastebin.com/1NBi7vyc)
[MAP](http://map.fswire.net/)

**Comment by Ysurac** [comment]
Your source is working without problems for me and your map is updating on my computer. Like ident NWA8875.
Maybe you was checking a plane that is not updated ?

**Comment by kferrano** [comment]
Ok updated apparently already.
Which file is responsible for the update or where is the intervall one?

**Comment by Ysurac** [comment]
Refresh is set by **$globalMapRefresh** in *require/settings.php*. This load live-geojson.php.
