### ISSUE TITLE
Unbelievable number of aircraft

### ISSUE THREAD

**Issue by kferrano** [Ysurac/FlightAirMap#306]
We have 44 aircraft on the map, we do not believe that this figure is right, because some aircraft fly, but the position is not updated. Is there a possibility the aircraft on the map to resten sodas first no longer there and the "spotter-deamon" or which file does, which can set aircraft again.

**Comment by Ysurac** [comment]
On 2D or 3D map ?
If I have data from the source that are updated (at least the time), I keep flights on screen.

**Comment by kferrano** [comment]
2D

**Comment by Ysurac** [comment]
The time on screen is defined by **$globalLiveInterval** in *require/settings.php*.

**Comment by kferrano** [comment]
What would be the most ideal as timer?
We have it at standard 200

**Comment by Ysurac** [comment]
I have it at 400, so 200 should be ok.

**Comment by kferrano** [comment]
The strange I stop the aircraft number since yesterday evening has not changed but it updated with some the position, but not at all some stand on the ground and move since yesterday not at all others are in the air and are reset each time.

**Comment by Ysurac** [comment]
Could you give me the result in MariaDB/MySQL of:

    SELECT * FROM spotter_live ORDER BY date DESC LIMIT 50;

**Comment by kferrano** [comment]
This table we emptied yesterday evening times because we thought it would go again, it was not so.

The command I can not run straight, because I have just no database access, but I meld me as soon as I have the info

**Comment by Ysurac** [comment]
Should be better in latest commit, at least if date in phpvms source is in UTC format...
Else I will have to define an option with source timezone.

**Comment by Ysurac** [comment]
You may have to truncate spotter_live table to see that it's working, else wait 200s.

**Comment by kferrano** [comment]
Now he says that he has discovered 5, but I see of the 5 only one and the aircraft which were alluded the whole time (which fly on really fly since I see it in the stream) are now also no longer there

**Comment by kferrano** [comment]
Now there are only 14 aircraft (credible) but I only see one

**Comment by kferrano** [comment]
`SELECT * FROM spotter_live ORDER BY date DESC LIMIT 50;`
[PDF](https://www.file-upload.com/ppmufhka80xy)

**Comment by Ysurac** [comment]
I will make some test. I revert previous commit, not working with your source, it's not UTC. I think I will have to add a timezone variable for phpVMS...

**Comment by kferrano** [comment]
Ok, I wait until you have something new.
Have changed again in the daemon-spotter.php like you

**Comment by Ysurac** [comment]
I added a timezone option by source in latest commit. Should be better.

**Comment by kferrano** [comment]
Do I need to run the install / index.php again? Or where do I set the time zone?

**Comment by Ysurac** [comment]
You need to run **install/index.php** each time you update FlightAirMap. There is now a new timezone option for each source.

**Comment by kferrano** [comment]
This looks kind of wrong
[IMAGE](http://prntscr.com/ffkdfg)

**Comment by Ysurac** [comment]
It's only displayed multiple times, not a big problem... And your source is not in UTC timezone

**Comment by kferrano** [comment]
i found my timezone.
I just noticed something else and I have entered the key but the layers are not there and the key is not synonymous in the settings.php

[IMAGE1](http://prntscr.com/ffkjoz)

[IMAGE2](http://prntscr.com/ffkmb4)

**Comment by Ysurac** [comment]
Fixed in latest commit.

**Comment by kferrano** [comment]
Thanks, goes.
How do i restart the daemon-spotter.php?
Plesk runs this file every minute

**Comment by Ysurac** [comment]
If it's running by cron (and **$globalDaemon** is set to **FALSE**), it's restarted at each run.

**Comment by kferrano** [comment]
Undefined Index class.spotterimport.php
[IMAGE](http://prntscr.com/ffp5ht)

**Comment by MrDalle** [comment]
any idea on this issue? my plesk keeps spamming with emails.. :D

`PHP Notice:  Undefined index: datetime in /var/www/vhosts/fswire.net/map.fswire.net/require/class.SpotterImport.php on line 134`

**Comment by Ysurac** [comment]
Fixed in latest commit
