### ISSUE TITLE
"Aircraft Detected" as a PHP variable

### ISSUE THREAD

**Issue by kferrano** [Ysurac/FlightAirMap#308]
Is it possible to pass the "Aircraft Detected" number into a PHP variable to include it on a website?
[IMAGE](https://prnt.sc/fghhsj)
Do not let the 130 irritate, in this place is the "Aircraft Detected" number.

**Comment by Ysurac** [comment]
In latest commit, I added an option to get aircrafts detected number using the url **search-ajax.php?ask=aircraftsdetected**
