### ISSUE TITLE
No see Planes

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#31]
OK Ycarus the installation is correct, The cron is good the tables are data to ivao correct, and statictis are gooddd.... see you...

![captura2](https://cloud.githubusercontent.com/assets/4571086/7885869/b778aa8a-0626-11e5-886b-5cd29e8bd540.JPG)

But in home no see planes..

![captura](https://cloud.githubusercontent.com/assets/4571086/7885910/e8258126-0626-11e5-9aba-f72b9a0998b3.JPG)

any ideas?

Thanks

**Comment by Ysurac** [comment]
What **live/geojson** return in your browser ?

**Comment by tonkepen100** [comment]
Sorry, but that's not it, not as it looks

**Comment by Ysurac** [comment]
I need to know what **http://yourwebsite/live/geojson** return.

**Comment by tonkepen100** [comment]
![captura](https://cloud.githubusercontent.com/assets/4571086/7886180/9499f81e-0628-11e5-9571-14d99b096706.JPG)

page in white

**Comment by Ysurac** [comment]
Could you check log of Apache ?

**Comment by tonkepen100** [comment]
Jaajajaja Ycarus the end you have determined to learn programming and you're gonna get, because every time you put the most complicated busyness overtakes me.

Take that to the truth is I do not look at it that.

http://airpiro.ovh/cpanel 

user:  airpiro
pass:   Tonique1962@

Thanks my friend


                

 
  
Tonique de la Peña
  Staff Piro.biz
  tonkepen@gmail.com 
 
  Piro.biz
  50001-Zaragoza · Spain
  admin@piro.biz  · piro.biz
  Resellers,Diseño Web,Aplicaciones Informaticas.
   TeamSpeak3:ts.piro.biz 
              

    
   
 
  No me  imprimas si no es necesario. Protejamos el medio ambiente
  
 
 
 
From: Ycarus
Date: 2015-05-29 17:45
To: Ysurac/FlightAirMap
CC: Tonique
Subject: Re: [FlightAirMap] No see Planes (#31)
Could you check log of Apache ?

**Comment by Ysurac** [comment]
I deleted your message. You must change your login and password now.

**Comment by Ysurac** [comment]
Fixed in commit 2b35587fa657d815d22bd0a3b34e68d773af8d1c

**Comment by tonkepen100** [comment]
Goodddddddd i see planes, Ysurac , OLEEEEEEEE thanks

**Comment by c0by1** [comment]
Ysurac is god like. ^^

**Comment by Ysurac** [comment]
It's fun to see all those IVAO flights.

**Comment by tonkepen100** [comment]
tonkepen@gmail.com sent you an invitation to join MEGA.\n\n";

--- Message from user: ---
Hola, únete a mi en MEGA y accede a almacenamiento y comunicaciones
encriptadas. ¡50 GB gratis!
---

Please create your free MEGA account by clicking on the following
link:\n\n";
https://mega.nz/#newsignupcmVwbHkrMDA0NWJmY2UzN2YxMTg1YjM0MGRiMWIyMGE5MTY5OTdlYmZiOWIwYTE0MjIxOTMwOTJjZjAwMDAwMDAxMTE4MDRiOWY5MmExNjljZTA0ZWE2MTYyQHJlcGx5LmdpdGh1Yi5jb21oQMhKytGlHw

Best regards,

Team MEGA
