### ISSUE TITLE
GEOID Error

### ISSUE THREAD

**Issue by kferrano** [Ysurac/FlightAirMap#311]
`Can't calculate geoid : Exception: Can't open /var/www/vhosts/fswire.net/map.fswire.net/require/../data/egm96-15.pgm in /var/www/vhosts/fswire.net/map.fswire.net/require/class.GeoidHeight.php:47 Stack trace: #0 /var/www/vhosts/fswire.net/map.fswire.net/require/class.SpotterImport.php(53): GeoidHeight->__construct() #1 /var/www/vhosts/fswire.net/map.fswire.net/require/class.ACARS.php(16): SpotterImport->__construct(Object(PDO)) #2 /var/www/vhosts/fswire.net/map.fswire.net/require/class.Spotter.php(202): ACARS->__construct(Object(PDO)) #3 /var/www/vhosts/fswire.net/map.fswire.net/require/class.SpotterLive.php(530): Spotter->getDataFromDB('SELECT spotter_...', Array, '', true) #4 /var/www/vhosts/fswire.net/map.fswire.net/aircraft-data.php(41): SpotterLive->getLastLiveSpotterDataById('BER0015BERTT000...') #5 {main}`
[IMAGE](http://prntscr.com/fhilq1)

**Comment by Ysurac** [comment]
run **update_db.php**
