### ISSUE TITLE
Map no longer works

### ISSUE THREAD

**Issue by kferrano** [Ysurac/FlightAirMap#316]
Since yesterday's update, the map no longer works
[MAP](http://map.fswire.net/)

**Comment by Ysurac** [comment]
Your mapquest key seems to not be defined and your default map is mapquest.

**Comment by kferrano** [comment]
Simply change the map to another, then display it. What is the problem is that the aircraft is no longer displayed

**Comment by kferrano** [comment]
Have done with the mapquestkey

**Comment by Ysurac** [comment]
No flights are detected, check that **spotter-daemon.php** is running.

**Comment by kferrano** [comment]
Yes, the running, these have also run again manually

**Comment by Ysurac** [comment]
Check **spotter-daemon.php** output.

**Comment by kferrano** [comment]
You mean hope times the daemon-spotter.php because a spotter-daemon.php does not exist
I hope you mean this output
`Connecting...
Connect to all...
Connected!
SCAN MODE`

**Comment by Ysurac** [comment]
What lines do you have after that ?

**Comment by kferrano** [comment]
no lines

**Comment by Ysurac** [comment]
You have a source defined ?

**Comment by kferrano** [comment]
What do you mean exactly?

**Comment by Ysurac** [comment]
What is the value of **$globalSources** in *require/settings.php* ?

**Comment by kferrano** [comment]
`$globalSources = array(array('host' => 'I HAVE MADE AWAY','port' => '80','name' => '','format' => 'auto','sourcestats' => FALSE,'noarchive' => FALSE,'timezone' => 'Europe/Paris','callback' => FALSE));
`

**Comment by Ysurac** [comment]
Fixed in latest commit.

**Comment by kferrano** [comment]
works again.
