### ISSUE TITLE
globalTimezone

### ISSUE THREAD

**Issue by kferrano** [Ysurac/FlightAirMap#317]
he does not enter the globalTimezone into the settings
[IMAGE](http://prntscr.com/flpp8d)

**Comment by Ysurac** [comment]
Schedules aircraft don't use timezone, it's what I get on airlines websites (or alliance PDF), often based on departure airport timezone. Schedule part need some work but airlines doesn't really give schedules easily...

Timezone in settings is fixed in latest commit.
