### ISSUE TITLE
Inaccurate Flight Plans

### ISSUE THREAD

**Issue by koliha** [Ysurac/FlightAirMap#326]
Most flight plans (when pulled) are correct, but there are quite a few that come up with stale data?  I think one of them that I checked was listing info for a flight that occured ~3hr ago on the web interface.  I was questioning the sources that were in the array (within settings.php) so I removed 2 of 4 (leaving behind flightradar24 and flightaware).

Still seeing the issue though?

Example:
![screen shot 2017-07-07 at 9 06 47 pm](https://user-images.githubusercontent.com/20598387/27981360-c097ae5e-6358-11e7-8471-1451dffaa120.png)
![screen shot 2017-07-07 at 9 06 37 pm](https://user-images.githubusercontent.com/20598387/27981363-c3d70f60-6358-11e7-8bb0-946859329553.png)
![screen shot 2017-07-07 at 9 06 25 pm](https://user-images.githubusercontent.com/20598387/27981364-c6997a1c-6358-11e7-806b-10b2906aad3a.png)

**Comment by Ysurac** [comment]
Schedules sources are not called each times.
KATL is a route stop, I have an error here.

**Comment by Ysurac** [comment]
In fact I have correct flight plan in DB, I think it's because you didn't use web install, you have some old schedule source in table.

**Comment by Ysurac** [comment]
You can run in SQL:

  TRUNCATE routes;

And then run **scripts/update_db.php** again.

**Comment by koliha** [comment]
Truncating the routes tables seems to have solved this -- thanks :)
