### ISSUE TITLE
Database updates

### ISSUE THREAD

**Issue by kferrano** [Ysurac/FlightAirMap#327]
If you make database updates, I have to delete the respective table or update it me automatically when I run the install?

**Comment by Ysurac** [comment]
All updates are done via install script. But for the latest airlines update I doesn't yet made a schema update, I will maybe update it via update_db.php script. For now you can insert the latest .sql if you use a real flights source and don't want to wait.

**Comment by Ysurac** [comment]
Airlines table now updated via *update_db.php* script.
