### ISSUE TITLE
Real Flight

### ISSUE THREAD

**Issue by DemonRem** [Ysurac/FlightAirMap#328]
sorry for a stupid question but this tool can follow real flights ? if yes how i can do that?

**Comment by Ysurac** [comment]
Yes. But you need to have a source for real flights.
* For commercial flights (with antenna and an usb key), you can use ADS-B: https://github.com/Ysurac/FlightAirMap/wiki/ADS-B
* For private small flights (and without material), you can use Flarm from OGN network: https://github.com/Ysurac/FlightAirMap/wiki/Glidernet

**Comment by DemonRem** [comment]
seems like when i press on plane update settings its jump backward

**Comment by Ysurac** [comment]
Where ?

**Comment by DemonRem** [comment]
when i turn on the aircraft animated per update the animation going back sometime then jump forward

**Comment by Ysurac** [comment]
Animation is the result of estimation of aircraft position based on speed, heading,...
When there is data refresh last know position is displayed.
I could always display estimated position but... it's not the case yet, maybe later.

**Comment by DemonRem** [comment]
so in this case its not yet stable

**Comment by Ysurac** [comment]
It's in beta...
And animation between update in 2D mode is not a major feature for me.
I opened issue #329 to follow work on this. You are free to contribute, it's an opensource project.
