### ISSUE TITLE
connect Db phpvms

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#33]
Good to know that already works perfectly taking data wazzup, my question now is this ...

In my website http://piro.biz grabs data from registrants of wazzup file and sent to a database, which sends the data to the Web itself.

It is possible that such data grab db and send them FlightAir Map ?.

Osease in the config file, which you would have to put so that only data cojiera db my website.

Thanks Ysurac

PD. It is storing data that is phpvms db, with some changes ...

![captura1](https://cloud.githubusercontent.com/assets/4571086/7896333/eb874748-06b5-11e5-9323-888e44b7e474.JPG)

Thanks again

**Comment by Ysurac** [comment]
I will not use DB directly, I need a feed : a JSON, a txt in wazzup file format, a CSV,...

**Comment by tonkepen100** [comment]
ahh ok, I mean then I understand that the data we have in this db, would have to send them to a txt file, like wazzup.txt, but our right ?.
