### ISSUE TITLE
Remove 30min disconnect

### ISSUE THREAD

**Issue by MrDalle** [Ysurac/FlightAirMap#334]
Hey!

how can i remove the timer so pilots dont disconnect after 30mins?

We have some Twitch streamer using it for live telemetry. Would be awesome to get a hint!

**Comment by Ysurac** [comment]
Set **$globalMapIdleTimeout** to 0. It's also available in install page as *Map idle timeout*.

**Comment by MrDalle** [comment]
Must over saw that.. thanks anyways! working!
