### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by rkshinde** [Ysurac/FlightAirMap#336]
Hello, 

We are getting below error when trying to run the install/index.php 

PHP Fatal error:  Can't use method return value in write context in /var/www/html/flightairmap/require/class.Accident.php on line 323

We are on PHP 5.4.16, please let me exactly what causing this.

**Comment by rkshinde** [comment]
I have resolved this by below fix. 
changed 
if (empty($Image->getSpotterImage($cr['registration']))) {

to 

$SpotterImage=$Image->getSpotterImage($cr['registration']);
                if(empty($SpotterImage)) {

Couple of permissions issue on require/settings.php and install/tmp

**Comment by Ysurac** [comment]
This is fixed in commit 6ab92f3a823edc28659d0f9239eca991cc167d6c
Permissions are checked by *install/index.php* script.

**Comment by rkshinde** [comment]
Nice .. thanks for the update
