### ISSUE TITLE
Initial Zoom

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#34]
Hello again ...

The point is this when I open the web map with this zoom out ...

![captura1s](https://cloud.githubusercontent.com/assets/4571086/7896400/40f60f86-06b9-11e5-83f5-e0b09bf1adcc.JPG)

there would be some way to tell you want to display zoom to load the map ?.

for example instead of the first.

![captura2s](https://cloud.githubusercontent.com/assets/4571086/7896405/45d51f06-06b9-11e5-837c-4b3949bdb740.JPG)

thanks

**Comment by c0by1** [comment]
i agree. ^^

**Comment by Ysurac** [comment]
I agree too.
OK I will add an option...

**Comment by Ysurac** [comment]
Done in commit 3c0798d5a751b84a5fcb4a4386abb2781e101dfa
