### ISSUE TITLE
aircraft.json

### ISSUE THREAD

**Issue by nzradar** [Ysurac/FlightAirMap#342]
Using aircraft.json as input I seem to get no flight number.

![fm1](https://user-images.githubusercontent.com/3992918/30892481-7ff51dc8-a395-11e7-857c-71723d6386c6.jpg)

The other thing I notice is the styling of some of the pages hanging off the Statistics page, so when viewing Statistics and then selecting aircraft or registration the page is not looking too good!

![fm2](https://user-images.githubusercontent.com/3992918/30892535-be68f1c4-a395-11e7-8bd2-7847b5dd19fd.jpg)

**Comment by nzradar** [comment]
Perhaps I should add that I'm using piaware on a rpi3 as the data source and Xubuntu to host flightairmap.  By changing to port 30003 sourced data the flight info is provided OK but I lose the flightaware MLAT!  Perhaps a mismatch of the json data?

**Comment by Ysurac** [comment]
* Last commit fix ident for aircraft.json format. Sorry.
* What is the value of **$globalURL** in *require/settings.php* (or *Site directory* in install script) and what is the url of FlightAirMap ?
I think it's the problem: if your url is http://127.0.0.1/flightairmap/ then $globalURL must be /flightairmap
I will add an autodetect for this value.

**Comment by Ysurac** [comment]
If I remember correclty, for MLAT on 30003 port, you need to add **--forward-mlat** to Dump1090.

**Comment by nzradar** [comment]
$globalURL is '.'

**Comment by nzradar** [comment]
aircraft.json fix is perfect, than you very much :+1:

**Comment by Ysurac** [comment]
**$globalURL** should not be a '.'. Empty if no subdirectory in path or the subdirectory name.

**Comment by nzradar** [comment]
OK, I have set the $globalURL to the full URL of my flighairmap and all is well now.  Thanks for the prompt support.

**Comment by Ysurac** [comment]
You only need to put */flightairmap*. No need for the full URL.

**Comment by nzradar** [comment]
OK, will try that soon.

**Comment by TomMuc1** [comment]
> I think it's the problem: if your url is http://127.0.0.1/flightairmap/ then $globalURL must be /flightairmap
I will add an autodetect for this value.

the autodetect fails and auto-inserts '/install/' as root what of course wont work ...

**Comment by Ysurac** [comment]
Should be fixed in latest commit.

**Comment by TomMuc1** [comment]
you are unbelievable :) hope the way and words i post possible bugs is ok for you. if you want more/different way of input just let me know ...
