### ISSUE TITLE
Some aircraft type names are incorrect

### ISSUE THREAD

**Issue by daviessm** [Ysurac/FlightAirMap#343]
In FlightAirMap/db/aircraft.sql, for example:

    (6,'A310','Polaris','AIRBUS','http://www.airbus.com/aircraftfamilies/out-of-production/a310/','generic_J2H.png','Landplane','Jet',2,'H',NULL),
    (8,'A319','VC-1 ACJ','AIRBUS','http://www.airbus.com/aircraftfamilies/passengeraircraft/a320family/','A320.png','Landplane','Jet',2,'M',NULL),
    (19,'A359','Prestige (A-350-900)','AIRBUS','http://www.airbus.com/aircraftfamilies/passengeraircraft/a350xwbfamily/','generic_J2H.png','Landplane','Jet',2,'H',NULL),
    (49,'B712','Business Express','BOEING','http://www.boeing.com/boeing/commercial/717/index.page?','generic_J2M.png','Landplane','Jet',2,'M',NULL),
    (54,'B732','CT-43','BOEING','http://www.boeing.com/boeing/commercial/737family/index.page','B73X.png','Landplane','Jet',2,'M',NULL),
    (59,'B737','BBJ','BOEING','http://www.boeing.com/boeing/commercial/737family/index.page','B73X.png','Landplane','Jet',2,'M',NULL),
    (60,'B738','BBJ2','BOEING','http://www.boeing.com/boeing/commercial/737family/index.page','B73X.png','Landplane','Jet',2,'M',NULL),
    (61,'B739','BBJ3','BOEING','http://www.boeing.com/boeing/commercial/737family/index.page','B73X.png','Landplane','Jet',2,'M',NULL),
    (68,'B752','C-32','BOEING','http://www.boeing.com/boeing/commercial/757family/index.page','B752.png','Landplane','Jet',2,'M',NULL),

It looks strange with EasyJet flying VC-1s and Ryanair BBJs! Is there a better list that you could grab from somewhere?

**Comment by Ysurac** [comment]
The list come from official icao doc8643.
One ICAO can be more than one aircraft model, I always choose the latest one. So nothing is wrong here.
I can choose always the first one, or maybe concatenate all models value but this will be a long text.

**Comment by daviessm** [comment]
That makes sense. FlightAware (not sure about others) provide an API to retrieve this information and their responses seem to be sensible - would it be possible to use this?

    {'AircraftTypeResult': {'description': 'twin-jet', 'type': '737-800', 'manufacturer': 'Boeing', 'engine_type': 'jet', 'engine_count': 2}}

**Comment by Ysurac** [comment]
Not possible. Data are not free.
And it's the same problem: they choose a data arbitrary from doc8643.

**Comment by daviessm** [comment]
They do, but it looks like they've manually selected the most common. Since the FlightAware API is used for route information, if an API key is entered it could also be used for this to overwrite aircraft types as they're seen? I might create a pull request for this when I get some time.

**Comment by Ysurac** [comment]
I concatenate aircraft type in latest commit. At least we now have all possible type of an aircraft.

**Comment by Ysurac** [comment]
Now this should display must common aircraft model but others aircraft models by highlight on the link.
I will make this on all pages tomorrow. I think it's the best solution.

**Comment by daviessm** [comment]
Looks good! How did you decide the most common? Manually?
