### ISSUE TITLE
Translation: plural of aircraft in English is aircraft

### ISSUE THREAD

**Issue by daviessm** [Ysurac/FlightAirMap#344]
A few places in the application have the word "aircrafts" used in English, where the correct word is "aircraft" in both singular and plural.

https://english.stackexchange.com/questions/255727/why-is-the-plural-of-aircraft-not-aircrafts

**Comment by Ysurac** [comment]
Thanks, it's fixed now.

**Comment by daviessm** [comment]
Thought you were resting for the weekend now! Thanks.
