### ISSUE TITLE
FlyBe (BEE) logo is wrong

### ISSUE THREAD

**Issue by daviessm** [Ysurac/FlightAirMap#346]
Happy to report this upstream if you can tell me where you generate the airline list from, but the logo should be the one from [here](https://brandfolder.com/flybe) not the silly bee clipart.

**Comment by Ysurac** [comment]
Most of airlines logo come from wikipedia. I think I add an error for this one (This bee was fun)
Fixed in latest commit.

**Comment by daviessm** [comment]
Brilliant! Will that update when update_db.php is run or does it need a manual update?

**Comment by Ysurac** [comment]
This need a git pull
