### ISSUE TITLE
Enhancement: Projected route lines as Great Circle routes

### ISSUE THREAD

**Issue by daviessm** [Ysurac/FlightAirMap#348]
It would be nice if the dashed route line to a plane's final destination was projected along the great circle route rather than a straight line.

**Comment by Ysurac** [comment]
True. Will be available soon.

**Comment by daviessm** [comment]
If there's anything you'd like me to help with I'm a developer/DBA by day, let me know and I'll see what I can do!

**Comment by Ysurac** [comment]
Done in latest commit.
You can always submit pull requests :)
