### ISSUE TITLE
On /statistics/registration: error : SQLSTATE[42S22]: Column not found: 1054 Unknown column 'registration_count' in 'order clause'

### ISSUE THREAD

**Issue by daviessm** [Ysurac/FlightAirMap#349]
Page shows data, but above the graph this error is shown:

    MOST COMMON AIRCRAFT REGISTRATIONS
    Below are the Top 10 most common aircraft registrations.
    
    error : SQLSTATE[42S22]: Column not found: 1054 Unknown column 'registration_count' in 'order clause'

**Comment by daviessm** [comment]
Looks like lines 465, 466, 477, 478 in class.Stats.php should be order by s.cnt desc. Haven't set up a local repository yet to do a PR!

**Comment by Ysurac** [comment]
thanks
