### ISSUE TITLE
List/Table of Aircrafts on Map View

### ISSUE THREAD

**Issue by TomMuc1** [Ysurac/FlightAirMap#350]
the only feature i miss in FlightAirMap and that apps like VirtualRadarServer and others offer is a list of all aircrafts (or ships/whatever) messages are received with data like distance, altitude, callsign, message-rate, etc.

if there is a chance to add this i could make a mockup in photoshop how this could look like :)

cheers
tom

**Comment by Ysurac** [comment]
All flights available are in **Currently** page. I will not add a list like that on the map.

**Comment by TomMuc1** [comment]
maybe it's just me - if so no question you cannot add everything that just a single users desire were

**Comment by Ysurac** [comment]
And this would be too much data on the map page, It's why all is on **currently** page.

**Comment by wohali** [comment]
I'd love to see an optional popup window with this info in a more compact form. "currently" page is too hard to scroll through.
