### ISSUE TITLE
Airline not showing up in flightid-overview

### ISSUE THREAD

**Issue by gleven** [Ysurac/FlightAirMap#352]
While showing the flight details, on top of page i see 
**_UNDEFINED INDEX: AIRLINE_NAME IN /VAR/WWW/FLIGHTAIRMAP/FLIGHTID-OVERVIEW.PHP ON LINE 133_**
and under the photo i see also this:
**_Notice: Undefined index: airline_name in /var/www/flightairmap/flightid-overview.php on line 348_**

**Comment by Ysurac** [comment]
What source do you use ?

**Comment by gleven** [comment]
aircraft.json from a remote dump1090

**Comment by Ysurac** [comment]
I think it's solved now

**Comment by gleven** [comment]
Now i get messages all over the place 
Notice: Undefined offset: 0 in /var/www/flightairmap/require/class.Spotter.php on line 425

Notice: Undefined offset: 0 in /var/www/flightairmap/require/class.Spotter.php on line 426

Notice: Undefined offset: 0 in /var/www/flightairmap/require/class.Spotter.php on line 427

Notice: Undefined offset: 0 in /var/www/flightairmap/require/class.Spotter.php on line 428

Notice: Undefined offset: 0 in /var/www/flightairmap/require/class.Spotter.php on line 429

Notice: Undefined offset: 0 in /var/www/flightairmap/require/class.Spotter.php on line 430

Also the same in spotter tv

**Comment by Ysurac** [comment]
What is the value of **$globalNoAirlines** in *require/settings.php* ?

**Comment by gleven** [comment]
$globalNoAirlines = TRUE;

**Comment by Ysurac** [comment]
Should be fixed in latest commit.
But why you don't want to see airlines ? This option is only for source where airlines is not needed (private aircraft, glider,...)

**Comment by gleven** [comment]
It's fixed now. 
I was playing with the options in the settings.php  I'm a full time developer and cannot resist in checking :)

**Comment by Ysurac** [comment]
lol ok
