### ISSUE TITLE
Antenna icon element is injected every second

### ISSUE THREAD

**Issue by gleven** [Ysurac/FlightAirMap#354]
While inspecting the live map, i realized that one antenna icon element is added every second

<img src="/images/antenna.png" class="leaflet-marker-icon leaflet-zoom-animated leaflet-interactive" tabindex="0" style="margin-left: -8px; margin-top: -9px; width: 16px; height: 18px; transform: translate3d(776px, 509px, 0px); z-index: 509;">

I think this is why my browser crashes after an hour of monitoring the live traffic.

**Comment by Ysurac** [comment]
Fixed in latest commit, but I think you have a very short **$globalLiveInterval** setting in *require/settings.php*.

**Comment by gleven** [comment]
Fixed.
Indeed i have short live interval setting. (1 sec) 
What is the purpose of this setting?

**Comment by Ysurac** [comment]
**$globalMapRefresh** is in second when the map refresh
**$globalLiveInterval** is number of seconds used to put a flight as "live".

**Comment by gleven** [comment]
I actually had the $globalMapRefresh as 1 sec and the $globalLiveInterval left to 200.
It's fixed anyway
