### ISSUE TITLE
Statistics do not work

### ISSUE THREAD

**Issue by gleven** [Ysurac/FlightAirMap#355]
It seems that by default the filtering box is set to airline ZZ which gives the result of ALL instead. 
When something else is selected , including ALL, nothing is returned.

**Comment by Ysurac** [comment]
By default this is not set to ZZ, but to all that return all.
If you use archive mode only detected airlines are shown and stats are updated via *scripts/update_db.php*.

**Comment by gleven** [comment]
I don't use archiving . Sometimes when selecting ALL, it only returns the military flights

**Comment by gleven** [comment]
This is what i see when opening statistics:

![image](https://user-images.githubusercontent.com/31960612/31185119-dd56e0e8-a933-11e7-9c89-95adb1475038.png)

And after selecting ALL i see this:
![image](https://user-images.githubusercontent.com/31960612/31185194-09e0cb7e-a934-11e7-8e6b-f0f6c36d1133.png)

**Comment by Ysurac** [comment]
Should be ok now.
