### ISSUE TITLE
List of minor bugs, missings or inexplicit behavior 2

### ISSUE THREAD

**Issue by TomMuc1** [Ysurac/FlightAirMap#359]
3d model for HARBIN C-99 (E145) with BMI logo is always displayed in muuuch bigger size than all other aircraft models

<img width="1544" alt="bildschirmfoto 2017-10-05 um 21 24 46" src="https://user-images.githubusercontent.com/31601862/31248321-a9f71174-aa13-11e7-8af6-163881ea31d1.png">

**Comment by Ysurac** [comment]
Fixed when you run **scripts/update_db.php**.

**Comment by TomMuc1** [comment]
works :)

small map window in lower rirgt corner does not zoom to aircraft position and does not follow selected aircraft -> nearly zero orientation in 3d mode for user when watching a selected aircraft.

**Comment by TomMuc1** [comment]
3d model for twin engine business jet does sit correctly on path - see pix

<img width="1545" alt="bildschirmfoto 2017-10-05 um 22 15 21" src="https://user-images.githubusercontent.com/31601862/31250394-f4d84670-aa1a-11e7-87af-bd9d1d344686.png">

**Comment by Ysurac** [comment]
minimap fixed

**Comment by TomMuc1** [comment]
wow awesome - and how fast you are!!! the zoom level now is a little high. is there a variable and in which file i can manipulate this on my own. and then when i found the sweet spot give you the number i used?

**Comment by Ysurac** [comment]
in *js/cesium-minimap.js* line 83

**Comment by TomMuc1** [comment]
whatever numbers i apply here(line 84) the zoom in minimap when aircraft is selected does not change

    	    pos.height = Math.max(Math.min(pos.height,2200000) * 2, 2000);

**Comment by TomMuc1** [comment]
the way 'sun shadow' is rendered is not nice nor in any way realistic

![bildschirmfoto 2017-10-06 um 14 30 00](https://user-images.githubusercontent.com/31601862/31277828-17dba5bc-aaa3-11e7-9d3c-a34690ed4f23.png)


![bildschirmfoto 2017-10-06 um 14 29 36](https://user-images.githubusercontent.com/31601862/31277833-1dde4dca-aaa3-11e7-88ad-4a42a7f55da4.png)

**Comment by Ysurac** [comment]
Again I don't see problem with sun shadow here. It's realistic for me. You can don't like sun shadow but it's another story.

**Comment by TomMuc1** [comment]
ok - then we call it 'i don't like this way of sun shadow' :)

**Comment by TomMuc1** [comment]
but what about the mini map zoom above? i tried to alter the three numbers in line 84 since found no number in line 83 - but this did not change the zoom level in mini-map ...

**Comment by Ysurac** [comment]
This change the height of the "camera", so it's really the "zoom" level.

**Comment by TomMuc1** [comment]
ah - ok - and is there an easy option to hard code a different zoom level? as the map now looks a little unsharp and moreover shoes to small aerea to really know where you are. it is really great now that this mini map center follows the aircraft - but if it would show say 200 x 200 km i think about this  the sweet spot were to have the 'big picture'

**Comment by Ysurac** [comment]
An easy option: no. But all can be dev.

**Comment by TomMuc1** [comment]
ok - but since a day has just 24h not really all is possible. and i have seen many times now how fast you add/alter options for users like me! i'm sure when you say there is no easy option then there is definitely no easy option. so many thanks for reply and for having a look into this mini-map-thing :)

**Comment by Ysurac** [comment]
I'm working on some features for 3D mode and I try to fix 3D models, this take a long time...

**Comment by TomMuc1** [comment]
ok - but i'd spend not too much time with the models. you have already much more aircrafts in flightairmap than i saw in fr24 (i know i'm not allowed to compare). i'd simply threw out the ugly ones with holes and other defects - and use just the shiny ones and use one nice as a dafault for thoses were no nice model is availible at the moment ...

**Comment by TomMuc1** [comment]
btw - did you see this duesseldorf airport yesterday - wohooo https://www.youtube.com/watch?v=hTT_FpC768M

**Comment by TomMuc1** [comment]
YOU ARE THE BEST!!! thank you sooo much for adding this cool new feature :)
'Only display selected flight on 3D mode'

that makes me super happy!!!

**Comment by TomMuc1** [comment]
now fam runs in 3d using less memory, cpu and graphic-card than fr24 and moreover while fma shows higher resolution 3d satellite background image. and i like your start into 3d-mode way more than this silly ground view with the circling to the aircraft fr24 does. i know i don't have to compare :)))

**Comment by TomMuc1** [comment]
now load in 3d mode is so low that my newer macbook not even starts to use the dedicated gpu but remains using the intel onboard low-power gpu! and even when i'm in 3d-mode i can switch in sidebar-menu to show all! great job!!!

**Comment by Ysurac** [comment]
Now I'm really out for the week-end :)

**Comment by TomMuc1** [comment]
yes - and i wish you the best thinkable weekend :)
cheers

**Comment by TomMuc1** [comment]
- instead of a380 model b747 shows up
- require/settings.php $globalAircraftSize - when set to any size e.g. '25' all aircrafts on map do not move any more
- helicopter model path slightly off axis

**Comment by TomMuc1** [comment]
Only display selected flight on 3D mode - runs flawless, fast and instantly without any bugs :1st_place_medal:

**Comment by Ysurac** [comment]
* fixed
* fixed
* fixed

**Comment by TomMuc1** [comment]
- worx :)
- worx :)
- is this a new blue helicopter now? starts very big zoomed in in 3d?!
thanks :)

**Comment by TomMuc1** [comment]
an additional question in js/map.3d.js.php i set 'shadows : false' but despite that the a380 shows obviously some sort of very nice and smooth shading? see pictures below ...

![bildschirmfoto 2017-10-09 um 14 10 48](https://user-images.githubusercontent.com/31601862/31339215-644cf8ae-ad02-11e7-8510-a0895006bfa9.png)

![bildschirmfoto 2017-10-09 um 14 10 58](https://user-images.githubusercontent.com/31601862/31339224-6e06a7be-ad02-11e7-848f-6d02588f3391.png)

![bildschirmfoto 2017-10-09 um 14 11 07](https://user-images.githubusercontent.com/31601862/31339242-7c550acc-ad02-11e7-9374-f049affe3692.png)

**Comment by Ysurac** [comment]
* Yes. No idea why it's bigger... Need more tests.
* The model have a "sun" source of light in it.

**Comment by TomMuc1** [comment]
aah - that's why - looks very nice and natural! unbelievable how big the differences in quality the different models are ...

**Comment by TomMuc1** [comment]
anyways - the guy who made the a380 model did a great job :)

**Comment by TomMuc1** [comment]
new 3d sun shadow install doest not work. shows 'map3dshadows' instead of true or false in install website and then overwrites existing map3dshadows = FALSE in settings.php

**Comment by Ysurac** [comment]
Fixed in latest commit.
If you don't have to set $globalinstalled to TRUE, anybody that access your website can change settings...

**Comment by TomMuc1** [comment]
thanx :)

how about a simple password and password-field in install.php that is stored as md5-hash in settings.php or database

**Comment by TomMuc1** [comment]
would be great if there were:
- a really nice helicopter model
- a really nice sailplane model
- a really nice single engine prop private aircraft

any chance - are there some already existent anywhere?

**Comment by Ysurac** [comment]
If you don't like models, you can contribute ;)
And there is no single models of each type, models are based on aircraft ICAO. Only if the aircraft ICAO model is not available it use a default model of the same type. 
I also have to use as low possible polygons models, else models use too much memory.

**Comment by TomMuc1** [comment]
i did not say you should start modeling new models - and so do i ;) the question was 'are there already existing models that could be included without too much effort' e.g. from sources like this? https://grabcad.com/library/airbus-a380-4

**Comment by Ysurac** [comment]
No idea of the license, they must have many polygons, not sure I can open them in Blender,...
The screenshots are rendered, this will always be better.

**Comment by TomMuc1** [comment]
yep that were the same questions i was wondering about :) and yes - no question - over here we render all solidworks models in maxwellrender - and this is totally different to what is possible in realtime! but i thought the modeling is the by far most time consuming part - so it were maybe an option to reuse those existing models and export them to the needed format? no one over here ever used blender so i have no idea about that ...

**Comment by Ysurac** [comment]
I need to use open license.
I also use liveries when available.
And again we can have far more beautiful models, but we have the same problems as flightgear (it's why I use models from them): models must have a low number of polygons.
Else any models in glTF 1.0 or 2.0 format can be used.

**Comment by TomMuc1** [comment]
next week i look with one of our 3d guys into some of those step and solidworks files to see how complex they are. do you have a number or range of polygons that fit to flightairmap e.g. the nice a380 or b777

**Comment by Ysurac** [comment]
No idea, but file must be as small as possible.
For these models it's more nice textures than a good model.

**Comment by TomMuc1** [comment]
display actual receiver message rate in aircraft detected layer would be nice

**Comment by TomMuc1** [comment]
i know i asked this already - but now using this very cool single aircraft 3d mode since a while these two things are really inconvenient:

- in 3d i use 95% of the time satellite background - in 2d i use 95% of time map background so i have to swich the map everytime i switch between 2d and 3d
- the minimap in 3d would be a huge help to see where the aircraft flys - but the zoom factor is really too high

**Comment by Ysurac** [comment]
* rate of messages may be added later as the value already exist for stat page
* I will add a "synchronize map" option for 2D and 3D
* It's really a question of choice... I will try to make minimap zoomable

**Comment by TomMuc1** [comment]
regarding the mini-map i don't think that zoomable is really need for - if just the hard set zoom-factor would be say 2 steps lower anything were just perfect :)
