### ISSUE TITLE
db performance etc

### ISSUE THREAD

**Issue by c0by1** [Ysurac/FlightAirMap#36]
do you got a hint for better mysql performance or a good howto for maria db? mysql kills my server. got a load of 4 - 6...

**Comment by Ysurac** [comment]
Check if spotter_live and spotter_output use INNODB engine.
You can use ARCHIVE engine for spotter_archive.
You can add some index (this is done in latest .sql, but I've not yet done this in update script) : 
> ALTER TABLE spotter_output ADD INDEX(flightaware_id);
> ALTER TABLE spotter_output ADD INDEX(date);
> ALTER TABLE spotter_live ADD INDEX(flightaware_id);
> ALTER TABLE spotter_live ADD INDEX(date);
> ALTER TABLE spotter_live ADD INDEX(longitude);
> ALTER TABLE spotter_live ADD INDEX(latitude);
> ALTER TABLE routes ADD INDEX(CallSign);
> ALTER TABLE aircraft_modes ADD INDEX(ModeS);
> ALTER TABLE aircraft ADD INDEX(icao);
> ALTER TABLE airport ADD INDEX(icao);
> ALTER TABLE translation ADD INDEX(Operator);

You can also use http://mysqltuner.com/

**Comment by c0by1** [comment]
i wait for the update script.

**Comment by c0by1** [comment]
runs smoother

![image](https://cloud.githubusercontent.com/assets/5725891/7897972/51409d1a-06f1-11e5-97a5-b074651265f7.png)

**Comment by c0by1** [comment]
yeah runs smoother... only 1.0 load @ 5 min... good work...
