### ISSUE TITLE
My 2 most missed features in FlightAirMap

### ISSUE THREAD

**Issue by TomMuc1** [Ysurac/FlightAirMap#362]
i love FlightAirMap and the super-fast and responsive behavior even on older tablets. the single aircraft 3d mode is simply stunning - especially with the beautiful A380, B777 and B747 models. moreover it's cool that now it is so easy to install and use with a FlightAware setup based on lighttpd and aircraft.json!

there are two features that i really really miss from my subjective view as a flightaware feeder.

- table of all aircraft that my site live receives messages directly on the map window that holds data like: aircraft, tail number, distance, speed, altitude, message-power, message-rate, message age, time since first message from aircraft etc. (like skyview, virtualradarserver etc.)

- receiver data in map window e.g. number of aircrafts with and without position, overall message-rate

the search field could be shifted and made smaller - this way numbers for overall aircratf, aircrafts with position and actual receiver message rate could be placed in the blue top-bar. the language drop-down-menu should move to left side-bar menu because this setting mostly only one time after install will be changed. the layer for selected aircraft data should get a little slimmer and placed directly under the blue head-bar - this way it would not collide anymore with the mini-map in lower right corner.

the aircraft list on the bottom should be vertical resizable e.g. to show minnimum 5 lines up to maximum e.g. 30 lines.

alternative the same way vrs does (display list and selected aircraft data in one table on the right side would be fine too.

again - i'm superhappy to have this really cool and fully free fam now - but if the two above features were builtin in fma i could use this as my all-day software that then would replace skyview and virtualradarserver ...

thanx
tom

![fam_mockup](https://user-images.githubusercontent.com/31601862/31823691-3106e2bc-b5ad-11e7-9df0-47880bc4422e.jpg)

**Comment by Ysurac** [comment]
It collide with mini map because you have a small screen resolution ;)
There is now an option to set scaling factor for rendering, this can increase quality (and use more CPU) or decrease quality (and use less CPU).

There is now a table with visible flights bottom of the page for now. It's not finished.

**Comment by TomMuc1** [comment]
hehe - true that happend @1.440x900 what is the resolution of my old notebook but tablets often have a similar screen-res :)

the scaling factor thing seems to mess up things at the moment, as soon as i slided the to left or right - the whole machine starts to freeze while cpu nor gpu are under huge load. in addition 3d single mode out of a sudden starts to show all aircrafts and then 'game over' :)))

very very cool the table thing - when this enhancement is finished this will again be a huge advantage for this application. thanx man!

**Comment by TomMuc1** [comment]
even a browser restart with deleting all cookies/cache did not bring fma back to life ...

**Comment by Ysurac** [comment]
I will try make some CSS more screen size dependent.

Strange, scaling factor is working for me under chromium. And there is really a visual improvement when set at 2 (and it's really dirty when set at 0.5).

**Comment by TomMuc1** [comment]
used firefox and safari - both died a sudden death and moreover 3d single mode does not work since then. but hey - tomorrow is another day - so don't worry. and because anything before was just perfect - there is already a solution :)

**Comment by TomMuc1** [comment]
what would the 'scaling factor' mean or look like - what and where should then be different if my browsers wouldn't crash?

**Comment by Ysurac** [comment]
Are you sure you use the good GPU ? this only set a cookie.

In fact if it's set to 2, this render the model with scale x2 and resize it to normal. This improve visual quality of models.

**Comment by TomMuc1** [comment]
yes - was the dedicated gpu - but of course on old notebook. but even there it should run with 0.5 or 1 - because before update anything was just perfect. and again the 3d single mode that worked for weeks and until 5 minutes before update now is totally messed up ...

**Comment by TomMuc1** [comment]
i'd say there is now a bug with 3d single mode and this is the main reason for all problems ..

**Comment by TomMuc1** [comment]
yep if i just open the sidebar-menu in 3d mode and scroll down to the new slider even without touching it the aircraft disappears

**Comment by Ysurac** [comment]
Last commit reset to default value. Maybe this used too much memory for your computer.

**Comment by TomMuc1** [comment]
thanx - but nope - as i said the stunning thing was that memory/cpu/gpu/gpu-memory all was below 30/50% but the machine fully hung. i monitor those numbers 24/7 see pix

![bildschirmfoto 2017-10-24 um 21 49 13](https://user-images.githubusercontent.com/31601862/31964732-453e8c70-b905-11e7-8741-06233e648434.png)

![bildschirmfoto 2017-10-24 um 21 46 06](https://user-images.githubusercontent.com/31601862/31964739-4b2a2b76-b905-11e7-9eef-e39ceb9c1f11.png)

![bildschirmfoto 2017-10-24 um 21 46 16](https://user-images.githubusercontent.com/31601862/31964747-505f99fa-b905-11e7-8964-bcfaaa5efa9b.png)

**Comment by Ysurac** [comment]
All is set as default. So you don't have any real changes in 3D mode now.
You should check temperature or something like that...

**Comment by TomMuc1** [comment]
ok i'll see whether it works now :)
nope - i know i had once overlooked the gpu-switch-thing. but believe me hardware wise we build our own render farms, 3d workstations and heavily modify mac-pros internally - so i'm quite familiar with computer hardware :)))

**Comment by TomMuc1** [comment]
you set 2E3->3E3 but +viewer.scene.globe.tileCacheSize = 1000; was the same before and slider is still there???

**Comment by Ysurac** [comment]
I put data back. You can comment them and test if you want.
I didn't remove slider, it only set cookie, no need to remove that (and I like it).

You only don't see an aircraft, I was thinking 3D mode didn't work at all...
Are you sure the flight is still here ? What errors do you have in dev console ?

**Comment by TomMuc1** [comment]
this was after i did git pull and loaded new map.3d.js.php. nope as i said the flights now simply disappear and you see there are 56/151 aircrafts in 3d mode then. this is what messes all up and wasn't before i made the gitpull in early evening today. last git-pull before was yesterday with no updates => the commit of today messed things up - no question

**Comment by TomMuc1** [comment]
now often the aircraft in 3d mode disappears and then all aircrafts come up in 3d mode - and this never was before

**Comment by Ysurac** [comment]
It's why I need dev console errors if there is any...
You can also try to remove all cookies.
And then try to comment in js/map.3d.js options like viewer.scene.globe.maximumScreenSpaceError

**Comment by TomMuc1** [comment]
yannick - this is all full of errors - it's not possible that you don't see them in your own console?! see:

![bildschirmfoto 2017-10-24 um 22 57 46](https://user-images.githubusercontent.com/31601862/31967704-fc76fd10-b90e-11e7-9d71-e5663ca0ec30.png)
![bildschirmfoto 2017-10-24 um 22 55 01](https://user-images.githubusercontent.com/31601862/31967705-fc9deeac-b90e-11e7-9e40-eeced773a15a.png)
![bildschirmfoto 2017-10-24 um 22 57 56](https://user-images.githubusercontent.com/31601862/31967706-fcc33572-b90e-11e7-8c41-40c5a5f0fec3.png)

**Comment by Ysurac** [comment]
I don't have any errors.
Error are from cesium (and corrupt download pics). You seems to have a WebGL problem.
You use local Cesium (a clone using -recursive so js/Cesium is not empty) or distant Cesium ?
In latest commit a put again a fail if WebGL is not working correctly.

**Comment by TomMuc1** [comment]
fact is - up to 4 hours before i had zero problems - now there are problems since last commit.
this looks nice - but it already in level 1 like it was looked good enough.

![bildschirmfoto 2017-10-24 um 23 16 16](https://user-images.githubusercontent.com/31601862/31968776-91d74c2c-b912-11e7-845f-b93719736b09.png)
![bildschirmfoto 2017-10-24 um 23 12 33](https://user-images.githubusercontent.com/31601862/31968777-91f7d032-b912-11e7-9099-17485f572b68.png)
![bildschirmfoto 2017-10-24 um 23 12 11](https://user-images.githubusercontent.com/31601862/31968778-9216b394-b912-11e7-8fa4-16d276b1d8f6.png)
![bildschirmfoto 2017-10-24 um 23 11 47](https://user-images.githubusercontent.com/31601862/31968779-92399e04-b912-11e7-8c00-b56b6b4b22f6.png)

**Comment by TomMuc1** [comment]
![bildschirmfoto 2017-10-24 um 23 29 24](https://user-images.githubusercontent.com/31601862/31968988-3fd4c08e-b913-11e7-84c3-a211bc262869.png)

**Comment by TomMuc1** [comment]
you should file a patent on your computer where you always have no errors - seems to be a real magic mystery machine :)))

**Comment by TomMuc1** [comment]
![bildschirmfoto 2017-10-24 um 23 34 38](https://user-images.githubusercontent.com/31601862/31969169-f63163aa-b913-11e7-913e-2531796f3e31.png)
![Uploading Bildschirmfoto 2017-10-24 um 23.34.07.png…]()

**Comment by Ysurac** [comment]
I have some of them under Firefox, nothing under chromium.
the last pics it's not error, under some warning.
The big error I see, is on first pic: the asm error. And this may be the same as error #356

**Comment by TomMuc1** [comment]
i have no idea what is going on. what i know is that all was fine until today afternoon. and i'd say an application should run on a new 3800 euro notebook - especially as the app until before ran on a 8 year old notebook perfectly. bedtime now :) don't be frustrated - all code up to yesterday was fine - so this will work out in one way or an other.

cheers
tom

**Comment by Ysurac** [comment]
Nothing was really changed on 3D map. Working for me, no real error in console log dev even for you. Can't fix if there is really a bug.

**Comment by Ysurac** [comment]
You have the error #356 in chrome, you should try to disable chrome://flags/#enable-asm-webassembly
It's a chrome/chromium stupid idea to enable this by default. At least this can be the reason why it's slow.
For disappearing flights and then all are visible, this was not changed since a long time. When the flight was no more selected this displayed all flights. It's fixed in latest commit.

**Comment by TomMuc1** [comment]
ok - since last commit now 3d single mode is back working again and even if the selected aircraft is lost no others show up that was the behavior i saw over the last weeks - and this is how it should be - thanx. 

i used chrome just yesterday for testing the bug - the sandards for fam for me are safari and firefox - but maybe i look into the chrome thing.

but something changed in the way the satellite backgroud looks and is rendered. i use arcgis satellite - and now:
- mode 0.5 antything looks unacceptable
- mode 1 looks mixed some tiles are better than it was over the last weeks - some tiles are worse - and often tiles with different quality show up what does not look good
- mode 1.5 mostly all looks better and sharper than the last weeks but it is very demanding for older machine
- mode 2 looks best but is unusable on slower machine and even brandnew computer remarably resources are needed

=> my like/conclusion on this is very mixed-up

**Comment by TomMuc1** [comment]
moreover there seems to be a cookie problem too. when i change settings with slider back to level 1 the background often looks lousy - but then leaving level 1 -> going back to 2d -> going again to 3d -> suddenly anything looks great while slider is still on level 1???

**Comment by TomMuc1** [comment]
does not change anything and still gives same error - but same with fr24

![bildschirmfoto 2017-10-25 um 14 42 19](https://user-images.githubusercontent.com/31601862/31999239-e51f8ffe-b992-11e7-9143-e93808770168.png)

![bildschirmfoto 2017-10-25 um 14 43 02](https://user-images.githubusercontent.com/31601862/31999246-e85090b0-b992-11e7-9109-8788a2d39291.png)

**Comment by TomMuc1** [comment]
the new list on map page is great!
- it should not stick below the the map but on the bottom of map
- the bottom line 'deleloped ...' should really be eliminated in 2d and 3d mode
- no/never scrollbars should appear in 2d and 3d map view - whether vertical nor horizontal
- the only scrollbar in aircraft-list
- rows and typo of list a little smaller
- list menu should stay in place while rows scroll
- sorting by single menu item

![bildschirmfoto 2017-10-25 um 16 57 10](https://user-images.githubusercontent.com/31601862/32006455-1e2dc36a-b9a7-11e7-84b2-d33ed4d9ef0e.png)

![bildschirmfoto 2017-10-25 um 16 57 14](https://user-images.githubusercontent.com/31601862/32006466-257e4ad6-b9a7-11e7-9fb8-026452431df9.png)

**Comment by Ysurac** [comment]
* I don't care about jetvision or anything else.
* I need to keep copyright, so copyright will always be above list
* It's copyright... this will be keep.
* Why not ? if we have 3000 flights, it's difficult without scrollbar.
* No idea of meaning of this
* I don't like to use a magnifying lens
*  No idea of what you mean
* It's sorted by last update.

**Comment by Ysurac** [comment]
I hope you didn't close all bugs because you think I answer too harshly, I only try to be effective. Sorry if it's the case.

**Comment by TomMuc1** [comment]
thanx for reply - but no - i just thought it is simply your application and because you obviously have a different view on these items i did not want to make those longer subject of discussion :)

**Comment by Ysurac** [comment]
I often on different view at first but then I make it like only selected flight on 3D view. It's better even for me lol
You can suggest other changes, even if I'm not ok with them at the beginning :)

**Comment by TomMuc1** [comment]
thanx again for this super-friendly offer! i will :) and i want you to know that i'm fully aware that it is always much easier to complain here and there than to code all this - and nothing you did here i were able to do it better!

cheers
tom
