### ISSUE TITLE
Some Aircraft Models Kill 3D Performance

### ISSUE THREAD

**Issue by TomMuc1** [Ysurac/FlightAirMap#365]
#i made a really interesting finding!

mostly i see a320 and b737 aircrafts - when watching them over the alps in quality level 1 normally on my old notebook it looks ok but the gpu only renders about 8-12 frames per second.

but this time i had the very nice a380 model exactly on the same route over the alps - and the performance was just stunning. a super-smooth flight - nice rendered background at level 1 AND 30 frames per second!!!

i changed to 2d -> selected another aircraft in the same region -> 3d mode 8-12 frames

again back to a380 - again 30 frames with ease and very smooth

![screen](https://user-images.githubusercontent.com/31601862/32010655-c438f422-b9b2-11e7-8f29-1ff894e393ad.jpg)

**Comment by Ysurac** [comment]
Some aircraft are more detailed than others. But i'm open to pull request.
