### ISSUE TITLE
PiroSail...

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#369]
After conversations with my friend Ycarus. I open this thread for the PiroSail Away operation.

Thank you for your effort, and you know that you will have your reward, for your work, that has not been little throughout this project.

I know that for years, everything we have asked for has come true.

Thanks Ysu ...
============================================================

**Comment by tonkepen100** [comment]
Ysurac, I understand, that 3D, still does not work? Because it keeps loading without stopping, but I do not see the positions of the boats.

I say it in case I'm doing something wrong.

Thank you.

**Comment by Ysurac** [comment]
Should be fixed in latest (big) commit.
You should increase your live map refresh ($globalMapRefresh), this seems to be 15, but data are not refreshed so often, so you can put at least 30 or 60.

**Comment by tonkepen100** [comment]
Agreed, thank you very much, I saw yesterday, that the boat types are already out. Sensational, sensational.

**Comment by tonkepen100** [comment]
oJJJ, With this last update, I put the address /install/index.php and it tells me that it can not find the page.

I get it in white, what could it be ?.

**Comment by Ysurac** [comment]
You use really latest commit ? I fixed some issues.

**Comment by tonkepen100** [comment]
If I went up all over again, and now if he leaves me, what I see now is that no ship comes out, stays at 0, does not detect them. and the crons, it seems they're fine

![captura](https://user-images.githubusercontent.com/4571086/33144054-1f6ea98a-cfbc-11e7-8ba1-b59fd14ae177.PNG)

**Comment by tonkepen100** [comment]
It already works, false alarm, sorry and your ...

**Comment by tonkepen100** [comment]
**BUTTON NEXT PAGE**

In Races, and for example Volvo ocean race 2, there are several pages, only the 1 is shown, when you click to see the next page, you can not find it.

![captura](https://user-images.githubusercontent.com/4571086/33163243-d58d9430-d02d-11e7-8094-ec79fae8ea80.PNG)

![captura2](https://user-images.githubusercontent.com/4571086/33163248-da857584-d02d-11e7-89c5-064ec16f15cf.PNG)

**Comment by Ysurac** [comment]
Fixed in latest commit.

**Comment by Ysurac** [comment]
I make many changes in latest commit, but you will have to truncate all marine tables. This will remove past trace, sorry about that.

    TRUNCATE TABLE marine_live; TRUNCATE TABLE marine_output; TRUNCATE TABLE marine_archive; TRUNCATE TABLE marine_archive_output;

**Comment by tonkepen100** [comment]
Well I do first delete the tables, and then upload it, or the other way round.

Nothing happens, I understand perfectly, the question is that it is being sensational, Ycarus.

Tonique de la Peña
50001 - Zaragoza - Spain
http://piro.biz
ts.piro.biz

De: Ycarus
Enviado: jueves, 23 de noviembre de 2017 16:56
Para: Ysurac/FlightAirMap
CC: Tonique; Author
Asunto: Re: [Ysurac/FlightAirMap] PiroSail... (#369)

I make many changes in latest commit, but you will have to truncate all marine tables. This will remove past trace, sorry about that.
TRUNCATE TABLE marine_live; TRUNCATE TABLE marine_output; TRUNCATE TABLE marine_archive; TRUNCATE TABLE marine_archive_output;

**Comment by tonkepen100** [comment]
Well I do first delete the tables, and then upload it, or the other way round.

Nothing happens, I understand perfectly, the question is that it is being sensational, Ycarus.

**Comment by Ysurac** [comment]
You should upload it and then truncate the table with the SQL command above.

**Comment by tonkepen100** [comment]
![captura](https://user-images.githubusercontent.com/4571086/33181999-7e47f7e8-d072-11e7-878f-3b42c8890869.PNG)
It's already, I think I did it right, a Ycarus question. the distance and momentary classification offered by sail, do you have the idea to add it?

![captura2](https://user-images.githubusercontent.com/4571086/33181995-7bd3a57a-d072-11e7-9a1b-4d18dede3e48.PNG)

**Comment by Ysurac** [comment]
It's added. You should truncate again tables because I think that the daemon was working the first time, so you have data 2 times.

**Comment by tonkepen100** [comment]
Go, verry thanks Ysu..

**Comment by tonkepen100** [comment]
**## IDEAS ABOUT THE INFORMATIVE POSTER ....**

![captura](https://user-images.githubusercontent.com/4571086/33201137-91dce02c-d0f7-11e7-9667-2e889c525964.PNG)




I'm going to tell you my ideas about the boat information sign:


1.- Photograph of the Ship ....

As we know, we have 5 types of boat, and we have the pictures of them, you could put the photo of the type of boat, exactly as they leave the aircraft, to be 5 I do not think it is much problem, so we give a little color and good appearance to the informative poster.

2.- Coordinates ....

Currently the decimal coordinates are output, it is the case that the simulator uses both decimal and Cartesian types, one for GPS, and the others for positions on the map. A little absurd, but that's the way it is.

Therefore it would be a good idea, reflecting the two types of coordinates. I think it's simple, it's a conversion, I think.

3.- License and Name of the Captain

It would also be sensational that up where the license plate of the boat leaves, it will be changed by the NAME OF THE CAPTAIN, as the license plates of the ship are constantly changed, the name of the captain is always the same. therefore, it would simply be to change its position.

4.- Meteo ...

As I explained in the post Meteo, implement the wind speed and course.

5.- Distance and relative Position

It could also include the distance data to the buoy, and position within the race.

6.- Moon phase

The simulator supports both real stars and lunar phases, that is, the climate.

It could include a logo, or information about the weather and the lunar state.

something simple like a little symbol, or simple information. I do not know if I explain myself.

For me these are the most important points for this poster. naturally you can include more, but given the limitation of data that the simulator gives us, I do not know what to say.

I do not know what idea you had for that poster, but I leave you these, in case you see them useful.

**Comment by Ysurac** [comment]
1. Not possible. I don't have the rights on the pics. This can be pics in public domain from somewhere else but not from the game.
2. I don't thinks it's really needed, maybe using an option for unit like speed, altitude,...
3. Strange. We always ident a boat by his name, not by the captain name. Can be done for sailaway...
4. maybe...
5. this will be added in the infobox
6. maybe later

**Comment by tonkepen100** [comment]
Ok then on point 1, we can look for 5 photos of open right, or that give me permission to use those 5 photographs.

Or even if you tell me what size, I'll give you 5 photos, with a logo of each boat.

**Comment by Ysurac** [comment]
I will add an option to add the pics in the settings

**Comment by tonkepen100** [comment]
Of course, it would also be sensational that these photos, also come out in the listings, I mean here ....

![captura](https://user-images.githubusercontent.com/4571086/33205442-41e18c98-d107-11e7-84d8-b75fd35f60a3.PNG)

**Comment by tonkepen100** [comment]
# **BATIMETRIA....**

Another idea, worth studying, is the possibility of having bathymetric data on the maps. bone the depth at a given point.

Especially in coastal areas.

![captura](https://user-images.githubusercontent.com/4571086/33209112-bafb7096-d114-11e7-98ea-b00f8d714063.PNG)

**Comment by Ysurac** [comment]
It's more a layer function to display this.
I also don't have an "elevation"/depth source for sea. I use SRTM htg files for elevation, but this seems to be only available for ground.

**Comment by tonkepen100** [comment]
I'm going to inform me, where they take it from, sailaway ..

**Comment by tonkepen100** [comment]
ONE COLOR FOR EACH TYPE OF BOAT.

There are five different types of boat, because we can not assign a predetermined color to each type of boat.

It would be sensational, since at a single glance, we can know with what type of boat it sails.

This does not affect the aircraft tracker at all, since it only determines the color of each type.

If this is achieved, I think it is a big step inside the 2D map.

I breathe that they are ideas, simply ideas, but imagine how beautiful it can be to see different colors, depending on the boat in which you sail,

**Comment by Ysurac** [comment]
I will add custom icons for each boat but not custom colors.

**Comment by tonkepen100** [comment]
Oppss, ok ok, thanks

**Comment by Ysurac** [comment]
Yes.
I need to find 3d models for 3d...

For pics you can add this, for example, in your *require/settings.php* (you can change pics and copyrights):

    $globalMarineImagePics = array('type' => array('50\' Performance Cruiser' => array('image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/CS_27_sailboat_Gryphon.jpg/1024px-CS_27_sailboat_Gryphon.jpg','image_copyright' => 'Ahunt'),'Mini Transat' => array('image' => 'https://upload.wikimedia.org/wikipedia/commons/8/82/Mini_transat_2007.JPG','image_copyright' => 'Butterfly voyages'),'52\' Cruising Cat' => array('image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Boyer_Mk_IV_A_class_catamaran.jpg/640px-Boyer_Mk_IV_A_class_catamaran.jpg'),'Sailaway Cruiser 38' => array('image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Sagitta-Racing2002_8mR_world_cup.jpg/550px-Sagitta-Racing2002_8mR_world_cup.jpg','image_copyright' => 'Tajna Wesolowski'),'Caribbean Rose' => array('image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Tanzer_26_sailboat_2612.jpg/640px-Tanzer_26_sailboat_2612.jpg', 'image_copyright' => 'Ahunt')));

**Comment by tonkepen100** [comment]
But what is this?. So hard is it that I believe, 5 logos, and they can be put on?

**Comment by Ysurac** [comment]
It's some sails pics. It's an example. You can change url as you want.

**Comment by tonkepen100** [comment]
I put 5 images and have to put all that, I swear I get into college, to learn computer science.

**Comment by Ysurac** [comment]
I didn't add configuration in the install script yet. It's only an array with pics in it.

**Comment by tonkepen100** [comment]
Ok, do not worry, tomorrow I go to the university, to study how to put 5 logos created by me.

And what of copirright noses, if they are mine.

**Comment by tonkepen100** [comment]
ok let it, what I see is hard to do

**Comment by tonkepen100** [comment]
$globalMarineImagePics = array('type' => array('50\' Performance Cruiser' => array('image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/CS_27_sailboat_Gryphon.jpg/1024px-CS_27_sailboat_Gryphon.jpg','image_copyright' => 'Ahunt'),'Mini Transat' => array('image' => 'https://upload.wikimedia.org/wikipedia/commons/8/82/Mini_transat_2007.JPG','image_copyright' => 'Butterfly voyages'),'52\' Cruising Cat' => array('image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Boyer_Mk_IV_A_class_catamaran.jpg/640px-Boyer_Mk_IV_A_class_catamaran.jpg'),'Sailaway Cruiser 38' => array('image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Sagitta-Racing2002_8mR_world_cup.jpg/550px-Sagitta-Racing2002_8mR_world_cup.jpg','image_copyright' => 'Tajna Wesolowski'),'Caribbean Rose' => array('image' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Tanzer_26_sailboat_2612.jpg/640px-Tanzer_26_sailboat_2612.jpg', 'image_copyright' => 'Ahunt')));

Esto para pòner, 5 logos?. en serioen serio me dices esto?

**Comment by tonkepen100** [comment]
But what wikipedia, or nadam if I believe them, myself, and do not have to define copirrigght or anything, are 5 logos, nothing more.

**Comment by Ysurac** [comment]
If you don't want to add pics, don't add them. I didn't add it in the install script yet, it's all.
Wikipedia is not copyright free...

**Comment by tonkepen100** [comment]
But what rights, if I tell you that the 5 logos, I believe them, me.

I do not understand why I have to put all that code, that neither put it, to be able to put 5 logos made by me.

That's what I do not understand,

**Comment by Ysurac** [comment]
It's an example... I don't have your logos...

**Comment by tonkepen100** [comment]
Ok, but a moment we talk about the 2d logos, which are in the post, or we are talking about 3D. is what I do not understand, sorry.

**Comment by Ysurac** [comment]
I speak about boat pics that you see in infobox and list.

**Comment by tonkepen100** [comment]
No problem tomorrow I have them done, tell me what measures and what format. please

**Comment by Ysurac** [comment]
80x80 png same color as images/aircrafts/new/*.png

But I will make them, I take some pics on internet of sails saw from the sky, I only need to make them logos.

**Comment by tonkepen100** [comment]
Quiet. for 2d images, I do them, simply by setting the type of vessel. they'll be fine with me, they're just 5

Tomorrow I believe them and see them, to see what they look like.

**Comment by tonkepen100** [comment]
By the way, within two days you have already completed, the Spanish language in your tracker, 100 per 100 translated.

**Comment by tonkepen100** [comment]
[LogosShips.zip](https://github.com/Ysurac/FlightAirMap/files/1502916/LogosShips.zip)

Yca ..., here I upload the logos of the 5 boats, look at them and tell me what.

Thank you.

**Comment by tonkepen100** [comment]
The truth, I do not know if I put this well, this last work I do not understand much, you will forgive me, besides I do not know what happens, that goes out all the time internal server error, you will have to see this problem, because it surpasses me .

![captura](https://user-images.githubusercontent.com/4571086/33229197-3713cac4-d1ca-11e7-9ef0-d3e4a1ef71d7.PNG)

**Comment by tonkepen100** [comment]
Okay I understand, perfect, I finally understood.

**Comment by tonkepen100** [comment]
Okay, and now comes the final question, for the issue of the images of the boats ...

In the event that Sailaway gives us permission to use the 5 captures, of each one of its boats, could they be put?

Naturally putting his copyrright, and all that.

Thank you.

**Comment by Ysurac** [comment]
Sure, without problem if they put it as public domain or give the right to link to them somewhere on their website with copyright.

**Comment by tonkepen100** [comment]
#  INFORMATION ON THE REGATAS ..

Is there a possibility to create in the menu, or a submenu of a section, where you can put the information of a career ?.

![captura](https://user-images.githubusercontent.com/4571086/33233928-780f6ebc-d21e-11e7-96dc-37548c091a92.PNG)


For example the text, of which consists the Vendee, or the Volvo, or whatever career.

In itself, I think it would be to put an editor or something to put the regulations of the careers that interest us.

Example: 

![captura](https://user-images.githubusercontent.com/4571086/33233952-c46c8c7c-d21e-11e7-9d9f-7f9647e0cdd5.PNG)

Etc etc...

**Comment by Ysurac** [comment]
I can add the description of the race, example: *The Vendée Globe is a race that consists of sailing around the world on a solo basis, without stops and without assistance.\r\n\r\nAprox.. From 78 to 128 Days.\r\n\r\nREGISTRATION : pirosail.ovh\r\n\r\nContact: sail@piro.biz, Steam or Teamspeak3 (ts.piro.biz).\r\n\r\n\r\n\nby Tonique [VDG]*. but difficult to add something else...

If you make an other page, you can add a link to show only a race like: http://pirosail.ovh/?raceid=7436
This only filter race on the map page for now.

**Comment by tonkepen100** [comment]
I do not understand it very well, sorry.

What I understand is that you can add a small description of the race, and how do you add ?, where ?.

And where would it look?

Then you tell me that if I have another website, I can link it. well I have http://pirosail.ovh/Sail where the whole texts come out. of said regattas.

But the nice thing would be to be able to put the descriptions, of those races inside the tracker.

I do not know, I'm sorry I did not understand much.

**Comment by Ysurac** [comment]
I can add it on the race page, the example I give is an information I get from sailaway data.

I will not add a custom editor or something like that in FlightAirmap. Because it's lot of code (would need an editor, users,...), only usable for you if I want that clean,... I try to make all code usable for any other simulator (and real boat when possible).

**Comment by tonkepen100** [comment]
I understand, perfect, it would be great to be able to add, at least that information.

And even, to be able to put an external link under said information, in case you want to go to another website.

Would it be possible?

**Comment by Ysurac** [comment]
Should be possible with some changes. I will try to find a good way to add an option for that.

**Comment by tonkepen100** [comment]
Thank you very much Ysu, really Thank you.

Now I send you another challenge, which I think is important.

**Comment by tonkepen100** [comment]
# BOYS

Well, here we have a theme, which I really believe is already implemented, in the tracker, currently using some trap.

![captura](https://user-images.githubusercontent.com/4571086/33234338-756bfd5e-d225-11e7-9992-1145c807929a.PNG)


I explain:

In the configuration file, there is the possibility to put markers, which go to a Source_location table, fine.

![captura](https://user-images.githubusercontent.com/4571086/33234334-4bd34a42-d225-11e7-8dd9-8bb8ba470964.PNG)


As you can see, and put both the exit, arrival, and the 3 buoys of the globle vendee.

First problem, when loading the cron every so often, the icons that I put, automatically reload, leaving the originals, that is, the antenna icon.

Second problem, it would be sensational, to be able to put a filter, to determine, and manually put the buoys, for each race, I mean, if I select the Volvo, the icons of that race will be seen. If I select the Vendee, the icons of that race will be seen.

If you can not filter, nothing would happen, since if you can select existing icons, such as flags, and other icons that are already inside the tracker, you can change them for each race, and they would all be seen.

The solution is to tell the cron not to restore the icons, or to be able to define those icons.

I do not know if I explained myself very well.

**Comment by Ysurac** [comment]
What would be cool is to find a way to get marker position from sailaway...
I will make source_location logo pics really usable.

**Comment by tonkepen100** [comment]
Yes. today I send the developer the possibility of this topic. As also the use of images.

I am waiting for the answer, but I tell you that it will be a yes, since everything we are asking for becomes a reality.

But do it, since if you can do it, from the beginning we would have another problem solved.

Realize that now, it is only useful for long races, which is what interests us.

And again, millions of thanks.

PD: look how beautiful, your work ....

![captura](https://user-images.githubusercontent.com/4571086/33234471-977448b4-d227-11e7-9fd8-277751f4809b.PNG)

**Comment by Ysurac** [comment]
This seems to be possible to get more info using a login and pass: https://github.com/dakk/sailaway-cli
I will try to create a working account (never received the mail for the last test...)

**Comment by Ysurac** [comment]
hmmm account on sailaway website doesn't give access to anything...

**Comment by tonkepen100** [comment]
You need an account, you?

If you need it, I give you one.

**Comment by tonkepen100** [comment]
![captura](https://user-images.githubusercontent.com/4571086/33234586-036461d8-d22a-11e7-98bf-c7dd7e02d651.PNG)

Now something happened ...

**Comment by tonkepen100** [comment]
Wait, I'm going to talk to these resellers, who are always the same.

And they are already touching me cojon ,,,,,

**Comment by Ysurac** [comment]
Yes I see that... Strange

**Comment by tonkepen100** [comment]
let's see your servers do not ?. send me an email, and I'll buy you a room, I want this to work well.

Send me prices, and I'll pay you right now.

I'm up to these little balls. the same thing always happens.

**Comment by Ysurac** [comment]
I don't have the server power to add this new source for now.
But any [kimsufi](https://www.kimsufi.com/) VPS or dedicated server (dedicated server are always better) would be better than your really small VPS. I can then sell you the administration/install part if you want.

**Comment by Ysurac** [comment]
They seems to be available under CPanel, so you should be able to do everything you want the same way as your current VPS.

**Comment by tonkepen100** [comment]
If I have two Kimsufis, for more than 10 years, but I do not want to keep, a VPS, I already did it and I went crazy, really.

I have them now for two private WoW servers.

**Comment by Ysurac** [comment]
There is only 512Mo of memory on your current server, it's really really small.

**Comment by tonkepen100** [comment]
Now I'm going to try to solve it. sorry

**Comment by Ysurac** [comment]
working now

**Comment by tonkepen100** [comment]
Yes Ysu.  duplicate memory, and 3 hours x3, joder

It's that I have even the balls (sorry)

**Comment by tonkepen100** [comment]
With these Argentine guys I've been around for a long time, but much more than 25 years ago, when there was not a lot of computer science.

And I love them, since they helped me a lot at that time, and I always keep this reseller with them.

It is a war, between the two, and they behave well, and if I tell you the price, then you will tell me that I am a usurer. hahaha

Finally inside, 3 hours put it with 3 GB of memory, I think it will be enough.
And forgive for these problems.

**Comment by tonkepen100** [comment]
=========================================================

**Comment by Ysurac** [comment]
accounts are created in-game ?

**Comment by tonkepen100** [comment]
Ummm, forgive what you mean by creating accounts?

**Comment by Ysurac** [comment]
Account on web page are working. So I have more data now.
I will add all I can on FlightAirMap next week.

**Comment by tonkepen100** [comment]
Sensational Yca ..., thank you very much.

If you need an account in SailAway, tell me, and I bought it for you?

Wonderful your work.

I'll be putting more ideas if it does not matter.

**Comment by Ysurac** [comment]
Not needed. I can get markers for every race now. I will add data next weeks. No need more ideas for now, I have lot of works...

**Comment by tonkepen100** [comment]
Ok but please, do not leave the project, okay ?.

I'm asking you please.

**Comment by Ysurac** [comment]
No, I'm only off for the week-end now.

**Comment by tonkepen100** [comment]
![captura](https://user-images.githubusercontent.com/4571086/33235227-04433c8c-d234-11e7-8231-ca9c7ac995d3.png)

**Comment by tonkepen100** [comment]
Let's see, it seems to me sensational, that all the credits of the world are yours. just missing

But fuck, the minimum is to be able to treat the tracker, for a user of your project.

What does not seem right, is that we can not change the text, we want it to be.

Fuck Ysu, it seems to me enough, bad that we can not put, not even that is our concept of the tracker. At least the minimum text, explaining what goes.

**Comment by tonkepen100** [comment]
![captura](https://user-images.githubusercontent.com/4571086/33235777-767332ec-d240-11e7-982e-1406d36ea71a.PNG)

**Comment by tonkepen100** [comment]
# LINE FASTSEAS

- I put the title, just so I do not forget the idea.

**Comment by tonkepen100** [comment]
Yurac It seems we have a problem, when you click on any race, it goes blank.

**Comment by Ysurac** [comment]
Should be fixed in latest commit, it's because data was not (yet?) populated.

**Comment by tonkepen100** [comment]
Thanks i see, is correct, Thats commitic , no charge boats.

**Comment by Ysurac** [comment]
You need to run *install/index.php*, there is a DB update and you have to write sailaway email and password in it.

**Comment by tonkepen100** [comment]
Ok i put.

**Comment by tonkepen100** [comment]
Yes, now I see some new markers, buoys do not ?.

**Comment by tonkepen100** [comment]
OHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH....

![captura](https://user-images.githubusercontent.com/4571086/33289481-fa6acad0-d3bf-11e7-8f67-8aff9a420922.PNG)

**Comment by Ysurac** [comment]
Markers icons are all markers that define a course for a race.

**Comment by tonkepen100** [comment]
If I see it but how do I put the data?

![captura](https://user-images.githubusercontent.com/4571086/33289880-3f8b8612-d3c1-11e7-8a41-571369097d16.PNG)

**Comment by Ysurac** [comment]
I get them from sailaway.

**Comment by tonkepen100** [comment]
Well almost prefer to put it as before, that at least had position data and the name of the buoy. I do not know what to tell you.

**Comment by tonkepen100** [comment]
It is almost preferable to put an exit icon, arrival and a buoy icon, and leave it as before. the truth be told. Yes, that lña db do not step on them, every time you load.

**Comment by Ysurac** [comment]
It's only markers added. I think it's nice and important to know steps of a race even if this can be better.

**Comment by tonkepen100** [comment]
Yes, totally agree, but then, there are two options, or leave only the markers. Or that they have data, not that they put Type4, and you will tell me to see who understands that type4.

**Comment by tonkepen100** [comment]
The logical thing would be to at least say what career it is. if you do not imagine the follon that can be mounted.

**Comment by Ysurac** [comment]
I have no idea of what it is for now. I had the name of the marker when I have it.
What career ? You mean the race name ? can be added. It's always the race of the selected boat or the filtered race.

**Comment by tonkepen100** [comment]
The idea is sensational. Look at this image, the four coordinates of departure and arrival actually come out, but with that numbering, you will tell me a user who understands ?.

![captura](https://user-images.githubusercontent.com/4571086/33291030-d867ee0e-d3c4-11e7-98f6-e4315302c385.PNG)


I do not know if I explain myself very well,

**Comment by Ysurac** [comment]
I didn't know the meaning, so I put number on them. How do you want me to know what markers was for without even playing the game ?
It would be better if I can know what the numbers are for.

**Comment by tonkepen100** [comment]
haha, it's that you're absolutely right, that's why I want to explain it to you.

Forgives. I explain.

Both the start and the arrival of a race are determined by two buoys, observe the image of before, in if they are two points for the exit, and two for the arrival.

And then there are the buoys. of the race, which is only a point.

So, it's very good that they come out, do not doubt it, but we have to define in some way, either with colors, or with text, or I do not know how, each buoy to which race it belongs. and even the coordinates of them.

Now there are two long races, the volvo and the vendee, and just coincide in Cape Town, that circumstance occurred, which comes sensational, precisely to be able to do this topic.

And sorry that I did not see your previous post before, I'm really sorry.

**Comment by tonkepen100** [comment]
So you can see how the buoys are created, look at this ... so they ride ...

![captura](https://user-images.githubusercontent.com/4571086/33291610-b2c2e47c-d3c6-11e7-8a9d-a9ad81a24741.PNG)

**Comment by Ysurac** [comment]
What is the race you put in the example above ? So I will be able to put the good lateral or cardinal buoy.

**Comment by tonkepen100** [comment]
The one above is the vendee, I SEE, the colors and they are perfect.

NOTE: if the important ones are the buoys, in terms of position, I mean, the departures and arrivals, with the colors daria equal.

**Comment by tonkepen100** [comment]
No, the example above is a short race, which is called "meridian regatta"  (Regata del meridiano).

**Comment by tonkepen100** [comment]
# DATAS

Just as a curiosity, of the data that we see in the capture, the API, which gives us ?, only the HDG and SPD.

No more data?

![captura](https://user-images.githubusercontent.com/4571086/33311890-82713b10-d426-11e7-80e4-c0de1850df58.PNG)

Thanks

**Comment by Ysurac** [comment]
Only speed and heading.

**Comment by tonkepen100** [comment]
Humpbacks, well, it's a bit short this API, haha

**Comment by tonkepen100** [comment]
# LINE FASTSEAS

Well, I put the idea here, in case one day it can be done .....

1.- We have the web Fastseas, (https://www.fastseas.com/#); This web what makes us is to put the starting point and the point of arrival, and with the meteorological data, plus the tides, to create the best route for our journey.

![captura2](https://user-images.githubusercontent.com/4571086/33312666-d19bf412-d428-11e7-9215-7448245d5347.PNG)


2.- When creating the route, it gives us the option to download 4 types of file, with the data previously calculated.

![captura](https://user-images.githubusercontent.com/4571086/33312642-c33d5f28-d428-11e7-8310-d621bf008012.PNG)


The idea is, the captain of each ship could upload some of those files, so that the line of your route would automatically come out ?.

I leave it as a possible idea.

**Comment by tonkepen100** [comment]
Yes sir, yes sir ...

![captura](https://user-images.githubusercontent.com/4571086/33315106-f9117d12-d42f-11e7-9860-2d59c823eb9e.PNG)

**Comment by tonkepen100** [comment]
Of course, I already understand the subject. the buoys appear, those of the vendee, since I have put my key and believe that career no ?.

For example the departure of the volvo and the arrival as I do not believe it because they do not leave.

I'm right?.

**Comment by Ysurac** [comment]
The buoys are the one used by filtered race or the selected boat race.

**Comment by tonkepen100** [comment]
Oysters, it's true

**Comment by tonkepen100** [comment]
Good morning Ysurac:

What idea do you have regarding this table below ?, since I think that this table is superimportant.

![captura](https://user-images.githubusercontent.com/4571086/33369395-b98cab6a-d4f4-11e7-83a7-950a2bfa138f.PNG)

**Comment by Ysurac** [comment]
I will put more data in it. At least rank and captain name.

**Comment by tonkepen100** [comment]
Well, thanks, but with regard to RANK, we have to define it well. since this point is essential.

I will write, explaining the subject, and you value it.

**Comment by Ysurac** [comment]
I get rank from sailaway.

**Comment by tonkepen100** [comment]
Yes, I know, but I want to explain that point, because it's just changing the name of RANK.

I explain it to you and you value it.

**Comment by tonkepen100** [comment]
We have two types of Careers:

1.- Finished races
2.- Active races.

With respect to races finished the word RANK, is completely correct.

that is seen in the final classification that Sailaway delivers, so perfect.

With regard to active races, the word RANK, which appears in the data tables, etc etc, would not be correct.

In itself it is only to define it in another way, as RELATIVE POSITION, PROVISIONAL RANGE. Etc etc. Or any synonym.

Why?:

Sailaway computes this position to the first buoy he finds, therefore computes it by subtracting the distance to the first buoy. But we know that there are, or there may be several, does not compute the total distance to the goal, unless it is only exit and arrival.

Therefore, this position is relative.

In that case, the correct thing would be to define, as it was said before in the parts where that data comes out.

I think that would be the right thing to do.

**Comment by tonkepen100** [comment]
Ysurac, a question on the 3D map, would you have to see a ship already, or not?

It is that the number of boats comes out but they do not come out to me. That's why I'm asking you.

Thank you.

**Comment by Ysurac** [comment]
The model is not downloaded on your site.
I think it's because your host disable the use of *exec*. In latest commit I check if it's available, and this should work.

So update, and wait. When the update script will run, all will be ok.

**Comment by tonkepen100** [comment]
Understood, if you need me to talk to those of the reseller, for that matter I can tell. and thanks.

**Comment by tonkepen100** [comment]
Well sincerely I have to be me, the one who does it wrong.

**Comment by Ysurac** [comment]
You have to wait that the *update_db.php* script run again (every 2 hours for you).

If you want it to work now you can put the file https://data.flightairmap.com/data/models/vehicules/sail.glb in your */models/vehicules/* directory.

**Comment by tonkepen100** [comment]
Ok, thanks Ysu...

**Comment by tonkepen100** [comment]
Ysurac, Wawes, exceptional.

**Comment by tonkepen100** [comment]
# MARINE ICON

Please, in options you could put the default color for the boat icons. I think this is about airplanes, but it would be good to put the one on ships,

![captura1](https://user-images.githubusercontent.com/4571086/33426749-36e5b39e-d5c3-11e7-8221-e592ac849920.PNG)


Thank you.

**Comment by Ysurac** [comment]
I added the option in the install script.

**Comment by tonkepen100** [comment]
Thank you, it's perfect.


    -

**Comment by tonkepen100** [comment]
Question, if I put this last update again, I have to put all the data in the setings.php file again?

![captura](https://user-images.githubusercontent.com/4571086/33437844-749fb218-d5e9-11e7-8b77-5798d9198e7b.PNG)

**Comment by Ysurac** [comment]
Don't copy the new *settings.php*
