### ISSUE TITLE
Cron-db Stop

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#37]
But now the cron is to just start to grab data basestation.

Connecting to SBS ... Connection in progress to 87.222.37.143:30003.... Connected! SCAN MODE *********** New aircraft hex : 47A46E ***********        CATACRASH//// STOP

**Comment by tonkepen100** [comment]
Connecting to SBS ... Connection in progress to 87.222.37.143:30003.... Connected! SCAN MODE Wrong line format. Ignoring... STA,,427,49436,4CA174,94507,2015/05/30,13:58:49.541,2015/05/30,13:58:49.541,SLArray ( [0] => STA [1] => [2] => 427 [3] => 49436 [4] => 4CA174 [5] => 94507 [6] => 2015/05/30 [7] => 13:58:49.541 [8] => 2015/05/30 [9] => 13:58:49.541 [10] => SL ) Connection in progress to 87.222.37.143:30003...

**Comment by Ysurac** [comment]
What is your source ? Dump1090 ? Radarcape ? something else ?

**Comment by tonkepen100** [comment]
Is puck1090

**Comment by tonkepen100** [comment]
port 30003 dump...

![captura](https://cloud.githubusercontent.com/assets/4571086/7897271/d95148f6-06d5-11e5-80af-380b0a556508.JPG)

format

and other is planeploter  output port 3004

![captura2](https://cloud.githubusercontent.com/assets/4571086/7897273/eea41ac6-06d5-11e5-80d0-06c77e6b61a5.JPG)


but two options crash cron

**Comment by Ysurac** [comment]
Should be better with commit d52efa61db12fb68f299bdb3a323f628d0c08a84

**Comment by tonkepen100** [comment]
I put the new but is the same. stops here ...

![captura](https://cloud.githubusercontent.com/assets/4571086/7897316/23ac7b9e-06d8-11e5-93bd-dce72c7e9c7e.JPG)

**Comment by tonkepen100** [comment]
y en el Puck con 30003 this...

Connecting to SBS ... Connection in progress to 87.222.37.143:30003.... Connected! SCAN MODE Not a message. Ignoring...

**Comment by Ysurac** [comment]
True. The script don't run really well with SBS if used as cronjob.
I made a dirty fix in latest commit, you need to set **$globalCronEnd** in *require/settings.php*.
The script will run for the amount of seconds set.
I will try to make this better latter...

**Comment by tonkepen100** [comment]
if now goes, keep watching to see such. and me you'll have to submit a shipping address for poderte send bottles of wine, man that you deserve.

**Comment by tonkepen100** [comment]
Puzzzzz but also a nativity scene noses mounts

![captura](https://cloud.githubusercontent.com/assets/4571086/7897570/c64f6520-06e0-11e5-839a-e950d462153c.JPG)

**Comment by Ysurac** [comment]
Fixed in commit 301d2660d587ee919e3fbe76a83dcdf8e5143b31

**Comment by tonkepen100** [comment]
It is that what I see every update repeats the plane, but does not erase the previous position.

![captura](https://cloud.githubusercontent.com/assets/4571086/7897682/b3af91de-06e4-11e5-82ad-5a2fe03f8a53.JPG)

**Comment by Ysurac** [comment]
Should be fixed in commit 56379e088c98a20fbf6efa194909c5a698e0ff8e

**Comment by tonkepen100** [comment]
Greatest of the great Ysurac

![captura](https://cloud.githubusercontent.com/assets/4571086/7897789/77f3e2ac-06ea-11e5-88c5-28326cee72fe.JPG)

**Comment by tonkepen100** [comment]
But notice that curious, I leave the oranges photo planeplotter the catches my radar

![captura](https://cloud.githubusercontent.com/assets/4571086/7897811/40a5f28a-06eb-11e5-97a0-f94f05be7367.JPG)


and look at the ones in the same web, I do not think out all


![captura2](https://cloud.githubusercontent.com/assets/4571086/7897813/488efd98-06eb-11e5-9e73-1cfb7a9cd3c0.JPG)

**Comment by Ysurac** [comment]
By running it with cronjob you lost some messages, so you can't see all flights.

**Comment by tonkepen100** [comment]
ahhh ok ok good
