### ISSUE TITLE
Color of the strokes

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#370]
Is it possible to change the color of the trail lines of ships and planes in some way?

![captura2](https://user-images.githubusercontent.com/4571086/33035572-edf8ffb8-ce2b-11e7-8782-6f29546178e1.PNG)

Thank you.

**Comment by Ysurac** [comment]
It's now set to a lighter color.

**Comment by tonkepen100** [comment]
Spectacular, thank you very much
