### ISSUE TITLE
Revision 2250

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#372]
This morning when loading the web, error goes out. I put the last revision the number 2250, and do not touch anything else,

![captura](https://user-images.githubusercontent.com/4571086/33228990-21064166-d1c6-11e7-93c5-9782644d740c.PNG)

**Comment by tonkepen100** [comment]
I think these values are triggered, with this last revision, before they were stable, it could not be that.

![captura](https://user-images.githubusercontent.com/4571086/33229081-361ec6ca-d1c8-11e7-9048-32ca5d7e8376.PNG)

**Comment by Ysurac** [comment]
You had **$MarineImageFetch** that was set to *TRUE*. So it take a longer time to run **scripts/spotter-daemon.php**. Many daemon was launched on the server now and the page can't be created.
This is solved now.

**Comment by Ysurac** [comment]
$MarineImageFetch is not usable for virtual sail, I will force it to be disabled it if virtual sail is used.

**Comment by tonkepen100** [comment]
Aja, and what do I do ?, I put it in FALSE?

**Comment by tonkepen100** [comment]
Thanks Ysu. repaired, thanks
