### ISSUE TITLE
Spanish Translation

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#373]
Sensational the inclusion of Spanish to the project.

But, the truth is really badly translated.

I was already translating it, but, cojere this already is and I will purify it, to leave it perfect.

Do you think it's OK?.

**Comment by Ysurac** [comment]
I know it's bad, it's done using google translate.
The file to translate is in **locale/es_ES/LC_MESSAGES/fam.po**

You can use Poedit to translate the po and compile it to **locale/es_ES/LC_MESSAGES/fam.mo** (only the compiled version is used by FlightAirMap).
You can also use https://translate.google.com/toolkit/ to help you translate a po (this was used in this case).

You can also use any editor to edit the fam.po and I will compile it, not a problem.

**Comment by tonkepen100** [comment]
If I know, I'll leave it perfect, so we already have it in Spanish.
