### ISSUE TITLE
2287

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#375]
Your project, at this moment is consuming transfer more than 1 gb, every 10 minutes.
Thank you.

**Comment by Ysurac** [comment]
Not possible. The only script that run so often is the daemon-spotter, and this only downloaded data are from the source.

**Comment by tonkepen100** [comment]
Yes, tomorrow or within two hours you will change it, and everything can happen, right ?.

We've known each other for years.

But thanks for your attention.

**Comment by Ysurac** [comment]
Stop being aggressive.

**Comment by tonkepen100** [comment]
Aggressive? , absolutely. I just ask and tell the truth, by God how can you say that before your project.

**Comment by tonkepen100** [comment]
I just ask, and I say what I think.

**Comment by Ysurac** [comment]
ok no need for aggressive people here bye.
