### ISSUE TITLE
SQL Issues

### ISSUE THREAD

**Issue by CaptainSpock** [Ysurac/FlightAirMap#378]
1/ When sorting by airport or airlines, I got this message using the search engine:

"Invalid query : SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'AND spotter_output.airline_icao = 'VRE' ORDER BY spotter_output.date DESC ' at line 2 Whole query: SELECT spotter_output.* FROM spotter_output WHERE AND spotter_output.airline_icao = :airline_icao ORDER BY spotter_output.date DESC LIMIT 25 OFFSET 0"

2/ Air Cote d'Ivoire isn't from Ukraine:
"NAMEAir Cote d'IvoireCOUNTRYUkraineICAOVREIATAHFCALLSIGNUKRAINE VOLARE"

**Comment by Ysurac** [comment]
1/ Fixed in latest commit
2/ It used VLE ICAO info instead of VRE... I will generate a new airlines list next week with this error fixed.

**Comment by Ysurac** [comment]
All is now fixed in lastest commit and airline update. Run *scripts/update_db.php* to update DB.
