### ISSUE TITLE
Shared idea

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#38]
To me an idea that could not be the solution to send data to a reseller by planeplotter.

![captura](https://cloud.githubusercontent.com/assets/4571086/7897874/3db8cb4e-06ee-11e5-8602-5e72a5a2cc34.JPG)

the question is sharear through it to the server ip and catch data.

I not if I'm talking nonsense but to me happened.

Light the subject would create a script to understand the data, no I do not understand.

**Comment by tonkepen100** [comment]
![sin titulo](https://cloud.githubusercontent.com/assets/4571086/7897903/0fdcfa32-06ef-11e5-98a7-6b8e45f03bed.png)

**Comment by tonkepen100** [comment]
In my case I think this would be the only solution would work, because using cron on a hosting, the statistics if that grabs well and is great to have them, but another issue is the map with the flights, because we lose a lot, and flights are not naturally fluid as it should be in a dedicated.

**Comment by Ysurac** [comment]
You can try to run the script every hour, day,... by cron. You only need to set $globalCronEnd to the seconds needed (3600,86400,...).
You can also set $globalLiveInterval to a higher value.

**Comment by tonkepen100** [comment]
Okay, but the question is in the cpanel how often I tell him run cron?

**Comment by Ysurac** [comment]
It's what I was telling.
You can run the script via cron in cpanel every hours, days,... set *require/settings.php* **$globalCronEnd** to the same amount of seconds.

**Comment by tonkepen100** [comment]
understood, I will try

**Comment by tonkepen100** [comment]
I have given with higher values, but to, I'll see every 5 minutes

**Comment by tonkepen100** [comment]
Nor is it for and jump every 5 minutes aircraft ...

![captura](https://cloud.githubusercontent.com/assets/4571086/7903507/04c683ca-07df-11e5-9a18-0547b63700ec.JPG)

![captura2](https://cloud.githubusercontent.com/assets/4571086/7903508/0b29ef7c-07df-11e5-8776-88620c3d9e29.JPG)

![captura3](https://cloud.githubusercontent.com/assets/4571086/7903509/0fbc45e4-07df-11e5-9487-47a9f391f333.JPG)

**Comment by Ysurac** [comment]
Yes, because you set **$globalMapRefresh** to 600, so every 10 minutes the map will refresh, and you set **$globalLiveInterval** to 5, so it will display flight saw last 5 seconds...

**Comment by tonkepen100** [comment]
Joderrrrrrr fucking I believe it and got some, I do not play more, and I'll pray.
