### ISSUE TITLE
broken links in accident stats pages

### ISSUE THREAD

**Issue by bobbyr172** [Ysurac/FlightAirMap#382]
The "next page"/"previous page" URL links in the accident stats pages do not redirect properly, resulting in a 404 error.  For example:

http://real.flightairmap.com/accident/2006

The default display lists the first 25 accidents (sorted by most recent) in 2006.  The "next page" should display the next 25.  However, the redirect link is to

http://real.flightairmap.com/accident-detailed/25,50

The correct syntax should be 

http://real.flightairmap.com/accident/{date}/{parameter}

For example,

http://real.flightairmap.com/accident/2006/25,50
or
http://real.flightairmap.com/accident/2006-01/25,50

A helpful feature addition would include a choice of how many results to display per page (10, 25, 50, 100,??)

**Comment by Ysurac** [comment]
Thanks, it's fixed in latest commit.
When I will find a way to display the numbers of results per page I will add it :)
