### ISSUE TITLE
acarsdec moved to github

### ISSUE THREAD

**Issue by TLeconte** [Ysurac/FlightAirMap#384]
In the README.md , the url for acarsdec is obsolete.
Acarsdec is now here : (https://github.com/TLeconte/acarsdec).

By the way , last version of acarsdec have json output. 
Is it an interesting format for FLightAirMap ?
Because if yes, it could be ported to my vdlm2 decoder : (https://github.com/TLeconte/vdlm2dec) to have 2 sources of acars in the same format .

**Comment by Ysurac** [comment]
I fixed the readme.

An output format is always good to have. I should be able to use that output using FIFO.
I will add the support for acarsdec json ASAP in FlightAirMap.

**Comment by Ysurac** [comment]
acarsdec json format support is added in flightairmap. More info here: https://github.com/Ysurac/FlightAirMap/wiki/ACARS

**Comment by TLeconte** [comment]
Great.
Now, [vdlm2dec](https://github.com/TLeconte/vdlm2dec) is able to output same  json format  too.
The 2 programs could send these json packet via UDP too.
