### ISSUE TITLE
Table output error

### ISSUE THREAD

**Issue by me2tkt** [Ysurac/FlightAirMap#389]
Thank you for the quick solution to my other issues.
This will be the last one for tonght.

For some flights or airlines there seems to be a problem with the schedule lookup.
This example is taken from the detailed view fro flights between sirports.
But it also occurs on other pages e.g. Latest Activity

![flights](https://user-images.githubusercontent.com/23280102/35199180-f85c9640-fefa-11e7-9fb7-e4be88f4c39d.jpg)

**Comment by Ysurac** [comment]
Thanks for reporting them.
