### ISSUE TITLE
Settings.php

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#39]
the installation fails because it lacks a ;

// FLIGHTS MUST BE INSIDE THIS CIRCLE
$ globalDistanceIgnore = array () <------ HERE

**Comment by Ysurac** [comment]
When you do what ?

**Comment by tonkepen100** [comment]
to install new version lacks the semicolon where you tick, why not continue and the installation fails

**Comment by Ysurac** [comment]
I'm not able to reproduce the problem.

**Comment by tonkepen100** [comment]
In archive setting.php in line ....

// FLIGHTS MUST BE INSIDE THIS CIRCLE
$ GlobalDistanceIgnore = array ()

There are the semicolon at the end and run http: // YouWeb / install, stops and does not finish the installation, bone need to put the semicolon, so ...

// FLIGHTS MUST BE INSIDE THIS CIRCLE
$ GlobalDistanceIgnore = array ();


![captura](https://cloud.githubusercontent.com/assets/4571086/7899398/9ebc90f0-0721-11e5-927c-4035326706dc.JPG)

**Comment by tonkepen100** [comment]
And attention from the last 431 planes have disappeared, but the cron works and delivers data.

**Comment by Ysurac** [comment]
Install script fixed.
For your plane, this is a problem with your DB, I think there is no support for spatial data. Delete **countries** and **airspace** table and all should be ok.

**Comment by tonkepen100** [comment]
if it will, but as I do to support those tables
