### ISSUE TITLE
daemon spotter errr message

### ISSUE THREAD

**Issue by me2tkt** [Ysurac/FlightAirMap#390]
Not sure if this is a local problem.
(I am using the data from the Radarcape 30003 port)

Daemon spotter is showing the following error message, seems to be related to the airport being not defined -

Notice: Undefined offset: 0 in C:\xampp\htdocs\FlightAirMap2\require\class.Spotter.php on line 3815
Notice: Undefined offset: 0 in C:\xampp\htdocs\FlightAirMap2\require\class.Spotter.php on line 3816
Notice: Undefined offset: 0 in C:\xampp\htdocs\FlightAirMap2\require\class.Spotter.php on line 3817
Notice: Undefined offset: 0 in C:\xampp\htdocs\FlightAirMap2\require\class.Spotter.php on line 3820
Notice: Undefined offset: 0 in C:\xampp\htdocs\FlightAirMap2\require\class.Spotter.php on line 3821
Notice: Undefined offset: 0 in C:\xampp\htdocs\FlightAirMap2\require\class.Spotter.php on line 3822

Some examples from my log file -
*********** New aircraft hex : 3C6DCF ***********
-> get arrival/departure airport info for BEL7AW
Notice: Undefined offset: 0 in C:\xampp\htdocs\FlightAirMap2\require\class.Spotter.php on line 3815
Notice: Undefined offset: 0 in C:\xampp\htdocs\FlightAirMap2\require\class.Spotter.php on line 3816
Notice: Undefined offset: 0 in C:\xampp\htdocs\FlightAirMap2\require\class.Spotter.php on line 3817
Notice: Undefined offset: 0 in C:\xampp\htdocs\FlightAirMap2\require\class.Spotter.php on line 3820
Notice: Undefined offset: 0 in C:\xampp\htdocs\FlightAirMap2\require\class.Spotter.php on line 3821
Notice: Undefined offset: 0 in C:\xampp\htdocs\FlightAirMap2\require\class.Spotter.php on line 3822

-----------------------

-> get arrival/departure airport info for KLM69M
Notice: Undefined offset: 0 in C:\xampp\htdocs\FlightAirMap2\require\class.Spotter.php on line 3815
Notice: Undefined offset: 0 in C:\xampp\htdocs\FlightAirMap2\require\class.Spotter.php on line 3816
Notice: Undefined offset: 0 in C:\xampp\htdocs\FlightAirMap2\require\class.Spotter.php on line 3817
Notice: Undefined offset: 0 in C:\xampp\htdocs\FlightAirMap2\require\class.Spotter.php on line 3820
Notice: Undefined offset: 0 in C:\xampp\htdocs\FlightAirMap2\require\class.Spotter.php on line 3821
Notice: Undefined offset: 0 in C:\xampp\htdocs\FlightAirMap2\require\class.Spotter.php on line 3822

---------------------------
Getting schedule info...
-> get arrival/departure airport info for NAX2CV
notice: Undefined offset: 0 in C:\xampp\htdocs\FlightAirMap2\require\class.Spotter.php on line 3815
Notice: Undefined offset: 0 in C:\xampp\htdocs\FlightAirMap2\require\class.Spotter.php on line 3816
Notice: Undefined offset: 0 in C:\xampp\htdocs\FlightAirMap2\require\class.Spotter.php on line 3817
Notice: Undefined offset: 0 in C:\xampp\htdocs\FlightAirMap2\require\class.Spotter.php on line 3820
Notice: Undefined offset: 0 in C:\xampp\htdocs\FlightAirMap2\require\class.Spotter.php on line 3821
Notice: Undefined offset: 0 in C:\xampp\htdocs\FlightAirMap2\require\class.Spotter.php on line 3822

Getting schedule info...
-> get arrival/departure airport info for DLH2310
New flight...
*********** New aircraft hex : 508123 ***********
Check if aircraft is already in DB... Already in DB.
DATA : hex : 508123 - ident :  - ICAO : B735 - Departure Airport :  - Arrival Airport :  - Latitude :  - Longitude :  - waypoints :  - Altitude :  - Heading :  - Speed :  - Departure Airport Time :  - Arrival Airport time :  - Source Name : Radarcape
\o/ Add  from sbs in Live DB : 
DATA : hex : 49D093 - ident :  - ICAO : A319 - Departure Airport : NA - Arrival Airport : NA - Latitude : 52.41777 - Longitude : 9.80224 - waypoints :  - Altitude : 250 - Heading : 32 - Speed : 419 - Departure Airport Time :  - Arrival Airport time :  - Source Name : Radarcape
\o/ Add  from sbs in Live DB : -- Delete previous data -- (Not adding to archive)success
Getting schedule info...
-> get arrival/departure airport info for TRA2L
Notice: Undefined offset: 0 in C:\xampp\htdocs\FlightAirMap2\require\class.Spotter.php on line 3815
Notice: Undefined offset: 0 in C:\xampp\htdocs\FlightAirMap2\require\class.Spotter.php on line 3816
Notice: Undefined offset: 0 in C:\xampp\htdocs\FlightAirMap2\require\class.Spotter.php on line 3817
Notice: Undefined offset: 0 in C:\xampp\htdocs\FlightAirMap2\require\class.Spotter.php on line 3820
Notice: Undefined offset: 0 in C:\xampp\htdocs\FlightAirMap2\require\class.Spotter.php on line 3821
Notice: Undefined offset: 0 in C:\xampp\htdocs\FlightAirMap2\require\class.Spotter.php on line 3822
Getting schedule info...
-> get arrival/departure airport info for RYR7386
Getting schedule info...
-> get arrival/departure airport info for EWG1HP
DATA : hex : 4CA24C - ident : RYR6AF - ICAO : B737 - Departure Airport : EGSS - Arrival Airport : EKBI - Latitude : 54.20705 - Longitude : 7.60113 - waypoints :  - Altitude : 326 - Heading : 35 - Speed : 421 - Departure Airport Time :  - Arrival Airport time :  - Source Name : Radarcape
\o/ Add RYR6AF from sbs in Live DB : -- Delete previous data -- (Add to Spotter archive : success)success
Getting schedule info...
-> get arrival/departure airport info for SXD8PK
DATA : hex : 484F18 - ident : KLM69M - ICAO : B738 - Departure Airport : AMS - Arrival Airport : FCO - Latitude : 52.10811 - Longitude : 5.48077 - waypoints :  - Altitude : 130 - Heading : 121 - Speed : 341 - Departure Airport Time :  - Arrival Airport time :  - Source Name : Radarcape
\o/ Add KLM69M from sbs in Live DB : -- Delete previous data -- (Not adding to archive)success
DATA : hex : 44CE65 - ident :  - ICAO : A319 - Departure Airport : NA - Arrival Airport : NA - Latitude : 52.49231 - Longitude : 5.39619 - waypoints :  - Altitude : 390 - Heading : 46 - Speed : 461 - Departure Airport Time :  - Arrival Airport time :  - Source Name : Radarcape
\o/ Add  from sbs in Live DB : -- Delete previous data -- (Add to Spotter archive : success)success
DATA : hex : 4CA7A5 - ident :  - ICAO : B738 - Departure Airport : NA - Arrival Airport : NA - Latitude : 52.09368 - Longitude : 5.08997 - waypoints :  - Altitude : 370 - Heading : 36 - Speed : 451 - Departure Airport Time :  - Arrival Airport time :  - Source Name : Radarcape
\o/ Add  from sbs in Live DB : -- Delete previous data -- (Add to Spotter archive : success)success

**Comment by me2tkt** [comment]
Now I get 

Fatal error: Cannot use isset() on the result of an expression (you can use "null !== expression" instead) in C:\xampp\htdocs\FlightAirMap2\require\class.Spotter.php on line 3816

and the web page wont load.

**Comment by Ysurac** [comment]
I did a strange copy-paste or something like that... Sorry about that.
Fixed in latest commit.

**Comment by me2tkt** [comment]
Everything looks good. Webpage running as normal.
Havent seen the error again but will keep looking in the log

Thank you
