### ISSUE TITLE
Alliances

### ISSUE THREAD

**Issue by me2tkt** [Ysurac/FlightAirMap#392]
If I select an alliance and then select an option e.g. airport the  resulting airport table has an option to search flights. This function gives the message "Sorry, your search did not produce any results. :("
The same error occurs when selecting aircraft.

Switching from one alliance to another doesnt work, and gives the message "Sorry, the airline does not exist in this database. :("

**Comment by Ysurac** [comment]
I'm not able to reproduce this one. On what page you have this issue ?

**Comment by me2tkt** [comment]
First select an Alliance e.g. Oneworld
![alliance](https://user-images.githubusercontent.com/23280102/35651249-5518bbc0-06df-11e8-9105-af35b8615b68.jpg)

Then select another alliance from the dropdown menu e.g Skyteam.
When you press the ">>" button the following message appears

![alliance1](https://user-images.githubusercontent.com/23280102/35651315-897ef848-06df-11e8-9ecb-d5110f132262.jpg)
