### ISSUE TITLE
BAF image fix

### ISSUE THREAD

**Issue by matchaniat** [Ysurac/FlightAirMap#397]
Hello,
Can you fix the BAF airline logo which correspond to Belgian Air Component (the name of the Belgian Air Force) and not British United Air Ferries.
Thanks in advance

**Comment by Ysurac** [comment]
I will fix it next week, but the problem is here: https://en.wikipedia.org/wiki/Belgian_Air_Component
The page doesn't have ICAO (https://en.wikipedia.org/wiki/British_United_Air_Ferries have ICAO)

**Comment by matchaniat** [comment]
I think the Belgian Air Force has picked up this code: https://www.planespotters.net/airline/Belgian-Air-Force. Thanks for the fix.
