### ISSUE TITLE
Installation hangs during DB Import

### ISSUE THREAD

**Issue by tbrumm** [Ysurac/FlightAirMap#4]
Hi,
i've tried yesterday to install FlightAirMap, but Installation hangs at the DB Installation (we importing....!) and no DB will be created.

Further Question:
During Installation sqlite is a prerequisite, but later you only use mysql/postgresql - ?!? For what you need Sqlite?

Kind regards

Torsten

**Comment by Ysurac** [comment]
Hi,
You can fetch latest commit, this should display the error at DB creation.
Do you use MySQL or PostgreSQL ?

We need sqlite because we fetch databases from virtualradarserver.co.uk and pp-sqb.mantma.co.uk, for routes and modes, that are in sqlite format. So sqlite is only needed for installation and update.

Thanks,
Ycarus

**Comment by tbrumm** [comment]
Hi Ysurac, i have fethced the commit yesterday night, so if there is any new, i will checkl again tonight. Thanks for clarification regarding SQLITE :-)

**Comment by tbrumm** [comment]
Hi Ysurac,
grabbed again the latest source tonight, now i don't get any error, nothing happens. Then i installed the DB/Updates by hand, changed settings.php and update.sh and got a running DB. Then is started cron-sbs.php inside screen. i see flights going in into the DB but i don't see any on the web page.

From apache error Log:
[Wed Jan 28 20:12:23 2015] [error] [client 192.168.222.110] Negotiation: discovered file(s) matching request: /var/www/about (None could be negotiated)., referer: http://raspberrypi01.local/
[Wed Jan 28 20:12:25 2015] [error] [client 192.168.222.110] File does not exist: /var/www/live, referer: http://raspberrypi01.local/
[Wed Jan 28 20:17:50 2015] [error] [client 192.168.222.110] Negotiation: discovered file(s) matching request: /var/www/statistics (None could be negotiated)., referer: http://raspberrypi01.local/

did i miss something at apache level?

Thanks

Torsten

**Comment by tbrumm** [comment]
Sorry, me again. figured out the problem with the rewrite settings. Hint for all Debian Users: http://serverfault.com/questions/372733/apache-file-negotiation-failed
