### ISSUE TITLE
Install-table Squack

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#40]
![captura](https://cloud.githubusercontent.com/assets/4571086/7901459/e4ebbbe8-0788-11e5-8e31-d5a965d4bb57.JPG)
![captura2](https://cloud.githubusercontent.com/assets/4571086/7901460/e7c748b4-0788-11e5-956f-e9355bc693f4.JPG)

**Comment by tonkepen100** [comment]
![captura](https://cloud.githubusercontent.com/assets/4571086/7901618/430b422c-0791-11e5-9da0-98f26d5d08d8.JPG)

**Comment by Ysurac** [comment]
Fixed (strange export of table...)
