### ISSUE TITLE
Issue with deamon

### ISSUE THREAD

**Issue by MrDalle** [Ysurac/FlightAirMap#400]
Hey,

somehow the map displays 1 flight several times and draw it to the map on same position.. maybe the cron is wrong? any ideas?

![unbenannt](https://user-images.githubusercontent.com/7756672/39622298-ee185ca4-4f91-11e8-9ac0-2bbab0dd4b72.JPG)

**Comment by Ysurac** [comment]
What is the source used ?

**Comment by MrDalle** [comment]
https://vas.fswire.net/api/v1/acars/data?format=phpVMS 

the Cron ist set do every min. and update_DB once a day

**Comment by MrDalle** [comment]
The map is running like 2-3 Hours then its crashing the whole server.. there is right now 1 plane but counter shows various numbers of planes...

**Comment by Ysurac** [comment]
I have it running, as daemon, since some day with this source, for now I have no problems.
I will try with cron.
Are you sure you have daemon mode disabled when running with cron (**$globalDaemon=FALSE**)?

**Comment by MrDalle** [comment]
found problem.. cron time and refresh on page was the problem...
