### ISSUE TITLE
Apache errors in installation

### ISSUE THREAD

**Issue by mathni** [Ysurac/FlightAirMap#405]
Hello,
![image](https://user-images.githubusercontent.com/40674366/42057521-dca49a34-7b1d-11e8-936e-12467761d861.jpg)
![image](https://user-images.githubusercontent.com/40674366/42057550-ff35a804-7b1d-11e8-9dcd-32e987ec8e39.jpg)

I try to install but I read,two errors on the webpage 127.0.0.1/install/index.php

- rewrite don’t seems to work well. You need to desactivate MultiViews.
- /var/.../.htaccess doesn’t exist.

My 000-default.conf is attached. I tried two versions (Apache<2.4 and >2.4).

I think apache is 2.4.24 version.

Thank you for help.

Mathni.

**Comment by Ysurac** [comment]
So you know the problem... Put the .htaccess.
And take real screenshot please...

**Comment by mathni** [comment]
Sorry for screenshot’s quality.

I dont’ know where I must create .htaccess file exactly and file content.
I don’t see this step on installation tutorial.
Thanks

**Comment by Ysurac** [comment]
It's in the source: https://github.com/Ysurac/FlightAirMap/blob/master/.htaccess

**Comment by mathni** [comment]
Perfect. it’s ok for this problem.

Now i have an error when i launch install step with web browser.

Write configuration... success
Create and import tables...failed

I created database flightairmap with commands and max_allowed_packet=16M for Mariadb

Message
Error: error : SQLSTATE[HY000] [2002] php_network_getadresses: getaddrinfo failed: Name or service not known

I test without create database toggle but it’s wrong too.

**Comment by Ysurac** [comment]
The error is that it can't access the database at the name/ip you give.

**Comment by mathni** [comment]
Resolved: error with hostname... Thanks.
