### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by lgdeysel1980** [Ysurac/FlightAirMap#407]
Good day,

Followed the installation instructions. Ensured that all php modules were available. 
I checked my phpinfo for more details on what modules are installed. Since I couldn't see mod_rewrite, I did a test of it as well.

As you can see it's working, so my host has most probably got it's own mod_rewrite as it seems the SERVER API is on CGI/Fast CGI

I put the folder in my public_html folder. Added the Apache >V4 into my .htaccess file. The moment I do that I cannot access anything else on my site. Install index.php still gives Internal Server error.

After removing the added info in .htaccess everything seems to work again. Still install/index.php give Internal Server error.

Any ideas?

**Comment by Ysurac** [comment]
You should look at your log files to know the real error.

**Comment by Ysurac** [comment]
Should be in flightairmap directory, it's where it is by default.
But there is no "DocumentRoot" settings in the .htaccess, you have .htaccess of the repository ?

**Comment by lgdeysel1980** [comment]
Yes.

Nevermind. I think I figured it out. On the install you have adjustment to the webserver for Apache. I don't have access to make any changes to it except for via CPanel.

Sorry about the confusion. I'll have to remove this then. :(

**Comment by Ysurac** [comment]
webserver change are only needed in some case.
I know this work on some CPanel VPS, but each administrator can configure it like he want, so no idea if it's your case.

**Comment by lgdeysel1980** [comment]
I'm on a shared server so I don't get access to that side of the server. Thanks though!
