### ISSUE TITLE
Error_Log

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#41]
The error_log file in the Install folder fills up and overflows the sevidor ....

![captura](https://cloud.githubusercontent.com/assets/4571086/7901547/3dda633a-078e-11e5-90a5-332842947eae.JPG)

**Comment by Ysurac** [comment]
what are the errors in this error log ?

**Comment by tonkepen100** [comment]
then I'm sorry, because to fill so fast, and I had to delete because it fired a 2GB file.

**Comment by tonkepen100** [comment]
but it was safe for the error of the table squawk

**Comment by Ysurac** [comment]
If you have others error in an error_log, open a bug with the error :)

**Comment by tonkepen100** [comment]
Not quiet and not open any more.
