### ISSUE TITLE
Raspberry pi3 install script

### ISSUE THREAD

**Issue by ivandiazperez** [Ysurac/FlightAirMap#415]
Hi there!
I followed all the steps and everything seem to have gone smoothly but, when I try to load http://192.168.1.43/flightairmap/install/index.php
just a blank page is shown.
No errors at all, nothing.

Any ideas?
Thanks!

**Comment by Ysurac** [comment]
no need to open a bug multiple times...
Did you update to latest commit ?

**Comment by ivandiazperez** [comment]
Yes, I was not aware that I was posting on the wrong place. Really sorry for that.
I installed today for the first time, so I guess that I have the latest version of it all.
Right?

**Comment by Ysurac** [comment]
no. I fixed the bug in spotter_import.php

**Comment by ivandiazperez** [comment]
Now that it is fixed, how should update my current install?

**Comment by Ysurac** [comment]
git pull in flightairmap directory

**Comment by ivandiazperez** [comment]
That worked! :) Now, moving on with the install. What you do here is from another world. Impressive, really.

**Comment by ivandiazperez** [comment]
Up and running, thanks!
I am going to open a new thread regarding the importing of SBS data from a text file
