### ISSUE TITLE
Scripts error.log

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#42]
when the cron want to update the tables again fills the server error.log ...

![captura](https://cloud.githubusercontent.com/assets/4571086/7901891/dddff758-079f-11e5-99e7-a1ea151630f1.JPG)

**Comment by Ysurac** [comment]
Fixed in commit bc945ab

**Comment by tonkepen100** [comment]
Sorry but equal...

![image](https://cloud.githubusercontent.com/assets/4571086/7902026/90853538-07a7-11e5-801b-36723d439abc.png)

**Comment by Ysurac** [comment]
Are you sure you updated to latest commit ?

**Comment by tonkepen100** [comment]
Yeah, that error does not come out, now this goes .... to running the cron sbs

![captura](https://cloud.githubusercontent.com/assets/4571086/7902544/49b63114-07bd-11e5-835d-54b8dee347e4.JPG)

**Comment by Ysurac** [comment]
Are you sure you don't have some connection problems ?

**Comment by tonkepen100** [comment]
For the truly connections are OK, and before data entry work with the latest revision as `apparently not.

**Comment by tonkepen100** [comment]
cron opens the connection, grabs a plane and zassss antonio tells me you're staying with the desire to run your radar.
![captura](https://cloud.githubusercontent.com/assets/4571086/7902724/0f89bc9e-07c3-11e5-8bba-2b5b628b5eef.JPG)
