### ISSUE TITLE
Collation tables

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#43]
This can be solved in some way ?.

![captura](https://cloud.githubusercontent.com/assets/4571086/7904066/e12422be-07ee-11e5-91a0-9e8dbf620aee.JPG)

**Comment by Ysurac** [comment]
Commit 9e7fdcf19cf8d4fc8ed4bffef096060ede51a19d maybe fix your problem.

**Comment by tonkepen100** [comment]
The bigggggggggggggggggggggggggg Ysuraccccccccc , OLEEEEEEEEEEEE
