### ISSUE TITLE
Table to Text .. and shot that touches me

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#44]
Well after my greatest success of my computer science, continuous history with another equally important challenge.

This time I return to the fray with my tracker website htttp: //piro.biz .....

As we know the web grabs 5 wazzup.txt data files on different servers, which are compatible with airmap it confirmed since this works,

Web grabs that data and enters them into a table only if the flight is registered on the web.

![captura](https://cloud.githubusercontent.com/assets/4571086/7910289/acaa6d26-0853-11e5-8106-3197f9c3f94d.JPG)

Airmap grabs no data tables, so here comes the big question:

1. It is technically possible that this table send the data to a txt file format compatible with airmap?

2. We need to be a computer engineer to be able to do?

3. If you can technically there where you can see how compatible data file for that notation ?.

And as always, thanks.

**Comment by Ysurac** [comment]
What do you have in your */lib/skins/skyline/js/recentpireps.php* file ? maybe it's quite easy to add departure/arrival airports and all data needed in json for flightairmap.

**Comment by tonkepen100** [comment]
Well I have this ....

<?php 
ini_set('display_errors',1); 
error_reporting(E_ALL);
function GetDistance($laty1, $lonx1, $laty2, $lonx2) {

	$radius = 3443.917;

	$pi = 3.141593;

	$d = $pi / 180;

	

	$laty1 = $laty1 * $d;

	$lonx1 = $lonx1 * $d;

	$laty2 = $laty2 * $d;

	$lonx2 = $lonx2 * $d;

	

	$z1 = sin($laty1);

	$x1 = sin($lonx1) * cos($laty1);

	$y1 = cos($lonx1) * cos($laty1);

	$z2 = sin($laty2);

	$x2 = sin($lonx2) * cos($laty2);

	$y2 = cos($lonx2) * cos($laty2);

	

	$l1 = sqrt($z1 * $z1 + $x1 * $x1 + $y1 * $y1);

	$l2 = sqrt($z2 * $z2 + $x2 * $x2 + $y2 * $y2);

	

	$in = $x1 * $x2 + $y1 * $y2 + $z1 * $z2;

	

	$arc = acos($in / ($l1 * $l2));

	$dis = $arc * $radius;

	return $dis;

}

header("Content-type: application/json");
//Database information
$dbhost = "127.0.0.1";	//the host, normally localhost
$dbuser = "OLEEEEEEEEE";	//the username
$dbpass = "OLEEEEEEEEEE";	//the password
$dbname = "OLEEEEEEEEE";	//the database name
if ($dbname == "") die("Could not find Settings.php or no information entered in Settings.php.");
$con = mysql_connect($dbhost,$dbuser,$dbpass) or die("Could not connect to database, please check Settings.php.");
$db_selected = mysql_select_db($dbname,$con) or die("Could not select database, please check Settings.php.");
			
	$a="{\"pireps\":[" ;
			
		$sqlb = "SELECT * FROM phpvms_acarsdata";
		$Trackresult2 = mysql_query($sqlb);

			$i=1;

				while($rows2 = mysql_fetch_assoc($Trackresult2))

				{
					//get available data from phpvms_acarsdata table
					$array= json_decode($rows2['client']);
					$planedata= explode("/", $array[9]);
					$acwake=explode("-", $planedata[2]);
					$icon="plane";
					$pilotid=$rows2['pilotid'];
					$id=$rows2['id'];
    				$deplat=  $rows2['deplat'] ;
					$deplng=  $rows2['deplng'] ;
    				$arrlat=  $rows2['destlat'] ;
					$arrlng=  $rows2['destlng'] ;
					
					
					$alt=$rows2['alt'];

					$lat=$rows2['lat'];

					$lng=$rows2['lng'];

					$name=$rows2['pilotname'];

					$callsign=$array[0];
										
					$pilotid=$rows2['pilotid'];

					$sql = "SELECT * FROM phpvms_pilots  WHERE pilotid='$pilotid'"; 
     				$pilotinfo = mysql_fetch_assoc(mysql_query($sql));
					$name=$pilotinfo['firstname'];
					
					
									
					
					if($i==1){$a .= "{\"id\":\"".$id."\",\"callsign\":\"".$callsign."\",\"name\":\"".$name."\",\"icon\":\"".$icon."\",\"deplat\":\"".$deplat."\",\"deplng\":\"".$deplng."\",\"arrlat\":\"".$arrlat."\",\"arrlng\":\"".$arrlng."\",\"title\":\"".$callsign."\",\"lat\":\"".$lat."\",\"lon\":\"".$lng."\"}"; $i++;}

					else {$a .=",{\"id\":\"".$id."\",\"callsign\":\"".$callsign."\",\"name\":\"".$name."\",\"icon\":\"".$icon."\",\"pilotid\":\"".$pilotid."\",\"deplat\":\"".$deplat."\",\"deplng\":\"".$deplng."\",\"arrlat\":\"".$arrlat."\",\"arrlng\":\"".$arrlng."\",\"title\":\"".$callsign."\",\"lat\":\"".$lat."\",\"lon\":\"".$lng."\"}";} 
					

					}
			$sqlb = "SELECT * FROM pir_currentatc";
			$Trackresult3 = mysql_query($sqlb);
				while($rows2 = mysql_fetch_assoc($Trackresult3))

				{
					//get available data from phpvms_acarsdata table
					
					$pilotid=$rows2['pilotid'];
					$id=$rows2['id'];
    				$deplat=  $rows2['lat'] ;
					$deplng=  $rows2['lng'] ;
    				$arrlat=  $rows2['lat'] ;
					$arrlng=  $rows2['lng'] ;
					
					
					$alt=0;

					$lat=$rows2['lat'];

					$lng=$rows2['lng'];

					$name=$rows2['name'];

					$callsign=$rows2['position'];
										
					$pilotid=$rows2['pilotid'];

					$sql = "SELECT * FROM phpvms_pilots  WHERE pilotid='$pilotid'"; 
     				$pilotinfo = mysql_fetch_assoc(mysql_query($sql));
					
					$icon ="ct";
					$name=$pilotinfo['firstname'];
					
					
					$a .=",{\"id\":\"".$id."\",\"callsign\":\"".$callsign."\",\"name\":\"".$name."\",\"icon\":\"".$icon."\",\"pilotid\":\"".$pilotid."\",\"deplat\":\"".$deplat."\",\"deplng\":\"".$deplng."\",\"arrlat\":\"".$arrlat."\",\"arrlng\":\"".$arrlng."\",\"title\":\"".$callsign."\",\"lat\":\"".$lat."\",\"lon\":\"".$lng."\"}";
					
					}
				
			
			
				$a .= "]}" ;  
				
echo $a;


?>

**Comment by Ysurac** [comment]
What are the columns available in **pir_currentatc** ?

**Comment by tonkepen100** [comment]
Oysters, now if you do not understand what you ask me, I'm really sorry

You give me permission to send an email?

**Comment by tonkepen100** [comment]
Ahhhhhhhhhhhh this sorry....
![captura](https://cloud.githubusercontent.com/assets/4571086/7932077/e9fccce2-0915-11e5-81b9-05a9fe8aa5d1.JPG)

**Comment by Ysurac** [comment]
If you replace **/lib/skins/skyline/js/recentpireps.php** with http://pastebin.com/A8y9xPvf then I will be able to use the json we get (and everything that is using this file will keep working).

**Comment by tonkepen100** [comment]
Ysurac change it, but look that does not leave the map of flights in Piro. so it is when I change the file ....

![captura](https://cloud.githubusercontent.com/assets/4571086/7933847/889cd606-0922-11e5-9218-b6aba57d05a1.JPG)

**Comment by Ysurac** [comment]
You have to put your real password in file this time

**Comment by tonkepen100** [comment]
Ojjjjjj ,sorry, i put sorry

**Comment by Ysurac** [comment]
Support is added in latest commit. You need to set **$globalSBS1Hosts = array('http://piro.biz/lib/skins/skyline/js/recentpireps.php');** in *require/settings.php*.
If you want to also have speed, you need again to replace **/lib/skins/skyline/js/recentpireps.php** by http://pastebin.com/ELnthGjj (sorry, I forgot speed)

**Comment by Ysurac** [comment]
You also have to set **$globalCronEnd = '0';** else *cron-sbs.php* download file too often.

**Comment by Ysurac** [comment]
If you want to also have aircraft type, you need again to replace **/lib/skins/skyline/js/recentpireps.php** by http://pastebin.com/AA4VdhQL (this time we will have all data we can have...)

**Comment by tonkepen100** [comment]
I believe that God exists, I really believe that God exists, look .....

![captura](https://cloud.githubusercontent.com/assets/4571086/7940391/d755a5f6-0950-11e5-9db7-042aed24681c.JPG)


And what is the name of God? .... Ysurac perhaps?

**Comment by tonkepen100** [comment]
Good God it works, really works.

But now I have a dilemma, serious question of erasing what I have and put it back around to the statistics departing from scratch?

I think that would be best, because the database will be with the old data from my sbs.

  Input and not the last data changed pastebin, you told me, but I think that would be best.

On the other hand say that I'm talking to the mayor of my city to see if they make a monument,

**Comment by Ysurac** [comment]
You can truncate table : **spotter_output**,**spotter_live** and **spotter_archive**.

You will have more infos with the latest pastebin.

**Comment by tonkepen100** [comment]
Bagpipes, and now I'm completely lost, and not what the situation, I will put it all back, so that I stay calmer. and we test, I'm excited, I radiate happiness.

**Comment by tonkepen100** [comment]
Ysurac dear friend, and since as you said the pastebin, but please look at it because I think there's something wrong, go but disappear from time to time, and the data do not come, it is rare lake, perhaps maybe be the parameters config, the truth is not.

httt;//airpiro.ovh

Thnaks

**Comment by tonkepen100** [comment]
Ysurac Well, I think I have already slightly dominated, like every two minutes wazzp sends the data to the web, and since it is recharged every two minutes and seems to be stable.

Though it would be sensational to tell me how you think you have to put your settings for optimal performance out.

On the other hand I have attached photos to see if they could fix this point ....

![captura](https://cloud.githubusercontent.com/assets/4571086/7968256/d7c15c6c-0a2f-11e5-8acf-00e02510b0c6.JPG)


As always I appreciate your effort

**Comment by Ysurac** [comment]
For aircraft fix is in commit 464c6a5
For settings you can increase **$globalLiveInterval** to 300 for example.

**Comment by tonkepen100** [comment]
Good. now out but it seems that just likes 747-400
![captura](https://cloud.githubusercontent.com/assets/4571086/7969549/e1e7e4d8-0a37-11e5-8940-999fd1e73835.JPG)

**Comment by Ysurac** [comment]
wait and/or refresh page

**Comment by tonkepen100** [comment]
I need it please you to register on the web, as we have determined that we are going to put a banner of your company, and we'll put as a member of honor.

As you can put the VID quiet ivao what you put me.

http://piro.biz

**Comment by tonkepen100** [comment]
Hola  Ysurac, You think you could somehow fix the images of the planes?

![captura1](https://cloud.githubusercontent.com/assets/4571086/7978565/f7def8f8-0a96-11e5-982e-d3f9e4de5b85.JPG)

**Comment by tonkepen100** [comment]
is that the only two data that are not reflected squack and images of aircraft,

**Comment by tonkepen100** [comment]
Look, look, look how wonderful ....


![captura](https://cloud.githubusercontent.com/assets/4571086/7978674/5d407586-0a98-11e5-9c77-d120420fac6c.JPG)

**Comment by Ysurac** [comment]
I can't fix the image of plane because there is no images of planes. The plane doesn't exist in reality so no pics available. When it's not IVAO it's really the pics of the plane, not aircraft model.

For Squawk, I can't because I don't have the data.

For airlines, it's also because it's not real airlines. I have to make a table with virtual airlines from IVAO.

**Comment by tonkepen100** [comment]
Not the airlines with the exception of virtual as well tell you, I understand that it is logical to leave so, that's no problem.

The squack if we look out on the table acarsdata,,,,

![capturatrans](https://cloud.githubusercontent.com/assets/4571086/7979218/90b6b45c-0a9d-11e5-9506-d9e71b77269c.JPG)


And the images could not tell him to take on such side for some generic aircraft model or example ?, I put in a folder that pictures and take from there ?, I no clear solutions to my specific case this will think.

**Comment by tonkepen100** [comment]
And look at this curious title, now I'm flying GCXO to FACT. As you can see in the flight plan that sent ivao look .....

![plan](https://cloud.githubusercontent.com/assets/4571086/7979321/82beb8bc-0a9e-11e5-8e54-7b644a937fc3.JPG)

and our table as indeed also collects the data, look ....

![captura](https://cloud.githubusercontent.com/assets/4571086/7979328/8a90c94a-0a9e-11e5-8a77-40a0a02bf1a8.JPG)

and table...

![capturaasdasd](https://cloud.githubusercontent.com/assets/4571086/7979347/b2b5e13a-0a9e-11e5-892b-8dc0ae458194.JPG)


And here's the funny thing in my flight pinchame airmap and see ... jejejejeje to me is the only one who does not want to put the data well, will be detected by that I'm the boss of Piro, said ehhhh to you annoyance.

![captura2](https://cloud.githubusercontent.com/assets/4571086/7979352/baffc14e-0a9e-11e5-88a4-7906def73ffd.JPG)


It is curious

**Comment by Ysurac** [comment]
For Squawk, you have to replace again **/lib/skins/skyline/js/recentpireps.php** by http://pastebin.com/qRRJENXA
For routes, it's because it use route table to find route, so it replace route by data in this table. I will check what I can do.
For pics I will try to get them from Wikipedia.

**Comment by tonkepen100** [comment]
Ycarus fuck love you more every day, you really are a man to admire

**Comment by tonkepen100** [comment]
Huy with the latter pastebin flight map will not come flying in airpiro

![captura2](https://cloud.githubusercontent.com/assets/4571086/7979621/21741ee6-0aa1-11e5-9517-102a81dc2588.JPG)

![captura](https://cloud.githubusercontent.com/assets/4571086/7979629/298d47c4-0aa1-11e5-811e-dfe28c9530e4.JPG)

**Comment by Ysurac** [comment]
Sorry, should be fixed with this one : http://pastebin.com/XHmNT0K1

**Comment by tonkepen100** [comment]
Ohhhh lala, gooddddddd

**Comment by Ysurac** [comment]
Squawk support will be added in **cron-sbs.php** in next commit.

**Comment by tonkepen100** [comment]
Thank Yca, thanks

**Comment by tonkepen100** [comment]
Mais voyons Ycarus, zugaina est une société de logiciel qui non?, le vôtre plutôt que toute la journée vous dérange, ne parviennent pas à un accord et le même projet vous appliquez un Piro. Je veux dire par exemple la carte de la couverture et le tracker, tracker de vous ne pouvez pas voir et je pense que si vous n'êtes pas inscrit, inscrivez-vous et ainsi vous rendre compte quelle vue.

Sur les autres études de la main et combien vous voulez charger l'homme de l'avant, nous avons laissé les deux bénéficiaires.

Os vôtre est le même projet, mais pyro intégré, et laissez-moi de citer ci-dessous.

**Comment by Ysurac** [comment]
We will see that next week ;)
You can update to latest commit, if you use IVAO as source in install script (or set **$globalIVAO = TRUE;** in *settings.php*) there will be no problems with routes. You should also see some pics of aircrafts.

**Comment by tonkepen100** [comment]
Hi thanks Oh, is that yesterday was not well physically, now put it and look, thanks again

**Comment by tonkepen100** [comment]
But one wonders if the whole climb again, I have to run Install again or not?

**Comment by Ysurac** [comment]
Yes, to update some tables.

**Comment by tonkepen100** [comment]
aja in this moment up the new

**Comment by tonkepen100** [comment]
YESSSSSSSSSSSSSSSSSSSSSS, YESSSSSSSSSSSSSSSS AND YESSSSSSSSSSSSSSSSS

oHJJJJJJJJJJJJ, OJJJJJJJJJJJJJ.... SEEEEEEEEEEEE.......

![captura](https://cloud.githubusercontent.com/assets/4571086/8001703/7101412e-0b68-11e5-8c87-b7cad62d7e39.JPG)


My God will give me a heart attack

**Comment by tonkepen100** [comment]
But here I have something bad about you leave the old config, I'll put the new data step back, because I think something got wrong

**Comment by tonkepen100** [comment]
YSURAC Here we have to put ?,

![captura](https://cloud.githubusercontent.com/assets/4571086/8002062/ea4b8eec-0b6b-11e5-8e75-2c7c6a667f03.JPG)

**Comment by Ysurac** [comment]
It's to display sources location on map, not really needed for IVAO.

**Comment by tonkepen100** [comment]
OLEEEEEEEEE YSURAC

![captura](https://cloud.githubusercontent.com/assets/4571086/8003532/a5d511ea-0b78-11e5-9f30-dbaa61d61093.JPG)

**Comment by tonkepen100** [comment]
![captura](https://cloud.githubusercontent.com/assets/4571086/8002062/ea4b8eec-0b6b-11e5-8e75-2c7c6a667f03.JPG)


But if you could use to mark Hubs piro no ?.

What happens is that if so, where manually put in the config file ?, mine I see these entries.

Thanks Ysurac

**Comment by Ysurac** [comment]
You can mark what you want. Data are put in **source_location** table.

**Comment by tonkepen100** [comment]
Longitude-Latitude and Elevation = Coordenates Decimales and Feets ?
