### ISSUE TITLE
Offline Map

### ISSUE THREAD

**Issue by ghost** [Ysurac/FlightAirMap#458]
Hello,
I was not able to find any answer on this topic....how to use offline map ?
I need to use FlightAirMap in total offline mode on a server with no connection to internet.
But the map tiles always need a internet connection.

Have I missed something ?
Please, need help.

**Comment by Ysurac** [comment]
In ```require/settings.php``` you can set ```$globalMapOffline``` to ```TRUE``` or choose "Natural Earth (local)" as type of map in settings.

**Comment by ghost** [comment]
Yes, right,
But in despite of this, I cannot see the tiles offline or with difficulty..
Must we download them before ?

**Comment by Ysurac** [comment]
Tiles come from my modified Cesium repo (here : https://github.com/Ysurac/Cesium-minified/tree/master/Assets/Textures/NaturalEarthII), you should have it if the repo was cloned with --recursive.

**Comment by ghost** [comment]
Oh ok I will try it tomorrow. Thanks for your answer

**Comment by ghost** [comment]
So, @Ysurac 
I tried with no good result :-(
- I cloned the repo with --recursive and I got the tiles
- During the install, I checked the option "Map Offline"
- In the App I saw, in the menu, the map selected is Natural Earth
But when I display the map, it's always OpenStreetMap's.... et when I go offline, I get Javascript Errors for trying to download tiles from OpenStreeMap...

Merci pour ton aide ;-)
Ton application est vraiment superbe, et fait tout ce dont j'ai besoin, me manque plus que le mode offline.

**Comment by Ysurac** [comment]
This can be related to the cookie in the browser set to previous selected map. Remove it, or try with another browser.

**Comment by ghost** [comment]
Nop, I deleted the cookies, I tried Chrome / Brave / Firefox, with private navigation....and it's still the same

**Comment by ghost** [comment]
Ok I found the solution.
I switched $globalMapOffline to FALSE, then I return to the app and selected Natural Earth....
Again I switched $globalMapOffline to TRUE...and that works
Thanks for your help.

If I can, let me ask you another question about these tiles, are we able to have more zoom precision by downloading more tiles from Natural Earth ?

**Comment by Ysurac** [comment]
Maybe, you can try: https://www.naturalearthdata.com/downloads/10m-raster-data/10m-natural-earth-2/

**Comment by ghost** [comment]
Ok that's what I saw.. you confirm I am in the right way.
Thank you so much being so avalaible.
I appreciate. I close this issue.
Bye
