### ISSUE TITLE
mobile menu

### ISSUE THREAD

**Issue by c0by1** [Ysurac/FlightAirMap#47]
device: oneplus one
android: 5.02

could you move the statistic menu, a little bit to the left?

can't see the menu button.

![image](https://cloud.githubusercontent.com/assets/5725891/7920144/40ce5500-089d-11e5-9773-70c3e9c8d443.png)

**Comment by c0by1** [comment]
at the pc is all fine...

**Comment by tonkepen100** [comment]
Dear friend, I feel that vouch for having you here, it is that it is not fastened properly, but I did not find your mail, and you forgive me ysurac.

Are you registered on my website, but having no system id ivao you unsubscribe directly, and forgive me if you want to see the inside of PIRO please tell me and I will be delighted to have you with us

**Comment by Ysurac** [comment]
Fixed in commit f12383b
tonkepen100 I don't understand what your comment is doing here...

**Comment by tonkepen100** [comment]
sorry the comment was for c0by1, which try to register my site, but has no account on the system ivao rejects my website. and as my English Pope writes google me, because I understand that things are understood and sorry
