### ISSUE TITLE
Cron update_db (waipoints)

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#48]
When cron runs update_db all tables are filled except for the waipoints table.

thanks

**Comment by Ysurac** [comment]
**update_db.php** don't update waypoints table because this table don't need updates for now.

**Comment by tonkepen100** [comment]
Ah, but in my case it is empty, meaning that it is impossible to leave the waipoints, and before if they left,

look http://piro.biz

![captura](https://cloud.githubusercontent.com/assets/4571086/7931650/b3f7b57e-0912-11e5-8bac-41f861d65347.JPG)

**Comment by Ysurac** [comment]
In last commit I added a script **install/populate_db.php** to populate waypoints and airspace table.
