### ISSUE TITLE
strange altitude data?!

### ISSUE THREAD

**Issue by c0by1** [Ysurac/FlightAirMap#49]
what is this?

error or bug or reading errors?

![image](https://cloud.githubusercontent.com/assets/5725891/7934851/af5fb584-092b-11e5-8b99-95a7a4d1da40.png)

**Comment by Ysurac** [comment]
This was a check for strange altitude data, but it was not good. Sorry. I will make a better check asap
Fixed in commit ab9f47e7e5d95d6c10a4d77a8520d029b24342cc
