### ISSUE TITLE
Feature Request: Display location of my antenna / house

### ISSUE THREAD

**Issue by Zerstoiber** [Ysurac/FlightAirMap#50]
I would like to Display the Position of my antenna / my house on the Card.

Please add the Feature analogous to dump1090.
![dump1090_2015-06-02_18-57-50](https://cloud.githubusercontent.com/assets/12717815/7941704/4ec26dce-0959-11e5-9c81-aa3f8c711398.png)

**Comment by mluett** [comment]
This would be a feature I am also interested in!

**Comment by Ysurac** [comment]
This will be done asap.

**Comment by Ysurac** [comment]
Done in commit eef259b6b676a1d8377b76665a640b3ea81bfe84

**Comment by c0by1** [comment]
where is the data saved for this? i have two points... and i want to delete one.

**Comment by c0by1** [comment]
found it and delete it in the mysql db...

**Comment by Zerstoiber** [comment]
great work

**Comment by c0by1** [comment]
jupp great
