### ISSUE TITLE
Raspberry pi 2 Problem with cron-sbs.php

### ISSUE THREAD

**Issue by lordkane** [Ysurac/FlightAirMap#51]
Hi i have a Problem with cron-sbs.php i do not stop it .But the script cron-sbs.php (look the screenshoot) stop why ?
Sorry for my bad englisch.

Can you help me .... 
![Uploading cron-sbs.jpg…]()

Thanks
Mike

**Comment by Ysurac** [comment]
Do you have **$globalDaemon** set to **TRUE** in *require/settings.php* ?

**Comment by lordkane** [comment]
yes // DAEMON
$globalDaemon = TRUE; // Run cron-sbs.php as daemon (don't work well if source is a real SBS1 device)
$globalCronEnd = '60'; //the script run for xx seconds if $globalDaemon is disable in SBS mode

**Comment by Ysurac** [comment]
Do you have also **$globalDebug** set to **TRUE** ?

**Comment by lordkane** [comment]
Yes i have

**Comment by Ysurac** [comment]
really strange... Can you paste **settings.php** on pastebin.com, without passwords ?

**Comment by lordkane** [comment]
i reboot the pi2 now it work .... pi is dump1090 and flightairmap

**Comment by lordkane** [comment]
Thanks for you help
