### ISSUE TITLE
No Destination Information

### ISSUE THREAD

**Issue by Zerstoiber** [Ysurac/FlightAirMap#52]
90% of my flights has no Destination Information.
Any idea why?
![home _ airmap statistik_2015-06-03_09-26-50](https://cloud.githubusercontent.com/assets/12717815/7954799/f9db3be0-09d2-11e5-9c00-373058ffd449.png)

**Comment by c0by1** [comment]
i can't confirm... all looks good... got 30 flights at same and 2 - 6 without destination...

![image](https://cloud.githubusercontent.com/assets/5725891/7954837/58d8a81c-09d3-11e5-8362-5ba60f7b4e52.png)

![image](https://cloud.githubusercontent.com/assets/5725891/7954851/7949108c-09d3-11e5-8cfd-efefadd4380e.png)

**Comment by Ysurac** [comment]
Zerstoiber do you use **install/install_db.sh** to populate DB ?
I fixed a bug in this script for routes in commit 5a215013a740b500c39da8ea97d26f37c926ca57
You should always use PHP scripts.

**Comment by Zerstoiber** [comment]
Yes i use the install_db.sh script.

Its possible to fix it now?

**Comment by Ysurac** [comment]
Yes, you can run **populate_all.php** (pull latest commit) or **update_db.php**.
If this don't work, you have to do a **truncate table routes** in MySQL/MariaDB/... and run **populate_all.php** or **update_db.php** again.

**Comment by c0by1** [comment]
./update_db.php doesnt work... need to use ./populate_all.php

root@y: /var/www/flight/install # ./update_db.php
root@y: /var/www//flight/install #

**Comment by Ysurac** [comment]
There is a limit in **update_db.php**, you can run it only every 15 days if you already run it, you can't again. It's to limit downloads on external websites, don't want to use too much bandwidth on them.

**Comment by mluett** [comment]
sound great, thanks guys!

**Comment by Zerstoiber** [comment]
now it works perfect.

i must truncate table routes first and run populate_all.php

Thanks guys
