### ISSUE TITLE
Table Waipoints

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#54]
Please anyone who has updated the table waipoints, be so kind as to give it to me, I do not load, since a few days ago, I get always empty.

Thank you.

**Comment by Ysurac** [comment]
You can run **install/populate_all.php**.
Waypoints table is used only to display them on map.

**Comment by tonkepen100** [comment]
Good Now if they are sensational loading the tables thanks ysurac
![captura](https://cloud.githubusercontent.com/assets/4571086/7969609/5136d8f8-0a38-11e5-8000-809e7ee9f2cd.JPG)
