### ISSUE TITLE
Flightaware and Links not working

### ISSUE THREAD

**Issue by nzradar** [Ysurac/FlightAirMap#6]
I have installed and configured Flightaware as data source and also tried SBS (30003) but see no flights?

Secondly, when selecting a menu option from index.php page all I get is:

Not Found
The requested URL /statistics was not found on this server.

The url has the page name but no .php extension.

How does the Flightaware/SBS data get in?
How do I move from one page to another?

Running on Win7 with all the necessary modules loaded so on index.php I see a map with airports and options and also a menu at the top.

When I did the install I got this error when running install/index.php:

error : SQLSTATE[HY093]: Invalid parameter number: mixed named and positional parameters
 

Thanks,
Michael
hfaero.com

**Comment by Ysurac** [comment]
For FlightAware you need an API account. This is no more tested.
SBS is tested with dump1090, this is working.
If you use apache, the .htaccess should be read and should have no problems to find URL.

To get data you have to run "php cron.php" for flightaware and "php cron-sbs.php" for SBS (this one is a daemon, not cron, I have to change the name...).

This was never tested under windows, no idea if it work well (maybe not at all).

Install script should work well in new lastest commit.

Thanks,
Ycarus

**Comment by nzradar** [comment]
Hi Again,

 

When I run cron-sbs.php I get this error:

 

#!/usr/bin/php 
Notice: Undefined index: _ in E:\Apache24\htdocs\cron-sbs.php on line 10

Fatal error: Call to undefined function pcntl_signal() in E:\Apache24\htdocs\cron-sbs.php on line 12

 

It seems that there is no server identified on this line:

 

$_ = $_SERVER['_'];

 

What should go in the quotes?

 

Thanks,

Michael

**Comment by Ysurac** [comment]
In latest commit $_SERVER['_'] is no more used (not available under windows).

But for pcntl_signal() it's more difficult. pcntl is not available under windows.

I will try to make a slimmed-down version when pcntl is not available.

**Comment by nzradar** [comment]
Thanks again,

 

Will you app run on a Raspberry Pi2?

 

Cheers,

Michael

**Comment by Ysurac** [comment]
Yes, with Raspbian for example.
