### ISSUE TITLE
Time Meridian

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#62]
There would be any way to remove the problem of passing the meridian lines of the Pacific,

View Photo ...

Thank you.
![captura](https://cloud.githubusercontent.com/assets/4571086/8036313/685be736-0df7-11e5-881a-f4cd8544b183.PNG)

**Comment by tonkepen100** [comment]
Ysurac thank you very much, as always solving all problems.

After changing the file, I have to do something specific happen again ?, tables or something special or just to step on and work?

Thanks again

**Comment by tonkepen100** [comment]
Zambombas for now appears to be broken

**Comment by tonkepen100** [comment]
Ostiasssssssssssss, but if you get the number of pirooooo, my God gives me a heart attack, this is the pump, the pump
![captura](https://cloud.githubusercontent.com/assets/4571086/8103924/e1493b12-102c-11e5-9f52-bc6c44e09f70.PNG)

to see to see, ysurac where you can be anything you donate, send paypal account or god

**Comment by Ysurac** [comment]
Zambombas ? what is that ?

**Comment by tonkepen100** [comment]
ahhhh forgiveness is an expression in Spain, as saying this is milk. this is great etc etc.

But if zambomba in this ....

![images](https://cloud.githubusercontent.com/assets/4571086/8104130/9ac486ea-102e-11e5-9dd6-eb2c45a6ff5b.jpg)

Christmas typical musical instrument

**Comment by Ysurac** [comment]
ok

**Comment by tonkepen100** [comment]
What I see now is that the icons of the airplanes out as very small and I no longer appear as class, that's okay ?.

![captura](https://cloud.githubusercontent.com/assets/4571086/8104222/594b3e38-102f-11e5-8dca-d0a354512dca.PNG)


http://airpiro.ovh

**Comment by Ysurac** [comment]
It's the same icons but smaller if zoom is far from them.

**Comment by tonkepen100** [comment]
whether it is true, but do not you think that maybe a little bigger might be better ?, just a little.

I will be that I'm older and my eyesight is not very good

**Comment by Ysurac** [comment]
In commit a58548e16b91186be94db6c08023f95efac05ec0 you can set in *require/settings.php*, **$globalAircraftSize** to the size of icon you want in pixel.
