### ISSUE TITLE
From where to where?

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#63]
Here I launched a new challenge ....

It is putting up the plane and come out the line from where to where it goes.

For example so ....

![captura](https://cloud.githubusercontent.com/assets/4571086/8105612/efd9b324-103a-11e5-9631-b4c0edd50956.PNG)

this option is for both SBS and for VA, Vatsim, Ivao etc. because only grabs departure and destination. But by putting the mouse over zasss shows hotline of your flight.

**Comment by tonkepen100** [comment]
I still say go very, very small, the symbols of the aircraft, is that they can be difficult to puncture,

**Comment by Ysurac** [comment]
I have already said, In commit a58548e you can set in *require/settings.php*, **$globalAircraftSize** to the size of icon you want in pixel.

**Comment by tonkepen100** [comment]
This change still say that users would Ivao sensational if I could get to.

I mean put the mouse and you leave the starting line arrival, spectacular serious.

**Comment by tonkepen100** [comment]
Yes yes and Yes and OLeeeeeeee and Oleeeeeeeeee. I can not thank this Yurac, thank you very much, but many.
And you always put things complicated now I lamzo a challenge to see if you know the make.

Well we have the line of departure, sensational, what if we do that now comes out icon at the arrival airport and also, more or less would look like ....

![captura](https://cloud.githubusercontent.com/assets/4571086/10735159/ef9795a6-7c06-11e5-8177-dd04cd017a96.PNG)
