### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#64]
I put the last review, if you realize depends on the level of zoom you give him, the flights depart or not,

If you get out if you walk away disappear.

![captura](https://cloud.githubusercontent.com/assets/4571086/8126926/48144adc-10f3-11e5-9d47-f660d57afede.PNG)

![captura2](https://cloud.githubusercontent.com/assets/4571086/8126933/509b35b2-10f3-11e5-8091-342c76ba86c6.PNG)

**Comment by Ysurac** [comment]
Should be fixed in commit 616cd9c
