### ISSUE TITLE
NOTAMS

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#66]
Well now I go with the theme NOTAMS ...

I have created the account and this makes me,,,

![captura](https://cloud.githubusercontent.com/assets/4571086/8154532/8576af88-133b-11e5-87f2-ae348dcf6660.PNG)

In configuration i put this:

![captura2](https://cloud.githubusercontent.com/assets/4571086/8154542/97750fea-133b-11e5-9cb9-9aa8ea1af49f.PNG)

OK in navigator if i put http://notaminfo.com/feed?u=tonkepen, XML data out.

![captura](https://cloud.githubusercontent.com/assets/4571086/8154581/eb223e2e-133b-11e5-9fcf-1748c6d3d937.PNG)

But I think when you press the button notams not come out, or at least to me.

Again thanks Ysurac

**Comment by Ysurac** [comment]
NOTAM table is populated with **scripts/update_db.php**

**Comment by tonkepen100** [comment]
Then I understand that we will have to do a cron once a day, so they load it?

**Comment by tonkepen100** [comment]
![captura](https://cloud.githubusercontent.com/assets/4571086/8155187/fd8d9b5c-1341-11e5-81ad-017068fcab67.PNG)


OLEEEEEEEEEEEE, Thanks Ysurac

**Comment by Ysurac** [comment]
Yes, put it once a day in crontab.
I have more work to do for NOTAM display, but I would like to find an other source...

**Comment by tonkepen100** [comment]
Humps, sensational serious
