### ISSUE TITLE
Route display and flights pics for IVAO

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#67]
I return to the fray with two ideas of those fireman mine ....

1. In the tables and acarsphp refers to the route the pilot put in his flight plan, it would be possible to include such data. That daro in the case of simulation is vital, it occurs to me that could be included in the image when you click for example,,,,

![captura2](https://cloud.githubusercontent.com/assets/4571086/8156454/31042d2e-134d-11e5-986e-772cb25298ab.PNG)

![captura](https://cloud.githubusercontent.com/assets/4571086/8156465/380a4c98-134d-11e5-9bfa-521c4247b0e4.PNG)

Naturally this information to SBS, would have to not appear.

2.- Images MTL Ivao..

The website of IVAO MTL is this ....

http://mtlcatalog.ivao.aero/

It occurs to me but not if it will be feasible in the event that the images used with ivao aircraft used by users, may be taken from the original MTLS of ivao.

I know it can be difficult, but here I throw if you could

And as you know I'm very heavy, because again I thank you, is this you have done is wonderful.

**Comment by tonkepen100** [comment]
Thankssssssss Ysuraccccc thanks

**Comment by Ysurac** [comment]
Done in latest commit.

For route, you have to replace again **/lib/skins/skyline/js/recentpireps.php** by http://pastebin.com/17bu2HXj
For pics from IVAO, you have to add *ivaomtl* to **$globalAircraftImageSources**, like this **$globalAircraftImageSources = array('ivaomtl',.......**
To download this new pics, you have to *TRUNCATE spotter_image*

**Comment by tonkepen100** [comment]
For route, you have to replace again /lib/skins/skyline/js/recentpireps.php by http://pastebin.com/17bu2HXj , ok i change but no see planes in Airmap.

![captura](https://cloud.githubusercontent.com/assets/4571086/8189567/6f48f6e4-145d-11e5-9a6a-bfb1308428d8.PNG)

**Comment by tonkepen100** [comment]
stop stop i no change the new commit sorry

**Comment by Ysurac** [comment]
Do you have **route** column in **phpvms_acarsdata** table ?

**Comment by tonkepen100** [comment]
Yes this column i see in this table 

![captura](https://cloud.githubusercontent.com/assets/4571086/8189805/13425064-145f-11e5-8bfe-a38675e7a311.PNG)

**Comment by tonkepen100** [comment]
Ok i put the last commit, and reinstall but no see planes in this moment,

**Comment by Ysurac** [comment]
You put the pass/user/... in recentpireps.php ?

**Comment by tonkepen100** [comment]
if ysurac that works pyro looks okay so stuck

http;//piro.biz

**Comment by Ysurac** [comment]
I have no data http://piro.biz/lib/skins/skyline/js/recentpireps.php, but I don't see any syntax error in my pastebin...

**Comment by tonkepen100** [comment]
wait till you see what I'm going to hit again and see what happens

**Comment by Ysurac** [comment]
I found it, sorry, replace with that one : http://pastebin.com/vLZ2V5h7

**Comment by tonkepen100** [comment]
is good this?...

![captura](https://cloud.githubusercontent.com/assets/4571086/8190059/9aa0eccc-1460-11e5-950c-c01683bcc876.PNG)

**Comment by Ysurac** [comment]
true, it's the syntax error, I put the **\** after instead of before the **"**

**Comment by tonkepen100** [comment]
OLEEEEEEEEE I SEE Planes

**Comment by tonkepen100** [comment]
for images is good this ...

//Sources for Aircraft image (should be set to array() if no real aircrafts)
$globalAircraftImageSources = array('ivaomtl','wikimedia','deviantart','flickr','bing','jetphotos','planepictures','planespotters');

or only i put ivaomtl ?

**Comment by Ysurac** [comment]
as you want, if only ivaomtl, it will only search on ivao website, else it will search on next sites if not available.

**Comment by tonkepen100** [comment]
Well and let this line ....

//Sources for Aircraft image (should be set to array() if no real aircrafts)
$globalAircraftImageSources = array('ivaomtl');

and emptied the table and see what happens. that emotion, that emotion

**Comment by tonkepen100** [comment]
TACHANNNNNNNNNNNNNNNNNNNNN....

![captura](https://cloud.githubusercontent.com/assets/4571086/8190587/ba36781a-1463-11e5-85d7-e6e3ad855ba9.PNG)

Thank you ysurac not know how I can thank the work and the help you are giving me. really thanks.

**Comment by Ysurac** [comment]
So I can close this bug now

**Comment by tonkepen100** [comment]
I think we have a problem Houston, just out pictures of airbus a320,

for example, now he came with a friend and his ICAO concorde okay CONC and carries out ivao mtl conc, but do not know why not grabs

![captura2](https://cloud.githubusercontent.com/assets/4571086/8191734/15c01e9c-146a-11e5-8e1f-710777659cc7.PNG)


![captura](https://cloud.githubusercontent.com/assets/4571086/8191739/19e6b0ee-146a-11e5-988c-0f21c3348426.PNG)

**Comment by Ysurac** [comment]
Strange, for the Concorde from Air France, I have the pic without problem. Maybe a time out when the script check if the pic exist.

**Comment by tonkepen100** [comment]
if the truth is curious but I think where the subject will watch this case this man takes Virgin Atlantic and as the match mtl maybe it's that, your going with your mtl, not if it could be.

![capturaavion](https://cloud.githubusercontent.com/assets/4571086/8192273/3e152eca-146d-11e5-8563-929a4b6d5399.PNG)

and records in the db .... until now

![captura2](https://cloud.githubusercontent.com/assets/4571086/8192299/680a8d88-146d-11e5-957e-2c5a2f996ed0.PNG)

**Comment by Ysurac** [comment]
VRD = Virgin America for IVAO at least.
I search for pic with aircraft ICAO and airline ICAO, so in this case A320VRD, in previous case CONCAFR. If URL like http://mtlcatalog.ivao.aero/images/aircraft/CONCAFR.jpg is ok, then I add it.

**Comment by tonkepen100** [comment]
Indeed. if what you say is correct, but the issue is how not to get into the db, or do not understand.

When truncated CARE and the table, and made no new installation, could that be?

**Comment by Ysurac** [comment]
no, maybe a time out, or a limit in numbers of connection... Pic should be added next time aircraft is seen. It try each time aircraft is seen if pic is not already in DB.

**Comment by tonkepen100** [comment]
Ysurac a question, the spotter_live table that would understand exactly ?, where actual flights that are on the radar guard. no ?.

**Comment by Ysurac** [comment]
spotter_live contains latest flights data.

**Comment by tonkepen100** [comment]
Well it seems, it is to come out and stabilized and photo Ivao, I think it works well Ysurac.
