### ISSUE TITLE
typing -error in /js/map.js.php

### ISSUE THREAD

**Issue by linuxshredder** [Ysurac/FlightAirMap#7]
Hello , detected a error in /js/map.js.php
line 220 look like this 
      url: "live/geojson?"+Math.random()+"&coord="+bbox,

if we leave this as is , you will never get any routes or anything  your map , because 
/live/geojson? does not exist in your path !
you should change it to this 

      url: "live-geojson?"+Math.random()+"&coord="+bbox,

only change the / character to -
if you have changed that , the webserver can find live-geojson.php and draw the routes ,planes ,etc
Have a nice Day !

**Comment by Ysurac** [comment]
live/geojson redirect to live-geojson.php in .htaccess.

No error here.
