### ISSUE TITLE
Sidebar display old values

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#72]
Since the last review I think we have a little problem, is that when you click on the flight in the gusrda tab always the first flight, I mean for example a driver who makes its first flight with a Cessna and then performs another with a concorde its tab always goes the cessna.

I mean, does not erase the data and makes the new, and looked at the table and data go well, I bo that may be.

![captura](https://cloud.githubusercontent.com/assets/4571086/8722671/47387b80-2bc7-11e5-9548-7e47a4af44d1.PNG)

**Comment by Ysurac** [comment]
You mean if the aircraft change for a same flight (same ident) ?

**Comment by tonkepen100** [comment]
And discovered it is when you put ...

// INFO DISPLAY OF FLIGHTS IN A POPUP
$ globalMapPopup = FALSE;

If you put it so works well ...

// INFO DISPLAY OF FLIGHTS IN A POPUP
$ globalMapPopup = TRUE;

**Comment by tonkepen100** [comment]
FALSE...  

![captura2](https://cloud.githubusercontent.com/assets/4571086/8724861/3273e306-2bd1-11e5-9db4-84666672d90f.PNG)

BAD

TRUE

![captura](https://cloud.githubusercontent.com/assets/4571086/8724868/3eebb672-2bd1-11e5-9baf-a13f5c7c2f0d.PNG)

GOOD

**Comment by tonkepen100** [comment]
Ycarus, Do you think you could fix this bug?

Thank You

**Comment by Ysurac** [comment]
maybe

**Comment by Ysurac** [comment]
mmm I think I didn't understand the bug....
Popup or sidebar always display the latest data in live table.

**Comment by tonkepen100** [comment]
See I'll explain:

Settings have that line that says what kind of sample we select popup:

// INFO DISPLAY OF FLIGHTS IN A POPUP
$ GlobalMapPopup = FALSE;

Well if we put the option to TRUE things are going well, but if we put it in FALSE HERE COMES THE PROBLEM, and is as follows.

For example I make a flight with concorde, well and reached its destination, the program closes the flight, right now I change the flight plan and instead of concorde lame for example, a Cessna, since the lateral Poppup continues data continuously the priomer flight made, bone does not change the image or the model of the next flight, child's siguinete or those who do later, however if you put it to true, then if it goes well change the photo and the model plane, not even squack changes.
Look at the photos above

mmm I think I didn't understand the bug....
Popup or sidebar always display the latest data in live table.

Yes lateral bad.

**Comment by Ysurac** [comment]
If you keep the sidebar open ? Sidebar never refresh if you don't click again on the plane or another plane.
I can make it refresh sometimes.

**Comment by tonkepen100** [comment]
I've tried but it does not, the first flight made by the pilot always remains.

**Comment by Ysurac** [comment]
This should not be possible, at least if $globalDaemon is set to FALSE in settings.php

**Comment by tonkepen100** [comment]
Look for example now change squawk to 7004, with the lateral popup previous stays, but if this changed the table, if instead put the other popup, if you change either

![captura2](https://cloud.githubusercontent.com/assets/4571086/8766816/7a0363ea-2e47-11e5-94dd-87352c43032c.PNG)

![captura](https://cloud.githubusercontent.com/assets/4571086/8766820/8046b4d2-2e47-11e5-9be6-72fded90b2a2.PNG)

**Comment by Ysurac** [comment]
hum ok, maybe the page used for sidebar is put in the cache of your browser. I will make cache not possble for this.

**Comment by tonkepen100** [comment]
whether it will be for sure, because the db goes well

**Comment by Ysurac** [comment]
Should be ok with build 336d127eca1df9c3cd884e4ec3ee9d41d1db2c4f
I will add sidebar auto refresh later...

**Comment by tonkepen100** [comment]
Well, I think that's not it, and it changed and does not change, plus I'm setting and the data do not go well on the side, with the popup if you look ...

![captura](https://cloud.githubusercontent.com/assets/4571086/8766983/c2bffc06-2e4c-11e5-827e-4d6d8b8ae1f5.PNG)

![captura2](https://cloud.githubusercontent.com/assets/4571086/8766984/d11c628a-2e4c-11e5-8d3c-26056116a946.PNG)

![captura3](https://cloud.githubusercontent.com/assets/4571086/8766990/f9ba5102-2e4c-11e5-8f09-47058127a08a.PNG)

**Comment by tonkepen100** [comment]
![captura](https://cloud.githubusercontent.com/assets/4571086/8767002/6c60434c-2e4d-11e5-86ae-d8b2d94f4781.PNG)

WHIT POPPUP IS CORRECT

**Comment by Ysurac** [comment]
Strange... did you refresh the page after update ?

**Comment by tonkepen100** [comment]
Yes Ycarus i refresh

**Comment by Ysurac** [comment]
what is your browser ?

**Comment by tonkepen100** [comment]
chrome

**Comment by Ysurac** [comment]
coordinates of flight change when plane move and you click again on it ?

**Comment by tonkepen100** [comment]
![1](https://cloud.githubusercontent.com/assets/4571086/8767088/07f94166-2e51-11e5-8211-3fff768557c7.PNG)

2 MINUTES LATER

![2](https://cloud.githubusercontent.com/assets/4571086/8767090/128171da-2e51-11e5-800f-828ba16d8863.PNG)

No no change Ycarus

**Comment by tonkepen100** [comment]
Buff and see altitude and velocity

**Comment by Ysurac** [comment]
Should be fixed in commit eab36cd. This is a problem with hours added in DB. You will not see if it's working before tomorrow.

**Comment by tonkepen100** [comment]
Aja, Thankssss Ysurac

**Comment by tonkepen100** [comment]
Yurac, I think you got it, now speeds and heights are correct the squack changes, coordinates also change.

The only thing missing me to check if changing the flight is also changed the profile of the plane and the flight plan.

![captura1](https://cloud.githubusercontent.com/assets/4571086/8770930/450d4462-2eba-11e5-8d36-a5a69cbd4952.PNG)

Merci beaucoup champion

**Comment by tonkepen100** [comment]
Ysurac do not close it out now another problem, I think fatter.


Now do not go on the ad photos, and also the airport of departure and arrival are all wrong.

Look ....

![captura3](https://cloud.githubusercontent.com/assets/4571086/8771650/757691e4-2ec4-11e5-9a0c-06cb74d943d8.PNG)

![captura](https://cloud.githubusercontent.com/assets/4571086/8771662/85616930-2ec4-11e5-8a9e-661b2f7fc933.PNG)

![captura3](https://cloud.githubusercontent.com/assets/4571086/8771678/aa7da58a-2ec4-11e5-9155-086ba7633a83.PNG)

passes on all flights

**Comment by tonkepen100** [comment]
It is not, that does not leave any photo, it is as if all had gone.

![captura](https://cloud.githubusercontent.com/assets/4571086/8772052/b93e8374-2ec8-11e5-8f36-3abfe4cdbf96.JPG)

**Comment by Ysurac** [comment]
Paste your settings.php (without passwords)

**Comment by tonkepen100** [comment]
<?php
//INSTALLED OR NOT ?
$globalInstalled = TRUE;

//GLOBAL SITE NAME
$globalName = 'AirPiro Radar';

// GLOBAL URL
$globalURL = '';

// Logo URL
$logoURL = '/images/airpiroradar.png';

// Activate debug
$globalDebug = TRUE;

// LANGUAGE
$globalLanguage = 'EN'; // Used only for wikipedia links for now

// MAP PROVIDER
$globalMapProvider = 'MapQuest-OSM'; // Can be Mapbox, OpenStreetMap, MapQuest-OSM or MapQuest-Aerial
$globalMapboxId = 'tonkepe.md76aj2h'; // Mapbox id
$globalMapboxToken = 'pk.eyJ1IjoidG9ua2VwZSIsImEiOiJuZkI2SWRZ4NeEsjF7UpAgZBg'; // Mapbox token

//COVERAGE AREA (its based on a box model. i.e. top-left | top-right | bottom-right | bottom-left)
$globalLatitudeMax = ''; //the maximum latitude (north)
$globalLatitudeMin = ''; //the minimum latitude (south)
$globalLongitudeMax = ''; //the maximum longitude (west)
$globalLongitudeMin = ''; //the minimum longitude (east)

$globalCenterLatitude = '20.38'; //the latitude center of your coverage area
$globalCenterLongitude = '5.29';//the longitude center of your coverage area

$globalLiveZoom = '3'; //default zoom on Live Map

// FLIGHTS MUST BE INSIDE THIS CIRCLE
$globalDistanceIgnore = array();
// ^^ example for 100km : array('latitude' => '46.38','longitide' => '5.29','distance' => '100');

// DATABASE CONNECTION LOGIN
$globalDBdriver = 'mysql'; // PDO driver used. Tested with mysql, maybe pgsql or others work...
$globalDBhost = 'localhost'; //database connection url
$globalDBuser = ''; //database username
$globalDBpass = ''; //database password
$globalDBname = ''; //database name
$globalTransaction = TRUE; //Activate database transaction support


//FLIGHTAWARE API INFO
$globalFlightAware = FALSE; //set to TRUE to use FlightAware as data import
$globalFlightAwareUsername = ''; //FlightAware Username
$globalFlightAwarePassword = ''; //FlightAware Password/API key

// TIMEZONE
$globalTimezone = 'Europe/Madrid';

// DAEMON
$globalDaemon = FALSE; // Run cron-sbs.php as daemon (don't work well if source is a real SBS1 device)
$globalCronEnd = '0'; //the script run for xx seconds if $globalDaemon is disable in SBS mode

// FORK
$globalFork = TRUE; // Allow cron-sbs.php to fork to fetch schedule, no more schedules fetch if set to FALSE


// DISPLAY FLIGHT INTERVAL ON MAP (in seconds)
$globalLiveInterval = '60';

// LIVE MAP REFRESH (in seconds)
$globalMapRefresh = '60';

//IVAO
$globalIVAO = FALSE;

//ADS-B, SBS1 FORMAT
$globalSBS1 = TRUE; //set to FALSE to not use SBS1 as data import
$globalSBS1Hosts = array('http:','http:','http:','http://piro.biz/lib/skins/skyline/js/recentpireps.php','');
// ^^ in the form array('host1:port1','host2:port2','http://xxxxx/whazzup.txt'); Use only sources you have the rights for.
$globalSBS1TimeOut = '15';
$globalSBS1update = '1260'; //Put data in DB after xx seconds/flight

//ACARS Listen in UDP
$globalACARS = FALSE;
$globalACARSHost = ''; // Local IP to listen
$globalACARSPort = '';

// DISPLAY INFO OF FLIGHTS IN A POPUP
$globalMapPopup = FALSE;

// To display Squawk usage we need Squawk country for now
$globalSquawkCountry = 'US';

//BIT.LY API INFO (used in the search page for a shorter URL)
$globalBitlyAccessToken = ''; //the access token from the bit.ly API

//BRITISH AIRWAYS API INFO
$globalBritishAirwaysKey = 'u88an5thh5mwc';

//ignore the flights during imports that have the following airports (departure/arrival) associated with them
$globalAirportIgnore = array();

//Archive all data
$globalArchive = TRUE;

//NOTAM
$globalNOTAM = TRUE;
$globalNOTAMSource = 'http://notaminfo.com/feed?u=tonkepen'; //URL of your feed from notaminfo.com


//Retrieve Image from externals sources
$globalAircraftImageFetch = TRUE;
//Sources for Aircraft image
$globalAircraftImageSources = array('ivaomtl','wikimedia','deviantart','flickr','bing','jetphotos','planepictures','planespotters');
$globalAircraftSize = '25';

//Retrieve schedules from externals sources (set to FALSE for IVAO or if $globalFork = FALSE)
$globalSchedulesFetch = FALSE;
//Sources for airline schedule if not official airline site
$globalSchedulesSources = array('flightmapper','costtotravel','flightradar24','flightaware');

//Retrieve translation from external sources (set to FALSE for IVAO)
$globalTranslationFetch = FALSE;
//Sources for translation, to find name of flight from callsign
$globalTranslationSources = array('planefinder');
$globalMapAltitudeColor = TRUE;
$globalMapHistory = TRUE;
?>

**Comment by Ysurac** [comment]
**$globalIVAO = FALSE;** -> should be TRUE

**Comment by tonkepen100** [comment]
Ojjjjjjjj already happened, be wrong to change the true, rather than change in popup, change it in IVAO, Ysurac sorry, sorry and thank you again.

**Comment by Ysurac** [comment]
For silhouette and pics of "specials" aircraft I opened issue #73

**Comment by tonkepen100** [comment]
OK Well, I took several days without seeing popup continues avion.routes errors etc etc, suddenly works well, and poof suddenly goes crazy and puts all evil

**Comment by Ysurac** [comment]
*$globalIVAO* is set to TRUE ?

**Comment by tonkepen100** [comment]
Yes yes is true Ycarus

**Comment by Ysurac** [comment]
Strange... I will try to reproduce the issue on my computer.

**Comment by tonkepen100** [comment]
Okay thanks Ysurac

**Comment by Ysurac** [comment]
Fixed in commit a6f1bb2.

**Comment by tonkepen100** [comment]
Gooddddd Now, it seems that already goes well, sensational sensational
