### ISSUE TITLE
Add support for specials designator aircraft ICAO

### ISSUE THREAD

**Issue by Ysurac** [Ysurac/FlightAirMap#73]
For silhouette, pics downloads,...
Source : http://www.icao.int/publications/DOC8643/Pages/SpecialDesignators.aspx

**Comment by tonkepen100** [comment]
![captura](https://cloud.githubusercontent.com/assets/4571086/8772678/5d40acf4-2ece-11e5-8002-5abe1dffbd2f.JPG)

jjejejeee I made, and put table aircrafts, is this no?.

**Comment by tonkepen100** [comment]
and this..., of course if you want I send it to the goals, tell me and happy to send files.

![captura2](https://cloud.githubusercontent.com/assets/4571086/8772750/13dbb8d2-2ecf-11e5-9e81-89c076a8bfbf.JPG)
