### ISSUE TITLE
Time Zones

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#76]
In this parameter is posible put time UTC?

// TIMEZONE
$globalTimezone = 'Europe/Madrid';

to

// TIMEZONE
$globalTimezone = 'UTC';

Thanks

**Comment by Ysurac** [comment]
Yes, any Timezone that is supported by PHP ( http://php.net/manual/en/timezones.php )

**Comment by tonkepen100** [comment]
Ok ok thanks Ycarus
