### ISSUE TITLE
Icons Aerodromes Zoom

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#77]
That happens to come out, and information icons airports look there to make a considerable zoom.

![captura](https://cloud.githubusercontent.com/assets/4571086/8869712/54d0cb5a-31e7-11e5-850c-98a4cf7e989e.JPG)

![captura2](https://cloud.githubusercontent.com/assets/4571086/8869714/5e901cae-31e7-11e5-8750-634ff8e53dc5.JPG)

For users SBS, okay but for users IVAO, having very zooms away, is a real problem they can be viewed.

There would be any way to define what level of zoom out and look?

Sensational would be able to do because the user could determine to zoom wants to see.

Thanks as always for the effort and put up, which is something.

**Comment by Ysurac** [comment]
Maybe later when I will finish new user settings sidebar.

**Comment by tonkepen100** [comment]
Ohh, grâce Yurac comme toujours sur la balle

**Comment by tonkepen100** [comment]
Sensational, but I see I do not think there is a problem ..
when I leave this zoom they are perfect, but when the zoom magnification does not appear to me.


we have to do more besides put files files ?.
Thank you.

**Comment by Ysurac** [comment]
I don't understand your problem. When *Zoom level* is set to **15** you have to zoom a lot to see airports icons but this is working.

**Comment by tonkepen100** [comment]
ahhhhh, forgiveness is that the zoom is going backwards, the less you put, the further they look Yes, you're right forgiving toward him backwards

Thanks Ysurac

**Comment by tonkepen100** [comment]
Ysurac exceptional works perfect, thank you very much for this development.
