### ISSUE TITLE
Working On RPi2!

### ISSUE THREAD

**Issue by nzradar** [Ysurac/FlightAirMap#8]
I have the app working on my RPi2 but have a couple of issues.  I'm using some port 30003 (SBS) data so how do I keep the flow of data coming to the web?  I have a cron job ever 1 minute running the cron-sbs.php file but I'm not sure that's working.  When I run cron-sbs.php in my browser it eventually times out so no further data unless I manually refresh the page!

Secondly, the aircraft points the wrong way!  Mostly they are in the correct quadrant but definitely not pointing the same as the heading.

And lastly, the airport of arrival is always NA on the routing.  

I'll keep the app going so you can see this at http://hfaero.no-ip.org/index.php

Thanks,
Michael
hfaero.com

**Comment by Ysurac** [comment]
cron-sbs.php is not really a good name, it's a daemon. You should run it with an init script, you can run it in console to see debug log also.

Wrong aircraft orientation is a bug. I will look at it asap. Work in North of Earth maybe not in South...

For airport arrival/departure you should check if route table is not empty. Else NA is used when no data. I use some airline website, an external db or ACARS if available as datasources.

**Comment by Ysurac** [comment]
For airport arrival/departure, you used update_db.sh, there is a bug (will be solved or deleted soon), you should use update_db.php

**Comment by Ysurac** [comment]
For aircraft orientation what is your version of dump1090 ? Heading are really stranges, should be in degree but it's not the case on your install.

**Comment by nzradar** [comment]
Hi Ycarus,

 

I’m not using Dump1090, my port 30003 data comes from ModeSDecode (modesdeco2) by Sergsero, that data is OK I think.

 

I’ve found the FromAirport_Time holds the ToAirport_ICAO so I have corrected that with some SQL, I’ll see how that works.

 

Cheers,

Michael

**Comment by Ysurac** [comment]
ModeSDecode send float for heading instead of int used by dump1090. This is fixed in commit 4d8979fbc9b06f0058cbf42bdb669ec7aacfa503
