### ISSUE TITLE
Raspberry pi 2 Problem mysql 5.5.44-0+deb7u1

### ISSUE THREAD

**Issue by lordkane** [Ysurac/FlightAirMap#80]
Errorerror (import ../db/translation.sql) : SQLSTATE[HY000]: General error: 1293 Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause

no mysql 5.6 on raspberry pi2 

Please help me

**Comment by Ysurac** [comment]
CURRENT_TIMESTAMP can be used on only one column on MySQL < 5.6.5
I fixed this in commit bd9410ae4ead55fb7369437c414b41123e2f18a4

**Comment by lordkane** [comment]
Thanks it works fine !!
