### ISSUE TITLE
518 Problem

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#82]
Hello and since the last update, and I think everything goes wrong, side icons are blank and flights no longer leave.

Not that I have done wrong, help.

Thank you

![captura](https://cloud.githubusercontent.com/assets/4571086/9678541/a5b4feae-52e6-11e5-90a2-e3fa7419a5d4.JPG)

**Comment by Ysurac** [comment]
It's the new sidebar. This allow user configuration.
For flights check if you run the new *scripts/daemon-spotter.php*, I put a symbolic link but maybe this don't work for you.

**Comment by tonkepen100** [comment]
____For flights check if you run the new scripts/daemon-spotter.php, I put a symbolic link but maybe this don't work for you.____

This I understand that I have to do

**Comment by tonkepen100** [comment]
if I run this I get this .......

![captura](https://cloud.githubusercontent.com/assets/4571086/9680631/609ab70c-52f8-11e5-8817-118bc1b4a1c5.JPG)

**Comment by Ysurac** [comment]
You have some bug in your config file, but the script work. You should replace your cron job *scripts/cron-sbs.php* by *scripts/daemon-spotter.php*

**Comment by tonkepen100** [comment]
Yeah, and thank you very much Ysurac works in a personal capacity, without bad you know, I was pretty much aesthetic and other menu bar, but it is sure that you will know something.
