### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by FNATEC** [Ysurac/FlightAirMap#83]
Hi i have a problem with installing, but i properly chosen db.
![default](https://cloud.githubusercontent.com/assets/14258042/9835892/137a693c-5a09-11e5-98e2-015891764bfe.png)

**Comment by Ysurac** [comment]
Do you use MySQL or PostgreSQL ?
Database exist or not ?
Error seems to say that database doesn't exist (I need to add a check for that in install script...).

**Comment by FNATEC** [comment]
I use MySQL, database exist. One more thing, after installation no db username, name and pass in settings.php it's issue or not?)

**Comment by FNATEC** [comment]
If I manually edit settings.php there is no aircrafts on map I use IVAO wazzup file.

**Comment by Ysurac** [comment]
Yes if username, db name,... are not in settings.php it's an issue.
If you manually edit *settings.php* you need to run again *install/index.php* or *install/install_db.php* and *install/populate_ivao.php*.

**Comment by FNATEC** [comment]
Ok I will try it thx for fast answer))

**Comment by FNATEC** [comment]
I did as you said but no aircraft on map wazzup link is correct, DB works now.

**Comment by Ysurac** [comment]
Do you have **$globalIVAO = TRUE;** in your *require/settings.php* ?
How do you run *scripts/daemon-spotter.php* ? as a daemon or as a cron job ? What is the output of this script ?

**Comment by FNATEC** [comment]
Thanks it works!
