### ISSUE TITLE
2 records for same flight

### ISSUE THREAD

**Issue by kletellier** [Ysurac/FlightAirMap#84]
i encounter this problem many times in a day. i'm living near Orly airport in France. 

For example i've an Aigle Azur flight called AAF256 (Algier to Paris) who landed today at ~15:10 , the same plane restart in the other side near 16:30 and for few seconds has the same callsign AAF256 , thiw will create an entry in the spotter_output table but it's a fake. And after the plane switch to callsign AAF257 for flight Paris to Algier and this flight was normally created in db.

I think it's a very specific problem who can encounter when we are near an aiport.

For information i'm using cron-sbs.php who point on dump1090 mutability and SBS1 port 30003

**Comment by Ysurac** [comment]
It's not so specific in fact, I saw that quite often.
I need to find a way to resolve this...
