### ISSUE TITLE
no image on install

### ISSUE THREAD

**Issue by lordkane** [Ysurac/FlightAirMap#85]
i see no images with an fresh install and a sub dir...
![screen flightairmap](https://cloud.githubusercontent.com/assets/12719611/9980810/d534ed0c-5fa6-11e5-837b-5c2b6f5f3fca.JPG)

**Comment by Ysurac** [comment]
What is your setting in **require/settings.php** for  *$globalURL* ?

**Comment by lordkane** [comment]
ok i found the misttake i must the complete url rapsberrypi/fap/ now ...
first was raspberrypi
