### ISSUE TITLE
Duplicate a/c

### ISSUE THREAD

**Issue by FNATEC** [Ysurac/FlightAirMap#86]
Hello. I have a problem with info from phpvms. All aircraft doesn't change their positions they just duplicating. This problem only with phpvms.
![1](https://cloud.githubusercontent.com/assets/14258042/9982196/0bb3a334-5fdc-11e5-941a-86f5e8f70b6a.png)
![2](https://cloud.githubusercontent.com/assets/14258042/9982197/0c964e00-5fdc-11e5-87c5-fe8ccfc1d426.png)

**Comment by Ysurac** [comment]
If the URL of phpvms is public can I have it to make some tests ?
Do you run **daemon-spotter.php** as daemon or cron job ?

**Comment by FNATEC** [comment]
daemon-spotter.php, http://va-rossiya.com/action.php/acars/data

**Comment by Ysurac** [comment]
Fixed in commit d9deb92d3959c8f679b8ad71b141a841c21a872d
