### ISSUE TITLE
Rev 522

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#87]
By putting 522 rev, all ATIS information controls disappear, leaving only the name of the control.

![captura](https://cloud.githubusercontent.com/assets/4571086/9990972/3e8f85e0-6066-11e5-844e-9ee6d357b14c.JPG)

and 

[21-Sep-2015 11:34:01 UTC] PHP Notice:  Undefined offset: 1 in /home/airpiro/public_html/scripts/daemon-spotter.php on line 77
[21-Sep-2015 11:35:01 UTC] PHP Notice:  Undefined offset: 1 in /home/airpiro/public_html/scripts/daemon-spotter.php on line 77

**Comment by Ysurac** [comment]
What is rev 522 ? Last commit is working well with your source.
For errors, what is the value in *require/settings.php* of **$globalSBS1Host** ?

**Comment by tonkepen100** [comment]
![captura](https://cloud.githubusercontent.com/assets/4571086/9991470/98d18aae-606a-11e5-9781-d8f4a3a12a47.JPG

**Comment by Ysurac** [comment]
Delete **,''** at the end of *$globalSBS1Hosts*

**Comment by tonkepen100** [comment]
OK Ysurac
