### ISSUE TITLE
Issue with Database

### ISSUE THREAD

**Issue by uppaljs** [Ysurac/FlightAirMap#88]
Hi,

I am facing the following error with cron-sb.php

I am using Centos 7 and mariaDB.

\o/ Add PIA308 in archive DB : error : SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column 'squawk' at row 1
DATA : hex : 760981 - ident : PIA308 - ICAO : A320 - Departure Airport : OPKC - Arrival Airport : OPRN - Latitude : 30.94183 - Longitude : 71.31561 - waypoints :  - Altitude : 350 - Heading : 30 - Speed : 488 - Departure Airport Time :  - Arrival Airport time :
\o/ Add PIA308 in Live DB : error : SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column 'squawk' at row 1
\o/ Add PIA308 in archive DB : error : SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column 'squawk' at row 1
DATA : hex : 760981 - ident : PIA308 - ICAO : A320 - Departure Airport : OPKC - Arrival Airport : OPRN - Latitude : 30.94679 - Longitude : 71.31904 - waypoints :  - Altitude : 350 - Heading : 30 - Speed : 487 - Departure Airport Time :  - Arrival Airport time :
\o/ Add PIA308 in Live DB : error : SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column 'squawk' at row 1

**Comment by Ysurac** [comment]
What do you use as source ?
What is the version of mariaDB ?

**Comment by uppaljs** [comment]
rpm -qa | grep maria
mariadb-libs-5.5.41-2.el7_0.x86_64
mariadb-devel-5.5.41-2.el7_0.x86_64
mariadb-server-5.5.41-2.el7_0.x86_64
mariadb-5.5.41-2.el7_0.x86_64


MariaDB [flights]> select * from config
    -> ;
+----+----------------+-------+
| id | name           | value |
+----+----------------+-------+
|  1 | schema_version | 10    |
+----+----------------+-------+
1 row in set (0.00 sec)

MariaDB [flights]>

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 6739
Server version: 5.5.41-MariaDB MariaDB Server

Copyright (c) 2000, 2014, Oracle, MariaDB Corporation Ab and others.

**Comment by Ysurac** [comment]
I'm using MariaDB 10 but 5.5 should work without problem... strange...
Maybe this will work with the change I made in commit ea1f59aa9ffbab19585c2be4a8524591ccb5d2a4

**Comment by uppaljs** [comment]
Nope , still the same ... 

\o/ Add PIA306 in Live DB : error : SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column 'verticalrate' at row 1
\o/ Add PIA306 in archive DB : error : SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column 'verticalrate' at row 1
DATA : hex : 760997 - ident : PIA306 - ICAO : A320 - Departure Airport : NA - Arrival Airport : NA - Latitude : 30.12921 - Longitude : 72.50845 - waypoints :  - Altitude : 350 - Heading : 48 - Speed : 523 - Departure Airport Time :  - Arrival Airport time :
\o/ Add PIA306 in Live DB : error : SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column 'verticalrate' at row 1
\o/ Add PIA263 in archive DB : error : SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column 'verticalrate' at row 1
DATA : hex : 760993 - ident : PIA263 - ICAO : A320 - Departure Airport : NA - Arrival Airport : NA - Latitude : 29.94814 - Longitude : 72.00057 - waypoints :  - Altitude : 380 - Heading : 243 - Speed : 403 - Departure Airport Time :  - Arrival Airport time :
\o/ Add PIA263 in Live DB : error : SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column 'verticalrate' at row 1

**Comment by Ysurac** [comment]
I found the problem :  SQL Mode is set to STRICT on your MariaDB config.
I will make some changes asap to make all work with STRICT mode.

**Comment by uppaljs** [comment]
Thank you @Ysurac - Looking forward to it.

**Comment by Ysurac** [comment]
I made some change in commit e370d5fc1e682c380441233ffab6cad49618aa2
If this doesn't work, can you give me the result of **SELECT @@sql_mode;** in MariaDB ?
