### ISSUE TITLE
Issue with Cron-SBS

### ISSUE THREAD

**Issue by uppaljs** [Ysurac/FlightAirMap#89]
Hi

Latest checkout , causes the sbs to disconnect frequently - This is on local lan , everything is cabled.

[root@localhost html]# php cron-sbs.php
Connecting to SBS ...
Connection in progress to 192.168.20.174:30003(sbs)....
Connected!
SCAN MODE

ERROR : socket_select give this error Operation now in progress
Restarting...
Shutdown all sockets...Restart all connections...Connection in progress to 192.168.20.174:30003(sbs)....
ERROR : socket_select give this error Operation now in progress
Restarting...
Shutdown all sockets...Restart all connections...Connection in progress to 192.168.20.174:30003(sbs)....
ERROR : socket_select give this error Operation now in progress
Restarting...
Shutdown all sockets...Restart all connections...Connection in progress to 192.168.20.174:30003(sbs)....
*********** New aircraft hex : 760981 ***********

**Comment by Ysurac** [comment]
There is no changes in this script that can make this issue.
Try to increase **$globalSBS1TimeOut** in *require/settings.php*.

**Comment by uppaljs** [comment]
Changing that seems to fix the problem.
