### ISSUE TITLE
Date Issue

### ISSUE THREAD

**Issue by nzradar** [Ysurac/FlightAirMap#9]
I have a mostly working system but the date information is a bit strange.

I have the Port 30003 data set for local time (modesdeco2 setting) and the database is storing in local time (spotter_live & spotter_output tables).

When I "Explore" today's activity the right hand column shows the time +2.00 hours.
Spotter TV has the time as UTC!

Where should I go to change all dates/times to local?

Cheers,
Michael

**Comment by Ysurac** [comment]
What is your $globalTimezone value in require/settings.php ?
Spotter TV is now fixed in commit 01e411fd2cadad56225d528e717f458c2a6013a7

**Comment by nzradar** [comment]
It is 'Pacific/Auckland'.  Yep, I too fixed Spotter TV.

I was wrong, the data going into the database (spotter_live and spotter_output tables) are also UTC.  I see a mix of 'UTC' and 'America/Toronto' timezones in all the PHP files but I also see 'Europe/Paris' on the FlightID page and in its corresponding PHP (flightid-overview.php) that date is $globalTimezone despite the settings.php stating 'Pacific/Auckland'.

**Comment by nzradar** [comment]
Spotter TV fix sets time to my local time + 2 hours instead of UTC now!

**Comment by nzradar** [comment]
Sorry!!  My settings.php had 'Europe/Paris', not sure how, I was certain the time zone was Pacific/Auckland.

I'll restart and see how things look.

**Comment by nzradar** [comment]
OK, the +2 hours problem is now solved and so is Spotter TV, thank you but there's still the issue of UTC for data into the database tables.

**Comment by Ysurac** [comment]
Timezone America/Toronto will be removed asap.
Europe/Paris is default value in settings.php
All times in DB are in UTC (or should).
