### ISSUE TITLE
Selection map

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#90]
Question:

The customer can select the type of map you want to see or not?

Why me at least I do not get in options.

Thank you.

**Comment by Ysurac** [comment]
Not yet

**Comment by Ysurac** [comment]
Not yet

**Comment by tonkepen100** [comment]
AHHH Ok Ysurac

**Comment by tonkepen100** [comment]
Simply spectacular, thanks Ysurac,

**Comment by tonkepen100** [comment]
We have a problem with maps,,,

Loading map goes well, but when you drag the map to view the Pacific does not leave it is blank, it is impossible to see the flight of the Pacific area.

![captura](https://cloud.githubusercontent.com/assets/4571086/10150223/ae4bd892-663e-11e5-9931-2258fd9e78f3.JPG)

![2](https://cloud.githubusercontent.com/assets/4571086/10150230/b4fa1758-663e-11e5-8599-f7a426b65de3.JPG)

**Comment by Ysurac** [comment]
Yes, I now disallow map repeat. Flights are displayed between -180 and 180 longitude, so no need to repeat empty maps. This make no changes to flights display, only no more empty maps.

**Comment by tonkepen100** [comment]
Understood, but for users of ivao is no solution because, I repeat a flight, for example in Hawaii, you can not see.

Solution exist?

Thank you

**Comment by Ysurac** [comment]
You see them, as before. No flights was displayed out of this map. You can see flights to hawaii without problems.

**Comment by tonkepen100** [comment]
If indeed if they go all mine fatal error, sorry

![captura](https://cloud.githubusercontent.com/assets/4571086/10157583/75fc88fe-668b-11e5-9f77-7c3dbf67f403.JPG)

![aco](https://cloud.githubusercontent.com/assets/4571086/10157588/7cefcbee-668b-11e5-9c75-4862a890b933.JPG)

**Comment by tonkepen100** [comment]
Well we are now presenting another problem for maps dark blue icons aircraft are indistinguishable,

![a](https://cloud.githubusercontent.com/assets/4571086/10157987/25124ae2-668f-11e5-8d73-140a9031f4af.JPG)


Solution and created a folder with yellow icons aircraft.

![c](https://cloud.githubusercontent.com/assets/4571086/10157991/2b94b918-668f-11e5-821f-860c5d540bf7.JPG)

![b](https://cloud.githubusercontent.com/assets/4571086/10158001/37ae9250-668f-11e5-81c8-3ecd93439681.JPG)



It might be interesting to put options to choose the color of the icons of the aircraft.

If you want the shipment, so that they can get.

**Comment by Ysurac** [comment]
Color of aircraft icons can be changed in commit 58018a82af7ceed9d97973951a0f0c10357ccdcb

**Comment by tonkepen100** [comment]
By changing the map file is map.js.php I go blank, and does not work the menu of options ...

![captura2](https://cloud.githubusercontent.com/assets/4571086/10172370/3659c0e6-66df-11e5-94f6-42c60858668b.JPG)

![captura](https://cloud.githubusercontent.com/assets/4571086/10172372/3c7549c8-66df-11e5-8a51-fb232bae62cf.JPG)

**Comment by Ysurac** [comment]
Fixed in commit 6dcbee147a7e5b0597099cfc44b8441641b8f45d
Sorry

**Comment by tonkepen100** [comment]
Anything by God, but now out controls jijiji that hullabaloo
