### ISSUE TITLE
Folder images NEW

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#91]
After the change to choose the color of the icons I see planes coming out with a new folder called New aircraft icons, my question is ...

![captura2](https://cloud.githubusercontent.com/assets/4571086/10186577/5367b3be-6752-11e5-91ad-ea18a5f0ceb3.JPG)

Currently grabs where the aircraft ?, icons from images or from the new folder.

If I step NEW icons to the location of long delete that folder, something would happen ?.

Thank you.

**Comment by Ysurac** [comment]
If GD is supported by PHP, it's your case, icons come from the **new** directory only.
I made this directory because to be able to change colors of icons they must be PNG indexed without shadows.

**Comment by tonkepen100** [comment]
And when you click and it turns red, it still fucking the SELECTED folder or not ?.

thanks, again

**Comment by Ysurac** [comment]
no. Only the **new** directory.
