### ISSUE TITLE
No see Flights

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#94]
Hello Ysurac:
Well, this morning the radar was perfect, totally perfect, and suddenly the flights have been magically,

the call to file pyro works perfect ...

http://piro.biz/lib/skins/skyline/js/recentpireps.php

The crones are well placed,

Marrow was suddenly and absolutely not touched anything,

maybe it's the cron that updates the table every day or not, please help.

**Comment by tonkepen100** [comment]
![captura](https://cloud.githubusercontent.com/assets/4571086/10262065/dc9c15ae-69b8-11e5-9554-c2335c5badff.JPG)

**Comment by tonkepen100** [comment]
to run the cron I get this ....
![captura](https://cloud.githubusercontent.com/assets/4571086/10262082/98a9df60-69b9-11e5-81ca-ff9ab83b7181.JPG)

**Comment by tonkepen100** [comment]
It already Ysurac the problem, you have to see it, so that it can be corrected when a flight goes to the South Pole for example based Rhotera, flights automatically disappear, must be latitudes settings or something.

to cut the flight was making the user of Ushuaia r Lieutenant Marshall at the south pole, they have become flights

**Comment by tonkepen100** [comment]
Well, that's not it either

**Comment by Ysurac** [comment]
Check your *settings.php*, *$globalSBS1Hosts*. This MUST be **$globalSBS1Hosts = array('http://piro.biz/lib/skins/skyline/js/recentpireps.php');**

**Comment by tonkepen100** [comment]
Checked, when you fly to the South Pole, disappear all flights.

See ....

![captura1](https://cloud.githubusercontent.com/assets/4571086/10266857/3bee4c40-6a7a-11e5-8faa-1ba499999ee4.JPG)

![captura](https://cloud.githubusercontent.com/assets/4571086/10266858/43ad9292-6a7a-11e5-991d-1a6417729a3d.JPG)

![captur2a](https://cloud.githubusercontent.com/assets/4571086/10266859/4cba2dd2-6a7a-11e5-8705-dbbd60c3b7ee.JPG)

and the fault is in the filter believe this ....

Connecting... user FAM appid AirPiro Radar using FlightAirMap filter r/20.00/5.00/250.0 Connect to pirepsjson source... Connected! SCAN MODE

that I see the code is in the cron here ....

![capturasssa](https://cloud.githubusercontent.com/assets/4571086/10266877/2978e75e-6a7b-11e5-94b5-08650f6152f0.JPG)

Thanks Ysurac

**Comment by Ysurac** [comment]
This filter is only used in case of FAM source.
The error come from http://piro.biz/lib/skins/skyline/js/recentpireps.php
I have this error : *Malformed UTF-8 characters, possibly incorrectly encoded*

So I fixed this in latest commit. I force encoding to UTF-8.

**Comment by tonkepen100** [comment]
Verry thanks Ysurac, verry thanks

**Comment by tonkepen100** [comment]
yessssssss, perfectly corrected

![capturasssa](https://cloud.githubusercontent.com/assets/4571086/10267104/c5591a54-6a85-11e5-864d-2fd65aabfec2.JPG)
