### ISSUE TITLE
Notams Question

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#95]
Question:

I have to do to make NOTAMs are loaded every day ?, I have created an account on the website of notams, but I see no change every day. however daily web notams send me email updates.

Thanks Ysurac.

**Comment by Ysurac** [comment]
The script *update_db.php* should be run every day. If NOTAMs are in the feed of notaminfo then they are put in DB and availables.

**Comment by tonkepen100** [comment]
Aja perfect, but then the script can alter table aircraft me ?. because if my alter that table had a heart attack.

Thank you Ysurac

**Comment by Ysurac** [comment]
No, if **$globalIVAO** is set to **TRUE** the script *update_db.php* only update NOTAM so it only use *notam* table.

**Comment by tonkepen100** [comment]
OK GODD, Thanks Ysurac
