### ISSUE TITLE
Flights not end

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#97]
For two or three days ago, the flights flown by a pilot, not complete, join the following.

IVAO flight is successful, the radar if the pilot the flight line of the previous flight continues to be reflected not disconnected.

![captura](https://cloud.githubusercontent.com/assets/4571086/10558129/e2677cc8-74c4-11e5-988a-e7921d3a7d1d.PNG)

![captura](https://cloud.githubusercontent.com/assets/4571086/10558133/33634a62-74c5-11e5-90da-ef45b4df42d6.PNG)

**Comment by Ysurac** [comment]
This is possible if user use the same ident for different flights in the last 9 hours (all data older than 9 hours minimum are removed). 
I need to find a data that tell me it's not the same flight. Maybe when id is not the same, need to check if it's ok with all IVAO sources.

**Comment by tonkepen100** [comment]
Because the only thing that comes to Ivao me, are ICAOS airports.

But all came out well before the lines were erased, are only lines that map the current board all flights out perfect. I mean that if they change, what does not change is the line of flight on the map.

![captura](https://cloud.githubusercontent.com/assets/4571086/10560573/43433966-750f-11e5-8895-633d8f2bc394.PNG)

![captura2](https://cloud.githubusercontent.com/assets/4571086/10560574/48a16c34-750f-11e5-8b0f-3f847ff03e5d.PNG)

this is my flight right now, as seen out the two-stage and performed, but goes well the current flight departure and arrival.

**Comment by tonkepen100** [comment]
Or you can do for PIR number, when you see it other than to delete the previous one.

![captura](https://cloud.githubusercontent.com/assets/4571086/10560617/c02d5ea6-7510-11e5-9f2f-df8b0a70afbb.PNG)

**Comment by Ysurac** [comment]
PIR number is used, I use PIR number in hexa limited to 6 char combined with callsign as unique id for each flight. So if flight id or PIR number change, it's a new flight for me. 
BUT if a flight with the same callsign is see less than 30 minutes after previous one, I use the same ID as previous flight and no new flight is added in DB.
Maybe it's the problem in IVAO.

**Comment by Ysurac** [comment]
Maybe commit ecab4d1e008894d551d9b5a4ed2003be9057d547 solve the issue. Maybe not ;)

**Comment by tonkepen100** [comment]
Stepped on, the two files, now ascertained, to see that you have broken this time.

jajajjajaaja. it's a joke

**Comment by Ysurac** [comment]
We will not see if this work before 9 hours. When previous data will be deleted ;)

**Comment by tonkepen100** [comment]
no no, my flight is out and i i connect, and the rest of flights the lines duplicates is off,, see you in piro radar

**Comment by Ysurac** [comment]
ok good.

**Comment by tonkepen100** [comment]
Look, I put the hard busyness overtakes, the repairs all for nothing.

It is impossible to catch him in a revoke.

Thanks Ysurac, and I think it works well
