### ISSUE TITLE
Problem whit NOTAMS

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#98]
See if I explained well in English, which is not mine:

1.- I put options, the key to the web of NOTAMS, to put it in the browser I see the data, and that site every day sends me mail the NOTAMS, so I guess this well since.

2. In my Cpanel. I have put a cron that every day is the next run and I think it is what would have to be loaded into the db NOTAMS, such data:

------     php /home/airpiro/public_html/scripts/update_db.php> / dev / null 2> & 1

Well I took 3 days and seeing the table is empty, I mean not load the data.

What could be wrong ?. any ideas?.

Thank you

**Comment by Ysurac** [comment]
What is the value in **require/settings.php** of *$globalNOTAMSource* and of *$globalNOTAM* ?

**Comment by tonkepen100** [comment]
this

//NOTAM
$globalNOTAM = TRUE;
$globalNOTAMSource = 'http://notaminfo.com/feed?u=???????'; //URL of your feed from notaminfo.com

**Comment by Ysurac** [comment]
And you have some data at **http://notaminfo.com/feed?u=???????** ?

**Comment by tonkepen100** [comment]
see you:

http://notaminfo.com/feed?u=tonkepen

**Comment by Ysurac** [comment]
You can try commit 067b8c6f5328f24b47030414e3da965d381956ec

**Comment by tonkepen100** [comment]
Well change the file ..

1. put the cron for 1 minute to see if they carried .. not empty.

2. then reinstall the radar to see if it was loaded and so either.

![captura](https://cloud.githubusercontent.com/assets/4571086/10560359/4c5c9f34-7509-11e5-8b00-419fa19069d9.PNG)

**Comment by Ysurac** [comment]
NOTAM can only be fetched once by hour.  You can check time of last try in config table.

**Comment by Ysurac** [comment]
Also you can check if **install/tmp** is writable. The script download a file named *notam.rss* in this directory.

**Comment by tonkepen100** [comment]
ok i put temp in 777

**Comment by tonkepen100** [comment]
jejejee, in table config i only see the number 10

![captura](https://cloud.githubusercontent.com/assets/4571086/10560410/dfe16dec-750a-11e5-86cc-b828b58c9b48.PNG)

**Comment by Ysurac** [comment]
It was the problem.
It's solved in commit 65124737c1b2ce0282bba01a07a768ed7dfc0970

**Comment by tonkepen100** [comment]
OLEEEEEEEEEEEEEEEEE, This is my Ysuraccccccccc...

![captura](https://cloud.githubusercontent.com/assets/4571086/10560487/adf7d044-750c-11e5-956f-513fcdf0d2c6.PNG)
