### ISSUE TITLE
Install Problem...

### ISSUE THREAD

**Issue by tonkepen100** [Ysurac/FlightAirMap#99]
I find that after upgrading to retry install, comes the next problem ...

![errr](https://cloud.githubusercontent.com/assets/4571086/10648841/3594884e-7841-11e5-9622-c77a2a910c6a.PNG)

**Comment by Ysurac** [comment]
Should be fixed in commit e0031ca2f053748d1b448b669d5153c68c1b4c94

**Comment by tonkepen100** [comment]
Close ok
